### ISSUE TITLE
 init order with super

### ISSUE THREAD

**Issue by matrix3d** [apache/royale-asjs#1005]
```
class A{
public var a={};
}
class B extends A{
public function B(){
trace(a.xxx);
super();
}
}
new B();
```

the a={} need init first

**Comment by matrix3d** [comment]
@joshtynjala

**Comment by joshtynjala** [comment]
If I compile your code into an AIR app with either the Flex SDK compiler or Adobe's ASC 2.0, I get the following runtime error:

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
```

With that in mind, it appears that `a={}` should not init before the call to `super()`.

**Comment by matrix3d** [comment]
https://github.com/matrix3d/spriteflexjs/commit/0dd28701cec33a87c094c6b5acd3b5dd5449fe88#diff-c2ae40fa9c5d0c1c0082043add74edcae2ce3586727a01e7df987742185f0d99

https://github.com/matrix3d/spriteflexjs/blob/master/src/flash/events/EventDispatcher.as#L9


This class set text is an error before super.
EventDispatcher
listeners
Is null, but adobe air sdk can compile normally

**Comment by matrix3d** [comment]
The compiler is ok
Code problem
