### ISSUE TITLE
mx:TreeItemRenderer cannot be used as a base class in mxml

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#1006]
In this app

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application 
	xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.apache.org/royale/spark"
	xmlns:mx="library://ns.apache.org/royale/mx"
	creationComplete="init()"
	xmlns:comp="components.*"
	>
	<fx:Script>
		<![CDATA[

			import components.MyComp;
			
			private function init():void
			{
				var myComp:MyComp = new MyComp();
				addElement(myComp);
				trace(myComp.nested);
			}

		]]>
	</fx:Script>		
</s:Application>
```

with this component

```
<?xml version="1.0" encoding="utf-8"?>
<mx:TreeItemRenderer
	xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.apache.org/royale/spark"
	xmlns:mx="library://ns.apache.org/royale/mx"
	implements="org.apache.royale.core.IMXMLDocument"
	>
	<s:Group>
		<s:Group id="nested"/>
	</s:Group>
</mx:TreeItemRenderer>

```

trace says myComp.nested is undefined.

**Comment by yishayw** [comment]
It looks like the mxmlDescriptor needs to be generated by the server. For that to happen we need to have TreeItemRenderer implement IMXMLDocument and a [DefaultProperty("mxmlContent")] needs to be added. TreeItemRenderer as it is implemented relies on there not being children for proper layout and sizing. So there might be a refactor needed. As a workaround I will simply create a custom TreeItemRenderer in my app.

**Comment by aharui** [comment]
TreeItemRenderer seems to extend UIComponent which has all of the things needed to support MXML, so not obvious why it isn't working.

**Comment by yishayw** [comment]
>For that to happen we need to have TreeItemRenderer implement IMXMLDocument and a [DefaultProperty("mxmlContent")] needs to be added.

I didn't notice UIComponent already implements IMXMLDocument , but adding [DefaultProperty("mxmlContent")]  does seem to be necessary.

**Comment by aharui** [comment]
Interesting...   Flex doesn't seem to specify a defaultProperty for TreeItemRenderer.  IMO, this might be an unsupported use.  TreeItemRenderer was used in MXML for setting properties, but AFAICT, there was no support for additional children.  Spark has an MXTreeItemRenderer that could be used as the top tag in MXML, IIRC.

**Comment by yishayw** [comment]
Ur right, legacy app was using spark one, sorry for the noise.
