### ISSUE TITLE
Jewel GridCell - wideScreenDenominator - wideScreenNumerator

### ISSUE THREAD

**Issue by mjesteve** [apache/royale-asjs#1020]
Working with GridCell I have seen that when setting the wideScreenNumerator and wideScreenDenominator properties, reference is made to GridCellLayout.DESKTOP instead of GridCellLayout.WIDESCREEN:

![image](https://user-images.githubusercontent.com/55754195/102994569-9a4d6c00-451f-11eb-86c6-1939ce6b2c09.png)

GridCellLayout.WIDESCREEN should be referenced, right?

Thx.
Hiedra

**Comment by raudjcholo** [comment]
Fixed!!
