### ISSUE TITLE
TLF - org.apache.royale.textLayout.conversion.BaseTextLayoutExporter.exportrChild(flowElement) returns null

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#1047]
When flowElement is an org.apache.royale.textLayout.elements.ParagraphElement.

I suspect the reason is this line in 

org.apache.royale.textLayout.conversion.TextLayoutImporter.defaultConfiguration:
_defaultConfiguration.addIEInfo('p', org.apache.royale.textLayout.elements.IParagraphElement, org.apache.royale.textLayout.conversion.BaseTextLayoutImporter.parsePara, org.apache.royale.textLayout.conversion.BaseTextLayoutExporter.exportParagraphFormattedElement);

In contrast to other configuration items IParagraphElement is an interface rather than a concrete class. Should it not be

org.apache.royale.textLayout.elements.ParagraphElement instead?

**Comment by Harbs** [comment]
Probably.
