### ISSUE TITLE
royale-as-js : mxmlc.jar not exist !

### ISSUE THREAD

**Issue by mzamoun-veolia** [apache/royale-asjs#1059]
the compilation est OK, but there is no file of name mxmlc.jar !?

here is the result of the compilation : 
[INFO] Reactor Summary for Apache Royale: Framework: Parent 0.9.8-SNAPSHOT:
[INFO]
[INFO] Apache Royale: Framework: Parent ................... SUCCESS [  8.745 s]
[INFO] Apache Royale: Framework ........................... SUCCESS [  1.142 s]
[INFO] Apache Royale: Framework: Fonts .................... SUCCESS [  5.204 s]
[INFO] Apache Royale: Framework: Libs ..................... SUCCESS [  2.275 s]
[INFO] Apache Royale: Framework: Libs: Language ........... SUCCESS [  6.725 s]
[INFO] Apache Royale: Framework: Libs: Core ............... SUCCESS [ 18.894 s]
[INFO] Apache Royale: Framework: Libs: Binding ............ SUCCESS [  2.540 s]
[INFO] Apache Royale: Framework: Libs: Graphics ........... SUCCESS [  6.251 s]
[INFO] Apache Royale: Framework: Libs: Collections ........ SUCCESS [  2.544 s]
[INFO] Apache Royale: Framework: Libs: Basic .............. SUCCESS [ 20.222 s]
[INFO] Apache Royale: Framework: Libs: Charts ............. SUCCESS [  4.196 s]
[INFO] Apache Royale: Framework: Libs: Effects ............ SUCCESS [  2.667 s]
[INFO] Apache Royale: Framework: Libs: CreateJS ........... SUCCESS [  2.485 s]
[INFO] Apache Royale: Framework: Libs: Reflection ......... SUCCESS [  2.003 s]
[INFO] Apache Royale: Framework: Libs: DragDrop ........... SUCCESS [  2.562 s]
[INFO] Apache Royale: Framework: Libs: Express ............ SUCCESS [  2.484 s]
[INFO] Apache Royale: Framework: Libs: Formatters ......... SUCCESS [  1.537 s]
[INFO] Apache Royale: Framework: Libs: Network ............ SUCCESS [  3.842 s]
[INFO] Apache Royale: Framework: Libs: XML ................ SUCCESS [  2.282 s]
[INFO] Apache Royale: Framework: Libs: MXRoyale ........... SUCCESS [ 54.475 s]
[INFO] Apache Royale: Framework: Libs: Storage ............ SUCCESS [  1.345 s]
[INFO] Apache Royale: Framework: Libs: Crux ............... SUCCESS [  4.840 s]
[INFO] Apache Royale: Framework: Libs: Flat ............... SUCCESS [  1.698 s]
[INFO] Apache Royale: Framework: Libs: FontAwesome ........ SUCCESS [  1.774 s]
[INFO] Apache Royale: Framework: Libs: GoogleMaps ......... SUCCESS [  2.234 s]
[INFO] Apache Royale: Framework: Libs: HTML ............... SUCCESS [  2.914 s]
[INFO] Apache Royale: Framework: Libs: HTML5 .............. SUCCESS [  1.351 s]
[INFO] Apache Royale: Framework: Libs: Icons .............. SUCCESS [  1.439 s]
[INFO] Apache Royale: Framework: Libs: Jewel .............. SUCCESS [ 30.614 s]
[INFO] Apache Royale: Framework: Libs: JQuery ............. SUCCESS [  1.541 s]
[INFO] Apache Royale: Framework: Libs: Material Design Lite SUCCESS [  4.318 s]
[INFO] Apache Royale: Framework: Libs: Mobile ............. SUCCESS [  2.588 s]
[INFO] Apache Royale: Framework: Libs: RoyaleSite ......... SUCCESS [  1.572 s]
[INFO] Apache Royale: Framework: Libs: RoyaleUnit ......... SUCCESS [  1.946 s]
[INFO] Apache Royale: Framework: Libs: RoyaleUnitUI ....... SUCCESS [  2.417 s]
[INFO] Apache Royale: Framework: Libs: Text ............... SUCCESS [  2.413 s]
[INFO] Apache Royale: Framework: Libs: TLF ................ SUCCESS [ 14.656 s]
[INFO] Apache Royale: Framework: Libs: SparkRoyale ........ SUCCESS [ 16.823 s]
[INFO] Apache Royale: Framework: Themes ................... SUCCESS [  0.421 s]
[INFO] Apache Royale: Framework: Themes: Basic ............ SUCCESS [  0.419 s]
[INFO] Apache Royale: Framework: Themes: MDL .............. SUCCESS [  0.787 s]
[INFO] Apache Royale: Framework: Themes: MX ............... SUCCESS [  0.550 s]
[INFO] Apache Royale: Framework: Themes: JewelTheme ....... SUCCESS [  1.224 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Amethyst-Theme SUCCESS [  0.381 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Blue-Theme SUCCESS [  0.583 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Emerald-Theme SUCCESS [  0.447 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Green-Theme SUCCESS [  0.341 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Orange-Theme SUCCESS [  0.349 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Red-Theme SUCCESS [  0.402 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Sapphire-Theme SUCCESS [  0.349 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Sunflower-Theme SUCCESS [  0.380 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Topaz-Theme SUCCESS [  0.396 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Turquoise-Theme SUCCESS [  0.368 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Violet-Theme SUCCESS [  0.348 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Primary-Yellow-Theme SUCCESS [  0.381 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Amethyst-Theme SUCCESS [  0.429 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Blue-Theme SUCCESS [  0.438 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Emerald-Theme SUCCESS [  0.319 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Green-Theme SUCCESS [  0.303 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Orange-Theme SUCCESS [  0.434 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Red-Theme SUCCESS [  0.408 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Sapphire-Theme SUCCESS [  0.394 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Sunflower-Theme SUCCESS [  0.321 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Topaz-Theme SUCCESS [  0.375 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Turquoise-Theme SUCCESS [  0.387 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Violet-Theme SUCCESS [  0.478 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Secondary-Yellow-Theme SUCCESS [  0.354 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Amethyst-Theme SUCCESS [  0.375 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Blue-Theme SUCCESS [  0.362 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Emerald-Theme SUCCESS [  0.409 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Green-Theme SUCCESS [  0.424 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Orange-Theme SUCCESS [  0.490 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Red-Theme SUCCESS [  0.355 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Sapphire-Theme SUCCESS [  0.395 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Sunflower-Theme SUCCESS [  0.388 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Topaz-Theme SUCCESS [  0.505 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Turquoise-Theme SUCCESS [  0.422 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Violet-Theme SUCCESS [  0.313 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-NoFlat-Emphasized-Yellow-Theme SUCCESS [  0.301 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Amethyst-Theme SUCCESS [  0.371 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Blue-Theme SUCCESS [  0.398 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Emerald-Theme SUCCESS [  0.298 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Green-Theme SUCCESS [  0.285 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Orange-Theme SUCCESS [  0.400 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Red-Theme SUCCESS [  0.437 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Sapphire-Theme SUCCESS [  0.434 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Sunflower-Theme SUCCESS [  0.331 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Topaz-Theme SUCCESS [  1.017 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Turquoise-Theme SUCCESS [  0.386 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Violet-Theme SUCCESS [  0.353 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Primary-Yellow-Theme SUCCESS [  0.322 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Amethyst-Theme SUCCESS [  0.333 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Blue-Theme SUCCESS [  0.370 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Emerald-Theme SUCCESS [  0.493 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Green-Theme SUCCESS [  0.429 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Orange-Theme SUCCESS [  0.468 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Red-Theme SUCCESS [  0.362 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Sapphire-Theme SUCCESS [  0.320 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Sunflower-Theme SUCCESS [  0.300 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Topaz-Theme SUCCESS [  0.317 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Turquoise-Theme SUCCESS [  0.320 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Violet-Theme SUCCESS [  0.313 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Secondary-Yellow-Theme SUCCESS [  0.320 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Amethyst-Theme SUCCESS [  0.386 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Blue-Theme SUCCESS [  0.433 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Emerald-Theme SUCCESS [  0.445 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Green-Theme SUCCESS [  0.400 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Orange-Theme SUCCESS [  0.409 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Red-Theme SUCCESS [  0.406 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Sapphire-Theme SUCCESS [  0.319 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Sunflower-Theme SUCCESS [  0.307 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Topaz-Theme SUCCESS [  0.337 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Turquoise-Theme SUCCESS [  0.307 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Violet-Theme SUCCESS [  0.286 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Light-Flat-Emphasized-Yellow-Theme SUCCESS [  0.362 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Amethyst-Theme SUCCESS [  0.438 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Blue-Theme SUCCESS [  0.379 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Emerald-Theme SUCCESS [  0.347 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Green-Theme SUCCESS [  0.343 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Orange-Theme SUCCESS [  0.326 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Red-Theme SUCCESS [  0.323 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Sapphire-Theme SUCCESS [  0.367 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Sunflower-Theme SUCCESS [  0.300 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Topaz-Theme SUCCESS [  0.344 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Turquoise-Theme SUCCESS [  0.555 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Violet-Theme SUCCESS [  0.454 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Primary-Yellow-Theme SUCCESS [  0.575 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Amethyst-Theme SUCCESS [  0.379 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Blue-Theme SUCCESS [  0.295 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Emerald-Theme SUCCESS [  0.329 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Green-Theme SUCCESS [  0.318 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Orange-Theme SUCCESS [  0.338 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Red-Theme SUCCESS [  0.297 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Sapphire-Theme SUCCESS [  0.306 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Sunflower-Theme SUCCESS [  0.347 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Topaz-Theme SUCCESS [  0.394 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Turquoise-Theme SUCCESS [  0.957 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Violet-Theme SUCCESS [  0.415 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Secondary-Yellow-Theme SUCCESS [  0.336 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Amethyst-Theme SUCCESS [  0.409 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Blue-Theme SUCCESS [  0.600 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Emerald-Theme SUCCESS [  0.545 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Green-Theme SUCCESS [  0.344 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Orange-Theme SUCCESS [  0.337 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Red-Theme SUCCESS [  0.339 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Sapphire-Theme SUCCESS [  0.417 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Sunflower-Theme SUCCESS [  0.389 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Topaz-Theme SUCCESS [  0.308 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Turquoise-Theme SUCCESS [  0.298 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Violet-Theme SUCCESS [  0.334 s]
[INFO] Apache Royale: Framework: Themes: Jewel-Dark-NoFlat-Emphasized-Yellow-Theme SUCCESS [  0.325 s]
[INFO] Apache Royale: Framework: Archetypes ............... SUCCESS [  0.136 s]
[INFO] Apache Royale: Framework: Archetypes: Simple Royale Application SUCCESS [  0.484 s]
[INFO] Apache Royale: Framework: Archetypes: Jewel Royale Application SUCCESS [  3.004 s]
[INFO] Apache Royale: Framework: Archetypes: Jewel Royale Module Application SUCCESS [  0.553 s]
[INFO] Apache Royale: Framework: Archetypes: Simple Royale Pure-JS Application SUCCESS [  0.318 s]
[INFO] Apache Royale: Framework: Archetypes: Simple Royale Pure-SWF Application SUCCESS [  0.312 s]
[INFO] Apache Royale: Framework: Archetypes: Simple Royale Library SUCCESS [  0.888 s]
[INFO] Apache Royale: Framework: Archetypes: Simple Royale Typedef Library SUCCESS [  0.128 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:05 min
[INFO] Finished at: 2021-01-22T16:18:25+01:00
[INFO] ------------------------------------------------------------------------

**Comment by carlosrovira** [comment]
Hi, maven create artifacts in .m2
for mxmlc you need to create a distribution (that is the name of a SDK in maven). I think you already created since I see another issue, so probably you already know this.
In distribution mxmlc.jar is in `/js/lib` folder and `lib` folders.

**Comment by mzamoun-veolia** [comment]
Yes , I ve just do "mvn clean install" in royale-asjs/distribution/ : and I got it :) 
Thanks

**Comment by mzamoun-veolia** [comment]
Question: why we have the script mxmlc in bin and in js/bin ?

**Comment by carlosrovira** [comment]
there's no motive, we need to clean that from the distribution script and left just one :)

**Comment by mzamoun-veolia** [comment]
yes, it will be better :)
