### ISSUE TITLE
ERROR : royale-framework-parent: Execution prerequisite-check of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: Not all conditions met

### ISSUE THREAD

**Issue by mzamoun-veolia** [apache/royale-asjs#1061]
In royale-asjs, when I execute the command : 
./mvnw install -P with-examples,with-distribution,with-ui-testsuite,option-with-swf -Dwebdriver.gecko.driver=/drives/c/tools/royale/Downloads/geckodriver.exe -DdistributionTargetFolder=/drives/c/tools/royale/ApacheRoyale/SDKs

I got this error : 
[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (prerequisite-check) on project royale-framework-parent: Execution prerequisite-check of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: Not all conditions met, see log for details. -> [Help 1]

**Comment by carlosrovira** [comment]
Hi, I saw you already got build with maven. I use to build all with (mac style command script):

```
SDK_FOLDER="/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-maven"
mvn clean install -P option-with-swf,option-with-sass-compile,with-examples,with-distribution,with-ui-testsuite -Dwebdriver.gecko.driver=/Users/carlosrovira/Dev/Royale/geckodriver -DdistributionTargetFolder="$SDK_FOLDER"
```

as well, if I want to create the sdk distribution at later time I do from my royale-asjs folder:

```
cd distribution 
mvn clean install -DdistributionTargetFolder=/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-maven
```

HTH

Carlos

**Comment by mzamoun-veolia** [comment]
Thanks @carlosrovira  ; it is a good solution :)
