### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1062]
I need to create some graphical button in Royale and wondered if there was a way to do skinning yet? 

https://apache.github.io/royale-docs/features/styles-skins-themes

At this link, the team says that examples for skinning are coming soon.  I was wondering if there had been any updates on skinning, or if you have any suggestions for workarounds to create a graphical button in Royale?

Thanks!

**Comment by yishayw** [comment]
SinnbalbleContainer is implemented but not SkinnableComponent. So button skinning would not work. In the app I am currently porting I have created buttons based on the skin mxml to emulate the look and feel. Here's an example

```
<?xml version="1.0" encoding="utf-8"?>
<s:Group
	xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.apache.org/royale/spark"
	alpha.disabled="0.5"
	useHandCursor="true"
	buttonMode="true"
	top="0"
	left="0"
	bottom="0"
	right="0"
	creationComplete="onCreationCompleted(event)"
	>
	<fx:Script>
		<![CDATA[
			import mx.events.FlexEvent;

			[Bindable]
			private var customFontSize : Number = 11;

			protected function onCreationCompleted(event:FlexEvent):void
			{
				var parentFontStyle : Number =  getStyle("fontSize");
				customFontSize = (parentFontStyle) ? parentFontStyle :customFontSize;
				if (_labelPending)
				{
					labelDisplay.text = _label;
					if (parent)
						(parent as IEventDispatcher).dispatchEvent(new Event("layoutNeeded"));			
				}
				addEventListener(mx.events.MouseEvent.MOUSE_DOWN, mouseHandler);
			}

			private function mouseHandler(event:mx.events.MouseEvent):void
			{
				currentState = event.type == !enabled ? 'disabled' :
				       	mx.events.MouseEvent.MOUSE_DOWN ? "down" :
					event.type == mx.events.MouseEvent.MOUSE_UP ? "up" :
					event.type == mx.events.MouseEvent.ROLL_OVER ? "over" : "normal";
			}

			private var _labelPending:Boolean;
			private var _label:String;
			public function set label(value:String):void
			{
				_label = value;
				if (!labelDisplay)
				{
					_labelPending = true;
				} else
				{
					labelDisplay.text = value;
					if (parent)
						(parent as IEventDispatcher).dispatchEvent(new Event("layoutNeeded"));			
				}
			}

			/**
			 *  @private
			 */
			public function get label():String          
			{
				return _label;
			}
		]]>
	</fx:Script>

	<s:states>
		<s:State name="up" />
		<s:State name="over" />
		<s:State name="down" />
		<s:State name="disabled" />
	</s:states>
	<s:layout>
		<s:VerticalLayout verticalAlign="middle" paddingTop="4" />
	</s:layout>
	<!-- label -->

	<s:Label
		id="labelDisplay"
		fontSize="{customFontSize}"
		fontFamily="SMhelveticaCFF"
		text=""
		color="0xffffff"
		color.over="0x92cdcf"
		textDecoration="none"
		textDecoration.over="none"
		verticalCenter="-5"
		baselineShift="{2}"
		/>
</s:Group>

```

**Comment by Bilbosax** [comment]
Brilliant yishayw, thank you.  I will basically just create a button as an mxml component with states.  I only have two small problems with this approach that you could quickly help me with.'

1) If you are using VS Code, could you share your asconfig.json file with me?  I have been able to get the mx library recognized by VS Code, but I can't for the life of me figure out how to get it to include the spark components as well like those you used in your button.

2) If I want to dispatch an event from one component that I want heard in another component, in Flex, I always added my eventlisteners to the stage like this:

`systemManager.stage.addEventListener("someEvent", someMethod);`

This does not work in Royale.  How can I attach listeners that can hear events dispatched from other components?

Thanks for your insights!

**Comment by Bilbosax** [comment]
@yishayw I have created a button component, but I cannot figure out how to get it's click event heard OUTSIDE of the component by another MXML component.  If I want to dispatch an event from one component that I want heard in another component in Flex, I always added my eventlisteners to the stage like this:

systemManager.stage.addEventListener("someEvent", someMethod);

This does not work in Royale. How can I attach listeners in an mxml component that can hear events dispatched from other components?
