### ISSUE TITLE
Scaling SVG Graphics with Actionscript

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1063]
So in my older Flex apps, I use Rectangles as backgrounds for my Groups so that I can have a background color.  Now that I am trying to convert to Royale in the browser, I have to account for the fact that a browser window may be resized, so I listen for the resize event, and I adjust the size and position of some elements.  In Flex, I had no problems changing the size of a Rectangle with Actionscript, but I have not been able to do it in Royale.  The ONLY way that I have gotten Rectangle to work is if I declare its dimensions in MXML.  Here is my code example:

```
<?xml version="1.0" encoding="utf-8"?>
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
		xmlns:mx="library://ns.apache.org/royale/mx"
		xmlns:s="library://ns.apache.org/royale/spark"
                xmlns:j="library://ns.apache.org/royale/jewel"
              	xmlns:js="library://ns.apache.org/royale/basic"
              	xmlns:html="library://ns.apache.org/royale/html"
		xmlns:svg="library://ns.apache.org/royale/svg"
		xmlns:c="components.*"
		applicationComplete="appComplete(event)">
	
	<fx:Script>
		<![CDATA[

		import classes.AppVars;
		
		protected function appComplete(event:Event):void {
			
			//Set Initial State
			mainView.currentState = "props";

			//Event Listeners
			mainView.addEventListener("sizeChanged", sizeChangedHandler)

			//Set Values
			AppVars.appWidth = this.width;
			AppVars.appHeight = this.height;

			headerGroup.width = AppVars.appWidth;
			headerGroup.height = AppVars.appHeight * .08;
			headerGroup.x = 0;
			headerGroup.y = 0;
			headerRect.width = AppVars.appWidth;
			headerRect.height = AppVars.appHeight * .08;
			headerRect.x = 0;
			headerRect.y = 0;
			dimensions.x = headerGroup.width - 100;
			dimensions.y = (headerGroup.height - dimensions.height)/2;
			props.width = AppVars.appWidth;
			props.height = AppVars.appHeight * .92;
			props.x = 0;
			props.y = AppVars.appHeight * .08;
			view.width = AppVars.appWidth;
			view.height = AppVars.appHeight * .92;
			view.x = 0;
			view.y = AppVars.appHeight * .08;

		}

		protected function sizeChangedHandler(event:Event):void {
			headerGroup.width = this.width;
			headerRect.width = this.width;
			props.width = this.width;
			props.height = this.height;
			view.width = this.width;
			view.height = this.height;
		}
		
		]]>
	</fx:Script>

    <j:beads>
        <js:BrowserResizeHandler/>
    </j:beads>
	
    <j:initialView>    	
        <j:View localId="mainView" width="100%" height="100%">

	    <j:states>
                <js:State name="props" />        
                <js:State name="view" /> 
		<js:State name="photos" />
            </j:states>

	    <j:beads>
                <js:SimpleStatesImpl/>
            </j:beads>

			<j:Group localId="headerGroup">
				<svg:Rect localId="headerRect">
					<svg:fill>
						<js:SolidColor color="#323233"/>
					</svg:fill>
				</svg:Rect>
			</j:Group>

			<c:props localId="props" visible.props="true" visible.view="false" visible.photos="false"/>
			<c:view localId="view" visible.props="false" visible.view="true" visible.photos="false"/>     

        </j:View>
    </j:initialView>
</j:Application>
```

As you can see, when the applicationComplete event fires, I try to set the dimensions of some of my components, and when "sizechanged" event is thrown, I try to resize some paramenters of my components.  But they never work for <svg:Rect>.  A Rectange is never displayed.  The only way that I have been able to get the Rectangle to display is if I set the width and height parameters in MXML, then a Rectangle will display.

Is this a bug, or am I doing something wrong?

**Comment by carlosrovira** [comment]
Hi @Bilbosax, I was trying to build your example but depends on external code. Can you post another simpler one that shows the problem, so I can build and try easily? Thanks

**Comment by Bilbosax** [comment]
Sure Carlos.  This is just a simple MXML file that should create a Group in the upper left corner of the screen that is 800 x 50, and the group should be filled by an SVG Rectangle that is also 800 x 50.  The dimensions of both components are set by actionscript after the appComplete event is fired.  It does not work even though it traces out that the dimensions of both objects are actually 800 x 50.  But if you take the width, height, x, and y properties and put them directly into the Rect MXML, it works as expected.  But it cannot be resized with Actionscript if needed.

```
<?xml version="1.0" encoding="utf-8"?>
<j:Application  xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:j="library://ns.apache.org/royale/jewel"
              	xmlns:js="library://ns.apache.org/royale/basic"
		xmlns:svg="library://ns.apache.org/royale/svg"
		applicationComplete="appComplete(event)">

	
	<fx:Script>
		<![CDATA[
		
		protected function appComplete(event:Event):void {

			headerGroup.width = 800
			headerGroup.height = 50;
			headerGroup.x = 0;
			headerGroup.y = 0;
			headerRect.width = headerGroup.width;
			headerRect.height = headerGroup.height;
			headerRect.x = 0;
			headerRect.y = 0;
			
			trace("App Complete");
			trace(headerGroup.width, headerGroup.height, headerRect.width, headerRect);
		}
		
		]]>
	</fx:Script>
	
    <j:initialView>    	
        <j:View localId="mainView" width="100%" height="100%">
		<j:Group localId="headerGroup">
			<svg:Rect localId="headerRect">
				<svg:fill>
					<js:SolidColor color="#323233"/>
				</svg:fill>
			</svg:Rect>
		</j:Group>   
        </j:View>
    </j:initialView>
</j:Application>
```

**Comment by carlosrovira** [comment]
Thanks Bilbo, I could reproduce it, and I remember I had the same problem some time ago, and I think I reported, but seems it passed without notice. It was while working on this tutorial [1]. I recommend you to take a look since it uses the Flash Drawing API through `UIGraphicsBase` and probably that you will be very confortable for sure :). Also this problem is not in that API and was how I workaround at that time.

@Harbs, please, can you take a look at this simple example? I think you made SVG and probably could know better than me about how to fix this issue.

[1] https://royale.apache.org/working-with-vector-graphics/

**Comment by Bilbosax** [comment]
For now, I have simply created a rectangle in illustrator and exported it as SVG, and then manually had to edit the SVG to contain  preserveAspectRatio="none" so that I can shape the width and height in actionscript without it hanging onto its aspect ratio.  For me, this is not really a long-term solution as I can't change the color and do other things, and I use a lot of Rectangles in my app, so it would be nice to have a functioning SVG Rect

**Comment by Harbs** [comment]
Sorry I just noticed this. Life has been very busy...

Adding `headerRect.draw()` after setting the size and position will do what you want.
