### ISSUE TITLE
TopAppBar Functionality

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1066]
I have decided on a ResponsiveView for my final app.  I'm testing a lot of components in Royale that are not available in Flex before I get started because they have responsive characteristics.  Today, I tried TopAppBar, but there is hardly any documentation available for this component so I took from an example I found.  I put together this short sample, and it compiled fine, but I get no visible bar in the app.  I also get nothing in the ApplicationMainContent where I placed a simple card. I have included a jewel theme, so colors and CSS are there for the topAppBar.  What am I doing wrong that I can't see anything?

```
<?xml version="1.0" encoding="utf-8"?>
<j:ResponsiveView xmlns:fx="http://ns.adobe.com/mxml/2009"
		xmlns:mx="library://ns.apache.org/royale/mx"
		xmlns:s="library://ns.apache.org/royale/spark"
                xmlns:j="library://ns.apache.org/royale/jewel"
              	xmlns:js="library://ns.apache.org/royale/basic"
              	xmlns:html="library://ns.apache.org/royale/html"
		xmlns:svg="library://ns.apache.org/royale/svg">

	<j:beads>
            <js:ContainerDataBinding/>
            <js:BrowserOrientation localId="bo"/>
	    <j:CleanValidationErrors/>
        </j:beads>
                
	<j:TopAppBar fixed="true" hasDrawer="false">
		<j:BarRow>
			<j:BarSection>
				<j:BarTitle text="Apache Royale Tour de Jewel" />
			</j:BarSection>
			<j:BarSection itemsHorizontalAlign="itemsRight">
			</j:BarSection>
		</j:BarRow>
	</j:TopAppBar>

	<j:ApplicationMainContent>
		<j:Card>
			<j:CardTitle text="Jewel Simple Card"/>

			<j:Label text="This is the content"/>

			<j:Button text="Action" emphasis="primary"/>
		</j:Card>
	</j:ApplicationMainContent>


</j:ResponsiveView>
```

**Comment by carlosrovira** [comment]
Hi Bilbo,

can you check the MainContent in TourDeJewel and see if it helps you. I think there we show all you need to know:

https://github.com/apache/royale-asjs/blob/develop/examples/jewel/TourDeJewel/src/main/royale/MainContent.mxml

Notice that there's currently a known bug in TopAppBar that make it always work in "fixed" mode.
