### ISSUE TITLE
cess of possibly undefined property i sAttribute through a reference with static type QName.

### ISSUE THREAD

**Issue by blackjyn** [apache/royale-asjs#107]
I got this error when building from the source 

**[java] D:\Repo\ApacheRoyaleASJS\royaleasjs-sdk\frameworks\projects\XML\src\
main\royale\XML.as(1175): col: 12 Error: Access of possibly undefined property i
sAttribute through a reference with static type QName.
     [java]
     [java]                     if(name.isAttribute)
     [java]                             ^
     [java]
     [java] D:\Repo\ApacheRoyaleASJS\royaleasjs-sdk\frameworks\projects\XML\src\
main\royale\XML.as(1951): col: 6 Error: Property prefix is read-only.
     [java]
     [java]                                     ns.prefix = attr.split(":")[1];
     [java]                                     ^
     [java]
     [java] D:\Repo\ApacheRoyaleASJS\royaleasjs-sdk\frameworks\projects\XML\src\
main\royale\XML.as(2216): col: 47 Error: Access of possibly undefined property p
refix through a reference with static type QName.
     [java]
     [java]                     _name = getQName(nameRef.localName,nameRef.prefi
x,nameRef.uri,nameRef.isAttribute);
     [java]                                                                ^
     [java]
     [java] D:\Repo\ApacheRoyaleASJS\royaleasjs-sdk\frameworks\projects\XML\src\
main\royale\XML.as(2216): col: 74 Error: Access of possibly undefined property i
sAttribute through a reference with static type QName.
     [java]
     [java]                     _name = getQName(nameRef.localName,nameRef.prefi
x,nameRef.uri,nameRef.isAttribute);**

**Comment by Harbs** [comment]
Are you using the develop branch?

**Comment by blackjyn** [comment]
Yes of course

**Comment by estanglerbm** [comment]
No error like this when building XML, now.  Maybe this can be closed?

**Comment by blackjyn** [comment]
@estanglerbm this is very old thread , I don't even remember the specific version I cloned.
Did you have valid proof that this is no longer happening?
If so, just mention which Royale version solves this problem and I'm happy to close it.

**Comment by estanglerbm** [comment]
@blackjyn Well, if you build ``develop`` right now, there are no compile errors in XML.  Doesn't that prove it?

**Comment by blackjyn** [comment]
I'm no longer updated my local repo since then and prefer the binary dist instead.
I assume you already build latest version and the problem has gone so I'm gonna close it with peace
