### ISSUE TITLE
Error - ISelectableContent

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1072]
I have made a very simple app that contains a main app App.mxml with a ResponsiveView in the MainContent.mxml.  It is an extremely simple app modeled on the structure of Tour De Jewel.  I am having trouble moving forward because I get an error that I don't understand and can't find any information about.  The error is:

"Uncaught Error: One or more content in ApplicationMainContent is not implementing ISelectableContent interface."

I only have one component in the ApplicationMainContent that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<j:Grid xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:mx="library://ns.apache.org/royale/mx"
	xmlns:s="library://ns.apache.org/royale/spark"
        xmlns:j="library://ns.apache.org/royale/jewel"
        xmlns:js="library://ns.apache.org/royale/basic"
        xmlns:html="library://ns.apache.org/royale/html"
	xmlns:svg="library://ns.apache.org/royale/svg" itemsHorizontalAlign="itemsCenter" itemsVerticalAlign="itemsCenter">

        <fx:Script>
            <![CDATA[
               
            ]]>
        </fx:Script>

        <j:GridCell localId="mapCell" desktopNumerator="1" desktopDenominator="2"
            tabletNumerator="1" tabletDenominator="2"
            phoneNumerator="1" phoneDenominator="1" itemsHorizontalAlign="itemsCenter" itemsVerticalAlign="itemsCenter" height="550">
            <svg:Image localId="headerRect" src="svg/headerBar.svg" width="100%" height="100%"/>
        </j:GridCell>
        
        <j:GridCell localId="propListCell" desktopNumerator="1" desktopDenominator="2"
            tabletNumerator="1" tabletDenominator="2"
            phoneNumerator="1" phoneDenominator="1" itemsHorizontalAlign="itemsCenter" itemsVerticalAlign="itemsCenter">
            <j:List localId="propList" width="100%" height="550">
            </j:List>
        </j:GridCell>

</j:Grid>
```

In Tour De Jewel, you have one variable set up called private var currentContent:ISelectableContent, but the variable is never used.  Tour De Jewel compiles fine without this error, but my basic app with only one component in the ApplicationMainContent has it.

What is ISelectableContent and what objects do I need to incorporate into my components to get rid of this error?  I've attached the sample app to this post.
[TestError.zip](https://github.com/apache/royale-asjs/files/5900696/TestError.zip)

**Comment by Bilbosax** [comment]
I finally got the error to go away by filling my ApplicationMainContent with components built inside of j:SectionContent, but I am not exactly sure why this works.  What components use ISelectableContent, and where can you go to find these things out??

**Comment by carlosrovira** [comment]
Hi Bilbo,

1.- Containers that have navigation require that the inner components to navigate implement `ISelectionContent`.
The main component is `SelectionContent` (and if you want scrolling support `ScrollableSelectionContent`).

Other components that are made for navigation are `TabBarContent` (the content of a `TabBar` control) and `WizardContent` (the content for `Wizard`, but in this case is abstracted and if you see the TDJ example you add `WizardPage` components directly.)

2.- I'm in the process of filling this Royale Docs pages:

https://apache.github.io/royale-docs/component-sets/jewel#components

Although we have Royale ASDocs, that is automatic generation of the docs. This component pages are created manually to give the information about the component, the basic use, the events, properties and functions more relevant and also the beads available that can be specific for a component, optional or common. Also with links to examples in blogs or other articles.

Far from that, I think the only way is to experiment, and try to find your way. As any other technology the experience matters and is difficult to find a shortest path

HTH
