### ISSUE TITLE
HSlider Visibility Not Working

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1076]
The visibility of an HSlider cannot be turned off, either in MXML or in Actionscript.

This fails:

`<j:HSlider localId="numBathsSlider" minimum="0" maximum="5" snapInterval="1" valueChange="numBathsSliderChangeHandler(event)" visible="false"/>`

This also fails:

`numBathsSlider.visible = false;`

I need to be able to turn some components off and on depending on what a client is choosing.

**Comment by Bilbosax** [comment]
Hi Carlos.  Usually you respond to an issue before you close it.  I don't know if that means that you fixed it, or if it was so absurd you simply dismissed it and I am missing something ;)  I downloaded the nightly 0.9.8, and I still can't get the HSlider's visibility to change, so am I perhaps doing something wrong that I am unaware of?

**Comment by carlosrovira** [comment]
Hi Bilbo, when we fix the problem in a commit and add to the comment "fix #<number>", then after the commit github close the issue since the action state that "is fixes". So yes, the problem is now fixes ;)

Probably you are not seeing due to the fix not entering in the nightly or due to some cache issue. The problem was in CSS since hslider had an "!important" in the display rule, so modifing it was not having any effect. I removed the !important modifier since is not needed

**Comment by Bilbosax** [comment]
OH!  I'm glad you told me this, because I actually pull the CSS file out of the themes folder and use it manuallyin my app, so an update wouldn't have helped me because I am still using the old version.  I may have to change this approach.

**Comment by Bilbosax** [comment]
Hmmmm.  I have downloaded the nightly build again and have switched to using a theme in the asconfig file and it still does not work for me.  Can't turn off the visibility.  Any thoughts?

**Comment by carlosrovira** [comment]
Hi Bilbo,

just rechecked that all is ok. As I said, maybe the change did not enter in the nightly. Probably at the time I'm writing this will be for sure. If a new nightly still not work, must be something on your side, recheck your code to ensure nothing is interfiering.

The actual CSS code:

```css
.jewel.slider {
    display: flex;
    ...
}
```

If you don't have the change you should have instead `display: flex important;`

**Comment by Bilbosax** [comment]
Ok, I can confirm that using actionscript works, but using MXML does not. 

this works: ` numBathsSlider.visible = false;`

this does not: `<j:HSlider localId="numBathsSlider" visible="false"/>`

**Comment by carlosrovira** [comment]
Sorry, Bilbo,  just tested in TDJ and is working both mxml and as3. Something is still interfering.
