### ISSUE TITLE
MenuBar 3rd-level is not showing

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1084]
In my application, there is a hierarchy of menu like
**Admin** -> **Security** -> **Users** -> Create **User**
when I click **Admin** a popup opens for sub-menu level 1,
I selected **Security** then another popup opens for sub-menu level 2,
when I click **Users** nothing happens It should open another popup as in Flex

**Comment by aharui** [comment]
Array-based Menu data providers default to looking for `menu` instead of `children` at the 3rd-level and subsequent levels.  There's probably some way to set the `submenuField` in the model, or you can just change the name of the property in data.

```
			 // The Array data provider 
        [Bindable] 
        public var menuData:Array = [ 
                {label: "MenuItem A", children: [ 
                	{label: "SubMenuItem A-1", enabled: false,children: [ 
                		{label: "SubMenuItem A-1-1", enabled: false}, 
                		{label: "SubMenuItem A-1-2", menu: [ 
                			{label: "SubMenuItem A-1-2-1", enabled: false}, 
                			{label: "SubMenuItem A-1-2-2", type: "normal"} 
            				]} 
            			]}, 
                	{label: "SubMenuItem A-2", type: "normal"} 
            		]}, 
            		{label: "MenuItem B", type: "check", toggled: true}, 
            		{label: "MenuItem C", type: "check", toggled: false}, 
            		{type: "separator"}, 
            		{label: "MenuItem D", children: [ 
                	{label: "SubMenuItem D-1", type: "radio",groupName: "g1"}, 
                	{label: "SubMenuItem D-2", type: "radio",groupName: "g1", toggled: true}, 
                	{label: "SubMenuItem D-3", type: "radio",groupName: "g1"} 
            		]} 
        ]; 
```

**Comment by alinakazi** [comment]
Alex , tried a solution/work around for 3rd level menu items .. I changed Array to  XMLListCollection and it worked till 3rd level menu items. menu items are shown.
![image](https://user-images.githubusercontent.com/36731338/110765611-2e54e700-8276-11eb-897a-1787d4a28b87.png)

I will try and check also what you have suggested.
Thanks  a lot

**Comment by alinakazi** [comment]
Alex menu instead of children at 3rd level , I tried with an example and it worked.

Thanks
