### ISSUE TITLE
Uncaught TypeError: Cannot read property 'numElements' of null     (MenuBar.js:199)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1088]
With New SDK I got this Error and menuBar disappears
![image](https://user-images.githubusercontent.com/42200979/110323347-4dfdcc80-8036-11eb-9bf6-5ccbf41567b7.png)

**Comment by pashminakazi** [comment]
In old SDK numElements was defined : 
![image](https://user-images.githubusercontent.com/42200979/110325875-b7cba580-8039-11eb-83dc-4f334559e1b8.png)
![image](https://user-images.githubusercontent.com/42200979/110325894-be5a1d00-8039-11eb-82dd-ecd5f2652c9f.png)

**Comment by alinakazi** [comment]
I am looking this issue and it seems some commits for this fix earlier are reverted

**Comment by alinakazi** [comment]
Issue has been resolved with commits https://github.com/apache/royale-asjs/commit/99e3e3882074a26a85743cd2978d6d03f46460f4#diff-455495f701efeab756b6f58043524aaafbfecba548d98f14b21ba946fae35165
