### ISSUE TITLE
Royale+Flash Builder Integration FAILED

### ISSUE THREAD

**Issue by blackjyn** [apache/royale-asjs#109]
I follow the instruction on:
https://github.com/apache/royale-asjs/wiki/Flash-Builder-4.7
and download the apache-royale-0.9.0-bin.tgz
I'm on Win 8.1 x64

**What works:**
The nightly binary dist of Royale is able to build the provided samples under royale-asjs/examples

**What did NOT works:**
Flash Builder **_4.7 did NOT recognize the royale-asjs as Flex SDK_**, even after I:
`ant -f antscripts.xml setup`
and
`ant -f InstallAdobeSDKs.xml`

![royale-asjs not recognized](https://user-images.githubusercontent.com/6046191/34907560-1bfdff92-f8b3-11e7-9781-59d24bf04c08.png)

**Comment by blackjyn** [comment]
This problem still persists in Royale 0.9.1

**Comment by piotrzarzycki21** [comment]
Hi @blackjyn ,

Maybe you should try to use one of the IDE which currently supports the most Royale. [Moonshine IDE](http://moonshine-ide.com/) and [VSCode](https://nextgenactionscript.com/). Instructions are [here](https://github.com/apache/royale-asjs/wiki/Quick-Start).

Thanks, 
Piotr

**Comment by blackjyn** [comment]
I have tried Moonshine but autocomplete feature didn't work at all.
Big NO for VSCode 
I hope Royale works FBuilder as FlexJS was

**Comment by Harbs** [comment]
Curious what you don't like about VS Code.

Anyway. Did you check that you have the flex-sdk-description.xml in your SDK?

**Comment by piotrzarzycki21** [comment]
@blackjyn if it didn't work for you - raise Issue on GitHub. I would be glad to help you and fix issue if it were any.

**Comment by blackjyn** [comment]
Yes I have flex-sdk-desc , I have followed the instruction on the wiki

**Comment by Harbs** [comment]
I just tried adding my copy of royale-asjs to Flash Builder 4.7 and it worked.

You can try using the develop branch of royale-asjs and building from source to produce an IDE compatible SDK. Here's what should work:

1. Clone royale-asjs and pull the develop branch
2. Set the following environment variables (this is what I set them to on my Mac machine)
````
export ROYALE_COMPILER_REPO=/Apache/royale-compiler
export FLEX_HOME=/Apache/flex-sdk 
export AIR_HOME=/Apache/frameworks/AIRSDK_Compiler
export PLAYERGLOBAL_HOME=/Apache/frameworks/libs/player 
export FLASHPLAYER_DEBUGGER=/Apache/frameworks/Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger
export ROYALE_HOME=/Apache/royale-asjs
````
3. run `ant all`
4. Add a folder in framework/libs/player/[Flash Version]/playerglobal.swc

I'm pretty sure that's all that's needed to make a dev setup FB compatible.

**Comment by Harbs** [comment]
FLEX_HOME is old and probably not needed anymore...

**Comment by carlosrovira** [comment]
In Mac I use homebrew without the need to set any environment variable, then I build using maven

**Comment by aharui** [comment]
Hi, I tried it on Mac and Win with the nightly build and it worked for me.   Please try again by deleting your SDK folder, unpacking the nightly build, and post the output of InstallAdobeSDKs.xml.  I did see it fail for one version of the AIR SDK that happened to be in my downloads folder and seemed to have different package contents than we are expecting, but I deleted that package and downloaded a different one and it appeared to work.

**Comment by blackjyn** [comment]
Thanks Alex @aharui ! 
It works with the latest nightly build [2/7/2018]
