### ISSUE TITLE
Help using images and assets from SWC libraries

### ISSUE THREAD

**Issue by piltsen** [apache/royale-asjs#1106]
Hello everyone

We are working on a migration project using Apache Royale and the project contains plenty of SWC files that contains JPG and PNG images. 

We have been trying to use them directly from the libs but without any success. If we copy the file directly to the source folder it works. But we need to be able to refer and use the images inside the libs. 

Attached is an example project we setup showing 4 images (2 from libs and 2 from source folder) and the ones from the libs are not shown, not matter the compiler options we set in the asconfig.json. 

[using-images-example.zip](https://github.com/apache/royale-asjs/files/6387102/using-images-example.zip)

We are using VS Code with Apache Royal 0.9.8.

**Comment by yishayw** [comment]
I see things like

                                                <j:Image src="images2/afericao.png"/>

Have you tried

                                                <j:Image src="/images2/afericao.png"/>

Instead?

From: André Thiesen da ***@***.***>
Sent: Tuesday, April 27, 2021 10:28 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [apache/royale-asjs] Help using images and assets from SWC libraries (#1106)


Hello everyone

We are working on a migration project using Apache Royale and the project contains plenty of SWC files that contains JPG and PNG images.

We have been trying to use them directly from the libs but without any success. If we copy the file directly to the source folder it works. But we need to be able to refer and use the images inside the libs.

Attached is an example project we setup showing 4 images (2 from libs and 2 from source folder) and the ones from the libs are not shown, not matter the compiler options we set in the asconfig.json.

using-images-example.zip<https://github.com/apache/royale-asjs/files/6387102/using-images-example.zip>

We are using VS Code with Apache Royal 0.9.8.

**Comment by piltsen** [comment]
Hello @yishayw 

In my examples, the images referencing the source folder are working. The libs are not. As follows

![image](https://user-images.githubusercontent.com/18350146/116397598-2a1c6300-a7fd-11eb-9594-63e9532cff28.png)

I did try putting "/" in from the string but nothing worked afterwards. 

![image](https://user-images.githubusercontent.com/18350146/116397915-8aaba000-a7fd-11eb-8d0e-014f3cae2cce.png)

It seems that the files from the library are not being extracted when I run the build. Not sure how to ensure they are.

**Comment by alinakazi** [comment]
Yes it's not there. here images folder should be present. 
![image](https://user-images.githubusercontent.com/36731338/116400161-29a6bb00-a843-11eb-8138-8768b5a7a0fd.png)

Can you send library project also ?

**Comment by piltsen** [comment]
Hello @alinakazi 

Here it is

[images-swc.zip](https://github.com/apache/royale-asjs/files/6391862/images-swc.zip)
