### ISSUE TITLE
Wiki: Quick start -> Visual Studio Code is incomplete

### ISSUE THREAD

**Issue by neminovno** [apache/royale-asjs#111]
How to "Select a workspace in VSCode" ?
Is it "File -> Add folder to Workspace..." or "File -> Open folder" ?

When "Select the Debug panel in VSCode and hit the green arrow to build and run the application" then it says: "No configuration" and Select environment pops up dropdown.

**Comment by Harbs** [comment]
I just updated the instructions which were outdated for both the SDK and details about the VS Code extension. Assuming you are using version 0.9.0 of the extension, the current instructions should work. Please let us know if I'm wrong.

**Comment by neminovno** [comment]
All works except last step, I got this after green arrow click:
![image](https://user-images.githubusercontent.com/1468887/35592892-b2a4ac1c-060e-11e8-8bc5-26d5bc568c05.png)

**Comment by neminovno** [comment]
Probably this is missing in Wiki:
- press CTRL+SHIFT+B or Run Build Task
and 
- create launch.json with contents like this:
{
 	"version": "0.2.0",
 	"configurations": [
 		{
 			"name": "Launch Firefox, debug build with sourcemaps",
 			"type": "firefox",
 			"request": "launch",
 			"file": "${workspaceRoot}/bin/js-debug/index.html"
 		}
 	]
 }

This helped me: [Debug a transpiled ActionScript project in Visual Studio Code with Mozilla Firefox](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-transpiled-ActionScript-project-in-Visual-Studio-Code-with-Mozilla-Firefox)

Am I wrong? Is there really quick(er) way to run Royale app?

**Comment by pinacolada** [comment]
Any simple AS file to javascript (no library, flex, air...) working sample ?

**Comment by Harbs** [comment]
I don't usually use the integrated debugging. I usually just debug the js files directly in the browser I'm using. The steps should work exactly as specified in the wiki. What is not working for you?

If you want to used the integrated debugging, the wiki page includes links with more instructions there.
