### ISSUE TITLE
TabNavigator Issue in getTabAt

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1116]
Click on Hide Tab or Show Tab Button and see the Exception
[TabNavigator.zip](https://github.com/apache/royale-asjs/files/6644340/TabNavigator.zip)
![1](https://user-images.githubusercontent.com/42200979/121816329-6ebc6a80-cc94-11eb-8add-771d23d57215.png)
![2](https://user-images.githubusercontent.com/42200979/121816332-71b75b00-cc94-11eb-86b2-88f52b9ae9e7.png)

**Comment by yishayw** [comment]
I am closing this because my latest commit fixes the example, I would still advise against relying on getTabAt() at this point.

**Comment by pashminakazi** [comment]
@yishayw Thank u so much
Is there any alternate for getTabAt()?

**Comment by yishayw** [comment]
It depends what you want to do. If you need to remove a button, for example, I think you can change the dataProvider to exclude that particular button.

**Comment by pashminakazi** [comment]
@yishayw after your commit getTabAt() is working fine..Thanks
