### ISSUE TITLE
FormItem Required field is throwing Exception and Red mark for required field is missing

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1119]
Example : [FormExample.zip](https://github.com/apache/royale-asjs/files/6650336/FormExample.zip)
In FormItem if required is not added then the form is working fine,
But if I add required=true or required=false then the application is throwing Error :
and because of this exception index.html is blank if I removed the required from formItem then the form is working fine.
Uncaught TypeError: indicatorClass is not a constructor   (FormItem.js:737)
![image](https://user-images.githubusercontent.com/42200979/121936079-aa256a80-cd62-11eb-8674-a6db3c9e2dcb.png)
![image](https://user-images.githubusercontent.com/42200979/121936168-c45f4880-cd62-11eb-8f1c-626f375a5290.png)

There are two Issues 
1) Required in FormItem should work
2) Red mark for Required field

Like in Flex: 
![image](https://user-images.githubusercontent.com/42200979/121935849-5e72c100-cd62-11eb-9fac-b228e3b36dd4.png)

**Comment by alinakazi** [comment]
Use stringValidator

**Comment by yishayw** [comment]
I got rid of the runtime error but there is still a problem in  my test as far as finding the image source.

**Comment by yishayw** [comment]
@pashminakazi , please test
