### ISSUE TITLE
VSCode: "Select Workspace SDK" does not recognize latest version as SDK

### ISSUE THREAD

**Issue by neminovno** [apache/royale-asjs#112]
After downloading latest apache-royale-0.9.0 and trying to use it in VSCode, it seems that it can't be added as SDK. Did anyone manage to do this?

**Comment by neminovno** [comment]
Latest apache-royale-0.9.1-bin-js.zip downloaded from http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/ is recognized in VSCode but there is build error:
> MXMLJSC
> +flexlib=c:\dev\sdks\apache-royale-0.9.1-bin-js-jsonly\royale-asjs\frameworks
> --debug=true
> --source-map=true
> --targets=JSFlex
> src/HelloFlexJS.mxml
> Missing builtin type Object
> 
> 
> Unable to build SWF src/HelloFlexJS.js

**Comment by Harbs** [comment]
Are you using the VS Code extension v0.8.0 or 0.9.0?

Only the latest extension will work with Royale.

**Comment by neminovno** [comment]
As you can see, I was using 0.9.0 and 0.9.1, don't know what was problem, but now all works OK, after reinstalling everything.
