### ISSUE TITLE
README is missing: "npm install royale -g" requires Python

### ISSUE THREAD

**Issue by neminovno** [apache/royale-asjs#113]
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
>...

It should be in README that "npm install royale -g" requires Python.

**Comment by bigosmallm** [comment]
The `royale` module on npmjs.org is unrelated to Apache Royale.  
We will be uploading a new package `apache-royale` to npmjs.org soon.
