### ISSUE TITLE
Compile not catching missing states in skin MXML

### ISSUE THREAD

**Issue by estanglerbm** [apache/royale-asjs#1131]
If you define a skin MXML without states, Flex compiler throws errors:

```
MySkinFlex.mxml(8): Error: The required skin state 'disabled' is missing.
MySkinFlex.mxml(8): Error: The required skin state 'normal' is missing.
```

But Royale compiler does not.  Is this a compiler issue or something else to set?  Or expected change in behavior?

**Comment by joshtynjala** [comment]
@estanglerbm I cannot reproduce this issue. I tried the following code, and the compiler correctly reported that the two skin states were missing:

```actionscript
// MyComponent.as
package
{
	import mx.core.UIComponent;

	[SkinState("test1")]
	[SkinState("test2")]
	public class MyComponent extends UIComponent
	{
		public function MyComponent()
		{
			
		}
	}
}
```

```mxml
// MySkin.mxml
<spark:SparkSkin xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:spark="library://ns.apache.org/royale/spark">
	<fx:Metadata>
		[HostComponent("MyComponent")]
	</fx:Metadata>
</spark:SparkSkin>
```

Could you have forgotten the `[HostComponent]` metadata? Which component were you trying to create a skin for?

**Comment by estanglerbm** [comment]
The test case is from issue #995.  It has `[HostComponent("spark.components.SkinnableContainer")]`.  I don't know if the issue is specific to that component.

**Comment by joshtynjala** [comment]
It looks like the compiler is working correctly. It's just that the `[SkinState]` metadata in `SkinnableContainerBase` is commented out:

https://github.com/apache/royale-asjs/blob/a612f3c57beb4a3564d31c1666c6e337978c592a/frameworks/projects/SparkRoyale/src/main/royale/spark/components/supportClasses/SkinnableContainerBase.as#L37

I tried uncommenting it locally, and recompiling the .swc file, and I see the missing skin state errors appear correctly.

**Comment by estanglerbm** [comment]
Doh.  I missed that.  Thanks;  sorry for the bother.  Do you want to check in the change, or should I?

**Comment by joshtynjala** [comment]
@estanglerbm Go for it! I generally try to stick to the compiler only.
