### ISSUE TITLE
SizeChanged Event of an element

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#1132]
I use the sizeChanged event to handle the resizing of a window and update its content ...
```
addEventListener("sizeChanged", sizeChangedHandler);
addEventListener("widthChanged", sizeChangedHandler);
addEventListener("heightChanged", sizeChangedHandler);
```
The problem is that now I need to handle the resizing of a container, not just that of the window since there are times when the size of an element can change without the window being resized.

Is there a way in royale or a bead that allows me to do this?

**Comment by Harbs** [comment]
A specific element or all elements? `layoutNeeded()` is likely what you're looking for

**Comment by javeiga-iest** [comment]
> A specific element or all elements? `layoutNeeded()` is likely what you're looking for

Hi @Harbs thx for the reply , i need it for a specific element.

How can I use `layoutNeeded` for example with an HGroup in apache royale?

**Comment by mjesteve** [comment]
Hi, in my case this solution has not worked for me before....
(I have a main page with a container "X" of which I need to be notified when it is resized).
From the main page I define the listener:
mycontainer.addEventListener("layoutNeeded", onChangeContainer).
Is this incorrect?
Yes I can capture the "layoutComplete" event but not "layoutNeeded".

**Comment by estanglerbm** [comment]
@javeiga-iest  Are you trying to (a) detect the resize of the container, (b) detect the resize of an element of the container, or (c) just make sure the container is resized when the element is resized?

**Comment by javeiga-iest** [comment]
Option "A" - detect the container size change event @estanglerbm

**Comment by estanglerbm** [comment]
I can't speak to Jewel and others, but at least for MX or Spark:  if an element is resized that requires the container to be resized, then--as @Harbs mentioned--`layoutNeeded` will be generated up to the container.  (`layoutNeeded` will also be generated for other things.)  Probably need to listen on the container's `contentView`.

**Comment by yishayw** [comment]
>addEventListener("sizeChanged", sizeChangedHandler);
addEventListener("widthChanged", sizeChangedHandler);
addEventListener("heightChanged", sizeChangedHandler);

Did you try simply listening to these events on the container?

container.addEventListener("sizeChanged", sizeChangedHandler);
container.addEventListener("widthChanged", sizeChangedHandler);
container.addEventListener("heightChanged", sizeChangedHandler);

**Comment by mjesteve** [comment]
Yishayw, estanglerbm, I don't get it... neither listening to the three container events, nor with the layoutNeeded,....
I have put debug points in the sdk but it DOES NOT STOP IN ANY that I recognize after initialization.
The truth is that I don't know the architecture well enough and I'm sure I'm not doing it correctly, so I'm going to start again, this time, bead by bead, starting with the view on the same line that estanglerbm commented in his last message.

If I'm saying inconsistent things TELL ME so I can learn : )

**Comment by mjesteve** [comment]
I got it!!! : )
In the end, before getting back to debugging I thought I'd read about the resize event and I found the ResizeObserver API. 
The best thing is that when I started to test I found "org.apache.royale.utils.observeElementSize" Et voilà !!!! the magic was done...

My goal is to create a bead that controls the size of the container, from any of its children, so I have a bit of work to do. For now I'll share my little example:

`<?xml version="1.0" encoding="utf-8"?>
<j:ResponsiveView xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:j="library://ns.apache.org/royale/jewel"
    xmlns:js="library://ns.apache.org/royale/basic"
    xmlns:jc="library://ns.apache.org/royale/community"
    initComplete="onInitComplete()">

    <fx:Script>
        <![CDATA[
        import org.apache.royale.utils.observeElementSize;

        public function onInitComplete():void
        {
            observeElementSize(cellcontainer.element,onSizeChange);
        }

        private function onSizeChange():void
        {
            trace(cellcontainer.element.offsetWidth, cellcontainer.element.offsetHeight);
        }
        ]]>
    </fx:Script>

    <j:ApplicationMainContent localId="main" hasTopAppBar="true" hasFooterBar="true" className="mainbg1">
        <j:SectionContent>
            <j:beads>
                <js:Paddings padding="50"/>
            </j:beads>
                    
            <j:Grid gap="true">                    
                <j:GridCell desktopNumerator="1" desktopDenominator="2" tabletNumerator="1" tabletDenominator="1" phoneNumerator="1" phoneDenominator="2">
                    <j:Group id="cellcontainer" localId="box1" style="background-color: #333333;" percentWidth="100" height="200" />
                </j:GridCell>                    
                <j:GridCell desktopNumerator="1" desktopDenominator="2" tabletNumerator="1" tabletDenominator="1" phoneNumerator="1" phoneDenominator="2"/>
            </j:Grid>

        </j:SectionContent>
    </j:ApplicationMainContent>

</j:ResponsiveView>`

Thx. ;)

**Comment by mjesteve** [comment]
Here is a small demo

![GIF 29-07-2021 3-53-05](https://user-images.githubusercontent.com/55754195/127419403-9855af16-fb6d-4c89-a156-41ba4a30a4b1.gif)

The code here [[1](https://github.com/mjesteve/royale-examples-community/tree/develop)]

**Comment by javeiga-iest** [comment]
Thx, worked for me @mjesteve
