### ISSUE TITLE
ComboBoxList is moving up and down if i scroll,It should be closed if i scroll

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#1133]
ComboBoxList is moving up and down if i scroll,It should be closed if i scroll
![comboBoxPosition](https://user-images.githubusercontent.com/42200979/125756581-ba4eed70-4645-4947-b63c-970d90f402a6.gif)

_Originally posted by @pashminakazi in https://github.com/apache/royale-asjs/issues/1115#issuecomment-880508209_

**Comment by pashminakazi** [comment]
@yishayw Thank u so much 
after fixing this issue another issue occurs,
If we scroll any other scroller with touchpad then the comboBoxList should be closed,not when we scroll comboBoxList's scroller

When I scroll comboBoxList with touchpad it will be closed after this fix
