### ISSUE TITLE
Selected Tab is not highlighted

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1138]
Selected Tab should be highlighted when it is selected and If focus is out from Tab then also it remains highlighted it doesn't loose selection from Tab
[TabsSelection.zip](https://github.com/apache/royale-asjs/files/6870083/TabsSelection.zip)
![TabsSelection](https://user-images.githubusercontent.com/42200979/126814087-462a69e4-5791-4ad5-8cca-f57b6d23af53.gif)

**Comment by pashminakazi** [comment]
After this change my application doesn't work when i launch application this exception occurs : 
![image](https://user-images.githubusercontent.com/42200979/127125169-42118c5e-ef97-4053-b849-dd40a17e609d.png)

**Comment by yishayw** [comment]
Did you build basic as well as MX?

**Comment by pashminakazi** [comment]
Yes,Basic Core and MXRoyale

**Comment by pashminakazi** [comment]
When I revert these 3 lines from MXRoyale's default.css
IItemRendererClassFactory: ClassReference("org.apache.royale.core.OverridableSelectableItemRendererClassFactory"); IItemRenderer: ClassReference("org.apache.royale.html.supportClasses.SelectableTextButtonItemRenderer"); ISelectableItemRenderer: ClassReference("org.apache.royale.html.supportClasses.SelectableTextButtonItemRenderer"); 

Application start working

**Comment by yishayw** [comment]
Strange, I'm not seeing it. I'll look at it later today. Feel free to revert the whole commit if it's wasting your time.

**Comment by pashminakazi** [comment]
@yishayw by default first tab is selected in TabNavigator but the color or background-color  isn't changed for the first selected tab

**Comment by pashminakazi** [comment]
@yishayw I got this Error after this commit : 
![image](https://user-images.githubusercontent.com/42200979/127558083-aa31de27-c9d0-4577-959a-3a3819de119b.png)

import org.apache.royale.html.beads.SolidBackgroundBead; SolidBackgroundBead; is only defined for SWF not for JS because it is using Sprite

**Comment by yishayw** [comment]
@pashminakazi , good catch. I don't know how that got there... Should be fixed now.
