### ISSUE TITLE
ApacheCon

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1152]
Sorry to post this in the "Issues" section, but I can't find anywhere else to discuss this.  I was looking forward to hearing about Royale at ApacheCon which starts tomorrow. But I went to the ApacheCon website and I couldn't find Royale mentioned anywhere. Does anyone know if they are planning on having any talks about Royale, and if so, on what days??

Thanks

**Comment by cottage14** [comment]
There are no Royale talks this year, alas.

A
