### ISSUE TITLE
no targets?

### ISSUE THREAD

**Issue by matrix3d** [apache/royale-asjs#116]
C:\Users\Administrator.ADMIN-20170623B\Desktop\apache-royale-0.9.0-bin-js\royale-asjs\bin>mxmlc Test.as
Unknown tag:compiler.targets
正在加载配置: C:\Users\Administrator.ADMIN-20170623B\Desktop\apache-royale-0.9.0-bin-js\royale-asjs\frameworks\royale-config.xml

**Comment by blackjyn** [comment]
JSRoyale is the target

**Comment by matrix3d** [comment]
@blackjyn i set the target jsroyale,and also not work

**Comment by matrix3d** [comment]
```
C:\Users\pc123\Desktop\apache-royale-0.9.1-bin-js\royale-asjs\bin>mxmlc Test.as -targets=JSRoyale

command line 错误: 配置变量“targets”未知。
```

**Comment by justinmclean** [comment]
I'm also seeing this:
Unknown tag:compiler.targets
Loading configuration: /Users/justinmclean/ApacheRoyale-0.9.0/apache-royale-0.9.0-bin-js/royale-asjs/frameworks/royale-config.xml

/Users/justinmclean/ApacheRoyale-0.9.0/apache-royale-0.9.0-bin-js/royale-asjs/frameworks/royale-config.xml(33): col: 0 Error: unknown configuration variable 'compiler.targets'.
/Users/justinmclean/ApacheRoyale-0.9.0/apache-royale-0.9.0-bin-js/royale-asjs/frameworks/royale-config.xml (line: 33)
      <targets>

Looks like the compiler.targets option is not defined in ICompilerSettingsConstants but is for the OEM compiler in ConfigurationConstants so it will fail to run from the command line but not if compiling from ant or maven.

**Comment by blackjyn** [comment]
Holaaa, use mxmlc from the js\bin:
**royale-asjs\js\bin\mxmlc**

and NOT this :
royale-asjs\bin\mxmlc

it should work then
![royalecompilefromcmd](https://user-images.githubusercontent.com/6046191/35789799-454e19d4-0a71-11e8-8cff-a1601e9d4a59.png)

**Comment by matrix3d** [comment]
@blackjyn thanks ,it is work

**Comment by justinmclean** [comment]
I can see one is using /lib/mxmlc.jar and the other /lib/compiler-mxmlc.jar
