### ISSUE TITLE
Add bdd style testing

### ISSUE THREAD

**Issue by Harbs** [apache/royale-asjs#1167]
I'd like to add BDD style assertions to `RoyaleUnit`. My intention is to implement an `expect` interface similar to https://www.chaijs.com/guide/styles/#expect and http://man.hubwiz.com/docset/Chai.docset/Contents/Resources/Documents/chaijs.com/api/bdd/index.html

Not all of these are applicable to ActionScript and there might be some additional ones that make sense in ActionScript.

The more interest I see in this, the more likely I'll get to this earlier rather than later. If someone else gets to this first, I will not complain either... :wink:

**Comment by Harbs** [comment]
🎉

**Comment by Harbs** [comment]
Am I missing something? I don't see flags and many of the behaviors mentioned here: http://man.hubwiz.com/docset/Chai.docset/Contents/Resources/Documents/chaijs.com/api/bdd/index.html

**Comment by joshtynjala** [comment]
@Harbs So far, I've simply exposed the current assertions that we already had available. I have plans to add more, but I figured that this was a good starting point for now.

**Comment by Harbs** [comment]
OK. Thanks.
