### ISSUE TITLE
utf bug

### ISSUE THREAD

**Issue by matrix3d** [apache/royale-asjs#117]
`二月 09, 2018 11:34:15 上午 com.google.javascript.jscomp.LoggerErrorManager println
严重: ERROR - Cannot read file D:/proj/git/spriteflexjs/test/bin/js-debug/fairygui/GComboBox.js: Failed to read: D:\proj\git\spriteflexjs\test\bin\js-debug\fairygui\GComboBox.js, is this input UTF-8 encoded?

二月 09, 2018 11:34:16 上午 com.google.javascript.jscomp.LoggerErrorManager println
严重: ERROR - Cannot read file D:/proj/git/spriteflexjs/test/bin/js-debug/fairygui/GScrollBar.js: Failed to read: D:\proj\git\spriteflexjs\test\bin\js-debug\fairygui\GScrollBar.js, is this input UTF-8 encoded?

二月 09, 2018 11:34:16 上午 com.google.javascript.jscomp.LoggerErrorManager println
严重: ERROR - Cannot read file D:/proj/git/spriteflexjs/test/bin/js-debug/fairygui/utils/CharSize.js: Failed to read: D:\proj\git\spriteflexjs\test\bin\js-debug\fairygui\utils\CharSize.js, is this input UTF-8 encoded?

二月 09, 2018 11:34:16 上午 com.google.javascript.jscomp.LoggerErrorManager printSummary
警告: 3 error(s), 0 warning(s)`

and this file is there,but the encoding is  8 bits (gb18030)

**Comment by matrix3d** [comment]
this is the as file

https://github.com/matrix3d/spriteflexjs/blob/master/test/src/fairygui/GComboBox.as

**Comment by aharui** [comment]
Have you tried setting the environment variable: JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
If you set it and the compiler sees it the output should also contain the words:

"Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8"

Let us know if that works.

**Comment by matrix3d** [comment]
set the environment,and the same result

**Comment by aharui** [comment]
Did you get the output "Picked Up JAVA_TOOL_OPTIONS"?  Otherwise, you may need to restart your command prompt or computer.  Are you using command-line or an IDE?

**Comment by matrix3d** [comment]
i have restart the command-line.

not output picked up

**Comment by aharui** [comment]
When I run mxmlc, the first line of output says "Picked Up.."  You will have to figure out why you are not getting that.  Try some other Java app.  List out environment variables.  Check spelling.

**Comment by joshtynjala** [comment]
This issue should be fixed in commit b95cd6f3d47e1d21f1693347dc7bce676c72b682
