### ISSUE TITLE
URLLoader : Event.COMPLETE isn't fire if server return empty data (sdk 0.9.8)

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#1175]
Hi,
I found this bug when porting an Air project to Apache Royale 

In the following function 	, **ev_list_file_result()** is called only if the response data is >= 1 octet.
If response content-lenght is 0 the Event.COMPLETE is not fired.

![image](https://user-images.githubusercontent.com/6851433/151352971-a02446ba-cafa-4cd6-bb96-036fb9f45c91.png)

```
private function get_file_list(order_id:int):void{
				var url:String = "http://some_url.com/orders/php_list_file.php?id=" + order_id;
				var request:URLRequest = new URLRequest(url);
				
				var loader:URLLoader = new URLLoader();
				loader.addEventListener(Event.COMPLETE,ev_list_file_result);
				loader.load(request);
}
```

```
<?php
	$id = $_GET["id"];
	$find = 'uploads/order'.$id.'_*';
       $result = glob($find);
       die (implode(';',$result));
?>
```

**Comment by Harbs** [comment]
Please test and make sure the fix resolves your issue. Thanks!
