### ISSUE TITLE
As3 / JS error in date properties

### ISSUE THREAD

**Issue by Nisaba** [apache/royale-asjs#1180]
Hello,

This code crashes:

        public function GetDateString(pDate: Date):String {
            if (pDate == null) return "";
            return pDate.day.toString() + "/" + pDate.month.toString() + "/" + pDate.fullYear.toString() +
                " " + pDate.hours.toString() + ":" + pDate.minutes.toString();
        }

Here is the error in the browser console:
Uncaught TypeError: pDate.getDay is not a function

![image](https://user-images.githubusercontent.com/34550856/156826211-0e7da710-7cd0-464b-8692-9d7dfcc761a2.png)

**Comment by joshtynjala** [comment]
@Nisaba Could it be that `pDate` is not actually an instance of the `Date` type?

**Comment by Nisaba** [comment]
pDate is a Date type variable.
As it is specified in the AS3 code.

No warning in the code about that.
In the code, the calls to the GetDateString() function send Date variable.

Anyway, the AS3 compiler should prevent this issue, isn't it ?


Thanks

**Comment by joshtynjala** [comment]
> pDate is a Date type variable.
> In the code, the calls to the GetDateString() function send Date variable.
> Anyway, the AS3 compiler should prevent this issue, isn't it ?

Yes, the compiler certainly should prevent a value that isn't a `Date` from being passed to this function. However, something is obviously going wrong, so it seems to me that it's worth checking what the actual value is at runtime in your web browser.

**Comment by aharui** [comment]
The compiler is already checking the type information it has, but because the JS runtime does not do much type-checking, there is always a chance that what gets passed in at runtime is not what the type information told the compiler.

The stack trace at the exception can often contain clues, so please attach it if you can.

One of the most common places to lose type information is when converting a server response to AS3 objects.

The compiler "could" generate runtime type-checking, but I think that would slow everything down too much.

**Comment by Nisaba** [comment]
Yes, the date value come from a server response...
So what could I do ?

thanks

**Comment by joshtynjala** [comment]
The first thing I would do is figure out what type the actual value of `pDate` is at runtime (which is what I've been encouraging you to do). My guess is that it's a string, but you won't know until you check in the debugger, or possibly with `trace()`.

Once you know the type, you can to figure out how to convert that value into a proper `Date`. That conversion should probably happen in your code that parses the server response. If you do it early enough, you should have an object of the correct `Date` type before it ever gets to your `GetDateString()` function.
