### ISSUE TITLE
MX Combobox doesn't Work with XML data 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#1181]
https://drive.google.com/file/d/1yevsQrML4eaVTeD3-mdsG5e-uiZq_-xJ/view?usp=sharing

**Comment by pashminakazi** [comment]
Hi Yishay,
Can u make a change to make comboBox work proper without any change 
we are using comboBox in our application as


```
<mx:ComboBox id="cboStatus" width="120" height="22" dataProvider="{DS_cboStatus.Table}" labelField="EmailDocStatusNm">

[Bindable]
private var DS_cboStatus:Object = new Object();

DS_cboStatus = event.result;
```
event.result is having an XML type data

It was not working before your change and not after your change we have to make some changes to make it work but as we have 1000 of combobox in our application so we don't want to make change.

It works with this change
```
[Bindable]
private var DS_cboStatus:XML = new XML();

DS_cboStatus = new XML(event.result);
```

Please make it work as it is if there is small change required in SDK and do not charge for it.

**Comment by alinakazi** [comment]
Object type data is handled within the application source code

**Comment by yishayw** [comment]
I'm not sure there's a way around that. See the last few paragraphs of this guide

https://apache.github.io/royale-docs/migrate-an-existing-app/migrate-from-flex
