### ISSUE TITLE
How to have a floating Group always in front ? (like j:topbar or bottom bar)

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#1187]
Hi,
I make a small app using TDJ structure like this : 

```
</j:Application>
    <j:initialView>
       <j:ResponsiveView>
             <j:ApplicationMainContent>
                   <j:ScrollableSectionContent localId="page1"/>
                   <j:ScrollableSectionContent localId="page2"/>
                   <j:ScrollableSectionContent localId="page2"/>
             </j:ApplicationMainContent>
        </j:ResponsiveView>
    </j:initialView>
</j:Application>

```
I would like to have an "home" button always visible in the top left corner (or bottom left corner) like topbar or bottom bar.
Was is the best practice to do it ?

**Comment by Harbs** [comment]
If it's always in the same place, you probably want `position:sticky` or `position:fixed`. You should be able to apply the css to any element.

**Comment by cristallium** [comment]
Thanks, it do the trick, I thought that I can do it with j:Group
