### ISSUE TITLE
How to use ResourceManager ?

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#1190]
Hi,
I have issue when trying to use RessourceManager

I have set this in asconfig.json : 

```
  "source-path": [
            "src/main/resources",
            "locale/fr_FR",
            "locale/en_US"
        ],
"locale": ["en_US","fr_FR"],
```
( if I set locale/{locale} compiler complain about invalid source path )

files are `locale/fr_FR/AppMessages.properties` and `locale/en_US/AppMessages.properties`

content is like this : 

`MENU_1=MyMenu1`

In App.mxml I added : 
```
	<fx:Metadata>
		[ResourceBundle("AppMessages")]
	</fx:Metadata>

```

```
Now running the app give nothing : 

var locales:Array = ResourceManager.getInstance().getLocales(); // return empty array
trace(ResourceManager.getInstance().getString('AppMessages','MENU_1')); //return null
```
Could someone tell me how to do ? Thank in advance

**Comment by cristallium** [comment]
Digging in framework, I found this way to make it working : 

```
    <js:beads>
        <js:SimpleLocalizedValuesImpl id="resourceManager"  />
    </js:beads>
...
resourceManager.bundles = [en_USAppMessages,fr_FRAppMessages];
trace(resourceManager.getValue('AppMessages', 'MENU_1'));
```
I'm not sure that it's the best way..
I will make a full exemple to add it in exemples

**Comment by mjesteve** [comment]
I have never used ResourceManager...
en_USAppMessages and fr_FRAppMessages is what the *.properties file is called?

**Comment by mjesteve** [comment]
I had not seen your PR... :P

**Comment by cristallium** [comment]
Yes, I do an exemple because it wasn't obvious for me to use it, so I hope it will be useful for other people. 
However I don't know if is't the best way. In PR I'm using `embed `directive instead `ResourceBundle` because I didn't find a way to succes with ResourceBundle.
*.properties are the same for locales as Flex targeting  SWF.
