### ISSUE TITLE
Jewel List : How to detect selectedChange event in an itemRenderer ?

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#1192]
Hi, sorry if it's a noob question, but I'm stuck on an easy case : 

I have a List like this  : 

```

        .CarListItemRenderer
        {
            IItemRenderer: ClassReference("itemRenderers.CarListItemRenderer");
        }

 <j:List width="100%" height="100%"  id="lst_cars" className="CarListItemRenderer" >
```

**The itemRenderer (CarListItemRenderer) :** 

```
<j:ListItemRenderer xmlns:fx="http://ns.adobe.com/mxml/2009" 
    xmlns:j="library://ns.apache.org/royale/jewel" 
    xmlns:js="library://ns.apache.org/royale/basic" 
    xmlns="http://www.w3.org/1999/xhtml" height="50" >

 <fx:Script>
        <![CDATA[
			import org.apache.royale.collections.ArrayList;
			import org.apache.royale.jewel.List;
			import org.apache.royale.jewel.beads.views.ListView;
			import model.Car;


            [Bindable("selectionChanged")]
            private function ev_selectionChanged(e:Event):void{
                trace ("selection changed");
            }

            [Bindable("dataChange")]
            public function get name():String
            {
                return (data as Car).name;
            }
            
		]]>
    </fx:Script>


    <j:beads>
        <js:ItemRendererDataBinding />
    </j:beads>

    <j:Label html="{name}" multiline="true"/>

</j:ListItemRenderer>
```

But `ev_selectionChanged()` is never called.

How to do to call this function **in the itemrenderer** when selection changed ?

I also tried this : 

```
<j:ListItemRenderer ...   initComplete="ev_initComplete()">

            private function ev_initComplete():void {
                  var view:ListView = this.itemRendererOwnerView as ListView;
                if (view) {
                    var host:List= view.host as List;
                    if (host) {
                        host.addEventListener("selectionChanged",ev_selectionChanged);
                    }
            }
```
But the issue with this, is that on initComplete event, `this.itemRendererOwnerView` return null

Thanks

**Comment by yishayw** [comment]
Have you tried 'change' instead of 'selectionChanged'?

**Comment by cristallium** [comment]
Thank, for help. 
`[Bindable("change")]` doesn't work
If you thought about `host.addEventListener("selectionChanged",ev_selectionChanged);` the issue is that this is never reach because this.itemRendererOwnerView is null on initComplete

**Comment by yishayw** [comment]
Looking at DataItemRendererFactoryBase.as it looks like item renderers are first added (triggering initComplete), and then initialized with owner among other things. I would try to add the event listener on set data, which happens after initialization.

**Comment by cristallium** [comment]
Many thanks !!! this is working like you said (calling addEventListener on set data)
