### ISSUE TITLE
 JSOnly Nightly Build  is off line

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#1194]
Hi
link for JSOnly Nightly Build 
http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/

is off line

**Comment by piotrzarzycki21** [comment]
@cristallium I recommend you to use binary distribution produced by maven on this website https://nightlies.apache.org/Royale/Royale-asjs/ or download [Moonshine SDK Installer](https://moonshine-ide.com/download-sdk-installer/) - Where you can easly install released and nightly version of Royale.

**Comment by aharui** [comment]
We usually run out of free credits around the 15th and get new free credits a few days later.  I just restarted the VM.  Looks like it is running.

From: Piotr Zarzycki ***@***.***>
Reply-To: apache/royale-asjs ***@***.***>
Date: Monday, April 18, 2022 at 6:41 AM
To: apache/royale-asjs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [apache/royale-asjs] JSOnly Nightly Build is off line (Issue #1194)


@cristallium<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcristallium&data=04%7C01%7Caharui%40adobe.com%7C4de1d85c6dfd4d0c9f0d08da21411fac%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637858860831788081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0E73G32LMwtFBleio5lpF0IGjlzS1w5aoz0NAo7BDv4%3D&reserved=0> I recommend you to use binary distribution produced by maven on this website https://nightlies.apache.org/Royale/Royale-asjs/<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnightlies.apache.org%2FRoyale%2FRoyale-asjs%2F&data=04%7C01%7Caharui%40adobe.com%7C4de1d85c6dfd4d0c9f0d08da21411fac%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637858860831788081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Eckax%2Ff3wHlS3AmKl28xiruNqNaaVaDzOEFo166WDO4%3D&reserved=0> or download Moonshine SDK Installer<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmoonshine-ide.com%2Fdownload-sdk-installer%2F&data=04%7C01%7Caharui%40adobe.com%7C4de1d85c6dfd4d0c9f0d08da21411fac%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637858860831788081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wtxxh6t4TLp5MMXhWjRcZZMrnwQsYPHCFDLK%2BIf%2FUHg%3D&reserved=0> - Where you can easly install released and nightly version of Royale.

**Comment by cristallium** [comment]
Hi All,
Many thanks for there informations and links from Maven, I didn't know about the issue of credits
