### ISSUE TITLE
Can't build project Framework: Libs: Graphics

### ISSUE THREAD

**Issue by Rileran** [apache/royale-asjs#1211]
One of the dependencies of project Framework: Libs: Graphics is `apache.royale-sdk-pixel-bender-1.0.0-bin.zip`, which is supposed to be downloaded from https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/flex/pixelbender/1.0/binaries/apache-flex-sdk-pixel-bender-1.0.0-bin.zip (see `pixelbender.download-url` in `frameworks/projects/Graphics/pom.xml`).

However the site doesn't seem to be up anymore, thus making it impossible to build the project. It would be great if somebody could update the link or provide another way to get this library.

Maybe @yishayw could have an idea on how to do this, as you left a TODO a few month ago about migrating the file to maven.

Let me know if I can provide anymore information, or help to resolve the matter.

**Comment by yishayw** [comment]
Hi Rileran, I just clicked on the link you posted above, and it looks active to me. Is the build still failing for you?

Also, I don't know if you are outputting to swf at all, but I seem to recall pixelbender was only required for swf. If you are only interested in JS output then you can configure your (maven?) build to output to JS only and that lib should not be a requirment.

**Comment by joshtynjala** [comment]
I confirm that the URL is working for me too. Perhaps it was just a hiccup in the Apache mirroring system.
