### ISSUE TITLE
Latest npm version is incomplete

### ISSUE THREAD

**Issue by phreed** [apache/royale-asjs#1219]
When I install using the instructions found at https://apache.github.io/royale-docs/get-started/download-royale does not produce a functional installation.
I am installing on Windows 11.
```
npm install @apache-royale/royale-js -g
```
In particular, attempting to run `mxmlcnpm` produces the following error.
```
mxmlcnpm : The term 'mxmlcnpm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mxmlcnpm
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (mxmlcnpm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
I looked at the contents of the `npm list -g` ... `node_modules\@apache-royale\royale-js\package.json`.
It appears that the `mxmlcnpm` is not directly available from the package but rather `mxmlc`.
That being said it does not work as the only file in the `royale-js` directory is `package.json`.
I backed off the version to `0.9.8` and the balance of the files are present.
```
npm install @apache-royale/royale-js@0.9.8 -g
```
The `mxmlc` compiler is now present.

p.s.
I was also expecting to find a `amxmlc` compiler for Air sources. 
Should it be present?

**Comment by phreed** [comment]
Looking at the developers mailing list I am not the only one who saw this issue.
https://lists.apache.org/list?dev@royale.apache.org:2022-5

**Comment by joshtynjala** [comment]
Closing. mxmlc in the latest release seems to work correctly after installing with `npm install @apache-royale/royale-js -g`

**Comment by mithilsiva** [comment]
Thank you, it saved my time
