### ISSUE TITLE
Nightly builds inaccessible

### ISSUE THREAD

**Issue by cdouine39** [apache/royale-asjs#1221]
from page https://royale.apache.org/get-involved/, there are links to the nightly builds but the links are broken : 
![image](https://github.com/apache/royale-asjs/assets/23524780/1f4199d3-f934-4ec4-a8f2-465bd6da059b)

Is there another adress from where we can get the nightly builds ?

Thanks

**Comment by piotrzarzycki21** [comment]
Probably we need update that link. You can find nightly build here -> https://nightlies.apache.org/Royale/Royale-asjs/ - 0.9.11 would be the right one.

**Comment by cdouine39** [comment]
Thanks !
