### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by Nisaba** [apache/royale-asjs#1243]
Hi,

I would want to use a REST API.
Is there an easy way to serialize / deserialize AS3 objects in JSON ?

It seems that com.adobe.serialization.json.JSON package is available in Air but not in Royale...

Thanks

**Comment by piotrzarzycki21** [comment]
@Nisaba I believe you can simply use [JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON).

**Comment by Nisaba** [comment]
Are you sure that it works with AS3 objects ?

I would want to map the json I receive from API directly to an ArraList object.
And I want to map an ArrayList to a Json that I send to the API.

I can do that manually but it's not very efficient

**Comment by Harbs** [comment]
If you want to serialize an AS3 object, you should define a `toJSON()` method and that will automatically be used to serialize the object to JSON when using `JSON.stringify()`

For an ArrayList you can do something like this:
```
public class JSONArrayList extends ArrayList{
  public function JSONArrayList(initialSource:Array=null) {
    super(initialSource);
  }
  public function toJSON():Object{
    return source;
  }
}
```

**Comment by Harbs** [comment]
Maybe we should add toJSON to the built-in ArrayList, but it's not very difficult to create a serializable version. 🤷

**Comment by Harbs** [comment]
Also, check out the `org.apache.royale.reflection.beads.JSONReviver` bead. It's used in the ASDoc project.

**Comment by Nisaba** [comment]
Yes, it works !
That was easier than I thought !   :) 
Thank you
