### ISSUE TITLE
asformat prododuces invalid code.

### ISSUE THREAD

**Issue by evilpie** [apache/royale-asjs#1249]
The following snippet:
```actionscript
package Test
{
  public function split()
  {
    var element = null;
    if (!(element instanceof TextElement))
    {
      throw new Error("error");
    }
  }
}
```
will be formatted as 
```actionscript
package Test
{
	public function split()
	{
		var element = null;
		if (!(elementinstanceof TextElement))
		{
			throw new Error("error");
		}
	}
}
```

The formatted code is invalid: `elementinstanceof TextElement`. 

Version: apache-royale-0.9.10-bin-js-swf

**Comment by joshtynjala** [comment]
Fixed in apache/royale-compiler@975a04b9073b6f14ddc5ab4ddc609ceb724f9bab

It was not included in time for the the recent Royale 0.9.12 release, but it will be in the next one.
