### ISSUE TITLE
ClassReference doesn't work in themes

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-asjs#127]
Hi,

I first tried to create a class in a theme and use it through ClassRefence. When try to use in the final App I get an error. I thought it was something in my library. Now I tried to use 

IBeadView: ClassReference("org.apache.royale.html.beads.TextFieldView")

but the result is the same:

`[INFO] Executing MXMLC in tool group Royale with args: [-load-config=/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/target/compile-app-config.xml, -js-output=/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/target/javascript, -compiler.targets=JSRoyale,SWF, /Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/src/main/royale/App.mxml]
/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT.swc:royale-jewel-blue.css(225): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT.swc:royale-jewel-blue.css(225): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT.swc:royale-jewel-blue.css(225): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.`

**Comment by carlosrovira** [comment]
Hi Alex,

I just tried this but seems still not working. If I uncomment in project "JewelTheme", file _global.sass
line 28
//fonts: ClassReference("org.apache.royale.jewel.JewelThemeFontInject")
And compile this theme and then compile JewelExample I get the same error:

[INFO] Executing MXMLC in tool group Royale with args: [-load-config=/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/target/compile-app-config.xml, -js-output=/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/target/javascript, -compiler.targets=JSRoyale,SWF, /Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/src/main/royale/App.mxml]
/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT.swc:royale-jewel-blue.css(24): col: 11 Error: org.apache.royale.jewel.JewelThemeFontInject is not defined.


/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT.swc:royale-jewel-blue.css(24): col: 11 Error: org.apache.royale.jewel.JewelThemeFontInject is not defined.


/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT.swc:royale-jewel-blue.css(24): col: 11 Error: org.apache.royale.jewel.JewelThemeFontInject is not defined.

maybe I'm missing something?

thanks for fixing this

**Comment by aharui** [comment]
Did you get the latest compiler?

**Comment by carlosrovira** [comment]
I downloaded latest commit and recompiled all (I don't see anything more to push from the repo right now)

**Comment by carlosrovira** [comment]
To avoid problems, I'll close and clean all and recompile to see that all is ok on my part
thanks

**Comment by carlosrovira** [comment]
Hi Alex, after close and restart, remove all in .m2 and check there's nothing new to download, rebuild all, My output is the same as before and the error persist.

I think I my side is all ok. You can check this easily yourself with JewelTheme and JewelExample

thanks

**Comment by aharui** [comment]
See my emails on the list.  The Maven build of the theme needs to be fixed, but I think the entire Theme needs refactoring.

**Comment by carlosrovira** [comment]
Hi Alex, don't remember talking about JewelTheme fix or refactor can you point me to the thread where you talk about this? or let me know what I must do to fix pom.xml or what needs to be refactored
thanks!

**Comment by aharui** [comment]
I sent an email on the "how to inject html" thread a while ago, but I just noticed the mail server hasn't delivered it yet.  In it I said:

  1.  To get inject_html to work, you also need the .js transpile of the class.  I fixed the Ant build to transpile JewelThemeFontInject.  I'll leave it up to you to finish the Maven build, but first read the other notes in this post.
  2.  Using inject_html on a dummy class is, IMO, a hack, and not a recommended practice.  We should implement an alternative.  I will start a new thread on this.
  3.  I adjusted the JewelExample to use themes properly via Ant.  I don't know how to get Maven to work with a single CSS file as a theme.  The current JewelTheme project probably needs to be refactored.  More on this in a separate thread.

And I have started new threads on the list:

https://lists.apache.org/thread.html/09f0c1705142521f8692f5cedd86d0235f65dfbb1de0e5f64450eff7@%3Cdev.royale.apache.org%3E
https://lists.apache.org/thread.html/6482e33ac7cac0160e7d1cbc2e4b16568ab5ff9fe10f3bbeff263b29@%3Cdev.royale.apache.org%3E

Lots to think about,
-Alex

**Comment by carlosrovira** [comment]
Hi Alex,
I think mostly responded to all this in the email thread you open in the email list, so we can continue there. I'll be removing the class that tries to inject html since we see that's not the way to go.

Regarding other classes like the one that opens this thread (org.apache.royale.html.beads.TextFieldView), I must see if I already continue having problems, since view classes should be in themes and we should not have problems to operate with them

thanks!

**Comment by piotrzarzycki21** [comment]
@carlosrovira ,

Just one thing bothers me. Are you saying that TextFieldView should be in Theme.swc - What is in module then ? There is no view ? 

Whoever would like to use Jewel and modify it - Will need to modify Theme actually ?

**Comment by carlosrovira** [comment]
Hi Piotr,

In Jewel we have all controls, and with them other classes that are added as beads (i.e: Model, Controller). Those beads are very close to the business logic and considered pieces of the business logic.

In the other hand, I expect a View and classes that defines visual artifacts (i.e: A thumb or a track) that in SWF use to be a code represented in a class, should go in the theme.swc, since are things directly related to the theme and how things are represented.

If I swap themes, I expect a track or thumb will come from the theme so the visuals change.
If comes from the library.swc that part will not be changeable, or if you use another, that part will mostly unused since the theme should have their own.

But that's seems to be a problem more related to SWF, since in JS is not normal that we have code to define a visual part of the component.

**Comment by piotrzarzycki21** [comment]
What will happen if I implement my own Theme where I have TextFieldView, doesn't have for example ButtonView and I don't load default theme ? I load only mine.

**Comment by carlosrovira** [comment]
That case will fail since there are visuals that are missed. If the case is valid is what we should decide
We can think about this how we want to define it:

1) Is the theme is incomplete?, so is up to you to complete with the needed classes to be valid.

2) Should we consider a theme can't miss any of its building pieces? (code, styles, images, assets,... We can duplicate classes in the jewel library with visuals that most of the time will never be used carrying all the weight, but in that case shall we put in the library the rest of assets (css, images,...) to avoid fail at runtime?

(fails can be of building since there's something missing like code, or at runtime, since there's some image or css that is not there and makes the visuals shows distorted)

IMO, it's a matter of separation of concerns. Conceptually visuals should be in theme and logic should be in libs, that's how I always structure projects in Flex even in final apps and modules. But I could be wrong.

**Comment by piotrzarzycki21** [comment]
In my opinion Theme should change things, what exists in the module. View should be in module, but if you load theme with variations of that view - it can be override. 

I cannot imagine that user will have to cover for example 100 components in order to have one change. 

Does Flex also resolve tings in theme like that ? I truly doubt. I have never used theme.

**Comment by piotrzarzycki21** [comment]
@carlosrovira Move that discussion with link to the comments to the Dev

**Comment by carlosrovira** [comment]
> I cannot imagine that user will have to cover for example 100 components in order to have one change.

it should n't do that. I'll start from a theme template to start changing things to a new style

@piotrzarzycki21 , anyway, this is nothing fixed for any of us, people can take a way or another. In fact, as I develop a first theme and get more experience I'll see what is better based on experience. Right now I can only talk based on my Flex theme experience in our apps and from what it should be in a theme in Royale. So let's exercise it a bit and then I'll report and we can discuss better

**Comment by piotrzarzycki21** [comment]
Changing things to a new style how ? By css ? 

Are you saying that you didn't create Theme yet ? This is the right time to talk how it can looks like. 

Answer to that question during implementation. If I load theme with some visual styles, views etc. For some reason I created my own View which is not placed in the theme - Which one will be used if I apply mine by css ?

BeadView: MyView

**Comment by carlosrovira** [comment]
Since yours is in your App, your code is the winner over the others
