### ISSUE TITLE
Add ApplicationParametersBead

### ISSUE THREAD

**Issue by Harbs** [apache/royale-asjs#129]
We added two beads in a52284cfd826b8e1a385e0e72a976fd55a2c9bf1

ApplicationParametersBead retrieves url parameters specified when loading the app.
ApplicationParametersCaseInsensitiveBead is similar, but the url parameter keys are case insensitive.

**Comment by Harbs** [comment]
Here’s a distilled example of how to use these beads:
````
<js:Application xmlns:js="library://ns.apache.org/royale/basic">
  <js:beads> 
    <js:ApplicationParametersCaseInsensitive id="parameters" />
  </js:beads>
  <js:initialView>
    <js:View/>
  </js:initialView>
</js:Application>
````
And assuming “app" is a reference to your main class you can get values like this:

`var myVal:String = app.parameters.getValue("some_val”);`

**Comment by piotrzarzycki21** [comment]
@Harbs that bead is quite handy :) What do you think to have such example in the ASDoc on top of the class or maybe as a blog post on Royale website!

**Comment by Harbs** [comment]
Including use examples in ASDoc is probably a very good idea. Blog post too.

FYI, the bead can probably be attached to any strand in the app. It should not need to be the main class.

**Comment by aharui** [comment]
How is this different from URLParameterBead?

**Comment by Harbs** [comment]
URLParameterBead:
1. Subclasses EventDispatcher
2. emits ready events
3. Returns the raw url parameters

ApplicationParametersBead:
1. Does not subclass anything
2. Does not dispatch any events
3. Parses the url parameters once and has a method for returning values from keys.

I think URLParameterBead is best for urls which might change after the app is loaded (i.e. routing)
I think ApplicationParametersBead is best for static values which don't change and fit a simple key/value pair pattern. (i.e. not hash tags and the like)
