### ISSUE TITLE
Beads in a theme's css rule are not processed

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-asjs#133]
My test are with a component that extends a Group and has a css that declared a "iViewBead", the bead is a MXML Bead that creates a simple button

1) Beads in themes are not working, only work if both (component and viewbead) are located in the same lib. Or in other terms, if the component is in a lib and its viewbead is in the theme that doesn't work. I think this is a bug and that case is not considered in the compiler.

If I assign a Bead in a lib, and one in a theme, only the one in the lib is created at runtime. If I remove the one in lib, no bead is created. So the one in the theme is compiled and goes in the theme but is not processed in the final app. 

2) With 1) working, I should be able to have a viewbead in the lib and a viewbead in the theme, and the one in theme be the one used in final app.
(the one in the lib should not be considered). As well if I have a css rule in the final App that defines another viewbead, that should be processed as well.

**Comment by aharui** [comment]
This is working for me.  The git branch seems to be confused so I'm afraid to check stuff in, but I added the LabelViewBead to the JewelTheme by adding it to defaults.css

j|Label {
  IBeadView: ClassReference("org.apache.royale.jewel.beads.views.LabelViewBead");
}

and adding it to jeweltheme-manifest.xml

 <component id="LabelViewBead" class="org.apache.royale.jewel.beads.views.LabelViewBead"/>

and added Jewel Label to the example:

            <j:Label text="Hello World" />

And the output in App.js contained:

"org.apache.royale.jewel.Label",
function() {this["iBeadView"] = org.apache.royale.jewel.beads.views.LabelViewBead},

**Comment by carlosrovira** [comment]
Hi Alex, I final could test this and now is working, don't know if is some of the fixes you did in the last days or something wrong on my side. But finally we have this working and seems a very powerful feature.
Thanks!
