### ISSUE TITLE
Provenance of AMFNetConnection.as and AMFBinaryData.as

### ISSUE THREAD

**Issue by aharui** [apache/royale-asjs#16]
AMFNetConnection and AMFBinaryData are ports from JS to AS of amf.js from https://github.com/emilkm/amfjs which is under ALv2.

If you dig through the history, you will find that the code originally came from r-amf, a project now stored at GoogleCode https://code.google.com/archive/p/r-amf/ which claims to be under a Category X license.

However, it was established in https://github.com/emilkm/amfjs/issues/17 that permission was granted to relicense the code under ALv2.

**Comment by aharui** [comment]
closing

**Comment by justinmclean** [comment]
Think this needs to be reopened as it not been resolved see [1]

1. https://lists.apache.org/thread.html/76e27c7e838a4b6f82289b856b48f8bb51f84b9d6ba8b0a2828c656b@%3Cdev.royale.apache.org%3E
