### ISSUE TITLE
Fix mx.graphics.GradientEntry

### ISSUE THREAD

**Issue by Harbs** [apache/royale-asjs#164]
I merged PR #159 too soon.

The constructor needs to be removed or the values passed into the super constructor.

**Comment by Harbs** [comment]
@alinakazi Please fix this.

**Comment by alinakazi** [comment]
https://github.com/apache/royale-asjs/pull/165 GradientEntry Constructor Deleted

**Comment by aharui** [comment]
I don't think the constructor should be removed.  I think the compiler will generate a constructor without any parameters.  I think the parameters must exist and be passed to super.

**Comment by alinakazi** [comment]
GradientEntry Constructor Added  and parameters to super.
