### ISSUE TITLE
Corrupted umlaut symbols

### ISSUE THREAD

**Issue by Sashkko** [apache/royale-asjs#183]
Instead of characters like "Ü", a question mark "?" is displayed for TextButton, Label etc.

**Comment by aharui** [comment]
Is your development machine running Windows or OS X?  The compiler relies on the Java code page.  I think you may have to set (or export) JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

If you are using an IDE, you may have to convince the IDE to start up with those options.

**Comment by neminovno** [comment]
In my case it is Windows and Visual Studio Code with has by default `"files.encoding": "utf8"`

**Comment by aharui** [comment]
Royale uses a different compiler than Apache Flex and calls third-party JS optimization code.  It is great that Visual Studio Code is configured to output UTF-8, but if VSCode isn't a Java process and/or is forking a process to run the compiler, the compiler may not be running in a JRE configured for UTF-8.  AIUI, the JAVA_TOOL_OPTIONS sets the configuration for the JRE.

**Comment by neminovno** [comment]
```
C:\>set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
```
restart VSC, run project, still lost chars.

It should be dash in "UTF-8" ?
```
C:\>set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
```
restart VSC, run project, still lost chars.

In Terminal output there is one and UTF-8 related error:

> 
> com.google.javascript.jscomp.LoggerErrorManager println
> SEVERE: ERROR - Cannot read file C:/dev/royale-projects/royale-test/bin/js-debug/HelloFlexJS.js: Failed to read: C:\dev\royale-projects\royale-test\bin\js-debug\HelloFlexJS.js, **is this input UTF-8 encoded?**
> 
> com.google.javascript.jscomp.LoggerErrorManager printSummary
> WARNING: 1 error(s), 0 warning(s)
> The project 'HelloFlexJS' has been successfully compiled and optimized.
> 4.472022255 seconds
> 
> Terminal will be reused by tasks, press any key to close it.


NOTE: Probably related [issue](https://github.com/apache/royale-asjs/issues/117).

**Comment by neminovno** [comment]
As I understand google closure is used, and "is this input UTF-8 encoded?" string is found here in [SourceFile.java](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/SourceFile.java#L616)
Maybe that can help in fixing this issue.

**Comment by neminovno** [comment]
Tried copy first line from Terminal and running it from command line:
`C:\dev\royale-projects\royale-test>C:\ProgramData\Oracle\Java\javapath\java.exe -Dfile.encoding=UTF-8 -jar .......`
but no help. Noticed there is no "is this input UTF-8 encoded?" error when runned from cmd. 
Files build but still no UTF-8 chars. After manually checking files encoding noticed:
_js-debug/index.html_ is UTF-8, but 
_js-debug/HelloFlexJS.js_ is ANSI encoded.

**Comment by aharui** [comment]
If you used the JAVA_TOOL_OPTIONS environment variable, then when running from the command line, you should see console output that says: "Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8"

If you are seeing that and the output is still ANSI then attach your source file and I will try it on my Windows computer.

**Comment by neminovno** [comment]
It works ok when JAVA_TOOL_OPTIONS is set, and run from command line.
![image](https://user-images.githubusercontent.com/1468887/38895259-d2aaa3c8-428f-11e8-9eb0-a3e225335664.png)

But how to set it for VSC? Anyway shouldn't this be fixed somehow within tooling, and not to request all users to set this environment variable in order to use UTF-8 which is world wide common standard?

**Comment by piotrzarzycki21** [comment]
Are you building some example or just created tests APP ?

**Comment by piotrzarzycki21** [comment]
I'm wondering if in Moonshine it will work, because we are just using CMD to launch things.

**Comment by neminovno** [comment]
@piotrzarzycki21 I am using code posted above. I just tried to test it in Moonshine but can't set SDK..
![image](https://user-images.githubusercontent.com/1468887/38899772-4ae76444-4299-11e8-89b5-d3bc54be8a18.png)

@aharui Thanks for info and help. IMHO to avoid current and future encoding problems (been there many times) UTF-8 should be used 'everywhere'.

**Comment by piotrzarzycki21** [comment]
@neminovno what folder of downloaded SDK are you pointing ? You should point royale-asjs.

I just tested it in Moonshine and all components displays good text with JAVA_TOOL_OPTIONS set.

**Comment by neminovno** [comment]
@piotrzarzycki21 I have set SDK, run it, and same as in VSC, UTF-8 chars are lost, so it looks JAVA_TOOL_OPTIONS must be set.

**Comment by piotrzarzycki21** [comment]
It looks like released version Moonshine 1.10.0 do not pickup for some reason JAVA_TOOL_OPTIONS, but upcoming version 1.11.0 is working fine. At least what is happened on my machine.

**Comment by piotrzarzycki21** [comment]
We will release 1.11.0 probably this week.

**Comment by Sashkko** [comment]
Thanks, I use Flash Builder 4.7 as IDE and I added "JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8" to the environment variables and umlauts now displayed correctly.

**Comment by neminovno** [comment]
As test shows, this is fixed in latest VSCode. No need to set JAVA_TOOL_OPTIONS.

**Comment by piotrzarzycki21** [comment]
It looks like we have a solution. I'm closing that one.
