### ISSUE TITLE
RemoteObject requests in Firefox do not work for release application with accessing by URL

### ISSUE THREAD

**Issue by Sashkko** [apache/royale-asjs#189]
If run release application in Firefox browser by URL like `http://localhost:8085/hello/index.html` - remote object requests do not work. But if run this release application as file like `file:///D:/workspace/HelloWorld/bin/js-release/index.html` - remote object requests work. 
This problem applies only in Firefox (my version 59.0.2 (64 bit)) and when accessing the application by URL. But in Google Chome remote object requests works well. On server side configured BlazeDS under Tomcat 8.5.15.

Message in Firefox web-console (partitially translated from my local language):
`Code map error: SyntaxError: JSON.parse: unexpected character at line 7 column 1 of the JSON data URL resource: http://localhost:8085/hello/HelloWorld.js URL code map: ./HelloWorld.js.map`

Example:
```

<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
				xmlns:js="library://ns.apache.org/royale/basic"
				xmlns:local="*" pageTitle="HelloWorld" applicationComplete="application1_applicationCompleteHandler(event)">
	<fx:Script>
		<![CDATA[
			protected function application1_applicationCompleteHandler(event:Event):void
			{
				service.send("echo", ["echo response"]);
			}

			protected function onResult(event:ResultEvent):void
			{
				console.log("result: "+event.data);				
			}
			
			protected function onFault(event:FaultEvent):void
			{
				console.log("fault: "+event.message);
			}
		]]>
	</fx:Script>

	<js:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</js:valuesImpl>
	
	<js:beads>
		<js:ClassAliasBead/>
		<js:RemoteObject id="service" result="onResult(event)" fault="onFault(event)"
						 endPoint = "http://localhost:8085/messagebroker/amf"
						 destination = "hello-controller" 
						 source = "hello-controller"/>
	</js:beads>
	
	<js:initialView>
		<js:View width="100%" height="100%">
			<js:Container width="100%" height="100%">
				<js:beads>
					<js:HorizontalFlexLayout/>
				</js:beads>
				<js:Label text="Hello World"/>
			</js:Container>	
		</js:View>
	</js:initialView>
</js:Application>
```

**Comment by aharui** [comment]
What is the URL of the server?  This sounds more like a security/CORS issue.

**Comment by aharui** [comment]
We could set up something on the CI server, but does that really solve the problem?  It is one thing to run an our example against our test server, but I think everyone's real question is how to get it to work on their server.

**Comment by carlosrovira** [comment]
No, my request is to make easy for us to develop more AMF examples and see that we don't break anything, and as well for people to see that AMF is working. I think is good to have an example online.
People that wants to run AMF needs to deal with java servlet containers and make it run with all the info about this kind of stuff that is online, I think our problem is ensure that given a standard web app with BlazeDS libraries and some classes exposed, that's working right in debug and release, and that we cover all possible kinds of data transfers (strings, numbers, collections, back and forth...)

**Comment by aharui** [comment]
@carlosrovira Feel free to set up a server on http://apacheroyaleci.westus2.cloudapp.azure.com.  The credentials are on the private@ list.

**Comment by aharui** [comment]
@Sashkko A test using our example (RemoteObjectAMFTest and SampleAmfWebApp) worked fine in release application using localhost.  I suppose you could try removing the .js.map file and even look for which file loads it and kill the line that loads it, and see if that exception is somehow causing a problem.

Have you tried the 'debug' version?  It would help to know if it is only the release optimization that causes it to fail.

**Comment by aharui** [comment]
There isn't anything serving port 80.  Not sure if that can be changed or not.  Jenkins is running on port 8080.  You could set up BlazeDS on some other port.  I think you need to use Microsoft Remote Desktop to access the server.  The credentials are on the private mailing list.

**Comment by carlosrovira** [comment]
I think this was fixed with all the changes made some days ago
