### ISSUE TITLE
ArrayList Iteration with "for each" statement produce more loops than items 

### ISSUE THREAD

**Issue by saggelopoulos** [apache/royale-asjs#220]
The for each statement on ArraylLst produce more loops than item on ArrayList.
     var ar:ArrayList = new ArrayList;
    ar.addItem(new String("some value"));
    var index:int=0;
    for each (var obj:Object in ar)
    {
           index++;
    }
    trace ( "for each iteration ="+ index);
    index =0;
    for (var i:int=0;i < ar.length ;i++)
    {
           index++;
    }
    trace ("for iterations =" +index);
                               
    the console output : 
    
    16:26:13.431 Language.js:237 for each iteration =52
    16:26:13.432 Language.js:237 for iterations =1

**Comment by aharui** [comment]
ArrayList is not iterable (ArrayCollection/ListCollectionView are, as is Array).  I think you'll get 0 instead of 52 in Flex.

We could add code to return 0 as well, but I'm not sure how high a priority that is.

**Comment by carlosrovira** [comment]
Hi Alex, can we make ArrayList can be used with for each? is something to do in compiler? or just to do in ArrayList class?

**Comment by greg-dove** [comment]
I was planning to work on this next week (not specific to ArrayList and no
extra code in ArrayList) along with some other changes - I also need to
find a solution for removing externalizable support from ArrayList or
making it opt-in.
I'll do it in a branch for review.

**Comment by carlosrovira** [comment]
Hi Greg!, that sounds very good :)

**Comment by aharui** [comment]
As usual, this sort of functionality should be PAYG.  But also, I'm not convinced we should support iteration of objects, or if we do, we need to be explicit about that it means.

I have concerns over whether it will always be possible to iterate over an object on all future runtimes and target languages (or iterate efficiently).  Do we want to guarantee that the number of properties iterated will be the same on all future platforms/languages?  I hope not.

I think iteration on certain objects could be implemented in JS by a bead in a PAYG manner.  But if you are going to do that, it might be better to implement a more Java-like iterator interface instead.

My 2 cents.

**Comment by piotrzarzycki21** [comment]
To me iterate over ArrayList using for each loop is just unnecessary loose time for some small fish and we have probably bigger one to get on. I'm pretty busy this week and didn't jump into RM mode and during that time some of you could jump into Alex's instruction for release and maybe make it happen - This is the BIG fish to fry. 
I'm not opposing of course, but if that feature can bring problems in the future as Alex said better not have it or definitely have it as PAYG manner.

**Comment by carlosrovira** [comment]
Hi,

I think we're talking just about ArrayList - for each issue. I think that is widely used in Flex for ArrayCollection, that was one pain point in our migration having to change lots of loops that uses for each for iterate a collection. So for me is something very important.

Piotr, I think we count on you to be the first RM, Greg is working in other important stuff right now and I'm trying to fix latest Module issues that are as well really important for users trying to do a serious migration and as well want to continue on Docs. So I think we all have many tasks on the plate and are very busy. I think our current "formation" is right to accomplish the actual targets :)

**Comment by greg-dove** [comment]
Addressed in latest updates
