### ISSUE TITLE
The NPM install for royale-js-swf does not allow -y, --yes or other ways to confirm automatically

### ISSUE THREAD

**Issue by jgranick** [apache/royale-asjs#230]
In order to use `royale-js-swf` on a build or continuous integration server, it is necessary to be able to say "yes" to the install prompt automatically. I believe the "prompt" NPM library is already being used, so it would be great to add support for overriding:

https://www.npmjs.com/package/prompt#skipping-prompts

Using `yes | npm install` on a Linux install works, but returns an error code due to the way it interacts with NPM, so that also breaks our builds.

Thank you :smile:

**Comment by bigosmallm** [comment]
The download dependencies code runs as a postInstall script during the npm install lifecycle.  I am not sure if we can pass params to an `npm install` call.
This ticket: https://github.com/npm/npm/issues/8431 was closed a a `wont fix` :-(

Would setting up env variables be a valid option for you?

**Comment by jgranick** [comment]
Using an environment variable may be the best technical solution to this at the moment, it's a pity that `argv` isn't passed forward. It might make sense to still add the `argv` override method, in case a `-y` could be forwarded in the future, or if someone is manually running `npm run postinstall` later. The key here is we could install in a headless way for continuous integration testing or our build server :smile:

Thank you so much for your help!

**Comment by bigosmallm** [comment]
Understood.  I will try to get this one working soon and we can test it.

**Comment by bigosmallm** [comment]
Added check to see if `ACCEPT_ALL_ROYALE_LICENSES` env var is set.  Let's track the prompt -y option as a separate issue if needed.  I believe this should satisfy the automated build usecase.
