### ISSUE TITLE
RemoteObject needs to have exactly the same properties in server and client objects

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-asjs#236]
Using AMF/RemoteObject you can bring Typed objects from a backend (Java, PHP, ...) that has more properties in the server class that the ones we have in AS3 counterpart class. Said in other words, AS3 class can have all properties in the backend, or only a subset. This is very common and in Flex the deserialization works flawlessly. In Royale the first case (same properties in both side) works, but the second one fails.

**Comment by piotrzarzycki21** [comment]
@carlosrovira what will happen if you make AS3 class dynamic ?

**Comment by carlosrovira** [comment]
Hi Piotr, I did not try "dynamic" not Transient. Just the same objects we have in our application that is working in Flex. in AMFBinaryData.as there's a else that goes that route. I solved the current case, we should try as well marking as dynamic. But since the fix was a try-catch needed, I think it should work.
