### ISSUE TITLE
Issues when porting Starling

### ISSUE THREAD

**Issue by jgranick** [apache/royale-asjs#246]
We have been trying to build Starling using Apache Royale. Currently we have successfully released the Haxe->JS version of Starling using ActionScript @externs, but this is an attempt to move Starling out of JavaScript back to ActionScript, and to compile the full library.

With workarounds, we're at the point of resolving circular references and some other runtime issues, but we wanted to share some of the issues that occurred along the way. My apologies about making a "super issue" with multiple items.

## openfl.errors.Error/flash.errors.Error

ActionScript has top-level `Error`, `ArgumentError` and other error types. OpenFL supports them using `openfl.errors.Error`, `openfl.errors.ArgumentError` and so on. We can resolve this problem by making these types global or by adding imports to code that uses them, but the compiler has a `NullPointerException` when using `openfl.errors.Error`, due to the name collision with `Error` in the compiler.

_Workaround: Removed `import openfl.errors.Error` and commented code that relied on `error.errorID`_

EDIT: Issue created here: https://github.com/apache/royale-asjs/issues/249

## Custom namespace

I do not recall the error, but the `starling.core.starling_internal` namespace was resulting in errors in the compiler.

_Workaround: Replaced `starling_internal` with `public` and commented the relevant `import` and `use` code_

EDIT: Issue created here: https://github.com/apache/royale-asjs/issues/251

## Importing within the same module

Here is an example of what occurred, this resulted in errors in the compiler:

```
package test {
    public class ClassA {
        ...
    }
}
import test.ClassA;
class ClassB {
    ...
}
```

_Workaround: Removed the import reference (represented by `import test.ClassA` in the example)_

EDIT: Issue created here: https://github.com/apache/royale-asjs/issues/250

## ||=

Use of the `||=` operator resulted in errors within the compiler. For example:

```as3
target._tinted ||= _tinted;
```

_Workaround: Converted code to avoid use of the operator:_

```as3
if (!target._tinted) target._tinted = _tinted;
```

EDIT: Issue created here: https://github.com/apache/royale-asjs/issues/252

## XML

I assume that XML (E4X) is not supported as it is not available in the browser, but a lot of ActionScript code relies on it. Are there recommended workarounds? Plans for a compiler-based workaround?

## Base classes defined in an SWC

Using base extern classes as defined in an SWC was causing null exceptions in the compiler. Perhaps this is because no Google Closure JS files were generated for these types.

_Workaround: Switched to pointing to @externs \*.as files instead of an \*.swc_

## super()

At runtime, issues were experienced where a class instance did not have the members of it's super-class. It was revealed that the problem was that the class did not call `super()` in its constructor, thus the issue. Should this be implied in the Royale output, if the constructor does not call `super()`? 

## Reproduction

The current state of the code (with workarounds) is available online.

It currently requires a development version of OpenFL for NPM:

```
git clone https://github.com/openfl/openfl
cd openfl
npm install
npm run build -s
npm link
```

Then the remaining source files are all bundled in a test repository (where we can edit Starling's core files, etc)

```
git clone https://github.com/jgranick/StarlingAS3Test
cd StarlingAS3Test
npm install
npm link openfl
npm start -s
```

**Comment by jgranick** [comment]
Regarding `super()`, the class had none:

```as3
        public function Demo()
        {
            if (stage) start();
            else addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
        }
```

Upon inspection, it appears that the prototype chain is properly set up, the instance just hasn't run the parent constructor, so initialization has not occurred. Perhaps this is an expected behavior? It's tricky for us because `Sprite` in Flash Player doesn't require `super()`

**Comment by aharui** [comment]
What does the output look like?  In the test case for #234, I now have:

```
public class App extends Sprite {
   public function App()
   {
   }
}
```

resulting in:

```
/**
 * @constructor
 * @extends openfl.display.Sprite
*/
App = function() {
   App.base(this, 'constructor')
}
```

The "App.base" is the Google Closure Library equivalent of super() and should run the constructor function of the base class.  But if your base class is "external" then maybe the way Closure's "base" call works won't find the base class constructor.

**Comment by jgranick** [comment]
Actually, in one test where I've tried to reproduce it, I am getting the same output with and without `super()`, so perhaps there's a chance that this was an issue with 0.9.2 that is resolved in 0.9.3, or it's more difficult to reproduce.

**Comment by aharui** [comment]
Post at least a constructors of the JS for the base class and extended class.  I can then step through it and see if the "base" call should work or not.

**Comment by Harbs** [comment]
I just tested and JS does not support it. You get an "Unexpected token =" error.

We probably need to output `LEFTOPERAND = LEFTOPERAND || RIGHTOPERAND` instead of `LEFTOPERAND ||= RIGHTOPERAND`.

**Comment by jgranick** [comment]
I've opened new issues with more specific error output and test cases. Thanks :smile:
