### ISSUE TITLE
xml bug

### ISSUE THREAD

**Issue by matrix3d** [apache/royale-asjs#248]
找不到类型或类型不是编译时常量: XML。

**Comment by Harbs** [comment]
You need the XML swc to use XML in Javascript.

**Comment by matrix3d** [comment]
pls give me a command line

**Comment by matrix3d** [comment]
thanks

**Comment by Harbs** [comment]
What are you using? Make sure you include the frameworks/libs folder in your library path. Are you using the royalelib argument?

**Comment by Harbs** [comment]
Do you resolve this? Can we close this issue?

**Comment by Harbs** [comment]
Try adding the following argument:
`royalelib=%FLEX_HOME%\frameworks`

Also `targets` should be `JSRoyale`

**Comment by matrix3d** [comment]
col: 3 警告: public var may not work in minified JS output.  Use getter/setter instead.

		public var y:Number;

**Comment by matrix3d** [comment]
the public var ,can not work?

**Comment by matrix3d** [comment]
@Harbs 
command line 错误: 配置变量“royalelib”未知。

**Comment by matrix3d** [comment]
-library-path+=D:\sdk\apache-royale-0.9.8-bin-js\royale-asjs\frameworks\js\libs\XMLJS.swc
Could not find file for class: org.apache.royale.debugging.throwError
错误: 找不到文件: org.apache.royale.debugging.throwError


内部错误: java.lang.RuntimeException: Unable to find JavaScript filePath for class: org.apache.royale.debugging.throwError org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:638)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:667)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:667)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:667)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:656)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:656)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:656)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:656)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:656)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:656)org.apache.royale.compiler.internal.graph.GoogDepsWriter.buildDB(GoogDepsWriter.java:327)org.apache.royale.compiler.internal.graph.GoogDepsWriter.getListOfFiles(GoogDepsWriter.java:111)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:472)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:442)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:259)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:216)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:363)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:298)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:256)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:238)


6.3512122 seconds
Build halted with errors.
