### ISSUE TITLE
Where to download Flash Builder?

### ISSUE THREAD

**Issue by dogofpavlov** [apache/royale-asjs#253]
I'm sorry to create an issue for this, but lots of your directions refer to Flash Builder. But I can find no where online to download Flash Builder. I know it's part of the creative cloud, but the app isn't listed (though is if you have it installed).

**Comment by dogofpavlov** [comment]
sorry I found it, Apparently there is a "show older apps" option in the creatieve cloud which brings back Flash Builder.

**Comment by bigosmallm** [comment]
@dogofpavlov We do have a mailing list for questions like these: users@royale.apache.org :-)
