### ISSUE TITLE
col: 3 警告: public var may not work in minified JS output. Use getter/setter instead.

### ISSUE THREAD

**Issue by matrix3d** [apache/royale-asjs#260]
col: 3 警告: public var may not work in minified JS output. Use getter/setter instead.

**Comment by Harbs** [comment]
You can disable that warning with the compiler option:
`-warn-public-vars=false`

For code that's not used in MXML or string literals, you can safely ignore that warning.

**Comment by matrix3d** [comment]
but the code can not get release output

**Comment by Harbs** [comment]
Why not?

As long as you don't use mxml, or bracketed access (i.e. foo["baz"]), it will work fine.

**Comment by matrix3d** [comment]
i do not know

**Comment by Harbs** [comment]
>As long as you don't use mxml

I mean the public vars in mxml.

**Comment by matrix3d** [comment]
pls look at the proj.i have no idea.

**Comment by matrix3d** [comment]
https://github.com/matrix3d/spriteflexjs

**Comment by Harbs** [comment]
Are you saying the minified code does not work, or are concerned about the warning?

**Comment by piotrzarzycki21** [comment]
@matrix3d if you change that variable to get/set you will get rid of that warning.

**Comment by matrix3d** [comment]
i am saying Are you saying the minified code does not work.

**Comment by piotrzarzycki21** [comment]
@matrix3d do you have some proof that public variable has better performance in AS3 and JS ? Please provide here.

**Comment by matrix3d** [comment]
I have tested that flexjs getter has poor performance and posted a post at flexjs forum. But it doesn't matter whether the performance is good or not. I don't want to talk about performance.

But public VaR is more concise and requires only one line of code, while getter and setter require more than 5 lines of code.

And the way to write public VaR is a way of writing AS3. No compiler should write this warning.

**Comment by aharui** [comment]
The defaults for Royale send the JS output through the Google Closure Compiler minifier.  There, public vars get renamed and if the public vars represent external data, the app will not work.  So our compiler defaults are set up for that.  Vars are much faster than get/set functions since get/set functions incur function call overhead, but it is much harder to debug failures due to public variable renaming.

And that's why we give you options to suppress the warning in code.  We realize not everybody will need it.  But the warning has already saved us much time.

**Comment by bigosmallm** [comment]
@matrix3d Thanks for providing a link to your project repo.  If you can also provide steps to build and run the app, we can try to repro this issue.

Alternatively, you can write a small program that recreates this issue and add a link here.

**Comment by matrix3d** [comment]
D:\projs\git\spriteflexjs\test>D:\sdk\apache-royale-0.9.2-bin-js\royale-asjs/js/bin/asjsc.bat src\TestHungryHero.as -warn-public-vars=false -external-library-path+=lib\* -source-path+=../src -js-compiler-option="--compilation_level SIMPLE_OPTIMIZATIONS" -js-output-optimization=skipAsCoercions -remove-circulars -external-library-path+="D:\sdk\apache-royale-0.9.2-bin-js\royale-asjs\js\libs\js.swc" -external-library-path+=D:\sdk\apache-royale-0.9.2-bin-js\royale-asjs\frameworks\js\libs\XMLJS.swc -targets=JSRoyale -define=CONFIG::as_only,false -define=CONFIG::js_only,true

**Comment by Harbs** [comment]
@matrix3d There is a new compiler option called `-js-dynamic-access-unknown-members`. Setting it to true prevents renaming of untyped variables. It should eliminate the vast majority of minification problems.

**Comment by matrix3d** [comment]
js-dynamic-access-unknown-members”未知。
where download the sdk?

**Comment by matrix3d** [comment]
again.
严重: ERROR - Cannot read file D:/proj/spriteflexjs/trunk/test/bin/js-debug/flash/accessibility/AccessibilityImplementation.js: Failed to read: D:\proj\spriteflexjs\trunk\test\bin\js-debug\flash\accessibility\AccessibilityImplementation.js, is this input UTF-8 encoded?

**Comment by Incubatio** [comment]
As it was stated public var generates warnings.
I'm running royale via npm scripts.

Even if the js sources seem to compile fine, npm abruptly interupts the execution just after the compilation. It seems that it returns an error code, either that or npm is misinterpreting it as an error code.

That said adding ```-warn-public-vars=false``` fixed the problem for me.

**Comment by Harbs** [comment]
Have you tried the suggestions here? https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

**Comment by matrix3d** [comment]
内部错误: java.lang.NullPointerException org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:280)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:359)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:359)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:345)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:359)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:359)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:345)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:345)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:345)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:345)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sort(GoogDepsWriter.java:254)org.apache.royale.compiler.internal.graph.GoogDepsWriter.getListOfFiles(GoogDepsWriter.java:98)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:392)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:384)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:240)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:197)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:363)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:299)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:258)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:240)

**Comment by Incubatio** [comment]
@matrix3d have checked that all your dependencies are up to date ?
(java version, etc ...)
I got my first experience with royale using https://github.com/openfl/openfl-samples-as3 , it at least allow me to have a clean start with working examples.
Can you run those ?

Also note in the end that royale was not an ideal solution for me, as it required a bunch of modification before i was able to compile a small part of my projet, and even there i'm not really satisfied because the js it generates is far worse than any other generator.
I think i'm gonna try to move my source to haxe, and depending on what you expect, you might want to do the same.

**Comment by piotrzarzycki21** [comment]
@Incubatio it would be great if you could share your experience on Royale Dev list.

**Comment by Incubatio** [comment]
@piotrzarzycki21, hmm i don't know if my experience is worth your dev list.
I'm not sure royale has been designed for my case at all.
Maybe you could confirm that for me before i subscribe to your devlist.

My case is a ~30k lines as3, 3D game.
The two situations I was willing to use royale-js for were:
1. port / duplicate the game logic to my node.js server.
2. port the whole game to js for a html5/webgl release.

I feel royale is meant mostly for former flex user and flex app scope, am I wrong ?

**Comment by matrix3d** [comment]
https://youtu.be/6mKdmKJqEK4


I have already rolled back to flexjs. I don't really agree with the practice of royale. Why do you want to warn public var for some kind of problem? And to correct the code plus compile parameters? Instead of adding warnings to public var parameters? And flexjs has no problem with utf8 at all. And royale will have this problem. Why add java compiler parameters, not integrated into sdk.

**Comment by piotrzarzycki21** [comment]
@Incubatio I cannot put Royale into some box, that is suits to Flex only. I don't feel like that. However I'm also not an expert from the compiler sight and this is actually all about. You probably can get much more information on dev list.

**Comment by piotrzarzycki21** [comment]
@matrix3d What kind of practice specifically do you mean ? Could you share with us on dev list ?

**Comment by matrix3d** [comment]
@pentapache hi,i not good at english.and what do you mean?where is the dev list?

**Comment by Harbs** [comment]
> My case is a ~30k lines as3, 3D game.
> The two situations I was willing to use royale-js for were:
> 
> port / duplicate the game logic to my node.js server.
> port the whole game to js for a html5/webgl release.
> I feel royale is meant mostly for former flex user and flex app scope, am I wrong ?

A lot of our focus is on components because there's a lot of demand for that, but there's many aspects of Royale. We definitely would like more participation in the "core" which is the compiler and language features. The "core" seems to be a good fit for what you're doing.

> Also note in the end that royale was not an ideal solution for me, as it required a bunch of modification before i was able to compile a small part of my projet, and even there i'm not really satisfied because the js it generates is far worse than other generator i'm used to work with.

We want to make Royale have the best experience and have the best output. I would be very interested in knowing what was difficult and what the issue was with your output.

**Comment by Harbs** [comment]
@matrix3d 
> I have already rolled back to flexjs. I don't really agree with the practice of royale. Why do you want to warn public var for some kind of problem? And to correct the code plus compile parameters? Instead of adding warnings to public var parameters?
The reason for the warning was for classes which will be used in MXML. If that's not a concern for you, you can disable the warnings. That's what the compiler option is for. I have this warning disabled for all my projects. If you can come up with a better solution that will support MXML files, I'd be very happy to hear.

> And flexjs has no problem with utf8 at all. And royale will have this problem. Why add java compiler parameters, not integrated into sdk.

It's probably a bug. Without help from folks like you, it's going to be difficult to fix it. If you have a proposed solution to the UTF8 issue, please make a PR.

**Comment by matrix3d** [comment]
I am just a AS3 developer. Then every time you update SDK, you will add some odd parameters to use. Then I could not allow the new SDK to compile my project successfully, nor did bug correct it. Although flexjs has stopped updating. But it can indeed be successfully compiled. I don't want to use flexjs either, but I can't help it.

**Comment by matrix3d** [comment]
Why do you mainly focus on HTML and CSS? Why not learn such compilers as haxe, typescript, dark, coffescrpt and so on. None of these compilers is targeted at HTML CSS, because HTML CSS is good enough. These compilers are directed at typescript to JS. I think your idea is very strange. Do not want to turn AS3 to JS, do not go to HTML.

**Comment by Incubatio** [comment]
@Harbs, @carlosrovira, Alright, i have a tight deadline and will subscribe to dev list and share my experience in the next days.

Just for the update, yesterday I got curious about google closure with nodeJs (I didn't knew it was possible). After updating code in my as3 and generated js, I was able to port / duplicate the game logic to my node.js server.
Porting the whole game will probably be a greater challenge, mostly if I keep using external swc.

**Comment by carlosrovira** [comment]
@matrix3d, for me html/js/css is a need for my current work. And will be great for Royale to be able to add TypeScript language with MXML, so people can use AS3 or TS with MXML. But again, is just a matter of people interested in making this possible like you. As my case, I needed a UI set that looks good, and for that reason I spend latest year creating Jewel. You can do the same and jump the boat and start contributing TS, WASM or what ever you want, we need it! :)

@Incubatio great! :) we'll waiting for you in Dev list and to your contributions! As well, very cool to know what you get with Google closure and NodeJS, that talent will be very welcomed in Apache Royale team! :)

**Comment by mshaffer12882** [comment]
I think this topic should be started in its own thread, but just to add to the topic....

I think that most AS3 developers are looking for a solution to have their AS3 code to run in the native browser, without having to rewrite everything in TypeScript, Haxe, etc.  With the web changing to native and end of life for flash in 2020 more and more developers will be looking for the most simplistic way to achieve this.  That's why I started following projects like FlexJS and Google Swiffy years ago and now following projects like Royale, spriteflexjs, and OpenFL.  I think most of the code base that people are looking to convert is pure AS3, while I think MXML is important, I think its more important to support pure AS3 because of the amount of code bases that require this.  I think both spriteflexjs and OpenFL are very close to using Apache Royale so this can be achieved, but there are some outstanding issues that need to be addressed to accomplish this.

**Comment by Harbs** [comment]
@matrix3d I just created a pull request which makes spriteflexjs compatible with the latest build of Royale. https://github.com/matrix3d/spriteflexjs/pull/22
