### ISSUE TITLE
BlazeDS Trunky Server 

### ISSUE THREAD

**Issue by radubirsan** [apache/royale-asjs#264]
Adobe provided a Turnkey Server that had working samples of BlazeDS technology.
http://www.softpedia.com/get/Internet/Servers/Server-Tools/BlazeDS.shtml
Implementing a example Royale client that connects to this samples would be great.

**Comment by carlosrovira** [comment]
Hi Radu,
BlazeDS is now part of Apache Flex, and was upgraded with many patches and things since 2014 (the date of that url).

The samples in our repository are more up to date with versions newer so I recommend you to check the examples and the wiki page and see if you can run it. Otherwise please let us know what problems you find in your way so we can help you or see if we must to improve something.

Thanks

**Comment by radubirsan** [comment]
I get this error when trying to build:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:53 min
[INFO] Finished at: 2018-07-30T13:49:49+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project SampleAmfWebApp: Could not resolve dependencies for project org.apache.royale.examples:SampleAmfWebApp:war:0.9.3-SNAPSHOT: Failed to collect dependencies at org.apache.royale.examples:RemoteObjectAMFTest:war:0.9.3-SNAPSHOT: Failed to read artifact descriptor for org.apache.royale.examples:RemoteObjectAMFTest:war:0.9.3-SNAPSHOT: Could not find artifact org.apache.royale.examples:examples:pom:0.9.3-20180729.230525-270 in apache-snapshots (https://repository.apache.org/content/repositories/snapshots) -> [Help 1]

**Comment by radubirsan** [comment]
I tried to run a "mvn clean install" and I got:

 sampleamfwebapp: Could not resolve dependencies for project org.apache.royale.examples:sampleamfwebapp:war:0.9.2: Could not find artifact org.apache.royale.examples:RemoteObjectAMFTest:war:0.9.2 in apache-release (https://repository.apache.org/content/repositories/releases)

**Comment by carlosrovira** [comment]
Hi, current version numbers are 0.9.3 not 0.9.2
You must ensure you are completely synchronized to latest commits and then follow this guide:
https://github.com/apache/royale-asjs/wiki/Build-Apache-Royale-with-Maven

as well for preparing you dev environment if you're in Mac I recommend you:

https://github.com/apache/royale-asjs/wiki/Apache-Royale-OS-X-development-environment-in-five-minutes

**Comment by carlosrovira** [comment]
Hi, the second link is just the way I use to configure my Mac for development, but is not a requirement. Only a convenient, easy and fast way of configuration.

To install only Xcode command line tools without Xcode I just find this link:
http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

try it and see if that solves your problem. I didn't try to install it without Xcode, but seems it's possible.

For windows of course you can config it as well, but as I'm on Mac maybe others can help you that have more experience with that.
