### ISSUE TITLE
DataContainer does not support ArrayList

### ISSUE THREAD

**Issue by yestaro** [apache/royale-asjs#272]
`[Bindable]`  
`private var myList:ArrayList = new ArrayList(["AAA","BBB"]);`
`<j:DataContainer dataProvider="{myList}" />`

Then output as below, it does got two items, but ItemRenderer can't get data to paint.

`<div class="layout vertical" style="overflow: hidden;">`
`<span class=""></span>`
`<span class=""></span>`
`</div>`

Test on 0.9.3 nightly build $1180

**Comment by carlosrovira** [comment]
Thanks for reporting. DataContainer needed the bead "DataItemRendererFactoryForCollectionView" that is capable to manage Collections instead "DataItemRendererFactoryForArrayData" that only can handle simple Arrays
