### ISSUE TITLE
ReferenceError: int is not defined

### ISSUE THREAD

**Issue by Incubatio** [apache/royale-asjs#273]
this line triggers the runtime error (in the title):
```as 
var a:Object = { a: int, b:int, c:int, d:int };
```
Obviously javascript doesn't have int or uint.
Maybe the the compiler could replace int and uint by Number in such case ?

In other cases int is just get trimmed out normally.

**Comment by greg-dove** [comment]
Just a quick update...  
I have a proposed solution (which covers a number of general cases beyond the issue highlighted here) that also addresses this issue.
These assertions pass with the related code updates in the compiler and the framework:
https://github.com/apache/royale-asjs/blob/improvements/Language/manualtests/UnitTests/src/main/royale/flexUnitTests/github/GithubIssues2018.as#L56

This is in a separate branch at the time of posting this comment. I'll review it with others and hopefully it will make it into a future release.

**Comment by greg-dove** [comment]
Fixed and merged into develop
