### ISSUE TITLE
Error al compilar ImagePlayGround

### ISSUE THREAD

**Issue by Alvarad0** [apache/royale-asjs#293]
Al compilar el proyecto me marca los siguientes errores:

home/developer/Documentos/Programación/ApacheRoyale/royale-asjs/examples/royale/JewelExample/src/main/royale/ImagePlayGround.mxml(58): col: 5 Error: This tag is unexpected. It will be ignored.

                                <j:ImageButton id="imageButton" src="assets/royale_spheres.png" click="imageButtonClick(event)"/>
                                ^

/home/developer/Documentos/Programación/ApacheRoyale/royale-asjs/examples/royale/JewelExample/src/main/royale/ImagePlayGround.mxml(59): col: 5 Error: Child tag 'mxmlContent' bound to namespace 'library://ns.apache.org/royale/jewel' is already specified for element 'Card'. It will be ignored.

                                <j:Label id="imageButtonResult" text="Image is an input type='image' tag in html"/>
                                ^

/home/developer/Documentos/Programación/ApacheRoyale/royale-asjs/examples/royale/JewelExample/src/main/royale/MainContent.mxml(65): col: 13 Error: This tag is unexpected. It will be ignored.

            <j:ImageButton src="assets/apache-royale-jewel-logo-white.svg" height="140" click="goToHome()"/>
            ^

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.203 s
[INFO] Finished at: 2018-09-11T16:11:19-05:00
[INFO] Final Memory: 50M/657M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.royale.compiler:royale-maven-plugin:0.9.3-SNAPSHOT:compile-app (default-compile-app) on project JewelExample: There were errors during the build. Got return code 3 -> [Help 1]
[ERROR]

Si comento las lineas donde aparece ImagePlayGround en el archivo MainContent.mxml lo compila pero no me muestra la imagen del logo en el sidebar.

Lo curioso es que hace como dos horas que estaba trabajando con el proyecto funcionaba correctamente, luego baje la ultima versión por los commits que subieron el dia de hoy y fue que dejo de funcionar.

**Comment by carlosrovira** [comment]
Hola Alvaro, 

ImageButton lo subí ayer justo a esa hora, entiendo que debiste actualizar el ejemplo, pero no la librería Jewel. 

Hasta ahora teníamos el componente "Image" (en html es un tag "img"), ahora tenemos también "ImageButton" (en html sería un in input type="image"). En este último el cursor sería una mano para indicar que la imagen es en realidad un botón y puedes hacer click.

Si actualizas hoy no deberías tener problemas.

**Comment by piotrzarzycki21** [comment]
@carlosrovira what was all about ? :)

**Comment by carlosrovira** [comment]
Hi Piotr,

seems Alvaro download changes in JewelExample but not in Jewel. Yesterday I added ImageButton, and he reports a compilation fail. He need to update both projects to compile ok and get access to ImageButton in JewelExample

**Comment by Alvarad0** [comment]
Gracias @carlosrovira volví a compilar los proyectos Compiler, Typedefs y Framework con maven y funciono correctamente, lo curiosos es que ayer hice lo mismo y seguía marcando el mismo error, pero ya me funciono. Gracias :) :+1:
