### ISSUE TITLE
DateField doesn't select current date in DateChooser when date previous selected

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#30]
Date in DateField can get out of sync with date selected in DateChooser.

![2017-10-13_18-00-32](https://user-images.githubusercontent.com/144504/31534047-dc572234-b040-11e7-88a1-32cbb5c2f88a.png)

Steps to reproduce:
1. Open DateChooser and select date
2. Change date in DateField
3. Open DateChooser again

Sample code to reproduce:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic" xmlns:beads="org.apache.flex.html.beads.*"
                xmlns:accessories="org.apache.flex.html.accessories.*">

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>
    
    <js:initialView>
        <js:View>
            <js:Group id="content">
                <js:DateField>
                    <js:beads>
                        <accessories:DateFormatDDMMYYYYBead />
                    </js:beads>
                </js:DateField>
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>
```

**Comment by pentapache** [comment]
I am not able to reproduce this in the royale-asjs repo using the code as written (with change from "flex" to "royale" to get it to work).

**Comment by justinmclean** [comment]
Re step 2 I mean manually type in a different date - did you try that?

**Comment by Harbs** [comment]
DateField currently has no date validation for text typed in.

I'm not sure what the intent is.

If the intent is to only pick a date from the chooser, editing the field should be disabled.

If the intent is to allow the user to type in a date, the date should be validated and set.

**Comment by pentapache** [comment]
I think the default DateField out of Basic should not have an editable text field. I could see adding a DateInputValidatorBead to DateField (and maybe even to TextInput) that allows a date to be entered. That however, brings up a pattern-matching input editor. Like: "DD MM YYYY" sort of thing which could be applied to any TextInput component, really. In other words: default is not editable; add a bead to make it editable. I'd say an input editor is significant work unless there's a donated editor someone in the Apache realm we can use.
