### ISSUE TITLE
DateField model missing text in date field

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#31]
Currently it's a little cumbersome to get hold of the text typed into a date field and you need to know what class the view is.

For instance:
` dateFieldText = (dateField.view as DateFieldView).textInput.text;`

Full example:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic"
                xmlns:accessories="org.apache.flex.html.accessories.*">

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <fx:Script>
        <![CDATA[
        import org.apache.flex.html.beads.DateFieldView;

        public function showDate():void {
            selectedDate.text = dateField.selectedDate.toDateString();
            typedDate.text = (dateField.view as DateFieldView).textInput.text;
        }
        ]]>
    </fx:Script>

    <js:initialView>
        <js:View>
            <js:Group id="content">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:DateField id="dateField">
                    <js:beads>
                        <accessories:DateFormatDDMMYYYYBead />
                    </js:beads>
                </js:DateField>
                <js:TextButton text="Show Date" click="showDate()" />
                <js:Label id="selectedDate" />
                <js:Label id="typedDate" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>

```

**Comment by justinmclean** [comment]
Why is this invalid? A little more detail should be given before closing issues IMO.

**Comment by Harbs** [comment]
It's an edge use-case, and like you say, the contents of the text input can be accessed by addressing the view.

The important bit in the component is the selected date. The string that is displayed is just the view representation of that. I have no idea why you would even need to read the value. You have the Date and can format the selected date any way you like.

We do need better documentation on components and their standard beads, but that is a more general problem we're working on and not specific to this case.

**Comment by justinmclean** [comment]
IMO you quite often would need to get at the text.

For example:

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

    <js:beads>
        <js:ApplicationDataBinding />
    </js:beads>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:Group id="content" width="300" height="200">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:DateChooser id="dc" />
                <js:Label text="You booked for the {dc.model.formattedDate}" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>
```
Obviously this isn't going to work. And neither is trying to format something the same way a date is formatted like so:

```
                <js:Label text="{dc.selectedDate}">
                    <js:beads>
                        <accessories:DateFormatDDMMYYYY />
                    </js:beads>
                </js:Label>
```

**Comment by yishayw** [comment]
Like Harbs and you already said, there’s a way to do this in the current implementation. Another way is this [1]. Is your issue that you need to use binding? If so, you should create your own bead that exposes this as a bindable prop.

[1] https://github.com/yishayw/Examples/tree/DateField

________________________________

**Comment by Harbs** [comment]
Alternatively, you can subclass the component and add whatever bindable properties you like.

Even in Flex, I very often subclassed components to add properties and make them work exactly how I like.
