### ISSUE TITLE
Compilation Error using ant File (shmColumnList)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#319]
Error: https://paste.apache.org/2FJs
 https://www.dropbox.com/s/9xpcq5u8sww2p8f/shmColumnList.mxml?dl=0

**Comment by aharui** [comment]
Hard to say.  I've never seen errors there before.  My guess is that the build commands are not specifying the correct source and library folders so the compiler cannot parse the files.

**Comment by aharui** [comment]
[alina.zip](https://github.com/apache/royale-asjs/files/2489770/alina.zip)

Here is a sample project that uses Ant to build a library project and an application that uses the library.  Change the folder in env.properties and local.properties as needed.

**Comment by alinakazi** [comment]
I have tried alina.zip and compiled successfully.
Added my files to the "app" renamed as "applications" .
Internal error Occurred : 
    [mxmlc] 752000 bytes written to D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\alina\applications\target\Applications.swf in 16.962 seconds
    [mxmlc] 20.07706414 seconds
    [mxmlc] Internal error: java.util.NoSuchElementException java.util.ArrayList$Itr.next(ArrayList.java:854)com.google.common.collect.Iterators.getOnlyElement(Iterators.java:308)com.google.common.collect.Iterables.getOnlyElement(Iterables.java:294)org.apache.royale.compiler.clients.MXMLJSCRoyale.se
tupTargetFile(MXMLJSCRoyale.java:696)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:314)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:250)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:207)org.apache.royal
e.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:365)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:300)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:259)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:241)
    [mxmlc]
    [mxmlc]

BUILD FAILED
D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\alina\build.xml:32: The following error occurred while executing this line:
D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\alina\applications\build.xml:59: mxmlc task failed.

**Comment by alinakazi** [comment]
Thanks alot

**Comment by aharui** [comment]
[alina 2.zip](https://github.com/apache/royale-asjs/files/2496624/alina.2.zip)

Here is a version with a simple module
