### ISSUE TITLE
mxmlc gets  java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#320]
[mxmlc] Compiling file: D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\bin-debug\com\shm\bin\js-debug\com\shm\components\shmColumnList
    [mxmlc] Internal error: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory org.apache.commons.io.FileUtils.validateListFilesParame
oogPublisher.getDirectoryResources(JSGoogPublisher.java:290)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublis
e._mainNoExit(MXMLJSCRoyale.java:250)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:207)org.apache.royale.compiler.clients.MXMLJ
MLJSC.staticMainNoExit(MXMLJSC.java:259)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:241)
    [mxmlc]
    [mxmlc]
    [mxmlc] D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\src\com\shm\components\shmColumnList.mxml(41): col: 88 Warning: Data binding wi
    [mxmlc]
    [mxmlc]                                     <mx:CheckBox selectedField="isSelected"  change="onChange(event);" selected="{data.isSelected}">
    [mxmlc]                                                                                                                       ^
    [mxmlc]
    [mxmlc] D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\src\com\shm\components\shmColumnList.mxml(50): col: 27 Warning: Data binding wi
    [mxmlc]
    [mxmlc]                                     <mx:Label text="{data.label}" />
    [mxmlc]                                                          ^
    [mxmlc]
    [mxmlc] shmColumnList as: [mx.collections.ArrayCollection, shmColumnList, mx.managers.PopUpManager, org.apache.royale.events.ValueChangeEvent]
    [mxmlc] shmColumnList mxml: [spark.components.List, org.apache.royale.core.ClassFactory, shmColumnList, shmColumnList_component0, mx.controls.CheckBox, mx.c
nt, org.apache.royale.events.MouseEvent]
    [mxmlc] find project folder for d:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma/src/com/shm/components/shmcolumnlist.mxml
    [mxmlc] checking source path D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\src\com\shm\components
    [mxmlc] not found on source path, using parent file D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\src\com\shm\components
    [mxmlc] 10.479532274 seconds

BUILD FAILED
D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\build.xml:157: The following error occurred while executing this line:
D:\apache-royale-0.9.3-bin-js-swf\royale-asjs\examples\mxroyale\shma\build.xml:102: mxmlc task failed.

**Comment by aharui** [comment]
Unfortunately, the output appears to be clipped.  There are partial words and lines have been cut-off so it is impossible to determine what is going on.

It appears that you are trying to build your code inside the repo folder.  This is risky in that if you are not careful, you might commit your company's code to the repo.  You should work in folders outside of the repo.  Copy the folder structure including examples/build_examples.xml.  You may have to set some Ant properties but it will eventually work and be safer.
