### ISSUE TITLE
private static vars not compiled correctly

### ISSUE THREAD

**Issue by Harbs** [apache/royale-asjs#351]
[The following code here](https://github.com/apache/royale-asjs/blob/develop/frameworks/projects/TLF/src/main/royale/org/apache/royale/textLayout/utils/CharacterUtil.as#L79) compiles to:

````
org.apache.royale.textLayout.utils.CharacterUtil.isWhitespace = function(charCode) {
  return org.apache.royale.textLayout.utils.CharacterUtil.org_apache_royale_textLayout_utils_CharacterUtil_whiteSpaceObject[charCode];
};

org.apache.royale.textLayout.utils.CharacterUtil.whiteSpaceObject = org.apache.royale.textLayout.utils.CharacterUtil.org_apache_royale_textLayout_utils_CharacterUtil_createWhiteSpaceObject();
````
`whiteSpaceObject` is not defined due to the mismatch between `whiteSpaceObject` and `org_apache_royale_textLayout_utils_CharacterUtil_whiteSpaceObject`

**Comment by Harbs** [comment]
@aharui I believe that static vars should not be qualified because there should not be conflicts with subclasses.

**Comment by aharui** [comment]
Calls to formatPrivateName should be gated by a check to see if the property is static.  Feel free to scan the code and find where the checks are missing.

**Comment by Harbs** [comment]
It looks to me like AccessorEmitter is the only class which has this check. Can I assume that I can use isStatic() to check?

**Comment by aharui** [comment]
I didn't check them all, but ClassEmitter looks like it has a check higher up.  Other's might too, but it sure sounds like at least one is missing.  isStatic() should work.

**Comment by Harbs** [comment]
Fixed in https://github.com/apache/royale-compiler/commit/766894f68efad6f72d67c7e4c1fd8c5d01500f7c
