### ISSUE TITLE
Application.url is undefined

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#352]
Hi,
I am debugging my application.mxml file in visual studio code and file launched on firefox on this url
http://localhost:8080/SHMA/index.html
but the debug console have a TypeError 
TypeError: this.url is undefined

1) our shmApplication is extending mx:Application,
2) Opening and Closing tag of application.mxml is shmApplication
we use this.url in application.mxml
why url is undefined
is some functionality related to url is missing in mx:Application file?

**Comment by aharui** [comment]
Yes, if you look at mx/core/Application.as, you can see that the "get url()" won't return anything.  I would recommend adding a COMPILE::JS block with the code that will return the url.

**Comment by pashminakazi** [comment]
I have added get url property in COMPILE::JS block of class mx.core.Application.as 
But same TypeError
TypeError: this.url is undefined

**Comment by aharui** [comment]
What code did you add?  What is the stack trace?

**Comment by aharui** [comment]
Also, make sure you delete your bin/js-debug folder when changing framework classes.  The compiler will not replace existing files with new ones.

**Comment by pashminakazi** [comment]
Stack Trace:

unreachable code after return statement                                                           SystemManager.js:196
SyntaxError: expected expression, got ','
invalidateParentSizeAndDisplayList not implemented                                       Language.js:238
invalidateParentSizeAndDisplayList not implemented                                       Language.js:238
unreachable code after return statement                                                           SystemManager.js:196
TypeError: this.url is undefined                                                                           Application.js:54


do you want me to return my actual url in compile js block in mx:Application file?

**Comment by aharui** [comment]
You should implement the correct general way to return the url for anyone who uses mx:Application and commit that change to the repo.  I think it would be:

COMPILE::JS
{
return location.href;
}

What is code is at Application.js line 54?  What you provided above is the console output, not a call stack.

Again, make sure you have deleted your bin/js-debug folder before re-compiling the application.  I have to stop working for tonight.
