### ISSUE TITLE
Httpservice is not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#354]
Example File : https://paste.apache.org/kfa5

Issue: 
Function f_LoadConfiguration is working 
first line of function is a Alert which is shown in output Alert.show("f_loadConfiguration Called");

but httpservice is not working that's why Alert of result handler or Fault handler doesn't called

**Comment by aharui** [comment]
I believe that mx:HttpService is working in Tour De Flex.  It may not handle resultFormat=xml.  You can debug into Tour De Flex to see how it works and compare to your application.

**Comment by pashminakazi** [comment]
In tour De Flex mx:Httpservice is used in FileIOHelper class which is excluded from build file so i think its not working

**Comment by aharui** [comment]
It appears to be used in SourceTab.mxml and which is working, AFAICT.

**Comment by olafkrueger** [comment]
> but httpservice is not working...

Just a shoot in the dark:

You set `f_LoadConfigurationRH` as event listener:
`httpSrv.addEventListener(ResultEvent.RESULT,f_LoadConfigurationRH);`

but you implemented a static function as event handler:
`private static function f_LoadConfigurationRH(event:ResultEvent):void`

Shouldn't it be?: 
`httpSrv.addEventListener(ResultEvent.RESULT, MY_CLASS.f_LoadConfigurationRH);`

or 
`private function f_LoadConfigurationRH(event:ResultEvent):void`

Maybe this helps, but I could be totally wrong of course ... ;-)

**Comment by aharui** [comment]
I'm pretty sure statics are in scope of the instance methods and the compiler should generate the right code.

**Comment by alinakazi** [comment]
Thanks @olafkrueger  and @aharui
