### ISSUE TITLE
MenuBar DataProvider Issue

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#356]
We have a mx:MenuBar when we assign XMLList type dataProvider to it.
We got an error on console :
TypeError: mx.controls.beads.models.MenuBarModel.superClass_.get__dataProvider.apply(...) is undefined

**Comment by aharui** [comment]
Does it work if the dataProvider is not an XMLList?

When you get an exception, please always provide the call stack.  There is often critical useful information in the call stack.

In this case, I recommend looking in the debugger to see if the superClass is ArraySelectionModel.  Also check the .js files for MenuBarModel and ArraySelectionModel and see if they have get__dataProvider methods.

**Comment by alinakazi** [comment]
After your changes in develop branch for dataProvider of type  XMLListCollection in mx:MenuBar.  Now its working.
