### ISSUE TITLE
Module not working with Latest Apache Release and not with latest develop Branch

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#359]
Module shown blank in browser when below given example is compiled with latest Apache Royale release  0.9.4 in December 2018.

Blank output in browser when below given example is compiled with latest develop branch https://github.com/apache/royale-asjs/tree/develop/

Example :https://github.com/alinakazi/Examples/tree/master/ParentApplication%20property/HelloWorld
We have final deadline : 10-Jan-2019 . We will demonstrate some of the modules of our Application and those should be fully functional. 

MenuBar with XMLList type dataprovider, module loading, grid with customtype Dataprovider, parentApplication property. All these are mandatory to work property.

**Comment by aharui** [comment]
Is tourdeflexmodules working for you?  It seems to be working for me.

**Comment by alinakazi** [comment]
Yes tourdeflexmodules  was working for me with Latest Release.
After copying tourdeflexmodules  build.xml from  latest release  to my example build.xml .
Module is now working fine in my Example.
