### ISSUE TITLE
Develop branch currently broken and unable to compile with maven

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#36]
[ERROR]   The project org.apache.royale.compiler:debugger:0.9.0-SNAPSHOT (/Users/justinmclean/royale-compiler/debugger/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin net.sourceforge.jburg:jburg-maven-plugin:1.10.4 or one of its dependencies could not be resolved: Could not find artifact org.apache.royale.compiler:compiler-jburg-types:jar:1.1.0-SNAPSHOT in apache-plugins-snapshots (https://repository.apache.org/content/repositories/snapshots) -> [Help 2]

Moving to the rename branch on royale-compiler fails to fix the issue as it fails to compile.

**Comment by piotrzarzycki21** [comment]
Hi @justinmclean ,

Please try to build first in compiler - projects: compiler-jburg-types and compiler-build-tools.

Piotr

**Comment by justinmclean** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project compiler: Compilation failure: Compilation failure:
I did (and they compile) and it still fails with:
[ERROR] /Users/justinmclean/royale-compiler/compiler/target/generated-sources/antlr/org/apache/flex/compiler/internal/parsing/as/ASParser.java:[32,1] package org.apache.flex.compiler.tree.as does not exist

**Comment by piotrzarzycki21** [comment]
Did you able to build it at all when you are on branch feature/rename in, royale-compiler, royale-typedefs and royale-asjs ? 

Just wanted to know whether we will have problems once Harbs merge rest of the branches to develop.

**Comment by justinmclean** [comment]
I was on develop in royale-compiler and feature/rename in the other two repos I would expect the same issue if I was on all feature/rename branches and it's been merged into develop on royale-compiler but I'll give it a try tomorrow.

**Comment by justinmclean** [comment]
Updated develop branches now compile but some compiler tests are failing I'l raise another issue for that.

in royale-compiler:
mvn clean install -P utils
mvn clean install -D skipTests-true

In royale-typedefs:
mvn clean install 

In royale-asjs:
mvn clean install
