### ISSUE TITLE
With Apache Royale Latest Source

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#361]
We have downloaded latest src from develop branch 
**Following Issues are fixed :** 
1.Module & Module Loader are working fine with latest source
2.mx:MenuBar is working fine with XMLLIstCollection type dataprovider.

**But some issues occurred  with latest source are:**
1. We are unable to build our library project that we were able to build before : 
Build.xml : https://paste.apache.org/vA1k
2. ClassAliasBead is not working in latest source as we are unable to connect with our java/server side source now again.

**Comment by carlosrovira** [comment]
I can let you know that ClassAliasBead, AMF and RemoteObject continue working without issue. Latest issue was some weeks ago when some change in compiler causes an issue with "info" property AFAIK...that was addressed at that time

**Comment by pashminakazi** [comment]
our Library Project build file was using sdk library mxroyale.swc,sparkroyale.swc and etc
now in new release mxroyale.swc doesn't exist so errors on console were
mx.utils.ByteArray definition not found and all other classes not found
so i changed the lib path from
E:\apache-royale-0.9.3-bin-js-swf\royale-asjs\frameworks\libs
to
E:\apache-royale-0.9.3-bin-js-swf\royale-asjs\frameworks\js\libs
and changed mxroyale.swc to mxroyaleJS.swc now my Library can use the file of sdk without error

My Library Project Build File: https://paste.apache.org/HIH0
Now my library project is giving this Error
Console: 
https://paste.apache.org/C1H5

**Comment by aharui** [comment]
I am still confused.  The subject is about "latest sources", but your post above mentions "new release".  Both should generate or contain mxroyale.swc, but it is hard to help you when we don't know what configuration you are trying.

Are you building from sources, using the nightly build, or something else?  
Where are you looking for mxroyale.swc?
If the build from sources of royale-asjs does not produce an mxroyale.swc, that implies that the build is running in "js-only" mode, where there is no Flash playerglobal/airglobal.swc.  That should be ok if you are not interested in SWF output.

And if you are building in "js-only" mode, then yes, importing flash classes will not work and you will need to wrap those imports in COMPILE::SWF blocks or remove those imports.

**Comment by alinakazi** [comment]
We are building from sources.
Can someone please provide library project build.xml example that is working with Apache Royale Latest Source on github. So, we can compare it with our library project build.xml.

Now whenever we see any commit related to functionality we need. We download latest src from github to progress in achieving our target.

**Comment by aharui** [comment]
All of the SWCs in frameworks/js/projects and frameworks/projects are library projects with build.xml files.

**Comment by aharui** [comment]
If you are still getting the same errors posted earlier, then it is probably related to having environment variables that point to a valid playerglobal.swc and Adobe AIR SDK, if you had been using those before.  Otherwise, you will need to get rid of the imports of flash classes.

I'm at the end of my workday, so if you have further questions, hopefully somebody else will help.

**Comment by alinakazi** [comment]
Thanks alot. After setting goog home and playerglobal variable its working fine now.
