### ISSUE TITLE
Menubar works separately but not with other controls & components

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#362]
Working Example of Menubar : https://paste.apache.org/ez4g

file:///E:/apache-royale-0.9.3-bin-js-swf/royale-asjs/examples/mxroyale/HelloWorld%20-%20Copy/bin/js-debug/index.html

This Example shows Menubar but unable to click it : https://paste.apache.org/OloA

file:///E:/apache-royale-0.9.3-bin-js-swf/royale-asjs/examples/mxroyale/HelloWorld/bin/js-debug/index.html

What's the reason?

**Comment by aharui** [comment]
It looks like the Grid below the MenuBar in MXML may actually overlay the MenuBar.  If it doesn't have to overlay the menubar, try switching the order of the two MXML tags.  The last one goes on top of the one before it.

You can also try specifying CSS pointer-events on the div for the Grid and its children.
