### ISSUE TITLE
Could not find file for class: number  

### ISSUE THREAD

**Issue by iftikharrasool** [apache/royale-asjs#364]
I am getting this issue while compiling an example. 
 
Internal error: java.lang.RuntimeException: Unable to find JavaScript filePath for class: number org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:599)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:628)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:628)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:628)org.apache.royale.compiler.internal.graph.GoogDepsWriter.buildDB(GoogDepsWriter.java:303)org.apache.royale.compiler.internal.graph.GoogDepsWriter.getListOfFiles(GoogDepsWriter.java:111)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:421)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:438)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:265)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:222)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:365)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:300)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:259)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:241)

**Comment by piotrzarzycki21** [comment]
Hi @iftikharrasool,

Which example are you trying to compile ?

**Comment by iftikharrasool** [comment]
Actually I am trying to compile a self created example of our existing project which we are migrating on royale.

**Comment by aharui** [comment]
Scan the output js files in bin/js-debug for "goog.require('number')"

Attach the js file and the corresponding AS file.

**Comment by pashminakazi** [comment]
shmAttachmentPopup is our library mxml file which we are using in our application
shmAttachmentPopup.mxml : https://paste.apache.org/RYie
shmAttachmentPopup.js : https://paste.apache.org/hOlP
in this file goog.require('number') is present and it is causing error on console 
 [mxmlc]  Error: File not found: number
 [mxmlc] Could not find file for class: number
