### ISSUE TITLE
NumericStepper will show zero even when initial value is above zero

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#37]
If you set the minimum value (like 1) to a value the model gets updated but the existing value doesn't and stay at the default zero.

Code to reproduce:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic">


    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:Group id="content">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:NumericStepper id="ns" minimum="1" maximum="10" stepSize="1" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>
```
Even though the minimum is set to 1 0 is displayed like so:
![2017-10-18_17-01-33](https://user-images.githubusercontent.com/144504/31703293-bf435600-b427-11e7-9a86-e4e12f2d486e.png)

**Comment by Harbs** [comment]
I'm not convinced that this is an issue. If the minimum is above zero, I think it's reasonable that it should be required to specify an initial value.

**Comment by piotrzarzycki21** [comment]
@Harbs,

Are you saying that if someone set minimum=1 we should not make checks but rather sets initial value to 1 ? In that case you mean those initial value should set the framework not an user ?

**Comment by Harbs** [comment]
No. I'm saying that the framework should not do anything to the value when changing the minimum. It's the user's responsibility to make sure the initial value makes sense.

**Comment by piotrzarzycki21** [comment]
In Flex setting minimum means also that the initial value would be the same and for me it is quite natural. Have you seen any numeric stepper which behave as you said ? 
If you have strong will to have working numeric stepper like that, let's start discussion on Dev.

**Comment by Harbs** [comment]
Natural? Yes. Necessary? Not really.

It does not seem very PAYG to me to always check the value when setting the minimum and specifying the minimum in the app does not seem like a big deal to me.

Maybe this could be a feature of an express NumericStepper.

**Comment by piotrzarzycki21** [comment]
To be clear I'm not saying that RangeModel should do that, maybe more specific model. Agree with you let's have NumericStepper as light as it is possible and implement such things in the express package. :)
