### ISSUE TITLE
 Error: Unable to resolve resource bundle 'formatters'

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#371]
Console : https://paste.apache.org/57CK
Console: [output.txt](https://github.com/apache/royale-asjs/files/2749335/output.txt)
I am getting this Error on Console while compiling my application
 Error: Unable to resolve resource bundle 'formatters'

**Comment by aharui** [comment]
This has been discussed on the dev@ list.  Search the framework source and your source for [ResourceBundle("formatters")]

Comment out any that are not commented out.
