### ISSUE TITLE
AdvancedDataGrid doesn't work

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#373]
I am using mx:AdvancedDataGrid in my Application file.
it is compiled without Error but AdvancedDataGrid doesn't show
Example : https://paste.apache.org/rp0b
 
I also Compiled Tourdeflex AdvancedDataGridExample it's also not working

**Comment by aharui** [comment]
It would be best if your example contained sample data.  ADG can handle lots of different kinds of data.   I will work on the TDF ADG.

**Comment by pashminakazi** [comment]
Thanks Alex.
I have one more question Sorry for that
mx:TabBar doesn't set the mx:dataProvider for ViewStack
I have ViewStack with 3 navigatorContent
Can I replace ViewStack with TabNavigator And NavigatorContent with VBox and Remove TabBar??
or mx:TabBar will work for me with mx:dataProvider?

**Comment by aharui** [comment]
mx:TabBar was not in the list of components in the reports Alina provided, so nobody has bothered to make it work yet.  You are welcome to get it to work.

You should be able to replace a TabBar + ViewStack combination with TabNavigator.  There might still be bugs that need fixing.

**Comment by aharui** [comment]
TDF's AdvancedDataGrid should be working now

**Comment by pashminakazi** [comment]
Hi Alex,
In AdvancedDataGridItemRenderer,You Removed validateProperties Method SetStyle Property
Now I am getting Error on Console While Compiling my Library
https://paste.apache.org/fBpy

**Comment by aharui** [comment]
Please be more specific than just saying it "is not working".  Did you build it yourself?  Or are you running it from http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/TourDeFlexMigration/lastSuccessfulBuild/artifact/examples/mxroyale/tourdeflexmodules/bin/js-debug/index.html

Are there errors?  What are they?

The example at the link is working, but I noticed the build finished about 4 hours ago so maybe you checked too soon.  If you are building from sources, did you clean out the bin/js-debug folder first?

**Comment by aharui** [comment]
You can re-add the emulation of the APIs you need as long as the example still works.
