### ISSUE TITLE
MenuBarExample Please Help me

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#375]
I have uploaded my MenuBar Example with Java Code
Example : https://github.com/pashminakazi/MenuBarExample-For-Java
It's hard to give you my java source with config files and connection files
I just make a simple Java file with 1 Menubar label..
Paste my Java Menubar into your Java File and compile my Example with Java
and tell me why MenuBar doesn't show MenuBar and Please Solve my Problem

**Comment by aharui** [comment]
Before you send in server code and ask us to set all of that up, it is best to first try to simulate the server in the example.  You know what the server response looks like, so add a button to your example that when you click on the button it runs the same code as the result handler of your service.  IIRC, you get a String back from the server.  

Doing this also makes sure there is no actual server dependency to the problem.

**Comment by aharui** [comment]
To be more specific, in your Java version, I would add to fn_AppMenusRH a 
trace(e.message.body.toString()) or some way to see the exact string being returned from the server.

Then add a button that calls a new fn_AppMenusRH_Manual that looks like this:

private var someString= whatever the string was from the server

protected function fn_AppMenusRH_Manual():void {
	         trace("manual resulthandler called");
	         var menubar:XMLList = new XMLList(someString);		
		     menuDataProvider = new XMLListCollection(menubar);	
		     trace(menubar);
		     trace(menuDataProvider);
		     appView.APPMenu.enabled = true;

This should result in the same problem and then we can help you debug it without trying to set up your server.  And if it doesn't exhibit the same problem, make sure the string is exactly the same, especially with whitespace and line-breaks.

And if it still doesn't exhibit the problem, you now have a working and non-working code paths that should be very similar so you can compare them.
