### ISSUE TITLE
Building Royale SDK

### ISSUE THREAD

**Issue by LudvikWiejowski** [apache/royale-asjs#386]
Hello, maybe I do not understand the build process , but I have difficulties to build SDK so it's working for both, JS and SWF. I went through instructions in README files and it seems to me that instructions in downloaded 0.9.4 (JS+SWF) are outdated.
When using "npm install @apache-royale/royale-js-swf -g" it fails because link to flashplayer 25 does not work anymore.

When trying to do it via "ant -f InstallAdobeSDKs.xml" where I changed it manually from 25 to 32, which is working, but SWF output is not working when adding SDK to Visual Studio Code. When adding SDK to VS, it says (JS only).

Are there any actual instructions how to build SDK for mac?

**Comment by piotrzarzycki21** [comment]
Hi @LudvikWiejowski,

First question why are you trying to build on your own SDK ? If you need newest features you can use nightly build.

**Comment by carlosrovira** [comment]
Hi @LudvikWiejowski 

I used the following .sh to build on Mac every day:

https://gist.github.com/carlosrovira/768c312d6652866b14262a5c13319eaf

You can take it an customize as you need. It syncs three repos and build with maven, the generate the SDK with ANT

This could be useful too:

https://github.com/apache/royale-asjs/wiki/Apache-Royale-OS-X-development-environment-in-five-minutes

**Comment by LudvikWiejowski** [comment]
Thanks Guys, I finally make it work.
