### ISSUE TITLE
Some Css Styling Issues

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#389]
Hi,
I have issues with my Application's login page and Main Form

1) When I Press capsLock button of Keyboard Nothing happens
Example: https://paste.apache.org/sdia

2) In MenuBar there's no spacing between MenuItems, I will send you screenshots of Both MenuBar
Flex and Royale
Flex: 
![image](https://user-images.githubusercontent.com/42200979/51607069-764d0e80-1f35-11e9-990f-868eda075952.png)

Royale: 
![image](https://user-images.githubusercontent.com/42200979/51607100-8c5acf00-1f35-11e9-897a-004fc9a2e086.png)

3) In my login page and MainForm there is a white space showing in Top, Bottom, Left, Right.
In Flex Grids, BorderContainer, and Module are aligned but In Royale, they are not Aligned.

Flex: 
![image](https://user-images.githubusercontent.com/42200979/51607335-2e7ab700-1f36-11e9-872d-b4bcffc6c1db.png)

Royale: 
![image](https://user-images.githubusercontent.com/42200979/51607303-23c02200-1f36-11e9-9379-5eb2463d60a4.png)

4) In Flex Grids and BorderContainer have a Black Border surrounded the Grid and BorderContainer So, it
looks like a Proper Grid In Royale there's no Border of GridRow 
Flex: 
![image](https://user-images.githubusercontent.com/42200979/51607335-2e7ab700-1f36-11e9-872d-b4bcffc6c1db.png)

Royale: 
![image](https://user-images.githubusercontent.com/42200979/51607303-23c02200-1f36-11e9-9379-5eb2463d60a4.png)

Please implement the Functionalities of these Problems

**Comment by aharui** [comment]
I encourage you to attempt to fix these yourself.  For caps lock, it looks like Royale can use https://caniuse.com/#search=getModifierState to determine the caps lock state.

You can try adding CSS for MenuBarItemRenderer in MXRoyale's defaults.css to add some paddingLeft/paddingRight

You can examine and edit the CSS in the browser debugger and figure out what CSS needs to change to align the application then make the appropriate changes in MXRoyale's defaults.css.

You can do the same for BorderContainer and Grid.  I think BorderContainer's CSS goes in SparkRoyale's defaults.css.

**Comment by aharui** [comment]
Try adding a constructor with a typeNames="MenuBarItemRenderer".  If you are not sure how, search for "typeNames" in other classes.

**Comment by pashminakazi** [comment]
I am unable to fix CapsLock.
And I am using AdvancedDataGrid in my Application 
File : https://paste.apache.org/gYvR
Data which is Returned From Java Method is of VO type
public List<shmCompanySetupVO> fn_GetCompListDP() 
So AdvancedDataGrid doesn't set the data
![data](https://user-images.githubusercontent.com/42200979/51969447-3c7c8a80-2496-11e9-80c3-3ae9a3eb2c80.png)
