### ISSUE TITLE
Numeric stopper unable to step in 0.1 (or other units other than whole numbers)

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#39]
This code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic">


    <fx:Script><![CDATA[
        public function clicked():void {
            ns.minimum = 5;
            ns.value = 1;
        }
        ]]></fx:Script>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:Group id="content">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:NumericStepper id="ns" minimum="0" maximum="1" stepSize="0.1" />
                <js:TextButton text="Change minimum and value" click="clicked()" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>
```

Is forever stuck on 0 and the step arrow does nothing.

The issue is caused by this line in the model's snap function as Math.round is used:
`var n:Number = Math.round((value - minimum) / si) * si + minimum;`

**Comment by justinmclean** [comment]
Well it seems you can get it to mostly work if you also set the snapInterval to be 0.1 but then not all values are whole multiple of 0.1 you get values displayed like 0.30000000000000004 and 0.7000000000000001.

**Comment by Harbs** [comment]
Your code has a bug. You are setting the minimum to higher than the maximum.

**Comment by justinmclean** [comment]
Here's a better example that show the issue - please reopen.

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:NumericStepper width="300" minimum="0" maximum="1" stepSize="0.1" snapInterval="0.1" />
        </js:View>
    </js:initialView>

</js:Application>
```

![2017-10-28_02-19-47](https://user-images.githubusercontent.com/144504/32111558-8b66e64c-bb86-11e7-9ef2-b32b046dcc61.png)

**Comment by justinmclean** [comment]
Or if you prefer I can create another issue?

**Comment by Harbs** [comment]
The problem is due to floating point arithmetic. `0.2 + 0.1 = 0.30000000000000004` in JavaScript.
Multiplication has the same issue: `3 * 0.1 = 0.30000000000000004`

This results in both the stepping and the snapping to work not as expected.

I'm not sure what the right solution is to this problem. This is a problem both in the `SpinnerMouseController.incrementClickHandler()` and in the `RangeModel.snap()` functions. There are likely other classes which suffer from similar issues.

This seems like a potential problem for a which range of components, but introducing overhead for whole numbers does not seem right.

**Comment by justinmclean** [comment]
Please reopen. The fix while in the right direction it's not covering all cases for example:

 <js:NumericStepper width="300" minimum="1" maximum="2" stepSize="0.1" snapInterval="0.1" />

![2017-10-29_08-03-32](https://user-images.githubusercontent.com/144504/32138526-d8be0b6a-bc7f-11e7-996f-148bedf398be.png)

**Comment by justinmclean** [comment]
Another better example:
<js:NumericStepper width="300" minimum="0" maximum="15" stepSize="1.5" snapInterval="1.5" />

**Comment by Harbs** [comment]
Both of those cases work fine. (If you want the initial value to be 1 in the first case, you can either use the Express component, or specify a value of 1 explicitly.

An example which does *not* work with my fix is:
`<js:NumericStepper width="300" minimum="0" maximum="15" stepSize="1.1" snapInterval="1.1" />`
