### ISSUE TITLE
CapsLock is not Working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#392]
When I Press capsLock button of Keyboard Nothing happens
Example: https://paste.apache.org/sdia

**Comment by Harbs** [comment]
Please check the fix I just committed. It's using https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState to set the static value.

I am not able to test right now, but I'm 99% sure that it will work.

**Comment by aharui** [comment]
That part is right, but they are looking for a solution in the emulation component sets, which, if you followed the traffic on Issues, I said I have pending, and involves more files.  But I want them to clean up their other open bugs first.

**Comment by Harbs** [comment]
The fix was in the mx KeyboardEvent. I'm not sure what you mean.

**Comment by Harbs** [comment]
Ah. I see your comment in #391...

**Comment by Harbs** [comment]
I'm 99% sure that an input event will be converted to a KeyboardEvent. Have you checked?

**Comment by Harbs** [comment]
Input using voice or something will definitely not be a KeyboardEvent, but input resulting from keyboard input I would have thought would be.

Either way, it sounds like you've thought this through better than me. Do you want me to revert my commit?

**Comment by aharui** [comment]
In my testing, it did not go into the KeyEventConverter because the event.constructor.name is not KeyboardEvent.

IMO, it would be better if you revert so I don't have to deal with merge conflicts.  I took the time to test my changes, although there could certainly still be bugs.

**Comment by pashminakazi** [comment]
getModifierState is in JavaScript.
How can i use it in Apache Royale?

**Comment by pashminakazi** [comment]
getModifierState is in JavaScript.
How can i use it in Apache Royale?

**Comment by aharui** [comment]
Forgot to add fix in checkin notes for 9edb2b6d50b6cc1f595f2acba78903377ef2bc72
