### ISSUE TITLE
UIComponent focusIn and keyDown Event Handlers are not called

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#395]
I am using focusIn and keyDown Event with mx: TextInput But Event is not triggered.

HelloWorld.mxml : https://paste.apache.org/WUlS

**Comment by pashminakazi** [comment]
@aharui Thank u so much Alex

**Comment by carlosrovira** [comment]
Hi @aharui , I want to ask you about focus/key events in standard royale apps. you get this working only in MX or that's working as well in basic? Thanks!

**Comment by aharui** [comment]
I did not test Basic to see what is working or not there.  Feel free to start a thread on dev@ about the Basic implementation.
