### ISSUE TITLE
Components not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#399]
These all Components are not working
DropDownList
Scroller
PopUpMenuButton
StringValidator
AlternatingItemColor of menuBar and AdvancedDataGrid

When Scroller. DropDownList and PopUpMenuButton will be Working as other visual Elements?

**Comment by aharui** [comment]
Scroller seems to be working in the DataGroup example in TourDeFlexModules.

PopUpMenuButton was not in the list of components from the API report so nobody has worked on it.  DropDownList I thought was working at one point in time.

We want you to learn how to fix these components.  I suggest starting with DropDownList as I think it used to work.  Create a small test case and debug it and ask questions.

**Comment by aharui** [comment]
Look like because PopUpMenuButton was not in the API report it has not even been created in MXRoyale.  Please create emulations for PopUpButton and PopUpMenuButton that compile in your application and then we'll see what is the best strategy to getting them to work.

**Comment by pashminakazi** [comment]
I have Created PopUpButton and PopUpMenuButton Classes in MXRoyale

**Comment by aharui** [comment]
DropDownList and PopUpMenuButton are working in TourDeFlexModules

**Comment by aharui** [comment]
StringValidator is now working in TDF Form, FormItem example

**Comment by aharui** [comment]
ADG now shows alternating row colors in TDF
