### ISSUE TITLE
NumericStepper can exceed maximum value

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#40]
The bounds check to the upper value on NumericStepper is incorrect.

If you run this code:
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic">

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:Group id="content">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:NumericStepper id="ns" minimum="0" maximum="1000" stepSize="7" snapInterval="7"/>
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>

Ands click the up button / press space with the button focused you'll eventually get to a value of 1001.

![2017-10-18_19-02-11](https://user-images.githubusercontent.com/144504/31707070-e03f6114-b436-11e7-87d8-f8e51ac9f865.png)

This boundary check in the snap function would be causing the issue:
`if (value - n < n + si - value)`

**Comment by Harbs** [comment]
There is a conflict between the maximum and the snapInterval. If the snapInterval is 7, the maximum has to be a multiple of 7 for the maximum to make sense.

When there's a conflict, there's three possible ways to resolve it:
1. maximum is the maximum value *before* the snap (as it behaves now)
2. maximum is not really the maximum. Rather it's the nearest snap value to the maximum.
3. The snapInterval is ignored at the maximum value.

None of these are truly correct answers and I don't think it't the job of the RangeModel to make these decisions. The RangeModel implementation should be the implementation which has the smallest overhead.

I think we should leave it as-is. If someone needs a more sophisticated RangeModel, it should be implemented according to the needs of the client, and specified in the CSS of the app.
