### ISSUE TITLE
0.9.6 SDK not working is VSCode ..?

### ISSUE THREAD

**Issue by UncommonUnion** [apache/royale-asjs#400]
I've been updating JS-Only SDKs for my project since 0.9.2 and I am currently using 0.9.5 successfully (in VSCode)...  I just swap the SDK in VSCode and it works great.

However, I've been trying to get 0.9.6 to work for a while now and when I build the terminal just reports many, many errors and fails... Is there some additional configuration needed for 0.9.6 .. or breaking changes I should be aware of ? 

Thank you!

**Comment by aharui** [comment]
What are the first dozen errors you get?

**Comment by Harbs** [comment]
Also, make sure you clean before trying to build.

**Comment by UncommonUnion** [comment]
Thanks. 
Yes, I tried cleaning.
Here are the first few errors... and it just goes on like that.

MXMLJSC
+royalelib=/Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks
--debug=true
--targets=JSRoyale
--html-template=src/resources/template.html
--theme=${royalelib}/themes/JewelTheme/src/main/resources/defaults.css
-remove-circulars
-js-output-optimization=skipAsCoercions
--
src/index.mxml
/Users/hd/Documents/VSCode/App-js/src/com/comparatio/webclient/accesscontrol/AccessControl.as(28): col: 9 Warning: Definition mx.core.Application could not be found.

        import mx.core.Application;
               ^

/Users/hd/Documents/VSCode/App-js/src/com/comparatio/webclient/accesscontrol/AccessControl.as(1063): col: 10 Error: Access of possibly undefined property Application.

                                                if(Application.application.Main_LoginView.loginControl.US1_CB_CUST_READ) {
                                                   ^

/Users/hd/Documents/VSCode/App-js/src/com/comparatio/webclient/accesscontrol/AccessControl.as(1103): col: 10 Error: Access of possibly undefined property Application.

                                                if(Application.application.Main_LoginView.loginControl.US1_CB_CUST_READ) {
                                                   ^

/Users/hd/Documents/VSCode/App-js/src/com/comparatio/webclient/accesscontrol/AccessControl.as(1139): col: 10 Error: Access of possibly undefined property Application.

**Comment by aharui** [comment]
Add +configname=flex to your compiler options.

We decided to only have the MX components in flex-config.xml.  Having them also in the default royale-config.xml created some issues with CSS and code-hinting.

**Comment by UncommonUnion** [comment]
Thank you. That fixed it.
