### ISSUE TITLE
String Validator Blocking Input

### ISSUE THREAD

**Issue by UncommonUnion** [apache/royale-asjs#401]
The following was working for <0.9.6 -- now it seems that the validator fires on input and clears text while typing making it impossible to fill in form.

```
<j:TextInput id="LoginView_UserNameTextInput" width="100%">
                            <j:beads>
                                <j:TextPrompt prompt="Username"/>
                                <j:StringValidator required="3" autoTrim="true" requiredFieldError="Need more than 3 characters"/>
                            </j:beads>
</j:TextInput>
```

**Comment by piotrzarzycki21** [comment]
Fixed in https://github.com/apache/royale-asjs/commit/059f4c2d287916a319044dd3240246a0782f24f7 and https://github.com/apache/royale-asjs/commit/f6f54b5faf8d59d7af8fd94530d1e525bf488ffa. Available in nightly build [2015](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/2015/)
