### ISSUE TITLE
Compiler Error: Internal error

### ISSUE THREAD

**Issue by UncommonUnion** [apache/royale-asjs#402]
I had a working project and I made significant changes, worked through various issues and then, finally, the project started to compile successfully... but then the compiler failed mysteriously reporting an internal error... I'm not sure where to start debugging this and wondering if this is a bug in the framework?

The error is:

Internal error: java.lang.RuntimeException: Unable to find JavaScript filePath for class: flash.events.Event 

Terminal output is:

`using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/js/libs/js.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/StorageJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/MaterialDesignLiteJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/BindingJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/LanguageJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/TLFJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/DragDropJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/FlatJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/CollectionsJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/GoogleMapsJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/NetworkJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/IconsJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/HTMLJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/MXRoyaleJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/EffectsJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/BasicJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/RoyaleSiteJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/jQueryJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/MobileJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/CoreJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/ReflectionJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/XMLJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/CreateJSJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/TestingJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/ChartsJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/ExpressJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/FontAwesomeJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/GraphicsJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/FormattersJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/SparkRoyaleJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/HTML5JS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/TextJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/JewelJS.swc
using SWC: /Users/hd/Documents/VSCode/apache-royale-0.9.6-bin-js/royale-asjs/frameworks/js/libs/AceJS.swc
Could not find file for class: flash.events.Event
Error: File not found: flash.events.Event

Internal error: java.lang.RuntimeException: Unable to find JavaScript filePath for class: flash.events.Event org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:594)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:623)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:623)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:623)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:623)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:623)org.apache.royale.compiler.internal.graph.GoogDepsWriter.addDeps(GoogDepsWriter.java:623)org.apache.royale.compiler.internal.graph.GoogDepsWriter.buildDB(GoogDepsWriter.java:300)org.apache.royale.compiler.internal.graph.GoogDepsWriter.getListOfFiles(GoogDepsWriter.java:108)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:419)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:436)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:263)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:220)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:367)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:302)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:260)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:242)`

**Comment by aharui** [comment]
That means that somehow, one of the .JS files is referencing flash.events.Event.  In theory, none of the Royale classes do that without conditional compilation for the COMPILE::SWF option.  If your code is still referencing flash.events.Event, that could result in this error, but only, in theory, if your compiler options are set to also allow SWF compilation.

I think the quick check is to grep all of the .JS files in bin/js-debug for "flash.events.Event" and see which JS files are using it.  Royale code should be using org.apache.royale.events.Event or mx.events.Event or mx.events.FlexEvent in most cases.

**Comment by UncommonUnion** [comment]
Thanks, I chased down the issue.
