### ISSUE TITLE
MenuBar sub-menu Arrow not showing

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#407]
Menubar is not Showing sub-menu Arrow
![image](https://user-images.githubusercontent.com/42200979/55228652-77076700-523c-11e9-941f-e94dd0073315.png)

In Flex it was Showing sub-menu Arrow
![image](https://user-images.githubusercontent.com/42200979/55228728-b1710400-523c-11e9-8507-ca76e7b88532.png)

**Comment by aharui** [comment]
This might be a good task for you to try to fix yourself.  The menu is made up of renderers and the renderers can be taught to display the expand icon or graphic (or even just a ">")

**Comment by yishayw** [comment]
This should be ok now.
