### ISSUE TITLE
old bug ,box2d build and run

### ISSUE THREAD

**Issue by matrix3d** [apache/royale-asjs#408]
https://github.com/matrix3d/spriteflexjs/blob/master/examples/src/TestBox2D.as

**Comment by matrix3d** [comment]
https://matrix3d.github.io/assets/html5/flexjsstage3d/bin/js-release/#test_box2d

the flexjs,and build,but the new royale ,can not build?!

**Comment by carlosrovira** [comment]
Don't know others, but for me this kind of messages are very inefficient. We don't know what you want, can imagine about the problem maybe...but a correct issue should bring more phrases and constructions to open a conversation so we can know what's your problem, what did you try, what you want to solve, if you know the problem and if you know how to fix it and/or if you want to submit a pull request. In other way is difficult to offer you some help.
