### ISSUE TITLE
This tag is unexpected. It will be ignored. (<fx:Script>)

### ISSUE THREAD

**Issue by LudvikWiejowski** [apache/royale-asjs#413]
Hi,

my first try with RoyaleJS (VSCde), but I'm getting tag unexpected error for fx:Script.
Please, what is wrong?

asconfig.json
```
{
	"compilerOptions": {
        "source-map": true,
		"targets": [
			"JSRoyale"
		],
		"theme": "${royalelib}/themes/JewelTheme/target/JewelTheme.swc"
	},
	"files": [
		"src/Main.mxml"
	]
}
```

Thanks
Ludvik

**Comment by piotrzarzycki21** [comment]
@LudvikWiejowski if you could show code which you are trying to compile would be helpful.

**Comment by LudvikWiejowski** [comment]
`<?xml version="1.0" encoding="UTF-8"?>

<j:Application xmlns:fx="//ns.adobe.com/mxml/2009"
              xmlns:j="library://ns.apache.org/royale/jewel"
              xmlns:js="library://ns.apache.org/royale/basic"
              xmlns:html="library://ns.apache.org/royale/html">
    
    <j:initialView>
        <j:View id="view">
            <j:states>
                <js:State name="login" />        
                <js:State name="loggedIn" />        
            </j:states>
            
            <j:beads>
                <js:SimpleStatesImpl/>
            </j:beads>

            <j:Card id="loginForm" includeIn="login">
                <html:H1 text="Royale login"/>
                <j:TextInput id="username" text="someuser"/>
                <j:TextInput id="password" text="somepass">
                    <j:beads>
                        <j:PasswordInput/>
                    </j:beads>
                </j:TextInput>
                <j:Button text="Login" emphasis="primary" click="view.currentState = 'loggedIn'" />
            </j:Card>

            <j:Card id="loggedInForm" includeIn="loggedIn">
                <html:H1 text="You are logged in!! :)"/>
                <j:Button text="Logout" click="view.currentState = 'login'"/>

            </j:Card>
        </j:View>
    </j:initialView>

	<fx:Script>
		<![CDATA[
            
		]]>
	</fx:Script>
</j:Application>`

**Comment by aharui** [comment]
The fx prefix should be  xmlns:fx="http://ns.adobe.com/mxml/2009"

**Comment by LudvikWiejowski** [comment]
omg, of course, thanks. I did check this several times and now I can see, it was copy/paste error. I took it from examples on royal.apache.org website. E.g. here it's too. [https://royale.apache.org/loading-external-data-through-httpservice/](url) or here [https://royale.apache.org/using-view-states-to-show-or-hide-content/](url) I think it's everywhere. :)

**Comment by piotrzarzycki21** [comment]
It is not the first time problem with that example. Some time ago someone reported that also as part of one of Moonshine's issue in repository.

**Comment by carlosrovira** [comment]
Hi,
I'm a bit confused here. So I should update blog examples with xmlns:fx="http://ns.adobe.com/mxml/2009"?
And why I getting a successful compilation with "xmlns:fx="//ns.adobe.com/mxml/2009" ?

let me know so I can see what I should fix
thanks

**Comment by piotrzarzycki21** [comment]
> Hi,
> I'm a bit confused here. So I should update blog examples with xmlns:fx="http://ns.adobe.com/mxml/2009"?
> And why I getting a successful compilation with "xmlns:fx="//ns.adobe.com/mxml/2009" ?
> 
> let me know so I can see what I should fix
> thanks

Are you building by IDE or by Maven ?

**Comment by carlosrovira** [comment]
I always use maven, but don't think that should make a difference right?

**Comment by aharui** [comment]
In a quick look, the blog example sources in royale-asjs have the complete URI including "http".  I don't know why it would work without it for you.  I wonder if your editor is somehow hiding the "http".

**Comment by piotrzarzycki21** [comment]
> I always use maven, but don't think that should make a difference right?

Of course it shouldn't be, but in that case it does and I'm not sure why maven didn't catch that. Ok if this is actually VSCode editor hiding something maybe we won't have problems. Maybe it was copy paste issue?

**Comment by carlosrovira** [comment]
I think this can one can be close?

**Comment by LudvikWiejowski** [comment]
Hello,

I'm fine with it.

Thanks
Rgds
Ludvik
