### ISSUE TITLE
ArrayCollection implementation of PropertyNames() method

### ISSUE THREAD

**Issue by saggelopoulos** [apache/royale-asjs#417]
Implementing this method to ArrayCollection solve the problem with for each iteration.

**Comment by carlosrovira** [comment]
Hi @saggelopoulos are you saying that you implemented PropertyNames and have for each successfully working? Can you provide a patch with that code as a pull request so we can try and merge your code in Royale?
thanks

**Comment by saggelopoulos** [comment]
Hi Carlos , 
I open this issue because Alex ask. You could see this link 
http://apache-royale-development.20373.n8.nabble.com/For-each-iteration-in-ArrayList-and-ArrayCollection-tp9521.html  
I not familiar with pull requests but i can find how i can do this.

**Comment by carlosrovira** [comment]
Thanks, I missed that response :)

**Comment by yishayw** [comment]
I'm not sure if it's related, but the following code (dataProvider is a non-empty ArrayCollection):

			for each (var row:Object in dataProvider)
			{
				if (ExpressionUtils.resolveExpression(row, col.dataField, _processValues, _ignoreValues))
				{
					count++;
				}
			}
			return count;

row is undefined

**Comment by yishayw** [comment]
It transpiles to

```
var /** @type {number} */ count = 0;
var foreachiter3_target = this.dataProvider;
for (var foreachiter3 in foreachiter3_target) 
{
var row = foreachiter3_target[foreachiter3];
{
  if (com.amentra.flex.utils.ExpressionUtils.resolveExpression(row, org.apache.royale.utils.Language.string(col.dataField), this.com_tools_footerDataGrid_SummaryColumn__processValues, this.com_tools_footerDataGrid_SummaryColumn__ignoreValues)) {
    count++;
  }
}}
```

**Comment by yishayw** [comment]
```
			var test:Object = new ArrayCollection();
			test.addItem("One");
			test.addItem("Two");
			for each (var a:String in test)
			{
				trace(a);
			}
```

Does not work, but

`			var test:ArrayCollection = new ArrayCollection();
			test.addItem("One");
			test.addItem("Two");
			for each (var a:String in test)
			{
				trace(a);
			}`

does. So it seems to be a matter of explicitly declaring (or casting) the type. In Flex, iteration works the same whether or not the type is defined.

**Comment by aharui** [comment]
Yes, that's a fact of life for Royale at this time.  The Flash runtime knows about types so can choose different access methods for a.b.  The JS runtime does not, so you have to explicitly tell the compiler to generate the right access code.  So if "a" in XML or Proxy, it is important not to tell the compiler it is an Object.
