### ISSUE TITLE
model_internal functions generation error

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#419]
model_internal functions are not generated as expected:

model_internal::initialize(); in AS file is mapped to 

`main.mtest.model_internal.org.apache.royale.utils.Language.closure(this.http_$$www_adobe_com$2008$flex$model$internal__initialize, this, 'http://www.adobe.com/2008/flex/model/internal::initialize')();
`
in js file

Please find the related files : https://drive.google.com/open?id=1KxcXxCAlhjH0OmyIZmwgidVrW0aybYiZ

**Comment by nihavend** [comment]
Hi Alex,

I prepared sample project. Please find : https://drive.google.com/open?id=1jc0H1cf-Z2WJjeQy8Cy3rOuphrGjiNoL

You have to set to env vars for local to build the project :

CLOSURE_HOME
ROYALE_DIST_HOME

Thanks,
Serkan.

**Comment by aharui** [comment]
In your test case, the source code reads:

		model_internal function initialize() : void
		{
			model_internal::propagateEvents;
			model_internal::propagateEvents;
		}

I don't understand what you expect to happen when just naming a method instead of calling it.

If I change the code to a proper call:

		model_internal function initialize() : void
		{
			model_internal::propagateEvents(null);
			model_internal::propagateEvents(null);
		}

The output looks correct to me.  I suppose we should fix that someday, but probably after I get some other stuff done.

**Comment by nihavend** [comment]
You are right Alex, the original code was like below;

```
model_internal function initialize() : void
      { 
this.serviceControl.addEventListener(ResultEvent.RESULT,model_internal::propagateEvents);
         this.serviceControl.addEventListener(DataServiceFaultEvent.FAULT,model_internal::propagateEvents);
      }
```
When I was simplyfying source code I tought it was enough for test case. As I am not so good at as development, it was not true :)

Thanks.
