### ISSUE TITLE
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Basic.swc'  cannot be opened.

### ISSUE THREAD

**Issue by T-San001** [apache/royale-asjs#423]
I would think required swf files are incorrectly put in these versions. 
Would you please check?  I used the latest nightly build. 

------------------------------------------------------------------------------------------------------------- 

c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\js\bin\mxmlc Welcome.mxml 

C:\apache-royale-source>if "x" == "x" (set 
"ROYALE_COMPILER_HOME=c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\js\bin\..\.." 
)  else echo Using Royale Compiler codebase: 

C:\apache-royale-source>if "x" == "x" (set 
"ROYALE_HOME=c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\js\bin\..\.." ) 
else echo Using Royale SDK: 
MXMLJSC 
-sdk-js-lib=c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\js\bin\..\..\frameworks\js\Royale\generated-sources 
Welcome.mxml 
c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\frameworks\royale-config.xml(74): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\frameworks\libs\player\11.7\playerglobal.swc' 
を開くことができませ ん。 
c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\frameworks\royale-config.xml 
(line: 74) 

      </external-library-path> 

c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\frameworks\libs\player\11.7' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js-swf\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

*****************************************************************************************************

c:\apache-royale-0.9.6-bin-js\royale-asjs\js\bin\mxmlc Welcome.mxml 

C:\apache-royale-source>if "x" == "x" (set 
"ROYALE_COMPILER_HOME=c:\apache-royale-0.9.6-bin-js\royale-asjs\js\bin\..\.." 
)  else echo Using Royale Compiler codebase: 

C:\apache-royale-source>if "x" == "x" (set 
"ROYALE_HOME=c:\apache-royale-0.9.6-bin-js\royale-asjs\js\bin\..\.." )  else 
echo Using Royale SDK: 
MXMLJSC 
-sdk-js-lib=c:\apache-royale-0.9.6-bin-js\royale-asjs\js\bin\..\..\frameworks\js\Royale\generated-sources 
Welcome.mxml 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Basic.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Binding.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Charts.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Collections.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Core.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\CreateJS.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\DragDrop.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Effects.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Express.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Flat.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\FontAwesome.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Formatters.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\GoogleMaps.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Graphics.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\HTML.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\HTML5.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Icons.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Jewel.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\jQuery.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Language.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\MaterialDesignLite.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Mobile.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Network.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Reflection.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\RoyaleSite.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\RoyaleUnit.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Storage.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\TLF.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\Text.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path> 

c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml(127): 
col: 0 エラー : 
'c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\libs\XML.swc' 
を開くことができません。 
c:\apache-royale-0.9.6-bin-js\royale-asjs\frameworks\royale-config.xml 
(line: 127) 

      </library-path>

**Comment by aharui** [comment]
I think this was resolved on the mailing list.
