### ISSUE TITLE
Vector compiler warnings on getter methods

### ISSUE THREAD

**Issue by besa2042** [apache/royale-asjs#424]
I always get the following warning

_WARNING - Type annotation references non-existent type Vector.
  \* @type {Vector.<string>} */_

when compiling a getter method with a Vector return type,

`function get vector():Vector.<String>`

The js output type annotation is   `@type {Vector.<string>}`.

When I change the getter to a normal method it compiles without warning,

`function vector():Vector.<String>`

here the js type annotation is   `@type {Array}`.

**Comment by greg-dove** [comment]
I have fixed this in a branch that is focused on Vector implementation, which I hope will be merged to develop branch soon.
When the updated version lands it is now set up to output valid 'typed' notations for Google Closure, like Array.<string> and Array.<CustomClass> etc instead of just 'Array'

**Comment by carlosrovira** [comment]
Hi Greg, that means that with this change we'll be able to define a typed array (I mean not only a typed vector)? Or this is only internally when declaring Vectors in AS3 that will generate typed Arrays?
thanks!

**Comment by greg-dove** [comment]
@carlosrovira No, there is no new 'typed array' usable at as3 level, this is just for the type annotation output that Google Closure uses as type hints when it optimizes/minifies the code. Getting these to be more specific may provide more optimal minimization output (I am not sure that it will really make any difference in this case, but it *could* and regardless, it seems like providing more accurate hints to Closure is the right thing to do when we already have that information in our own compiler). See info here for the type annotations that Closure supports/expects: 
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#types-in-javascript

**Comment by carlosrovira** [comment]
Ok. seems that there's no typed array in closure. But maybe we have the base to have some day typed arrays in AS3, since I think many of us was waiting for this very long time :)

**Comment by greg-dove** [comment]
@carlosrovira sorry I don't really understand that - I think Vector in as3 is a typed Array.... The task was to make that work properly in javascript (which only has limited 'TypedArrays' for binary data). Maybe I am missing something...

**Comment by piotrzarzycki21** [comment]
@greg-dove What will be the output in JS when I do:

`var myVec:Vector.<String> = Vector.<String>([])`

**Comment by carlosrovira** [comment]
Hi Greg, you're right. Maybe I'm mixing things here. Trying to recap:

When developing apps in flex, we really end using ArrayCollection, and AC was unable to do something like:

    var myac:ArrayCollection<Product> = new ArrayCollection<Product>()

(I'm improvising grammar here but could be something like that or similar)

So it'd be great to evolve Royale AS3 to be able to do this with ArrayList (and ArrayCollection although AC seems secondary now that we have AL)

So I think Vector and Array is ok, but I was thinking really in "typed ArrayList".

Just something to dream for now :)

**Comment by greg-dove** [comment]
@piotrzarzycki21 I have been writing a lengthy explanation that I will post to a thread later today (it is taking longer than I expected to write up, and I apologise in advance, but it will be a bit long to read, but should give you answers to many possible questions). But to answer your question briefly now: it will still be an Array in javascript, just an 'enhanced' one that behaves like a Vector and is able to be considered as different to a regular Array when checked using 'is' and 'as' (in as3 code) but should still work the same if passed to 3rd party javascript which expects a native Array.

**Comment by greg-dove** [comment]
@carlosrovira right, got it. That is 'generics' - Vector in as3 is our only current example of that. But yes that has been brought up before and is something I guess on the horizon for possible language enhancements.

**Comment by piotrzarzycki21** [comment]
My question comes up from Carlos question about typed Array. If in the end Vector or let's say typed Array in AS3 would be translated to the same - Maybe there is no point to even thing about that. I would much prefer from features have ENUMS in AS3 than typed Array.

**Comment by greg-dove** [comment]
@piotrzarzycki21 it is not the same in the sense that (for your example) `myVec is Vector.<String>` is true. But` myVec is Array `is false (in as3) which means it behaves the same as flash. 
The output for what you posted literally looks like this:
`var /** @type {Array.<string>} */ myVec = org.apache.royale.utils.Language.synthVector('String')['coerce']([]);`

That could actually be optimized further because it is an empty array. But generally with that approach you have some content in the array that you are using as the Vector literal which is why the code is the way it is.
Vector is part of the standard typing in as3, so it needs a good implementation based on what as3 is now. Other things like generics and enums, sure they will be good to add in the future.

**Comment by greg-dove** [comment]
Fix for this is now merged into develop
