### ISSUE TITLE
SubMenuItem is not working in tourdeflexmodules Example

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#430]
![submenuINmenubar](https://user-images.githubusercontent.com/36731338/60494089-8ed10a00-9cc7-11e9-85f2-eb97eb65e318.png)

**Comment by yishayw** [comment]
MenuBar -> IMenuFactory needs to be a cascading menu. And also, CascadingMenuItemRenderer or derivative needs to be able to read XML.

**Comment by yishayw** [comment]
Should be fixed with my recent commits.
