### ISSUE TITLE
Unable to load Canvas File into ViewStack

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#432]
With Old Sdk (march 2019)  Canvas is loaded into ViewStack
With New Sdk (july 2019)  Canvas is not loaded into ViewStack index,html is blank
applications.mxml : https://paste.apache.org/en7aa
AppViewERP.mxml : https://paste.apache.org/u5q8h

**Comment by yishayw** [comment]
Hi Pashmina,

I tried taking a look at this but there the example has all sorts of dependencies so I can't [1] compile. Can you provide a test case?

    [mxmlc] C:\dev\flexjs\royale-asjs\examples\mxroyale\HelloWorld\src\main\royale\HelloWorld.mxml(21): col: 11 Warning:
 Definition com.shm.components.shmMessage could not be found.

**Comment by pashminakazi** [comment]
All Dependencies are Removed
applications.mxml : https://paste.apache.org/prtyo
AppView_ERP.mxml : https://paste.apache.org/cz8jl

![Home](https://user-images.githubusercontent.com/42200979/61292432-9bd31a80-a7ea-11e9-8a51-f3c79dcfe4a8.gif)
![ReleaseNotes](https://user-images.githubusercontent.com/42200979/61292434-9bd31a80-a7ea-11e9-98d1-e3a87bbc340d.gif)
![AppLogo](https://user-images.githubusercontent.com/42200979/61292435-9c6bb100-a7ea-11e9-876a-8663f3bd5810.png)
![ChangePassword](https://user-images.githubusercontent.com/42200979/61292437-9c6bb100-a7ea-11e9-8946-f4db9a10cefb.gif)
![ClientLogo](https://user-images.githubusercontent.com/42200979/61292438-9d044780-a7ea-11e9-960b-78a1035e15ce.gif)
![DataGrid_headerBackgroundSkin](https://user-images.githubusercontent.com/42200979/61292439-9d044780-a7ea-11e9-8796-39869f4c7acb.png)
![exit](https://user-images.githubusercontent.com/42200979/61292440-9d9cde00-a7ea-11e9-9518-c3dd8adc6aa3.gif)
![HeaderLogo](https://user-images.githubusercontent.com/42200979/61292442-9d9cde00-a7ea-11e9-8ab1-876671c656b3.png)
![Help](https://user-images.githubusercontent.com/42200979/61292443-9e357480-a7ea-11e9-99d7-6e8b362f8d1d.gif)


Output with Old SDK :
![image](https://user-images.githubusercontent.com/42200979/61292587-1308ae80-a7eb-11e9-9b09-22daa4b5796e.png)

Output with New SDK : 
![image](https://user-images.githubusercontent.com/42200979/61292562-fe2c1b00-a7ea-11e9-9d13-5fbac3185e2a.png)

**Comment by pashminakazi** [comment]
Images Used in AppView_ERP.mxml

![Home](https://user-images.githubusercontent.com/42200979/61292432-9bd31a80-a7ea-11e9-8a51-f3c79dcfe4a8.gif)
![ReleaseNotes](https://user-images.githubusercontent.com/42200979/61292434-9bd31a80-a7ea-11e9-98d1-e3a87bbc340d.gif)
![AppLogo](https://user-images.githubusercontent.com/42200979/61292435-9c6bb100-a7ea-11e9-876a-8663f3bd5810.png)
![ChangePassword](https://user-images.githubusercontent.com/42200979/61292437-9c6bb100-a7ea-11e9-8946-f4db9a10cefb.gif)
![ClientLogo](https://user-images.githubusercontent.com/42200979/61292438-9d044780-a7ea-11e9-960b-78a1035e15ce.gif)
![DataGrid_headerBackgroundSkin](https://user-images.githubusercontent.com/42200979/61292439-9d044780-a7ea-11e9-8796-39869f4c7acb.png)
![exit](https://user-images.githubusercontent.com/42200979/61292440-9d9cde00-a7ea-11e9-9518-c3dd8adc6aa3.gif)
![HeaderLogo](https://user-images.githubusercontent.com/42200979/61292442-9d9cde00-a7ea-11e9-8ab1-876671c656b3.png)
![Help](https://user-images.githubusercontent.com/42200979/61292443-9e357480-a7ea-11e9-99d7-6e8b362f8d1d.gif)

**Comment by aharui** [comment]
Alina sent an email to dev@royale that included an exception stack trace.  This information should always be included in a bug report if it exists.  The stack trace indicates that some bead is being added that doesn't implement IBead.  Running the application in the debugger should reveal which bead that is.  New checks were added to Royale to verify that all beads added implement IBead.

**Comment by Harbs** [comment]
> New checks were added to Royale to verify that all beads added implement IBead.
I missed that change. Is that a debug-only check?

**Comment by greg-dove** [comment]
Yes it is debug only.

**Comment by alinakazi** [comment]
link for "detail stack trace & image" is given below:
 https://sharefiles.app/download/6fd1f597478a79edd3e1f051f0855bf22843b61c

**Comment by aharui** [comment]
You will have to actually debug this yourself.  The debugger should stop when the exception is thrown and by examining the objects on the call stack you should be able to determine which bead (that isn't an IBead) was being passed into addBead

**Comment by yishayw** [comment]
The offending bead is spark.components.Group

**Comment by yishayw** [comment]
In SparkRoyale's defaults.css we have this:

SkinnableContainer
{
	IBeadView: ClassReference("spark.components.beads.SkinnableContainerView");
	IBeadLayout: ClassReference("spark.layouts.supportClasses.SparkLayoutBead");
	IViewport: ClassReference("org.apache.royale.html.supportClasses.ScrollingViewport");
	IViewportModel: ClassReference("org.apache.royale.html.beads.models.ViewportModel");
	IContentView: ClassReference("spark.components.Group");
}

**Comment by yishayw** [comment]
Should it be spark.components.GroupView instead?

**Comment by aharui** [comment]
It may be that IContentView should not be assumed to be a bead.  It might be better to just get it from ValuesManager and instantiate it.

Basic's ContainerContentArea is both a UIBase and an IBead which is unusual.  If subclasses of ContainerContentArea do not use the host strand, then the code probably shouldn't assume that IContentView is an IBead.

**Comment by yishayw** [comment]
I agree. Also, looking at the code in UIBase it assumes there's only one IBeadView, so my previous suggestion would mess that up.

**Comment by alinakazi** [comment]
![issue7](https://user-images.githubusercontent.com/36731338/61357082-1191c180-a891-11e9-90be-4312de76fb95.png)
![issue8](https://user-images.githubusercontent.com/36731338/61357084-1191c180-a891-11e9-91a2-5c2d4da3f2fd.png)
![issue1](https://user-images.githubusercontent.com/36731338/61357085-122a5800-a891-11e9-822f-5a3da78bcc8d.png)
![issue2](https://user-images.githubusercontent.com/36731338/61357086-122a5800-a891-11e9-8867-912d0b341b66.png)
![issue3](https://user-images.githubusercontent.com/36731338/61357088-12c2ee80-a891-11e9-99a0-1fe55525cda8.png)
![issue4](https://user-images.githubusercontent.com/36731338/61357090-12c2ee80-a891-11e9-9b50-e564e69bfef7.png)
![issue5](https://user-images.githubusercontent.com/36731338/61357091-12c2ee80-a891-11e9-8951-b0b29fc6800f.png)
![issue6](https://user-images.githubusercontent.com/36731338/61357092-135b8500-a891-11e9-87ef-f2b32bb4189c.png)
These are "call stack" images. Do i have to change any thing in sdk ?

**Comment by yishayw** [comment]
Hi Alina,

Following the above discussion I would make changes in org.apache.royale.html.supportClasses.Viewport.as and make sure iContentView is not added as a bead. Note that it's stored in Viewport.contentArea anyway.

Let us know if you need guidance.

**Comment by alinakazi** [comment]
Thanks @aharui  and @yishayw

**Comment by yishayw** [comment]
@alinakazi , can you test this?

**Comment by alinakazi** [comment]
@yishayw ok I am testing.

**Comment by alinakazi** [comment]
ViewStack and MenuBar are working now.
Thanks a lot.
