### ISSUE TITLE
File uploading / File browsing

### ISSUE THREAD

**Issue by paul-uulabs** [apache/royale-asjs#433]
I notice that org.apache.royale.file has file upload, file browser, etc... is there an example implementation of these somewhere? I cannot find any in the docs, etc.  Are they working?

**Comment by yishayw** [comment]
Hi Paul, have a look at examples/FileProxy/src/main/royale/FileProxy.mxml

It should give you an idea on how to use these beads.

**Comment by paul-uulabs** [comment]
Thanks yishayw -- in that example the filemodel  bead is not found; so I don't think it works. Has there been changes since this example has been created?

**Comment by yishayw** [comment]
@paul-uulabs , I just tried the example and it works for me. There have been some changes in the SDK recently to that part so it might be that you are using an example that was compiled before the changes were made and there's a mismatch.

Try using the latest nightly and recompiling the example (ant clean; ant if using ant).

**Comment by Harbs** [comment]
Commit fc874bf7bf0ed54c56e3d18f885114c00ceb6cb3 added a default file model. Make sure you use an SDK built after that commit.
