### ISSUE TITLE
Importing VO file in Mxml Calls FaultHandler

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#435]
When I import shmCompanySetupVO and create its object in shmCompanySetup.mxml, RemoteObject Calls FaultHandler..
If I comment shmCompanySetupVO Import and its object it calls ResultHandler

shmCompanySetup.mxml : https://paste.apache.org/o93i5
shmCompanySetupVO.as : https://paste.apache.org/vi3si

How can i work with VO File?
VO file is part of library

**Comment by carlosrovira** [comment]
Hi Alina,

use of VOs in Royale is already shown and working in the examples. You can check both Java project in /amf folder and the clients in /mxroyale folder. Don't see any problems in the code you exposed

**Comment by yishayw** [comment]
It would be easier to help if you tried to isolate the problem further. Can you provide a simple application that uses shmCompanySetupVO.as and demonstrated the problem?

For example, what happens when you run the following application [1]? Do you get the same error? If so, what happens if you remove line 9 where the object is constructed?

[1] https://paste.apache.org/hp3hb

**Comment by aharui** [comment]
It looks like your example is a Module.  Our Module examples generally build the module in a separate folder, then copy the results into a subfolder in the main app's folder.  Please make sure you are building your app in a similar way and then verify whether shmCompanySetupVO.as is also being used in the main application or not, and if so, show us the compiler options that you are using to control duplicate JS files in the module, and also tell us which RemoteObject is being used.  Is the RO in the main app or the module?

There is a chance that the VO is being loaded twice or that it isn't loaded in time, or isn't being registered with the decoder.  You might want to start with our ModuleExample and get it to include your VO in a similar way you are using it to see if that will produce a simpler test case for analysis.
