### ISSUE TITLE
index.html Issue

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#436]
I'm unable to launch my application
Uncaught ReferenceError: applications_mx_managers_SystemManager is not defined at index.html:962

Uncaught Error: Bad dependency path or symbol: org.apache.royale.effects.IEffect
    at visit (base.js:2796)
    at visit (base.js:2808)
    at visit (base.js:2808)
    at goog.DebugLoader_.load_ (base.js:2815)
    at Object.goog.require (base.js:846)
    at index.html:957

![image](https://user-images.githubusercontent.com/42200979/61864583-1ab30c00-aeeb-11e9-9a8f-690798fec1cd.png)

base.js : 
![image](https://user-images.githubusercontent.com/42200979/61864723-5ea61100-aeeb-11e9-90be-4216aff41d30.png)

index.html :
![image](https://user-images.githubusercontent.com/42200979/61864759-6cf42d00-aeeb-11e9-9caa-4720ccfc1f73.png)

**Comment by atta94** [comment]
I'm facing the same issue, can you tell me how did you resolved this issue.
Thanks

**Comment by Harbs** [comment]
This kind of error usually means that the dependency tree could not be constructed correctly. The exact error and some more info on your project would be helpful in diagnosing what went wrong.
