### ISSUE TITLE
Popup Issue 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#439]
We have a file PickList_Simple component of customtype "shmResizableTitleWindow extends TitleWindow".

We have these few lines in our actionscript code
var popUpWinInstance:PickList_Simple =
				PickList_Simple(PopUpManager.createPopUp(as_ObjThis as UIComponent,
					PickList_Simple, true));
when converted to .js
  var /** @type {com.shm.components.PickList_Simple} */ popUpWinInstance = org.apache.royale.utils.Language.as(mx.managers.PopUpManager.createPopUp(org.apache.royale.utils.Language.as(as_ObjThis, mx.core.UIComponent), com.shm.components.PickList_Simple, true), com.shm.components.PickList_Simple, true);

It generates error while executing this line, Stack Trace of the error is given below:
https://paste.apache.org/iiwpx

**Comment by aharui** [comment]
Use the debugger to determine what "cls" is at the time of the exception.  The debugger should help determine an offset into an array of MXML data.

Post the .JS file for com.shm.components.PickList_Simple

**Comment by alinakazi** [comment]
.js for  com.shm.components.PickList_Simple:  https://paste.apache.org/9ywz9

**Comment by alinakazi** [comment]
.mxml for com.shm.components.PickList_Simple: https://paste.apache.org/ii283

**Comment by aharui** [comment]
The exception is gone.  RichTextEditor is not laying out correctly and needs improvement
