### ISSUE TITLE
Annotation warnings given when trying to compile Apache Royale examples

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#44]
When doing a mvn compile in the example directory the following warnings are given I don't recall this happening before the rename.

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/HTMLElementWrapper.js:102: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
 * @type {org.apache.royale.core.WrappedHTMLElement}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/HTMLElementWrapper.js:290: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  * @type {org.apache.royale.core.WrappedHTMLElement} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/IRenderedObject.js:26: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
/**  * @type {org.apache.royale.core.WrappedHTMLElement}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/IViewportModel.js:28: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
/**  * @type {org.apache.royale.geom.Rectangle}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:866: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  var /** @type {org.apache.royale.core.WrappedHTMLElement} */ e = document.body;
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:894: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  var /** @type {org.apache.royale.core.WrappedHTMLElement} */ p = this.positioner.parentNode;
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:1007: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  * @type {org.apache.royale.core.WrappedHTMLElement} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:1024: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  * @type {org.apache.royale.core.WrappedHTMLElement} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/UIModuleLoader.js:58: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
 * @type {org.apache.royale.core.WrappedHTMLElement}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/UIModuleLoader.js:65: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
 * @type {org.apache.royale.core.WrappedHTMLElement}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:36: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
 * @type {org.apache.royale.geom.Rectangle}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:43: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
 * @type {org.apache.royale.geom.Rectangle}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:83: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
  * @type {org.apache.royale.geom.Rectangle} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:89: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
  * @type {org.apache.royale.geom.Rectangle} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/MainApp/target/javascript/bin/js-debug/org/apache/royale/html/supportClasses/Viewport.js:96: WARNING - Type annotation references non-existent type org.apache.royale.geom.Size.
 * @param {org.apache.royale.geom.Size} contentSize
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:26 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 15 warning(s), 96.8% typed
Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/HTMLElementWrapper.js:102: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
 * @type {org.apache.royale.core.WrappedHTMLElement}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/HTMLElementWrapper.js:290: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  * @type {org.apache.royale.core.WrappedHTMLElement} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/IRenderedObject.js:26: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
/**  * @type {org.apache.royale.core.WrappedHTMLElement}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/IViewportModel.js:28: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
/**  * @type {org.apache.royale.geom.Rectangle}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:866: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  var /** @type {org.apache.royale.core.WrappedHTMLElement} */ e = document.body;
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:894: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  var /** @type {org.apache.royale.core.WrappedHTMLElement} */ p = this.positioner.parentNode;
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:1007: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  * @type {org.apache.royale.core.WrappedHTMLElement} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/core/UIBase.js:1024: WARNING - Type annotation references non-existent type org.apache.royale.core.WrappedHTMLElement.
  * @type {org.apache.royale.core.WrappedHTMLElement} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:36: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
 * @type {org.apache.royale.geom.Rectangle}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:43: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
 * @type {org.apache.royale.geom.Rectangle}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:83: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
  * @type {org.apache.royale.geom.Rectangle} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/html/beads/models/ViewportModel.js:89: WARNING - Type annotation references non-existent type org.apache.royale.geom.Rectangle.
  * @type {org.apache.royale.geom.Rectangle} */
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Oct 24, 2017 7:46:32 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/justinmclean/royale-asjs/examples/royale/ModuleExample/Module/target/javascript/bin/js-debug/org/apache/royale/html/supportClasses/Viewport.js:96: WARNING - Type annotation references non-existent type org.apache.royale.geom.Size.
 * @param {org.apache.royale.geom.Size} contentSize
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Harbs** [comment]
Fixed.
