### ISSUE TITLE
No default selection on adg

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#441]
requireSelection=true not functioning

**Comment by yishayw** [comment]
I've seen this on spark DropDownList, but it's probably true to all implementers of that API. 

Sounds to me like a bead should be listening to data provider changes on the strand model. It should probably be added at the end of the strand to allow other beads to select the index, if no index has been selected, it selects the first item (provided it  exists).

**Comment by alinakazi** [comment]
Test Case : https://paste.apache.org/21x16
OnCreationComplete  System should auto set selectedIndex to 0 instead of -1
![selecteditem and selectedIndex in ADG](https://user-images.githubusercontent.com/36731338/62536524-9ad05e80-b867-11e9-8155-50628e3f6482.png)

**Comment by aharui** [comment]
I'm confused.  AdvancedDataGrid doesn't have a requireSelection property and requireSelection is not used in the test case.

**Comment by aharui** [comment]
I ported the test case back to Flex and the results were also -1 and null.

There may be other aspects of your real app that call some API that set selectedIndex to 0 in Flex that isn't working in Royale but you will need to identify that API and add it to the test case.
