### ISSUE TITLE
Itemclick on mx radiobuttongroup

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#443]
Itemclick event on mx radiobuttongroup is not working

**Comment by yishayw** [comment]
Hi Alina, please attach a test case for this.

**Comment by alinakazi** [comment]
Test Case : https://paste.apache.org/lk9xo

**Comment by alinakazi** [comment]
On Click to radioButton system should listen to ItemClick i.e searchDG() in test case. But System never call  searchDG() when I click on radioButton.
