### ISSUE TITLE
Sub Menu Item Overlapping Issue (Screenshot Attached)

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#445]
![submenu overlapping](https://user-images.githubusercontent.com/36731338/62532672-660bd980-b85e-11e9-906d-84c218ac0fbb.png)
Previous SubMenu window should be closed on the selection of next SubMenu

**Comment by alinakazi** [comment]
Foreign Currency > Rates
                                Types
Should be Close on Click to Store Room

**Comment by yishayw** [comment]
Still not working for seome deep nesting cases

**Comment by pashminakazi** [comment]
Still not working
https://paste.apache.org/y00xp
![image](https://user-images.githubusercontent.com/42200979/63411660-7485f380-c40f-11e9-9ed8-71770b62ecf2.png)

**Comment by piotrzarzycki21** [comment]
@pashminakazi can you look into compiled file CascadingMenuSelectionMouseController.js and see whether there are changes from @yishayw ? https://github.com/apache/royale-asjs/commit/d5556b3a31a73346ea6edb70db514f081322347e and https://github.com/apache/royale-asjs/commit/ef6466d49b95a807658cc9ef3318c49c33d32fdc

**Comment by pashminakazi** [comment]
d5556b3 changes
![image](https://user-images.githubusercontent.com/42200979/63413748-c7fa4080-c413-11e9-8176-ee565b8a7b7c.png)

ef6466d changes
![image](https://user-images.githubusercontent.com/42200979/63413934-363f0300-c414-11e9-940d-af256b3e0e24.png)

clearSubmenusOnSameLevel Function
![image](https://user-images.githubusercontent.com/42200979/63414038-730afa00-c414-11e9-910d-870b16e27f6f.png)


getMenuWithDataProvider Function
![image](https://user-images.githubusercontent.com/42200979/63414121-99309a00-c414-11e9-9ea2-647f2e70afe8.png)

**Comment by piotrzarzycki21** [comment]
You can try debug yourself and see what has happened. @yishayw is on vacation - he will back at the beginning of September.

**Comment by yishayw** [comment]
Thanks for reporting this. Hopefully I'll have time to look at this tomorrow.

**Comment by yishayw** [comment]
Looks like this is not working for menus with xml data. The reason being that the sub menu data provider is recreated each time it's accessed and this cannot be used as an identifier to retrieve the open menu.

**Comment by pashminakazi** [comment]
@yishayw Thanks issue resolved.
