### ISSUE TITLE
[QUESTION] "style" property, background not changing

### ISSUE THREAD

**Issue by angelhdz** [apache/royale-asjs#449]
### Me again... with styling issues...

I'm trying to understand Royale, so after a lot of time struggling with Jewel themes, I decided to try styling the components directly with CSS. So, I started with the background property, obviously. And bam! No black background... but the color property actually works, it paints the text red as it should. I tried setting opacity to 100%.

`<j:Button text="Black Button" style="background: #000; color: #f00; opacity: 100%">`

**Comment by carlosrovira** [comment]
Issue checked. `background: #000`, is translated to: `background: 0px center; ` so this is incorrect. As well `opacity`, although is used with incorrect value (should be from 0 to 1),  is ignored. only color is generated ok.

Thanks for reporting. I'll assign to others that could take a look at compiler level.

**Comment by carlosrovira** [comment]
@angelhdz in the other hand to work-around this issue you can add CSS rule at MXML level or in a CSS external file:

```as3
<fx:Style> 
        .jewel.button.mybtn
        {
            background: #000;
            color: #f00;
            opacity: 0.5;
        }
    </fx:Style>

<j:Button text="Black Button" className="mybtn"/>
```

**Comment by aharui** [comment]
Please never assign anyone to an issue other than yourself.  We are all volunteers here and work on what we want.

**Comment by angelhdz** [comment]
> Please never assign anyone to an issue other than yourself. We are all volunteers here and work on what we want.

Pardon me?

**Comment by aharui** [comment]
Was not a compiler issue,
