### ISSUE TITLE
Data binding warning in Apache Royale TODO list example

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#45]
/Users/justinmclean/royale-asjs/examples/royale/TodoListSampleApp/src/main/royale/sample/todo/renderers/TodoItemRenderer.mxml(49): col: 26 Warning: Data binding will not be able to detect assignments to 'title'.

	<js:CheckBox text="{data.title}" 
	                        ^

/Users/justinmclean/royale-asjs/examples/royale/TodoListSampleApp/src/main/royale/sample/todo/renderers/TodoItemRenderer.mxml(50): col: 30 Warning: Data binding will not be able to detect assignments to 'selected'.

	             selected="{data.selected}" 
	                            ^

/Users/justinmclean/royale-asjs/examples/royale/TodoListSampleApp/src/main/royale/sample/todo/renderers/TodoItemRenderer.mxml(49): col: 26 Data binding will not be able to detect assignments to 'title'.

	<js:CheckBox text="{data.title}" 
	                        ^

/Users/justinmclean/royale-asjs/examples/royale/TodoListSampleApp/src/main/royale/sample/todo/renderers/TodoItemRenderer.mxml(50): col: 30 Data binding will not be able to detect assignments to 'selected'.

	             selected="{data.selected}"

**Comment by Harbs** [comment]
The warning looks correct. That looks like a bug in the example.
