### ISSUE TITLE
Trying to convert old flex application to royale in moonshine

### ISSUE THREAD

**Issue by wrath2019** [apache/royale-asjs#451]
How do I get moonshine to look at the mxroyale library emulation components when I go to build.  Where do I add the library entries.  Any help would be great.  Thank you.

**Comment by piotrzarzycki21** [comment]
What version of sdk are you using?

**Comment by wrath2019** [comment]
0.9.4

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by piotrzarzycki21** [comment]
Please try to use [Nightly build](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/) this time. We will update Moonshine with availability of Nightly very soon. Download sdk and once you unpack archive point to folder royale-asjs in Moonshine. Let me know if it's helped.

**Comment by wrath2019** [comment]
I would try the nightly build but I have not seen that the link has been good.

**Comment by piotrzarzycki21** [comment]
> I would try the nightly build but I have not seen that the link has been good.

Are you saying that provided link doesn't work for you ?

**Comment by wrath2019** [comment]
Yes it was not available

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wrath2019** [comment]
Connection timed out

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by piotrzarzycki21** [comment]
I hope now it's working.

**Comment by wrath2019** [comment]
Tried several times same result.  I get a timeout.

**Comment by piotrzarzycki21** [comment]
Email me: piotrzarzycki21@gmail.com I will upload it on my server and provide you a link.

**Comment by carlosrovira** [comment]
strange, just tried the link and seems to work fine

**Comment by piotrzarzycki21** [comment]
> strange, just tried the link and seems to work fine

It's working for me as well. Maybe there is some company restriction on Greg's sight.

**Comment by wrath2019** [comment]
Your link worked great thanks.

**Comment by piotrzarzycki21** [comment]
Thanks. I'm closing this.
