### ISSUE TITLE
<fx:Binding doesn't work in some cases

### ISSUE THREAD

**Issue by piotrzarzycki21** [apache/royale-asjs#456]
We are trying to use in our project two way Binding. We have run into an issue where in some cases it doesn't work at all or event break binding in some files. 

I have Jewel DropDownList and TextInput where I'm using following code:
`<fx:Binding source="dpl.selectedItem" destination="this.user" />`

Above code should assign to local variable user value in the result of changed selection in drop down list.
What's wors there is also commented out code which break completely binding in this file.

<fx:Binding source="this.myText" destination="textInput.text" />

I'm attaching project and generated js file. Project is being configured with Moonshine and Maven. 
[DropdownlistBindingIssue.zip](https://github.com/apache/royale-asjs/files/3551272/DropdownlistBindingIssue.zip)
[Content.zip](https://github.com/apache/royale-asjs/files/3551280/Content.zip)

**Comment by carlosrovira** [comment]
We have already a regression of bindings not working at application level. So maybe recent changes caused regressions in this issue too (don't know if that was working before like the other one).

**Comment by piotrzarzycki21** [comment]
I've seen problems also in itemrenderers with binding in cases where it should just work or it was working.

**Comment by greg-dove** [comment]
I have some local progress on the Application level issues, but had to set it aside as I work through something else. Although if you are referring to the Constant binding issue at application level, Carlos, afaik that is not a regression (or I don't think it is a recent one if it is). I don't think I tried to use a Binding tag in royale yet like that Piotr. I will be spending more time on Bindings soon. It may be as early as tomorrow but probably more likely next week. Feel free to assign this or other Binding tickets to me if that is ok for your timeframes.

**Comment by carlosrovira** [comment]
Hi Greg, thanks. I think we don't have the Application binding level issue as a ticket, I look into it an create one and assign it to you. I'm assigning this to you as well if you don't mind. Maybe Piotr has more needs, in my case I'm this days with docs work, so no problem. What I'm seeing is that blog examples that use App binding can fail, so that could be a problem for newcomers. Thanks!.

**Comment by greg-dove** [comment]
Guys just to let you know I have not lost sight of this, I have just been swamped with other things that have to take priority. I don't usually use private vars for bindings, but I am porting some Flex code that uses private var bindings and it only worked when I switched them to public. I'm just adding that here so that I can look at it later when I get to this stuff.

**Comment by carlosrovira** [comment]
Hi @greg-dove thanks for letting us know. I think this issue will impact many people trying to migrate, so great to know you have it controlled :)

**Comment by greg-dove** [comment]
Piotr, I did not try this with your two-way binding described here, but I think it should work now. Please re-open if not, with more details.

**Comment by piotrzarzycki21** [comment]
> Piotr, I did not try this with your two-way binding described here, but I think it should work now. Please re-open if not, with more details.

Wow! That would be big ;) I will try to let you know next week or so. Thank you!

**Comment by greg-dove** [comment]
to be clear... just in case I gave the wrong impression...  I don't mean the actual twoWay binding syntax. I thought you were using two fx:Binding tags to do it. I did not look at the twoWay stuff itself. That is for another day.

**Comment by carlosrovira** [comment]
Thanks for clarifying @greg-dove hehe, I was running to try "@" ;)

**Comment by piotrzarzycki21** [comment]
> to be clear... just in case I gave the wrong impression... I don't mean the actual twoWay binding syntax. I thought you were using two fx:Binding tags to do it. I did not look at the twoWay stuff itself. That is for another day.

Yes you are right I was talking about fx:Binding - We are using it to emulate two way binding.
