### ISSUE TITLE
ApplicationDataBinding is failing with constants

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-asjs#457]
Using constants at Application level in bindings fails currently. For example this code will not work properly:

using this bead at app level:

`<js:ApplicationDataBinding />`

and using this code inside a view or container:

`<j:Button text="Primary" emphasis="{Button.PRIMARY}"/>`

**Comment by piotrzarzycki21** [comment]
@greg-dove I'm not sure if it's related but I discovered another case where it's failing :( 
I have custom component which contains property `selectedItem ` with [Bindable] tag. I would like to have `Disabled` working when `selectedItem ` changed. In general binding for some reason work worse than it was before. :/

```
<j:VGroup xmlns:fx="http://ns.adobe.com/mxml/2009" 
		  xmlns:j="library://ns.apache.org/royale/jewel">
	  <j:beads>
		<js:ContainerDataBinding />
	</j:beads>
<j:Form localId="formBody">
		<j:beads>
			<j:FormValidator id="formValidator" trigger="{btnSubmit}" triggerEvent="click"/>
		</j:beads>
		<j:FormItem label="Customer ID:" required="true">
			<controls:AccountSelector localId="ddlCustomerId" />
		</j:FormItem>
		<j:Spacer height="20"/>
		<j:FormItem label="First Name:" required="true">
			<j:TextInput percentWidth="100">
				<j:beads>
					<j:StringValidator required="1"/>
					<j:Disabled disabled="{ddlCustomerId.selectedItem == null}"/>
				</j:beads>
			</j:TextInput>
		</j:FormItem>
</j:Form>
</j:VGroup>
```

**Comment by greg-dove** [comment]
@carlosrovira The original issue should be solved with latest code (duplicated in another ticket)

**Comment by greg-dove** [comment]
@piotrzarzycki21  I finally got to look at this, and for now I can't reproduce your issue.

I tested with the following code in an mxml component:

```
<j:VGroup xmlns:fx="http://ns.adobe.com/mxml/2009"
          xmlns:js="library://ns.apache.org/royale/basic"
          xmlns:j="library://ns.apache.org/royale/jewel">
    <fx:Script>
		<![CDATA[
        import org.apache.royale.collections.ArrayList;

        public function getDataProvider():ArrayList{
            var content:Array = ['test1', 'test2','test3', 'test4','test5', 'test6'];
            return new ArrayList(content);
        }
        ]]>
	</fx:Script>
    <j:beads>
        <js:ContainerDataBinding />
    </j:beads>
    <j:Form localId="formBody">
        <!--<j:beads>
            <j:FormValidator id="formValidator" trigger="{btnSubmit}" triggerEvent="click"/>
        </j:beads>-->
        <j:FormItem label="Customer ID:" required="true">
         <!--   <controls:AccountSelector localId="ddlCustomerId" />-->
            <j:DropDownList localId="ddlCustomerId" dataProvider="{getDataProvider()}"/>
        </j:FormItem>
        <j:Spacer height="20"/>
        <j:FormItem label="First Name:" required="true">
            <j:TextInput percentWidth="100">
                <j:beads>
                    <j:StringValidator required="1"/>
                    <j:Disabled disabled="{ddlCustomerId.selectedItem == null}"/>
                </j:beads>
            </j:TextInput>
        </j:FormItem>
        <j:FormItem label="Submit Button:" >
            <j:Button localId="btnSubmit" text="SubmitButton" click="ddlCustomerId.selectedItem=null"/>
        </j:FormItem>
    </j:Form>
</j:VGroup>
```

I could see the Disabled bead toggling on and off depending on whether the selectedItem was active or null.
Obviously I cannot check your custom AccountSelector component, so I just used a regular DDL.
Do you still have this issue? Or could you please give me a minimal repro? Thanks, Greg

**Comment by carlosrovira** [comment]
@greg-dove Thanks I can test the problem and seems is solved
@piotrzarzycki21 the problem in this ticket is about Application/ApplicationDataBinding only, bindings in sub files that use ContainerDataBinding has no problem . For that reason you can see anything wrong.
IMO, this issue was affecting to people entering royale and testing simple example that use bindings of constants in the main Application file (for example j:Button with emphasis={Button.PRIMARY}")
