### ISSUE TITLE
ViewDataBinding not working as expected when binding to properties within objects

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#46]
This flex SDK code:
```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
			   xmlns:s="library://ns.adobe.com/flex/spark" 
			   xmlns:mx="library://ns.adobe.com/flex/mx"
			   applicationComplete="init()">

	<s:layout>
		<s:VerticalLayout />
	</s:layout>
	
	<fx:Script>
		<![CDATA[
		[Bindable] public var obj:Object;

        public function init():void {
            obj = {text:"Hello World"};
        }
		]]>
	</fx:Script>
    
	<mx:Label text="{obj.text}" />

</s:Application>
```

Generates a warning re binding but still display "Hello World" as expected as the entire object is replaced.

The similar RoyaleJS code also generate a binding warning but fails to display "Hello World".

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic"
                xmlns:local="*" applicationComplete="init()">

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <fx:Script><![CDATA[

        [Bindable] public var obj:Object;

        public function init():void {
            obj = {text:"Hello World"};
        }
        ]]></fx:Script>
    
    <js:initialView>
        <js:View percentWidth="100" percentHeight="100">
            <js:beads>
                <js:ViewDataBinding/>
            </js:beads>
            <js:Label text="{obj.text}" />
        </js:View>
    </js:initialView>

</js:Application>
```

I can see that the binding event is being dispatched when the obj assignment is executed.

**Comment by piotrzarzycki21** [comment]
It will not be assigned cause you have to use appropriate bead for that purpose: "ApplicationDataBinding". Check and let us know whether it's working for you.

**Comment by piotrzarzycki21** [comment]
I see that you have used ViewDataBinding, can you also check with ApplicationDataBinding, without ViewDataBinding. Additionally check whether it is working for you if initial View is in separate file.

**Comment by piotrzarzycki21** [comment]
Additionally obj.text property is not [Bindable] - that is the reason. If you change Object to custom VO is it working for you ?

**Comment by justinmclean** [comment]
If you remove the ViewDataBinding and add this at the top level:
```
    <js:beads>
        <js:ApplicationDataBinding />
    </js:beads>
```
Hello world will show as expected.

Having the view as a component makes no difference.

obj.text property not being  [Bindable] is not the reason this doesn't work as obj is [Bindable] and the whole object is being replace not just the text changed. If you compile and run the Flex SDK version you'll see that it works.

**Comment by justinmclean** [comment]
In fact it seems that even simpler versions using a direct binding to string also fails see #47

**Comment by Harbs** [comment]
Do I understand correctly that using ApplicationDataBinding works?

**Comment by justinmclean** [comment]
Adding an ApplicationDataBinding bead and removing the ViewDataBinding bead does work.
