### ISSUE TITLE
How to create popup using actionscript ?

### ISSUE THREAD

**Issue by Dakshinads** [apache/royale-asjs#465]

**Comment by carlosrovira** [comment]
There are several ways to do this. In Basic, MXRoyale, Jewel, MDL... depends on UI set you're using it.
Here's code example from Tour de Jewel:

https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/PopUpPlayGround.mxml

and TDJ is here showing it running:

https://royale.apache.org/tourdejewel/

**Comment by Dakshinads** [comment]
Not this method .i want below the method
var pop:PopUp= new PopUp();
			pop.id="popup1";
			pop.className="somePopUpContent";
			pop.modal=true;
			
please correct the code.
Thank you

**Comment by carlosrovira** [comment]
do you mean to use in AS3?
that's ok.
after you add to parent:

`parent.addElement(pop);`

You can open it like this:

`pop.open = true` (or false)

**Comment by Dakshinads** [comment]
Specially thank you help me @carlosrovira

**Comment by sanjeev-rajput** [comment]
@carlosrovira 
do we also need to call parent.removeElement(pop) along with pop.open=false;
