### ISSUE TITLE
Button enabled Property is not working (Test Case Attached)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#467]
https://paste.apache.org/v74pl

button is enabled if enabled="false"

**Comment by aharui** [comment]
Set a breakpoint in the UIComponent 'enabled' setter.  It should cause the DisabledBead to set some CSS.  Then if you can click on it, look at the HTMLElement in the debugger and see if it still has that CSS on it.

**Comment by piotrzarzycki21** [comment]
enabled was commented out, but I just bring it back. I think we should emulate as much as we can, instead force user to change every button in his application for using DiasabledBead.

**Comment by piotrzarzycki21** [comment]
@pashminakazi please check with newest build.

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Thanks issue fixed.

**Comment by aharui** [comment]
MX Button should addBead DisabledBead.  MX component users should rarely need to add beads.  The MX components should automatically add them.
