### ISSUE TITLE
RemoteObject Data Retrieval is Very Slow

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#468]
In our application we are using mx:RemoteObject and in resultHandler we are recieving data as
e.result as Arraycollection but Grid is not populating because Java is sending much data (8000 fields)
when we decrease the data to (300 fields) the Grid will be populated

**Comment by alinakazi** [comment]
When populated rows are more than 300 and we assign e.result to adg.dataprovider. it takes alot time to show data in grid. Debugger stops  more than a minute at line adg.dataprovider = e.result; if data is much more like 8000 rows debugger stops at line adg.dataprovider = e.result and never excute it

**Comment by pashminakazi** [comment]
@aharui Thank u so much Alex

Before these commits
Virtual layout in ADG. Should fix #468
some refactoring and exposing more protected members to allow override
our CompanySetup looks like
![image](https://user-images.githubusercontent.com/42200979/64406487-5ff65c00-d09b-11e9-97b4-68165e1df648.png)


After these commits
Virtual layout in ADG. Should fix #468
some refactoring and exposing more protected members to allow override
our CompanySetup looks like
![image](https://user-images.githubusercontent.com/42200979/64406583-9af88f80-d09b-11e9-98cb-a4385189b386.png)

**Comment by aharui** [comment]
Probably some exception is being thrown.  Check the console and/or debug the code.

**Comment by pashminakazi** [comment]
Thanks a lot @aharui @piotrzarzycki21 . RemoteObject Retrieval issue has been resolved.
