### ISSUE TITLE
labelFunction issue in AdvancedDataGrid (Test Case Attached) Formatting

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#472]
Test Case :
https://paste.apache.org/uxwvf

**Comment by piotrzarzycki21** [comment]
This issue has to be fixed in two steps
1. Fix NumberFormatter - Done - I just pushed fix and it should be available with [build 28](http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/28/)
2. Fix labelFunction - I will try to get back to that on tomorrow or on Wednesday

**Comment by piotrzarzycki21** [comment]
@aharui I have implemented labelFunction handling in item renderer in following way, but it doesn't work and I think it may be a compiler issue.
1. I have created [DataGridColumnICollectionViewModel](https://github.com/apache/royale-asjs/blob/features/issue_472_label_function/frameworks/projects/MXRoyale/src/main/royale/mx/controls/beads/models/DataGridColumnICollectionViewModel.as) for [AdvancedDataGridColumnList ](https://github.com/apache/royale-asjs/blob/e0bc3320629c048a2fe645c2a83f813756beca33/frameworks/projects/MXRoyale/src/main/resources/defaults.css#L98) which holds `columnIndex`
2. AdvancedDataGridView sets [columnIndex](https://github.com/apache/royale-asjs/blob/e0bc3320629c048a2fe645c2a83f813756beca33/frameworks/projects/MXRoyale/src/main/royale/mx/controls/beads/AdvancedDataGridView.as#L78)
3. DataItemRendererFactoryForICollectionViewAdvancedDataGridData [sets columnIndex](https://github.com/apache/royale-asjs/blob/e0bc3320629c048a2fe645c2a83f813756beca33/frameworks/projects/MXRoyale/src/main/royale/mx/controls/advancedDataGridClasses/DataItemRendererFactoryForICollectionViewAdvancedDataGridData.as#L157) in AdvancedDataGridListData using created model
4. AdvancedDataGridListData provides all data in item renderer to [call labelFunction](https://github.com/apache/royale-asjs/blob/e0bc3320629c048a2fe645c2a83f813756beca33/frameworks/projects/MXRoyale/src/main/royale/mx/controls/advancedDataGridClasses/AdvancedDataGridItemRenderer.as#L139)

I'm assigning my labelFunction like that:
`<mx:AdvancedDataGridColumn dataField="ci_Code" headerText="Code" width=".40"  labelFunction="fn_FormatGrid" />`

For some reason it's not being called from item renderer. It looks like some anonymous function without any params in debugger. I'm attaching example with build based on my branch. 
[adg_labelfunction.zip](https://github.com/apache/royale-asjs/files/3775984/adg_labelfunction.zip)

**Comment by piotrzarzycki21** [comment]
@alinakazi , @pashminakazi I just pushed changes which should fix this issue. Note that there were also fixes on compiler sight, so make sure that you have also fresh version of that one.

**Comment by piotrzarzycki21** [comment]
@pashminakazi any update on this ?

**Comment by pashminakazi** [comment]
Example : https://paste.apache.org/pdbn4
![labelfunction](https://user-images.githubusercontent.com/42200979/67929011-25fa8f80-fbde-11e9-8c20-52b102754d55.gif)

**Comment by piotrzarzycki21** [comment]
> Example : https://paste.apache.org/pdbn4
> ![labelfunction](https://user-images.githubusercontent.com/42200979/67929011-25fa8f80-fbde-11e9-8c20-52b102754d55.gif)

@pashminakazi but your example itself is invalid - do you see that ? You are providing data source with strings:
`new ArrayCollection(["24236482.324234", "23424.435","42344.23423"]);`

and later you are trying to reach item with property item.ci_Code <- This property doesn't exists at all. Remove property item.ci_Code and it will work. 
`fmtAmount.format(item);`

Or provide proper data source:

`new ArrayCollection([{ci_Code : "24236482.324234"}, {ci_Code :"23424.435"},{ci_Code :"42344.23423"}]);`

**Comment by pashminakazi** [comment]
Issue has been resolved Thanks
