### ISSUE TITLE
spark Dropdownlist has no default selection,and List showing issue (Test Case Attached)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#474]
Spark DropDownList is not Showing List if once click on the dropdown and not selecting any Item from List,Also there is no default selection

https://paste.apache.org/yo4v7

**Comment by piotrzarzycki21** [comment]
I don't quite see issue with no list display, but definitely selection in drop down list was broken. I have fixed and hopefully it will work better. Please take a look into newest build [3616](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/3616/). Property requireSelection still doesn't work, but you can just initially make selectedIndex="0" and it will be enough. Please check how that fix work for you and let me know.

**Comment by piotrzarzycki21** [comment]
@pashminakazi any update on that ? Does my fix helps you ?

**Comment by pashminakazi** [comment]
@piotrzarzycki21 
Still same issue
Spark DropDownList is not Showing List if once click on the dropdown and not selecting any Item from List

**Comment by piotrzarzycki21** [comment]
Can you record some video to show me that ? You can use https://www.screentogif.com/

**Comment by piotrzarzycki21** [comment]
I'm asking for that cause I don't see this issue on mys sight. As I described selection didn't work at all in DropDownList, but I have fixed that. I need to see what is happening actually, cause we may not understand correctly each other.

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Thanks,
![Output](https://user-images.githubusercontent.com/42200979/66141457-2888ba00-e61d-11e9-814e-d6a28fce7ba0.gif)

**Comment by piotrzarzycki21** [comment]
Can you initially make selectedIndex="0" so we could eliminate at least that part.

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Check now
![Output2](https://user-images.githubusercontent.com/42200979/66145600-a1d7db00-e624-11e9-960f-4ed5a0b9e1aa.gif)

**Comment by piotrzarzycki21** [comment]
@pashminakazi I just fixed that issue. It will be available with build [3632](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/3632/)

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Thanks a lot it's working fine now
