### ISSUE TITLE
In ADG,Assigning ArrayCollection to dataprovider is not working in new sdk

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#477]
https://paste.apache.org/vaykh

**Comment by alinakazi** [comment]
we have downloaded sdk on 2 september last time , ArrayCollection example attached was working till 2nd of September. After 2nd of September we have download latest sdk today and the example is not working.

**Comment by piotrzarzycki21** [comment]
@alinakazi Please try build [3612](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/3612/) - I'm not entirely sure whether it is correct fix, but it ends up with proper rendering of ADG. Let me know whether there is no regression.

**Comment by alinakazi** [comment]
Issue has been fixed. Thanks
