### ISSUE TITLE
FocusManager.setFocus is throwing an exception

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#478]
Pause on exception 
TypeError: Cannot read property 'setFocus' of null

https://paste.apache.org/cvoig

**Comment by piotrzarzycki21** [comment]
I don't have solution for focus manager, but you are trying to place cursor inside TextInput. Try do this: 
`this.searchText.element.focus();`.

Remember that you may loose that focus once popup appear.

**Comment by aharui** [comment]
Pashmina is using the MX emulation components so the emulation should emulate the focusManager APIs.  She should not have to add the workaround you suggest.

**Comment by carlosrovira** [comment]
I think something more robust should be done at Royale level and then add to emulation like with the rest of other things. Focus management is a missing subject in Royale at least done in the right way (Multiplatform). In Jewel we solve with the trick Piotr refer, but is really a workaround that should be modified at later time

**Comment by piotrzarzycki21** [comment]
I agree with @aharui that she should use emulation straightforward, but my workaround was provided to help her move forward. If this allows meets deadlines it is better to change one line of code than wait couple of weeks till some volunteers will have time to look into that.

**Comment by pashminakazi** [comment]
After replacing "focusManager.setFocus(searchText);" with "this.searchText.element.focus()";
File : https://paste.apache.org/b1a2o
Console Error : https://paste.apache.org/m8qcs

**Comment by Harbs** [comment]
You should only get that error if you are compiling with SWF compatibility.

If it's a js-only app, add the following: `"targets": ["JSRoyale"]` (That would be in a `asconfig.json` file if you are using that.)

**Comment by piotrzarzycki21** [comment]
> After replacing "focusManager.setFocus(searchText);" with "this.searchText.element.focus()";
> File : https://paste.apache.org/b1a2o
> Console Error : https://paste.apache.org/m8qcs

I don't see that issue at all. I have tried build with Moonshine and by Maven. Everything worked fine. I did following. 
1) I went to [MX Hello World](https://github.com/apache/royale-asjs/tree/develop/examples/mxroyale/HelloWorld) example 
2) I have opened it  to Moonshine
3) I have opened file [HelloWorld.mxml](https://github.com/apache/royale-asjs/tree/develop/examples/mxroyale/HelloWorld/src/main/royale)
4) I copied content of your file (https://paste.apache.org/b1a2o) and paste into HelloWorld.mxml
5) I did menu Project -> Build and Run as JavaScript
Something is probably wrong on your sight.

**Comment by piotrzarzycki21** [comment]
> After replacing "focusManager.setFocus(searchText);" with "this.searchText.element.focus()";
> File : https://paste.apache.org/b1a2o
> Console Error : https://paste.apache.org/m8qcs

What version of SDK are you using? Is it JS or JS-SWF ?

**Comment by pashminakazi** [comment]
Thanks,Issue resolved
