### ISSUE TITLE
Issue in porting a file

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#481]
<mx:AdvancedDataGridColumn>
		<mx:itemEditor>
			<fx:Component>
				<s:MXAdvancedDataGridItemRenderer
we are using item renderer in our MXML file and generated output has errors

dbzVerificationPlanSetup : https://paste.apache.org/8lxdq
dbzVerificationPlanSetup.js : https://paste.apache.org/abxa9

Errors in javaScript file Image
![image](https://user-images.githubusercontent.com/42200979/65662035-af9dc700-e04c-11e9-88f0-c01284318f25.png)
![image](https://user-images.githubusercontent.com/42200979/65662077-c47a5a80-e04c-11e9-8c9a-66a7bfb87038.png)
![image](https://user-images.githubusercontent.com/42200979/65662087-c8a67800-e04c-11e9-8aaa-7eb11c56940d.png)
![image](https://user-images.githubusercontent.com/42200979/65662107-cf34ef80-e04c-11e9-88c7-359b7b4ab5c2.png)

**Comment by piotrzarzycki21** [comment]
```
<s:TextInput id="dgTxtInput2"   width="150%" maxChars="15" text="{data.levelDesc}"
													 updateComplete="vlddgTxtInput2.validate().type==ValidationResultEvent.INVALID ? '': returnPN1=dgTxtInput2.text;"
													 change="vlddgTxtInput2.validate().type==ValidationResultEvent.INVALID ? '' : returnPN1=dgTxtInput2.text;"/>
```

It looks like you have problems with above code. Can you try create methods for `change` and `updateComplete` event.  Put code inside that method and see if error goes away.
