### ISSUE TITLE
Unable to port a function in Royale

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#482]
we have a function in ActionScript File, setValueObject which is not working correctly 
when we call setvalueObject from one of our MXML files.
In flex, the behavior of it was copying arrFormItems to ValueObject.
In Royale, we send values correctly in arrFormItems as a parameter but the method is unable to set these values to valueobject 
setvalueObject : https://paste.apache.org/2130p

**Comment by greg-dove** [comment]
instead of:
 val.setValue[aValuObject] = aFormItems[k].text;
try using:
val.setValue(aValuObject,  aFormItems[k].text)

**Comment by pashminakazi** [comment]
@greg-dove Ok, thanks I will try this.
