### ISSUE TITLE
Adding bead <j:HorizontalCenteredLayout/> break child vertical position (attached file to reproduce)

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#483]
Hi,

When adding **<j:HorizontalCenteredLayout/>** in a **Group** then vertical position of childs elements is broken like if the **y** origin position is the **half of the child's height** and not the **top**.

issue on SDK  0.9.4 and 0.9.6 tested on Chrome Version 77.0.3865.90 (Build officiel) (64 bits)

Expected result would be that y position of childs don't change when adding HorizontalCenteredLayout

[Main.txt](https://github.com/apache/royale-asjs/files/3657582/Main.txt)

**With HorizontalCenteredLayout**
![image](https://user-images.githubusercontent.com/6851433/65686742-390dc300-e066-11e9-8820-b92fe9bb579c.png)

**Without HorizontalCenteredLayout**
![image](https://user-images.githubusercontent.com/6851433/65686783-55a9fb00-e066-11e9-88e9-39b165d3f760.png)

Regards

**Comment by carlosrovira** [comment]
Hi,

you're mixing Basic and Jewel components and that can generate unwanted or unexpected results.
Here the main problem is that Js:View (Basic View) is adding some styles on its own while that doesn't play well with Jewel Group.

Here's a version with all changed to Jewel

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
               xmlns:js="library://ns.apache.org/royale/basic" 
               xmlns:j="library://ns.apache.org/royale/jewel" >

    <j:valuesImpl>
        <js:SimpleCSSValuesImpl />
    </j:valuesImpl>
    
    <j:beads>
        <js:ApplicationDataBinding />
    </j:beads>

    <j:initialView>
        <j:View>
            <j:Group>
                <j:beads>
                    <j:HorizontalCenteredLayout gap="3"/>
                </j:beads>

                <j:Button width="100" height="100" text="B1" emphasis="primary"/>
                <j:Button width="50" height="150" text="B2" emphasis="secondary"/>
                <j:Button width="120" height="70" text="B3" emphasis="emphasized"/>
            </j:Group>
        </j:View>
    </j:initialView>
</j:Application>
```

The example produce this:

![Captura de pantalla 2019-09-27 a las 19 53 56](https://user-images.githubusercontent.com/1701640/65790798-a56ced00-e160-11e9-9f2b-e3ccee880a4d.png)
