### ISSUE TITLE
stateChangeComplete event is fired if set again same state (bug or not) ?

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#486]
Hi,

Suppose you have 2 states : **A** and **B** and currentState is **A**
Then setting currentState again to **A** will fire _stateChangeComplete_.

I don't know if we can consider this as a bug or not... On Flex component setting twice the same state doesn't fire _stateChangeComplete_

There is a simple workaround : just test the currentState before setting it.

Regards

**Comment by carlosrovira** [comment]
Hi, this seems to me a bug. change event should only be dispatched if state is not the same.

**Comment by cristallium** [comment]
Merged https://github.com/apache/royale-asjs/commit/42cd0c7c450f385a8fb2e5194cb1c7660578cd6b
