### ISSUE TITLE
How to retrieve image after browsing   

### ISSUE THREAD

**Issue by Dakshinads** [apache/royale-asjs#488]
var fileModel:FileModel = myFileProxy.model as FileModel;
				Alert.show(myFileProxy.size + " bytes of " + fileModel.name + " were loaded");

				imageButton.src=myFileProxy.fileReference.name;

**Comment by carlosrovira** [comment]
Hi, info is incomplete to be able to help here.
I think filemodel.name brings what? the filename?, the complete url?.
debug and see what's coming in the `name` property and you'll get a clue about what do you need to pass to `src` property.

**Comment by Dakshinads** [comment]
protected function Cmb_Label_clickHandler1(event:Event):void
         {
            myBrowser.browse();
             
         } 
		 protected function modelChangedHandler(event:org.apache.royale.events.Event):void
			{
				myFileProxy.model.addEventListener("blobChanged", blobChangedHandler);
				trace('loading: ' +  myFileProxy.name);
				myLoader.load();
			}

			private var fileModel:FileModel;
			private function blobChangedHandler(e:org.apache.royale.events.Event):void
			{
				fileModel= myFileProxy.model as FileModel;
				Alert.show(myFileProxy.size + " bytes of " + fileModel.name + " were loaded");
				//imageButton.src="D:\121.png";
				imageButton.src=myFileProxy.name;
				Alert.show(fileModel.name);
			}


	<j:Button   emphasis="secondary" text="Browse" click="Cmb_Label_clickHandler1(event)" width="100"/>
					<js:FileProxy id="myFileProxy" modelChanged="modelChangedHandler(event)">
			<js:beads>
				<js:FileModel/>
				<js:FileBrowser id="myBrowser"/>
				<js:FileLoader id="myLoader"/>
			</js:beads>
					</js:FileProxy>

		<j:ImageButton id="imageButton"  click="imageButtonClick(event)" width="750" height="400"/>


I want to retrieve image in image button after browsing image.

**Comment by carlosrovira** [comment]
Hi,
what is the output of `trace('loading: ' +  myFileProxy.name);`?

**Comment by Dakshinads** [comment]
This is used for testing.

**Comment by Harbs** [comment]
Below is what we're using to upload a file after it's selected using FileProxy and FileBrowser.
FileUploader is a custom class which uses URLBinaryLoader to do a multipart upload.

````
private function sendRasterImage(fileRef:FileProxy):void{
	stopUpload();
	var params:Object = {
		"f"  : fileRef.name,
		"id" : "foobaz"
	};

	uploader = new FileUploader(params);
	uploader.onComplete = handleRasterResponse;
	uploader.onError = handleUploadError;
	uploader.onProgress = handleUploadProgress;
	uploader.bytesToUpload = (loadingFile.model as IFileModel).blob as BinaryData;
	
	CursorManager.setBusyCursor();
	uploadStartTime = new Date().getTime();
	uploader.upload(APIConstants.PUT_IMAGE_URL);
	
}
````

**Comment by Dakshinads** [comment]
i want to retrieve image

**Comment by Dakshinads** [comment]
How to retrieve image after browsing in the same time

**Comment by yishayw** [comment]
Hi Dakshinads, when you say 'I want to retrieve image' do you mean you want the ImageButton to have the image you selected? Please be more clear as to the expected behavior, versus actual behavior. Thanks.

**Comment by Dakshinads** [comment]
Yes
