### ISSUE TITLE
Issue on percentHeight compute on <j:image>

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#490]
Hi,

Take the exemple named TourDeJewel in SDK 0.9.6
Then edit the MainContent.mxml and replace the section  **<j:BarSection itemsHorizontalAlign="itemsRight">** with the following content (in fact replace togglesbuttons  by image)
```
 <j:BarSection itemsHorizontalAlign="itemsRight">
                <!-- <j:Image src="assets/royale_spheres.png" height="80"/> -->
                <j:Image src="assets/royale_spheres.png" height="100%"/> 
 </j:BarSection>
```

Now if image is **height="100%"** then it doesn't show on the top right **when full size**.
If image is **height="80"** then image is showing right **in full size**
In both case image is ok when drawer is hidden

![capture](https://user-images.githubusercontent.com/6851433/65996379-93a88400-e497-11e9-97cc-125123540632.jpg)

I suspect a wrong height compute on something like this.

Full code here 
[TourDeJewel.zip](https://github.com/apache/royale-asjs/files/3678346/TourDeJewel.zip)

Regards

**Comment by Dakshinads** [comment]
<j:Image src="assets/royale_spheres.png" percentHeight="100"/> 

Using this way

**Comment by cristallium** [comment]
Thanks, it is working, but now after set again height="100%", it is working !
I think I have a clean issue on rebuild...
Now when deleting bin folder and rebuild it, it's ok
So I close this topic....
