### ISSUE TITLE
have a video , voice recording functions?

### ISSUE THREAD

**Issue by Dakshinads** [apache/royale-asjs#496]

**Comment by carlosrovira** [comment]
Still don't have it. But you don't need a concrete implementation in Royale for it. You can use some existing JS library and integrate in Royale. Royale team expect that others like you can join us and contribute this kind of libraries so other could use it directly or improve it over time.

**Comment by Dakshinads** [comment]
how to integrate existing JS?

**Comment by carlosrovira** [comment]
Right, you can follow this tutorial to do something quick: https://royale.apache.org/using-external-javascript-libraries-in-apache-royale/

Or if you want to try to make a Royale library with components and other kind of things that could be integrated and reused, you can mix that tutorial and check MDL lib here:

https://github.com/apache/royale-asjs/tree/develop/frameworks/projects/MaterialDesignLite

just some thoughts.

**Comment by Dakshinads** [comment]
Thank you @carlosrovira 👍
