### ISSUE TITLE
Update to select a range of dates in DateChooser

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#50]
Wen trying to select a range of dates the text gets selected but only the last date is selected this is confusing.
![2017-10-25_18-46-58](https://user-images.githubusercontent.com/144504/31986716-370078ac-b9b5-11e7-847e-0f07546d4e88.png)

This is a common use case e.g. selecting the check in and check out dates for a hotel.

Visually it may be best to disable text selection in the date chooser?

The ability of selecting a date range  would need to be added via a new bead rather than the existing component.

**Comment by pentapache** [comment]
Probably best to prevent selection and should be an easy fix. Range selection might be accomplished by adding a bead.
