### ISSUE TITLE
rawgit content dependencies: MXRoyale and Ace libs

### ISSUE THREAD

**Issue by greg-dove** [apache/royale-asjs#500]
I did a quick search in files in as-js, and it picked up MXRoyale and Ace libs in as-js. Perhaps there could be others, but hopefully that is all. This was discussed in recent months on dev list.
I am just adding this as an issue so we don't lose sight of it.

Rawgit *may* continue to work after end of October 2019, but there are no guarantees because that was the original timeframe announced, with the implication of uncertainty beyond it. [1]
'If you're currently using RawGit, please stop using it as soon as you can'

Some of the library contents in MXRoyale and Ace which have these external js dependencies may no longer work after that date. Alternative solutions for those will need to be found.

1. https://rawgit.com/

**Comment by Harbs** [comment]
I'm trying to work on this. Base64Encoder has two methods: `encode` and `encodeUTFBytes`. It looks to me like they are identical in JS. I don't see a reason why we need `TextEncoderLiteWrapper` (which has one of the dependencies). Am I missing something?
