### ISSUE TITLE
Link need to be updated on Apache Royale Website / FAQ

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#503]
Hi,

I'm not sure it's the right place to do this request, but I don't find source code of Apache Royale Website.
There is a issue on a link on 
https://royale.apache.org/faq/
in the end chapter (last minus one) the link on VisualStudioCode is https://nextgenactionscript.com/ (seems death) I think the right one is https://as3mxml.com/

Regards

**Comment by carlosrovira** [comment]
Thanks for catch that Fred. I'll fix the link.

The main website is created with Wordpress in a pre site and then uploaded to public.
The public site is here: https://github.com/apache/royale-website

**Comment by carlosrovira** [comment]
I fix the problem in IDEs page too
