### ISSUE TITLE
Issue in dbzAttachmentPopup 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#506]
File is compiled successfully but has run time issues
file:
https://paste.apache.org/e62kx

Test case is available on VDI.

**Comment by alinakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y

**Comment by pashminakazi** [comment]
Setups->Product->Profile (dbzProductProfileSetup)
![image](https://user-images.githubusercontent.com/42200979/66916866-9d082380-f035-11e9-92cb-3514b01e5b30.png)


Setups-> Item Inspection Reason (dbzReasonTypeSetup)
![image](https://user-images.githubusercontent.com/42200979/66916976-db9dde00-f035-11e9-8bd4-e80c353b1609.png)

**Comment by aharui** [comment]
Duplicate of #514

**Comment by aharui** [comment]
I am no longer seeing the 'nullthis' error (Setups -> Products -> Profile)

**Comment by aharui** [comment]
I am no longer seeing the other error (Setups -> Item Inspection Reason)

**Comment by alinakazi** [comment]
Item inspection reason is opened on vdi.
Yes now it is ok no error on debugger console.

Thanks alot Alex.

Regards,
Aleena
