### ISSUE TITLE
Issue in MaskedTextInput

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#508]
File is compiled successfully but has run time issues
file:
https://paste.apache.org/gq558

Test case is available on VDI.

**Comment by alinakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y

**Comment by pashminakazi** [comment]
Setups->Store Room -> Store City Distance (dbzStoreCityDistanceSetup)
![image](https://user-images.githubusercontent.com/42200979/66917217-6979c900-f036-11e9-9f17-b761f4c9d7e6.png)
![image](https://user-images.githubusercontent.com/42200979/66917250-7b5b6c00-f036-11e9-8f36-9dd78e50aff3.png)

**Comment by alinakazi** [comment]
@aharui  Please check this issue on our VDI. Thanks in Advance

**Comment by aharui** [comment]
Looks like your MaskedTextInput relied on a protected var textField in mx.controls.TextInput which has not been emulated.  It also looks like someone on your team altered MaskedTextInput and added a private var textField which is not initialized, resulting in this error.

I recommend that you remove the private var textField and replace textField.setColor with setStyle("color, 0);
