### ISSUE TITLE
Issue in MaskedDateField

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#509]
File is compiled successfully but has run time issues
file:
https://paste.apache.org/trnny

Test case is available on VDI.

**Comment by alinakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y

**Comment by pashminakazi** [comment]
Setups->Products->Profile
![image](https://user-images.githubusercontent.com/42200979/66916702-3a168c80-f035-11e9-8923-df8e8fec8c41.png)

**Comment by pashminakazi** [comment]
Setups->Store Room -> Tank Calibration Chart (dbzDateWiseTankStateSetup)
![image](https://user-images.githubusercontent.com/42200979/66980215-9e832b80-f0c9-11e9-92cb-9d0cbe081bfd.png)

**Comment by alinakazi** [comment]
**Setups-> Carriage/Freight-> Freight Rate**
File name (dbzFreightRateSetup) 
![combobase maskedDateField Issue in Setups-Carriage_Freight-Freight Rate  dbzFreightRateSetup](https://user-images.githubusercontent.com/36731338/66986471-d9f30b00-f073-11e9-86ba-23995f4f3709.png)

**Comment by alinakazi** [comment]
@aharui Please check this issue on our VDI. Thanks in Advance
