### ISSUE TITLE
[object,object] in dropDownlist 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#510]
It should show dataProvider element at index 0 value instead of [object,object]  in view of dropDownList.

Test case is available on VDI.

**Comment by alinakazi** [comment]
![dropdown object issue in setups-product-conditions](https://user-images.githubusercontent.com/36731338/66914692-34d12780-efcc-11e9-9676-decaf44f3a07.png)

**Comment by piotrzarzycki21** [comment]
@carlosrovira is it not related to your last commit ?

**Comment by alinakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y

**Comment by alinakazi** [comment]
@piotrzarzycki21  alright we haven't downloaded latest sdk after commit https://github.com/apache/royale-asjs/commit/21c2cdfcfb4599b0bd2c111b7bbedad3b388757f
I will see if the issue is fixed, i will close this issue.

**Comment by carlosrovira** [comment]
> @carlosrovira is it not related to your last commit ?

Hi Piotr, it seems what you say. Maybe that means some "hard code" comparison about the older string "EventDispatcher"? The toString() method in EventDispatcher should not be important in the output for a component in screen.

**Comment by alinakazi** [comment]
we need to add labelField with each dropdownlist as workaround

**Comment by alinakazi** [comment]
@aharui  please review my commit to fix this issue https://github.com/apache/royale-asjs/commit/611ad6e5b7b17e499ed318cfed39da0e6281b62f
