### ISSUE TITLE
TypeErrors: createCursor and child of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#513]
Setups->Foreign Currency -> Rates (dbzFCRatesMain) Loading Module (dbzExchangeRateDatewiseSetup)
TypeError: Cannot read property 'child' of undefined 
![image](https://user-images.githubusercontent.com/42200979/66918217-49e3a000-f038-11e9-8dac-70475fc399c2.png)
![image](https://user-images.githubusercontent.com/42200979/66918299-75ff2100-f038-11e9-8eda-9d83381b3bc6.png)

TypeError: Cannot read property 'createCursor' of null
![image](https://user-images.githubusercontent.com/42200979/66918005-de99ce00-f037-11e9-8db7-657924b26411.png)

Setups->Store Room -> Store
TypeError: Cannot read property 'createCursor' of null
![image](https://user-images.githubusercontent.com/42200979/66918005-de99ce00-f037-11e9-8db7-657924b26411.png)

**Comment by alinakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y
