### ISSUE TITLE
Can't add event handler code in AdvancedDataGridItemRenderer In-line Components

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#514]
While checking out the mx example I stumbled upon various runtime errors. Particularly, it looks like you can't add event handler code in AdvancedDataGridItemRenderer in-line components.

_Originally posted by @yishayw in https://github.com/apache/royale-asjs/issues/501#issuecomment-542834329_

**Comment by greg-dove** [comment]
fyi I've seen a bunch of issues with porting inline components in the past with bindings. In Carlos' app we worked around it by refactoring and making external renderer classes. It does need attention for sure, but I'd suggest if it is holding you up that you might want to consider that for now also.

**Comment by aharui** [comment]
What is the source of:

`org.apache.royale.utils.Language.trace('hello')`

Should that really be there?

**Comment by yishayw** [comment]
It's from
`										<mx:ComboBox labelField="label" id="footerLocationDD" top="0" left="0" right="0" bottom="0" width="100" 
														change="trace('hello')"					
														/> 
													`

**Comment by aharui** [comment]
It isn't that code is being run before Language is loaded, it is that the generated code is wrong.  I will look into fixing the compiler.
