### ISSUE TITLE
error compiling hello world

### ISSUE THREAD

**Issue by mguajardo** [apache/royale-asjs#515]
Hi, I'm having trouble running a basic hello world app, any advice what may be wrong:

Installed the npm binary for mac:
`sudo npm install @apache-royale/royale-js -g`

mxml to compile:
`<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009" xmlns:js="library://ns.apache.org/royale/express">
	<js:initialView>
		<js:View>
			<js:Label text="Hello World" x="100" y="100"/>
		</js:View>
	</js:initialView>
</js:Application>`

the command used for compling:
`/usr/local/bin/mxmlc src/hello.mxml `

And getting the following output:

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Basic.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Binding.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Charts.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Collections.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Core.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/CreateJS.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/DragDrop.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Effects.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Express.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Flat.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/FontAwesome.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Formatters.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/GoogleMaps.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Graphics.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/HTML.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/HTML5.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Icons.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Jewel.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Crux.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/jQuery.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Language.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/MaterialDesignLite.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Mobile.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Network.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Reflection.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/RoyaleSite.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/RoyaleUnit.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Storage.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/TLF.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/Text.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml(129): col: 0 Error: unable to open '/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/libs/XML.swc'.
/usr/local/lib/node_modules/@apache-royale/royale-js/royale-asjs/frameworks/royale-config.xml (line: 129)

      </library-path>

**Comment by aharui** [comment]
See this thread: http://apache-royale-development.20373.n8.nabble.com/Broken-royale-config-in-JS-only-build-of-released-Apache-Royale-SDK-0-9-6-td12515.html#a12543

**Comment by mguajardo** [comment]
thank you, that solved the issue
