### ISSUE TITLE
TypeError: Cannot read property 'data' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#516]
Login Page (DbizLogin.mxml)
File: https://paste.apache.org/vra87

![image](https://user-images.githubusercontent.com/42200979/66982855-8a8ef800-f0d0-11e9-912b-51191d471dd1.png)
![image](https://user-images.githubusercontent.com/42200979/66982974-db9eec00-f0d0-11e9-8c0d-570afff047c0.png)

**Comment by alinakazi** [comment]
@aharui Please check this issue on our VDI. Thanks in Advance

**Comment by aharui** [comment]
This was fixed in this commit. 39d6240c85c925edfe40165c7f830774d777babe
