### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#517]
Check this issue on VDI

Setups->Security->Groups (dbzSecurityPolicy)
File : https://paste.apache.org/kek6k

![image](https://user-images.githubusercontent.com/42200979/66988602-43a6ff80-f0dc-11e9-98ef-36dd13be480e.png)
![image](https://user-images.githubusercontent.com/42200979/66988767-7e109c80-f0dc-11e9-9eb8-a63142bf733e.png)

**Comment by alinakazi** [comment]
@aharui Please check this issue on our VDI. Thanks in Advance
