### ISSUE TITLE
TypeError: this.generateMXMLAttributes is not a function

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#518]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
File Name : dbzGainLossMasterSetup
Test Module: Feasibility 
**Setups->Gain/Loss**
![setup gainloss (dbzGainLossMasterSetup)](https://user-images.githubusercontent.com/36731338/67005235-0704e500-f097-11e9-95ca-1aab746ddf2b.png)

**Comment by alinakazi** [comment]
@aharui  Please look into this issue . Thanks in Advance
Go to **Feasibility** from **Select** in Menu
then, Go to **Gain/Loss** from  **Setups** in Menu

**Comment by aharui** [comment]
Was fixed in b8fbdc40d30cdfcd02766b1255b5e0c852ee667c which was incorrectly attributed to #516.
