### ISSUE TITLE
No easy way to bind to selectedDate in DateChooser

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#52]
In this code the text label does not get updated if the selected date changes.

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

    <fx:Script><![CDATA[
        ]]></fx:Script>

    <js:beads>
        <js:ApplicationDataBinding />
    </js:beads>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View>
            <js:Group id="content" width="300" height="500">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:DateChooser id="dc1" height="200" />
                <js:Label text="{dc1.selectedDate}" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>
```

This is not too unexpected but in order to support binding you would need to create both a Bindable data model and a bindable date chooser as both contain a setter/getter for selected date.

**Comment by justinmclean** [comment]
See https://github.com/justinmclean/flex-asjs/tree/bindabledatechooser for work in progress.

**Comment by pentapache** [comment]
Interesting problem. The actual selectedDateChanged event is dispatched from the model, but to use this from MXML in data-binding, it should be dispatched from the strand/DateChooser. The DateChooserView intercepts the selectedDateChanged event from the model and it could re-dispatch it from the strand as a way to fix this. But as a general rule, we probably want most "properties" on the strand to be bindable.

**Comment by pentapache** [comment]
I pushed a change to develop branch that should fix this. A bindable selectedDate is consistent with other components like List, which has a bindable selectedIndex property.

**Comment by pentapache** [comment]
I also changed DateField so its selectedDate property is also bindable.

**Comment by justinmclean** [comment]
Thanks for that look good. I did notice one minor issue that I'll raise in another issue.
