### ISSUE TITLE
ClassAliasBead.js:47 Uncaught TypeError: app.info is not a function

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#520]
Run Time Error Screenshot:
![Inventory_Balance Transfer dbzBalanceTransfer](https://user-images.githubusercontent.com/36731338/67093015-85c85380-f165-11e9-9d8d-fcf02cd950ab.png)

Go To : **Inventory** form menu and then click **Balance Transfer**
Please check this issue on our VDI. Thanks in Advance
Project Details are :
https://paste.apache.org/cpo8y
Filename : dbzBalanceTransfer and dbzBalanceTransferDetail
available in D:\DBIZSOL\Main\Royale\src\com\dbz\modules\INV

**Comment by pashminakazi** [comment]
Issue not Resolved

Go To : Inventory form menu and then click Balance Transfer
Please check this issue on our VDI. Thanks in Advance
Project Details are :
https://paste.apache.org/cpo8y
Filename : dbzBalanceTransfer and dbzBalanceTransferDetail
available in D:\DBIZSOL\Main\Royale\src\com\dbz\modules\INV

![image](https://user-images.githubusercontent.com/42200979/67278634-ccf67180-f4e2-11e9-9c8c-1b4c6a288568.png)
![image](https://user-images.githubusercontent.com/42200979/67278681-e0a1d800-f4e2-11e9-982a-478d17b3dec1.png)

**Comment by aharui** [comment]
ClassAliasBead is being used on a BorderContainer.  It can only be used on an Application or Module.
