### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#526]
Go to: Select -> Purchase.
then, Setups-> Item Inspection Reason
Please check this issue on our VDI.
Project Details are :
https://paste.apache.org/cpo8y
File Name : dbzReasonTypeSetup
available in D:\DBIZSOL\Main\Royale\src\com\dbz\modules\PUR

![image](https://user-images.githubusercontent.com/42200979/67273976-f90cf500-f4d8-11e9-9bce-5a2607318f9a.png)

![image](https://user-images.githubusercontent.com/42200979/67273988-ff02d600-f4d8-11e9-85d2-39cb995eac1c.png)

**Comment by aharui** [comment]
Looks like the MaskedTextInput (id="setupCode") is expected to have an inputMask but it is set to "".  It is not obvious how it gets set, so you'll have to review your logic
