### ISSUE TITLE
TypeError: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#531]
Setups-> Store Room -> Store
Please check this issue on our VDI.
Project Details are :
https://paste.apache.org/cpo8y
File Name : dbzStoreSetup
available in D:\DBIZSOL\Main\Royale\src\com\dbz\modules\Common
![image](https://user-images.githubusercontent.com/42200979/67658858-ade15f00-f97c-11e9-8ea9-b4b4fbcc42cd.png)

**Comment by aharui** [comment]
Are you sure you've updated the application on the VDI?  I keep getting the setColor exception.  Also, I suspect that I have to click on a button to get this error and I don't know which button to click.

**Comment by aharui** [comment]
I commented out the setColor calls in MaskedTextInput.  But I do not see the TypeError.

**Comment by pashminakazi** [comment]
Check on VDI
![Validate](https://user-images.githubusercontent.com/42200979/67745861-15fc7780-fa47-11e9-8e1b-4923350b61da.gif)

**Comment by aharui** [comment]
This was fixed by royale-compiler f7627268a7560878b75d3ca127ae049d6fe7a352
