### ISSUE TITLE
Uncaught TypeError : Cannot read property 'http_$$www_adobe..._setSelection' of null at radiobutton.set__selected

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#534]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to Retail Inspection from Select in Menu
Go to **Action Plan Execution** from Setups in Menu
File : com/dbz/modules/RI/dbzactionplanexecutioncriteria

![image](https://user-images.githubusercontent.com/36731338/67745089-8e7c1d80-f9e0-11e9-8eae-7d3a28dac4ea.png)

**Comment by aharui** [comment]
On the VDI, this example instead says that it can't find dbzActionPlanExecution.css.

**Comment by pashminakazi** [comment]
dbzActionPlanExecution is Compiled on VDI

**Comment by aharui** [comment]
On the VDI, this example is now saying that it can't find dbzActionPlanExecutionCriteria.css.

**Comment by pashminakazi** [comment]
dbzActionPlanExecutionCriteria is compiled on VDI

**Comment by pashminakazi** [comment]
issued solved : https://github.com/apache/royale-asjs/commit/c9caecea73c550faf21667492e0e0b8b97bb6a4f
