### ISSUE TITLE
Uncaught TypeError: Cannot read property of 'textInputField' of null at ComboBase.get__textInput ComboBase.js

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#535]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to Purchase from Select in Menu
Go to Product Product Rates - Date Wise from Setups in Menu
File : com/dbz/modules/PUR/dbzProdWiseStoreSetup

![image](https://user-images.githubusercontent.com/36731338/67745404-5fb27700-f9e1-11e9-8049-c0bb47cfd679.png)

**Comment by aharui** [comment]
I got the error that dbzDateWisePrdRateSetup.css was not found

**Comment by pashminakazi** [comment]
dbzDateWisePrdRateSetup is Compiled on VDI

**Comment by aharui** [comment]
Now I get the error that shmPurchaseModules.css is not found

**Comment by aharui** [comment]
I built the shmPurchaseModule and cannot reproduce this problem.
