### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined _createLists  DataGridView.js

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#537]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to Purchase from Select in Menu
Go to Specific Gravity @60-60degf from Setups in Menu
File : com/dbz/modules/PUR/dbzSpecificGravitySetup
![image](https://user-images.githubusercontent.com/36731338/67746890-b1a8cc00-f9e4-11e9-8cf0-a8ae25e06654.png)

**Comment by aharui** [comment]
This example instead shows an error dbzSpecificGravitySetup.css not found.

**Comment by pashminakazi** [comment]
dbzSpecificGravitySetup is Compiled on VDI

**Comment by aharui** [comment]
Now I get the error that shmPurchaseModule.css is not found
