### ISSUE TITLE
NPM install freezes

### ISSUE THREAD

**Issue by q00u** [apache/royale-asjs#539]
`npm install @apache-royale/royale-js-swf -g`

Everything works until:
```
Downloading Adobe AIR from http://airdownload.adobe.com/air/win/download/25.0/AdobeAIRSDK.zip
Adobe AIR download complete
Extracting Adobe AIR
Adobe AIR download complete
Extracting Adobe AIR
Adobe AIR extraction complete
Installation complete!
Adobe AIR extraction complete
```
at which point it freezes.

**Comment by aharui** [comment]
Mac or Windows?

**Comment by q00u** [comment]
Windows 10 (1809)
npm 6.11.3

**Comment by aharui** [comment]
I just tried it and it worked for me.  For some reason you are getting double "close" events.  I only get one "download complete" and "Extracting" messages.  Are you consistently getting double messages?  Can you try temporarily disabling your anti-virus programs?

**Comment by q00u** [comment]
Double messages every time.

It's a work-managed computer, so no anti-virus I can disable.

**Comment by carlosrovira** [comment]
Hi @aharui are you on Windows10? 
I tried in Mac and worked ok. Maybe is something on a concrete OS? (just wondering)

**Comment by aharui** [comment]
Yes, I used Windows 10 and the same npm version.
