### ISSUE TITLE
Call to a possibly undefined method isItemSelected through a reference with static type AdvancedDataGrid

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#543]
Console Error:
com/dbz/modules/AR/dbzPostDatedReceipts.mxml
![image](https://user-images.githubusercontent.com/42200979/67925977-a4533380-fbd6-11e9-8e4e-4590382aaff6.png)

UnComment
example="dbzPostDatedReceipts"
to see this Error on Console

**Comment by piotrzarzycki21** [comment]
Do you experience a fail during build of your application ?

**Comment by pashminakazi** [comment]
@piotrzarzycki21  yes

**Comment by piotrzarzycki21** [comment]
> Console Error:
> com/dbz/modules/AR/dbzPostDatedReceipts.mxml
> ![image](https://user-images.githubusercontent.com/42200979/67925977-a4533380-fbd6-11e9-8e4e-4590382aaff6.png)
> 
> UnComment
> example="dbzPostDatedReceipts"
> to see this Error on Console

Where I can find mentioned example ?

**Comment by pashminakazi** [comment]
@piotrzarzycki21 
Example : https://paste.apache.org/q2mqm

**Comment by piotrzarzycki21** [comment]
I just checked and it looks like this method wasn't emulated, so it is a missing feature.

**Comment by pashminakazi** [comment]
Solved

**Comment by piotrzarzycki21** [comment]
Can you shed some light how did you solved ?

**Comment by pashminakazi** [comment]
@Piotrzarzycki21
I just uncomment this method to compile my application,but if some functionality is missing please make change to make it functional
