### ISSUE TITLE
Compiler warning that appears as an exception in web console

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#544]
Referencing static method of custom class outputs warning while compiling, throws exception in web console.

compiler output : 

`WARNING: D:/dev/royale-emulation-works/github/royale-testing/src/main/mtest/bin/js-debug/main/mtest/FindBug.js:141: WARNING - mx.resources.ResourceManager.getInstance defined before its owner. mx.resources.ResourceManager is defined at D:/dev/royale-emulation-works/github/royale-testing/src/main/mtest/bin/js-debug/mx/resources/ResourceManager.js:19
main.mtest.FindBug.ERROR = mx.resources.ResourceManager.getInstance().getString('messages', 'error');
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

web console : 

`FindBug.js:141 Uncaught TypeError: Cannot read property 'ResourceManager' of undefined
    at FindBug.js:141
(anonymous) @ FindBug.js:141
SystemManager.js:231 Uncaught TypeError: Cannot read property 'mixins' of undefined
    at FindBug_mx_managers_SystemManager.mx.managers.SystemManager.start (SystemManager.js:231)
    at index.html:366`

source code : 

<?xml version="1.0" encoding="utf-8"?>

    <s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
               xmlns:s="library://ns.apache.org/royale/spark"
               xmlns:mx="library://ns.apache.org/royale/mx"
               paddingBottom="0" paddingTop="0" paddingLeft="0" paddingRight="0"
               height="100%" width="100%"
               creationComplete="onCreationComplete()"
               >
    <fx:Metadata>
        [ResourceBundle("messages")]
    </fx:Metadata>
   
    <fx:Script>
        <![CDATA[
            import mx.resources.ResourceManager;
           
            public static const ERROR:String = ResourceManager.getInstance().getString('messages', 'error');
           
            public function onCreationComplete():void {
               
            }
           
            protected function button_clickHandler(event:MouseEvent):void {
            }

        ]]>
    </fx:Script>
   
    <fx:Declarations>
    </fx:Declarations>   
   
    <s:layout>
        <s:VerticalLayout gap="10" paddingRight="10" paddingLeft="10" paddingTop="10" paddingBottom="20" />
    </s:layout>
   
    <s:Button id="button" width="200" label="Show/Hide" click="button_clickHandler(event)"/>

    <mx:Panel title="Form Container Example"
              paddingBottom="10" paddingTop="10" paddingLeft="10" paddingRight="10"
              height="100%" width="100%">
       
        <mx:Text width="100%"
                 text="Moving from one form field to another triggers the validator."/>
       
        <mx:Form width="100%" height="100%" >
            <mx:FormHeading label="Enter values into the form."/>
           
            <mx:FormItem label="First name" >
                <mx:TextInput id="fname" width="200"/>
            </mx:FormItem>
           
            <mx:FormItem label="{resourceManager.getString('messages', 'userName')}">
                <mx:TextInput id="username" width="200"/>
            </mx:FormItem>   
        </mx:Form>
       
    </mx:Panel>
    </s:Application>

**Comment by aharui** [comment]
Fixed in royale-compiler 245a1f7246c8ef4bf32feeff3365c016bae49edf
