### ISSUE TITLE
Is it possible to compile Flex3 to JS with Royale?

### ISSUE THREAD

**Issue by vladimirjegorov** [apache/royale-asjs#546]
Hi,
I have a huge legacy project in Flex 3, that we want to convert to JS due to Flash EOL. Was wondering if it is possible to use Royale just to recompile Flex 3 code (minor adjustments acceptable) to JS? Or is a full re-write more feasible? 
Asking this because as far as I understood the documentation, Royal supports only Flex4>JS. Or am I missing something?
Thanks in advance :)

**Comment by Harbs** [comment]
Why are you assuming it only support Flex4? There's projects for both `MXRoyale` and `SparkRoyale`.

**Comment by carlosrovira** [comment]
Hi @vladimirjegorov, as @Harbs I'm interested in know the place where we state just Flex 4. that's wrong MX is supported too. Thanks

**Comment by aharui** [comment]
Apache Flex only has the Flex 4 source.  The Adobe Flex 3 source was never donated.  There are some differences between MX components in Flex 4 and Flex 3.

Royale's MXRoyale components were built based on the Flex 4 source.  However, I'd be interested in finding out if Vladimir's app has issues that are specific to Flex 3 behavior and modifying the MXRoyale components to emulate both Flex 3 and Flex 4 behavior (another reason for Beads).

**Comment by vladimirjegorov** [comment]
@aharui Thank you for the clarification. I have no issues yet, as our team has not started any development. Just wanted to know what should I consider before attempting to convert from Flex3. 
Very well, I'll first try to compile the code what I have and move on from there :)
I will report shortly if I will have any success :)

**Comment by vladimirjegorov** [comment]
Thank you everybody for the answers! Got a quick start for my project. Relatively quickly managed to convert a small portion of my app, but we can start from there :) 
@aharui I guess my main issue/problem was to 'start' :) I was trying to get compilation working with my favourite IDE - IntelliJ, however I was getting unknown compiler errors or it was not compiling at all. Then I tried importing my project to Flash Builder 4.7 and just by adding royale-js as my FlexSDK (and replacing the JRE, as it was mentioned in the official docs) it started to successfully compile :) Yay! I guess I will be still using IntelliJ for writing code, and switch to FlashBuilder from time to time just for compilation. Now comes a lengthy period of step-by-step conversion from FlexSDK to Royale :)
Would be nice to get Royale to work with IntelliJ, though (to get IntelliJ to compile-on-save, show compilation errors properly and code completion) :)
Rather than that, thanks to everyone who tried to help! Cheers!

**Comment by Harbs** [comment]
FYI, you'll probably have the best dev experience using either VS Code with the AS & MXML extension, or Moonshine. I'd recommend giving one, or both a try.

**Comment by carlosrovira** [comment]
Hi, I think VSCode or Moonshine are better options today and are supported tools developed actually. Is what we all here use.
I recommend trying to avoid FlashBuilder since is a deprecated IDE no longer supported.
IntelliJ maybe can be an option, but since there's no official support, maybe will be difficult to get something more of what you already have now.
