### ISSUE TITLE
Tree component does not refresh after data provider content is updated.

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#552]
Tree component does not refresh after data provider content is updated. When I debug to code I can see that the  validateNow() of UIComponent is not implemented.

**Comment by aharui** [comment]
The emulation components don't use validation/invalidation because JS doesn't have the same deferred rendering model that Flash does.  So whether validateNow does anything or not probably isn't the issue.

**Comment by aharui** [comment]
This issue references this thread: https://lists.apache.org/thread.html/28b227c83415d9b9c929f915c9ecce245d6ccdafcc26458e1f55ca3f@%3Cusers.royale.apache.org%3E

**Comment by aharui** [comment]
event.message.body may have been incorrectly converted to a String instead of XML.

**Comment by nihavend** [comment]
> event.message.body may have been incorrectly converted to a String instead of XML.
originally I was using event.result. 

`var treeXml:XML = XML(event.result);`

and setting new data for data provider

`liveTreeDP = new XMLList(treeXml);`

and running `liveTree.validateNow();` to get tree reconstructed. what is the royale approach to get tree re-rendered with new data ?

**Comment by aharui** [comment]
The code should remain the same.  We just need to understand what the data types are vs what they should be.

I suggest that you go back to your original code and in the JS debugger, determine if event.result is a String or XML before the line:

`var treeXml:XML = XML(event.result);`

Then see what treeXml is after that line executes.  Do not use trace() because that may not truly indicate the type of event.result.

**Comment by nihavend** [comment]
![552eventresult](https://user-images.githubusercontent.com/5983818/68540112-10cfee80-039e-11ea-9479-cc23f9cc9261.JPG)
It is XML

**Comment by aharui** [comment]
OK, keep going into the next lines of code.  What is the expected type of liveTreeDP?  Is it passed a reasonable value?  Maybe `XMLList(treeXML)` isn't doing the right thing.

**Comment by nihavend** [comment]
In js  `com.likya.pinara.comps.TreePanel["liveTreeDP"] = new XMLList(treeXml);` is the line that initialize the object.

![image](https://user-images.githubusercontent.com/5983818/68540386-61e1e180-03a2-11ea-981e-28526234fcdf.png)

**Comment by aharui** [comment]
Keep going.  What is TreePanel?  How does liveTreeDP actually become the dataProvider for an mx:Tree?

**Comment by nihavend** [comment]
TreePanel is a panel contains the components like Tree. And the three component references the data provider :

```
		<containers:AutoSizeTree id="liveTree"
				 labelField="@label"
				 fontSize="12"
				 showRoot="true"				 
				 dataProvider="{liveTreeDP}"
				 height="100%"				 
				 width="220"
				 contentBackgroundColor="#DAE0E6"
				 fontWeight="bold" 
				 color="#0D173C"
				 left="0" top="0" right="0" bottom="0"
				 openItems="true"
				 itemClick="tlosTree_itemClickHandler(event)"
				 itemDoubleClick="liveTree_itemDoubleClickHandler(event)"
				 />
```
containers:AutoSizeTree extends from Tree.

Here is the code : https://drive.google.com/open?id=1oxtgbbiOZTipjKfWTp6q9gupSse6_Tkp

**Comment by aharui** [comment]
What does TreePanel.js look like?  Post a link to it.  I'm wondering if the static var was handled properly by the binding code.

**Comment by nihavend** [comment]
https://drive.google.com/open?id=1F2g9UpwoiNrhKlQp7-33RkK5l5MhmzoK

**Comment by aharui** [comment]
I have to stop work for tonight.  I think the recent change that put static var initializers in getters broke static binding.  Maybe @greg-dove  has time to tweak the generated code for a static binding.  I don't get why the generated code doesn't access staticEventDispatcher.  I think it should, especially after the change to make staticEventDispatcher a getter.

If Greg doesn't have time I will try to find time about 23 hours from now.

**Comment by greg-dove** [comment]
I'm working on something else right now, but a quick glance at the generated code that was posted makes me think that the generated binding setter is probably not dispatching.
See ** comment below:

```
liveTreeDP: {
  get: function() {
    return com.likya.pinara.comps.TreePanel.liveTreeDP_;
  },
  
  set: function(value) {
    	var oldValue = com.likya.pinara.comps.TreePanel.liveTreeDP_;
    	if (value != oldValue) {
      		com.likya.pinara.comps.TreePanel.liveTreeDP_ = value;
      		var dispatcher = com.likya.pinara.comps.TreePanel._bindingEventDispatcher;  //** this should be '.staticEventDispatcher' not '._bindingEventDispatcher'      		
      		if (dispatcher) dispatcher.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(
      			com.likya.pinara.comps.TreePanel, "liveTreeDP", oldValue, value));
      }
    }
  }
```


Hopefully that is all that is needed. I can look at fixing this later today. However Serkan, if you want to confirm this you should be able to easily test it by making the change above in your js-debug output to see if it works. If you can confirm that, it would be helpful. (js-release won't work until this is addressed)

**Comment by greg-dove** [comment]
Actually on second thoughts, I am not sure about that... that ought to work after a listener was already added to the staticEventDispatcher as a getter... which should happen via the binding classes. I'll see if I can figure it out later today my time.

**Comment by greg-dove** [comment]
@aharui I did not get time to look at this today. I can definitely find time tomorrow if you don't get to it.

**Comment by nihavend** [comment]
> I'm working on something else right now, but a quick glance at the generated code that was posted makes me think that the generated binding setter is probably not dispatching.
> See ** comment below:
> 
> ```
> liveTreeDP: {
>   get: function() {
>     return com.likya.pinara.comps.TreePanel.liveTreeDP_;
>   },
>   
>   set: function(value) {
>     	var oldValue = com.likya.pinara.comps.TreePanel.liveTreeDP_;
>     	if (value != oldValue) {
>       		com.likya.pinara.comps.TreePanel.liveTreeDP_ = value;
>       		var dispatcher = com.likya.pinara.comps.TreePanel._bindingEventDispatcher;  //** this should be '.staticEventDispatcher' not '._bindingEventDispatcher'      		
>       		if (dispatcher) dispatcher.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(
>       			com.likya.pinara.comps.TreePanel, "liveTreeDP", oldValue, value));
>       }
>     }
>   }
> ```
> 
> Hopefully that is all that is needed. I can look at fixing this later today. However Serkan, if you want to confirm this you should be able to easily test it by making the change above in your js-debug output to see if it works. If you can confirm that, it would be helpful. (js-release won't work until this is addressed)

I made the changes in the js but could not make it work. I prepared a simple example, I made the changes on this small sample but even the sample did not work. 

Also colud not make it to load tree data dynamically.

Here is the source :

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
			   xmlns:s="library://ns.apache.org/royale/spark"
			   xmlns:mx="library://ns.apache.org/royale/mx"
			   paddingBottom="0" paddingTop="0" paddingLeft="0" paddingRight="0"
			   height="100%" width="100%" 
			   creationComplete="loadData()"
			   >
	
	<fx:Metadata>
	</fx:Metadata>
	
	<fx:Script>
		<![CDATA[
			
			import mx.collections.XMLListCollection;
			import mx.events.ListEvent;
			
			[Bindable]
			public var selectedNode:XML;
			
			[Bindable] 
			public static var liveTreeDP:XMLList;
			
			public function loadData():void {
				liveTreeDP = <><node label="3 Node"></node></>; 
			}
			
			public function Node3View():void {
				
				try {
					liveTreeDP = treeData3Node;
					myTree.validateNow();
				} catch(err:Error) {
					//Alert.show("HATA : " + errorString);
					trace(err);
				}
				
			}
			
			public function Node6View():void {
				
				try {
					liveTreeDP = treeData6Node;
					myTree.validateNow();
				} catch(err:Error) {
					//Alert.show("HATA : " + errorString);
					trace(err);
				}
				
			}
			
			private function tlosTree_itemClickHandler(e:ListEvent):void {
				
			}
			
			protected function liveTree_itemDoubleClickHandler(event:ListEvent):void {
				
			}
			
			public function treeChanged(event:Event):void {
				selectedNode=Tree(event.target).selectedItem as XML;
			}
			
		]]>
	</fx:Script>
	
	<fx:Declarations>
		<fx:XMLList id="treeData3Node">
			<node label="3 Node">
				<node label="Inbox">
					<node label="Marketing"/>
					<node label="Product Management"/>
					<node label="Personal"/>
				</node>
				<node label="Outbox">
					<node label="Professional"/>
					<node label="Personal"/>
				</node>
				<node label="Spam"/>
			</node>	
		</fx:XMLList>
		<fx:XMLList id="treeData6Node">
			<node label="6 Node">
				<node label="Inbox">
					<node label="Marketing"/>
					<node label="Product Management"/>
					<node label="Personal"/>
				</node>
				<node label="Outbox">
					<node label="Professional"/>
					<node label="Personal"/>
				</node>
				<node label="Spam"/>
				<node label="Sent"/>
				<node label="Region">
					<node label="First"/>
					<node label="Second"/>
				</node>
				<node label="Division">
					<node label="Up"/>
					<node label="Down"/>
				</node>
			</node>	
		</fx:XMLList>
		
		<fx:XMLList id="treeData">
			<node label="Mail Box">
				<node label="Inbox">
					<node label="Marketing"/>
					<node label="Product Management"/>
					<node label="Personal"/>
				</node>
				<node label="Outbox">
					<node label="Professional"/>
					<node label="Personal"/>
				</node>
				<node label="Spam"/>
				<node label="Sent"/>
			</node>	
		</fx:XMLList>
		
	</fx:Declarations>	
	
	<s:layout>
		<s:VerticalLayout gap="10" paddingRight="10" paddingLeft="10" paddingTop="10" paddingBottom="20" />
	</s:layout>
	
	<s:Button id="TreeNode" click="Node3View()"  label="3 Node"/>
	<s:Button id="SixNode" click="Node6View()"  label="6 Node"/>
	
	<mx:Panel title="Tree Control Example"
			  paddingBottom="10" paddingTop="10" paddingLeft="10" paddingRight="10"
			  height="50%" width="50%">
		
		<mx:Label width="100%" 
				  text="Select a node in the Tree control."/>
		
		<mx:HDividedBox width="100%" height="100%">
			<mx:Tree id="myTree" width="50%" height="100%" labelField="@label"
					 showRoot="false" dataProvider="{liveTreeDP}" change="treeChanged(event)"/>
			<mx:Tree id="myTreeStatic" width="50%" height="100%" labelField="@label"
					 showRoot="false" dataProvider="{treeData}" change="treeChanged(event)"/>
			<mx:TextArea height="100%" width="50%"
						 text="Selected Item: {selectedNode.@label}"/>
		</mx:HDividedBox>
		
	</mx:Panel>
	
</s:Application>
```

**Comment by greg-dove** [comment]
Thanks Serkan, that makes it easier. I can take a look now.

**Comment by greg-dove** [comment]
OK, I can see that it is a problem with the binding setup code, not working for static bindings in this case. I can fix this tomorrow my time (unless Alex wants to do it).

**Comment by greg-dove** [comment]
Just quickly: I was able to make it work with 2 simple changes:
```
ContainerBinding.as, line 175:     sb = new SimpleBinding(fieldWatcher.type == 'static');
SimpleBinding.as , line 207:	source = document.constructor;
```
But I suspect that there is more to be done in general in other parts

**Comment by aharui** [comment]
My evening did not work out as I expected so I won't have time to deal with this today.

**Comment by greg-dove** [comment]
@nihavend I just pushed a change that should fix this. I have intended to do a sweep through binding-related issues for some time, so if you see any others please add an issue and feel free to assign to me. Unfortunately I have kept deferring this task because I end up focusing on other higher priority tasks (based on my priorities, which are influenced by the needs of my clients), and the issues I know of so far are able to be worked around in various ways. But it does need a bit of attention, and I will get there before too long.

**Comment by aharui** [comment]
@greg-dove The fix is fine for now so that Serkan can keep going so thanks for doing that.  IMO, if you are going to do more work in this area, we definitely need to make static binding PAYG.  There should be no (or almost no) if statements.  Maybe create a SimpleStaticBinding class.  Maybe the compiler should generate the bindings array with additional data so the determination of what is or isn't a static binding is more straightforward (and possibly faster).  When the compiler knows something, it can often be worth encoding that knowledge so the AS/JS code doesn't have to figure it out at runtime.

**Comment by nihavend** [comment]
@greg-dove, @aharui thank you for the fix. I can confirm that your fix works for the test cases Greg. I have an issue related with different data that makes tree not populate correctly but still trying to discover. So I am closing the issue, we may continue on another one if necessary.

For note, this is the xml that does not work with dynamic tree loading just for info :

```
<fx:XMLList id="PInaraData">
	<list title="Grup Listesi" id="0">
		<jobGroup title="Independents" id="-1">
			<jobProperty title="SENSORDATA_HOURLY" id="1" statu="0" port="1"/>
			<jobProperty title="SENSORDATA_DAILY" id="2" statu="0" port="1"/>
			<jobProperty title="SENSORDATA_ALWAYSON" id="3" statu="0" port="1"/>
			<jobProperty title="SENSORDATA_FIVE_MIN" id="4" statu="9" port="1"/>
			<jobProperty title="PERSONAL_PROFILE_INFO" id="5" statu="9" port="1"/>
			<jobProperty title="SENSORDATA_AVG_CONS" id="6" statu="9" port="1"/>
		</jobGroup>
	</list>
</fx:XMLList>
```

**Comment by greg-dove** [comment]
@nihavend thanks for the details. The new issue sounds like something other than Binding-related, because the dataProvider binding sounds like it is working now. It seems to be Tree component internals, so it might be easier for others who worked on Tree recently. If no-one else takes it in a couple of days, I will try to look at it, though.
@aharui I hope to get to bindings sometime within the next month. When I do, my intention is to fix things that are not working right as initial focus, that is priority. Agree about the compiler comments, there are some things I think can be improved in the watcher stuff to reduce size/improve perf. I'm not sure yet how easy it will be with RoyaleUnit, but I'd like to make sure tests are available though so we can avoid repeats of some of the regressions that have happened during the last 3 years (mainly in swf, I think, which is likely not getting the same degree of attention). Then I can start a discussion thread in dev about PAYG/Bindings and refactor for PAYG based on consensus, adjusting tests as required. I'd aim to make sure this is all done before year's end.
