### ISSUE TITLE
Data can't be selected From PopUpManager 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#553]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to Feasibility from Select in Menu
Go to Misc -> Cities in Menu
File : com/dbz/modules/Common/dbzCitySetup
![PickList Issue](https://user-images.githubusercontent.com/42200979/68647059-abffca00-053e-11ea-9fcd-abebd6c37bef.gif)

**Comment by aharui** [comment]
I do not understand the problem.  What data cannot be selected from what component?  dbzCitySetup seems to be calling some other code.
