### ISSUE TITLE
mx:DateValidator not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#555]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to Feasibility from Select in Menu
Go to Product Grouping in Menu
File : com/dbz/modules/FS/dbzProductGroupingFeasilbilitySetup

In this setup we are using dbzSetupList 
Path : DBIZCOMLIB\src\com\dbz\modules\components\dbzSetupList
![SetupList hostfrm](https://user-images.githubusercontent.com/42200979/68647460-c1292880-053f-11ea-9bb1-99a550ead0fc.gif)

**Comment by aharui** [comment]
I do not understand what problem is being described here.  I cannot tell from the attached image.  Please provide more detailed steps and what components are involved and what is expected and what is actually happening.  I do not know how to get the validators to run or where to set breakpoints.

I did notice the DateValidators are binding to HostFrm which is an Object and not some explicit type, so there is a good chance that the production version will not work as the minifier may rename those properties.

**Comment by alinakazi** [comment]
@aharui
 the point where we called SetupList.HostFrm = this;
It was executed after the execution of line
		<mx:DateValidator id="vldDate"  source = "{HostFrm.setupColumnDate}"  inputFormat="{parentMxmlDocument.parentMxmlDocument.parentMxmlDocument.appParams.DATE_FORMAT}" property="text"/>

In flex SetupList.HostFrm = this; was executed before 
<mx:DateValidator id="vldDate"  source = "{HostFrm.setupColumnDate}"  inputFormat="{parentMxmlDocument.parentMxmlDocument.parentMxmlDocument.appParams.DATE_FORMAT}" property="text"/>
