### ISSUE TITLE
Uncaught TypeError: Cannot set property 'selectable' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#558]
Go to: Select -> Purchase.
then, Setups-> Shifts
Please check this issue on our VDI.
Project Details are :
https://paste.apache.org/cpo8y
File Name : dbzShiftSetup
available in D:\DBIZSOL\Main\Royale\src\com\dbz\modules\Common

![image](https://user-images.githubusercontent.com/42200979/68846945-a4335780-06ef-11ea-8046-d24927dc4a59.png)
![MaskedTextInput selectable](https://user-images.githubusercontent.com/42200979/68847048-ccbb5180-06ef-11ea-9d53-ac4540948b01.gif)

**Comment by aharui** [comment]
All other uses of textField in MaskedTextInput have been commented out except the ones in handleDoubleClick.  Seems like those should be commented out as well.
