### ISSUE TITLE
Layout issues in mx:advancedDataGrid

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#560]
Following points are reported by our QA team while testing our setups.

1. Sorting  functionality on columns like code and description in our setups is not implemented.
   column sorting functionality was implemented in flex sdk . when we use to click a column header  
   it sort the elements in ascending and descending order.

2. Grid column was re sizable in flex , not in Royale.

3. column separator was available in  flex , not in Royale.

**Comment by safrizal** [comment]
#response_container_BBPPID{font-family: initial; font-size:8pt; color: initial;}                                                                                                                                               Sent from my BlackBerry — the most secure mobile device — via the IndosatOoredoo Network                                                                                                                                                                           From: notifications@github.comSent: 15 November 2019 6:00 pmTo: royale-asjs@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [apache/royale-asjs] Layout issues in mx:advancedDataGrid (#560)  Following points are reported by our QA team while testing our setups.



Sorting  functionality on columns like code and description in our setups is not implemented.

column sorting functionality was implemented in flex sdk . when we use to click a column header

it sort the elements in ascending and descending order.



Grid column was re sizable in flex , not in Royale.



column separator was available in  flex , not in Royale.

**Comment by aharui** [comment]
These are now emulated.  They probably need improvements.

**Comment by alinakazi** [comment]
@aharui  thanks for the fixes.

column resize is still not working

**Comment by alinakazi** [comment]
Difference between flex and royale
![4](https://user-images.githubusercontent.com/36731338/69139875-4186e680-0a76-11ea-8bb5-4b28da33c622.gif)

**Comment by aharui** [comment]
Column Resizing should work now, although the graphics are not the same.
