### ISSUE TITLE
Tree component : labelFunction not implemented

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#563]
labelFunction not implemented in Tree component. The output for compiler : 

```
D:\dev\royale-emulation-works\github\royale-testing\src\main\mtest\FindBug.mxml(73): col: 7 Error: This attribute is unexpected. It will be ignored.

                                         labelFunction="treeLabel"
                                         ^

D:\dev\royale-emulation-works\github\royale-testing\src\main\mtest\FindBug.mxml(73): col: 7 Error: This attribute is unexpected. It will be ignored.

                                         labelFunction="treeLabel"
                                         ^
```

Sample code : 

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
			   xmlns:s="library://ns.apache.org/royale/spark"
			   xmlns:mx="library://ns.apache.org/royale/mx"
			   paddingBottom="0" paddingTop="0" paddingLeft="0" paddingRight="0"
			   height="100%" width="100%" 
			   creationComplete="loadData()"
			   >
	
	<fx:Metadata>
	</fx:Metadata>
	
	<fx:Script>
		<![CDATA[
			
			
			[Bindable] 
			public static var liveTreeDP:XMLList;
			
			public function loadData():void {
				liveTreeDP = PInaraData;
			}
			
			private function treeLabel(item:Object):String { 
				
				var node:XML = XML(item); 
				//Alert.show(node.localName());
				if (node.localName() == "list") {
					return node.@title; 
				} else if (node.localName() == "jobGroup") {
					if(node.@id == "") {
						// Alert.show("node : " + node);
					}
					return node.@title + " [Id:" + node.@id + "]"; 
				} else if(node.localName() == "jobProperty") {
					//return node.@name; 
					if(node.@id == "") {
						// Alert.show("node : " + node);
					}
					return node.@title + " [Id:" + node.@id + "]"; 
				}
				
				return node;
			} 
			
		]]>
	</fx:Script>
	
	<fx:Declarations>		
		<fx:XMLList id="PInaraData">
			<list title="Grup Listesi" id="0">
				<jobGroup title="Independents" id="-1">
					<jobProperty title="SENSORDATA_HOURLY" id="1" statu="0" port="1"/>
					<jobProperty title="SENSORDATA_DAILY" id="2" statu="0" port="1"/>
					<jobProperty title="SENSORDATA_ALWAYSON" id="3" statu="0" port="1"/>
					<jobProperty title="SENSORDATA_FIVE_MIN" id="4" statu="9" port="1"/>
					<jobProperty title="PERSONAL_PROFILE_INFO" id="5" statu="9" port="1"/>
					<jobProperty title="SENSORDATA_AVG_CONS" id="6" statu="9" port="1"/>
				</jobGroup>
			</list>
		</fx:XMLList>
	</fx:Declarations>	
	
	<s:layout>
		<s:VerticalLayout gap="10" paddingRight="10" paddingLeft="10" paddingTop="10" paddingBottom="20" />
	</s:layout>
	
	<mx:Panel title="Tree Label Function Example"
			  paddingBottom="10" paddingTop="10" paddingLeft="10" paddingRight="10"
			  height="50%" width="50%">
		
			<mx:Tree id="myTree" width="50%" height="100%" labelField="@title"
					 labelFunction="treeLabel"
					 showRoot="true" dataProvider="{liveTreeDP}" />
		
	</mx:Panel>
	
</s:Application>
```
@aharui I checked the AdvancedDataGrid, AdvancedListBase and ListBase but could not find the implementation for labelFunction. I need your assistance.

**Comment by piotrzarzycki21** [comment]
No so long ago I have resolved for Alina #472 . You can review commits and try to implement it similar.

**Comment by nihavend** [comment]
@piotrzarzycki21 thanks, I checked the implementation in [DataGridColumn.as](https://github.com/apache/royale-asjs/blob/e0bc3320629c048a2fe645c2a83f813756beca33/frameworks/projects/MXRoyale/src/main/royale/mx/controls/dataGridClasses/DataGridColumn.as) 

adding (get/set)ter for _labelFunction and and the event binding will work, right ?

```
    //----------------------------------
    //  labelFunction
    //----------------------------------

    /**
     *  @private
     *  Storage for the labelFunction property.
     */
    private var _labelFunction:Function;

    [Bindable("labelFunctionChanged")]
    [Inspectable(category="Other")]

    public function get labelFunction():Function
    {
        return _labelFunction;
    }

    /**
     *  @private
     */
    public function set labelFunction(value:Function):void
    {
        _labelFunction = value;
    }

```

@aharui you suggested to add the _labelFunction to base class. Which one is the right place, UIComponent or UIBase ?

**Comment by nihavend** [comment]
@piotrzarzycki21 @aharui  hope ypu have time to check.

I changed the function in ListBase.as as follows 

```
        /**
         *  @private
         *  @royaleignorecoercion org.apache.royale.core.ISelectionModel
         */
        public function set labelField(value:String):void
        {
			
			if (labelFunction)
			{
				(model as ISelectionModel).labelField = labelFunction(value);
			}
			else
			{
				(model as ISelectionModel).labelField = value
			}
			
			
            // (model as ISelectionModel).labelField = value;
        }
```

Unfortunately, labelField setter is called before the labelFunction setter so does not have any effect on the result.

**Comment by greg-dove** [comment]
I can't spend time on this now sorry, but (as at least a temporary solution) did you try changing the order of : 
labelField="@title"  labelFunction="treeLabel"

to : 
labelFunction="treeLabel" labelField="@title" 

in the mxml?

**Comment by aharui** [comment]
I won't have time to look carefully until late next week, but at a quick glance, it does not make sense to have a labelField setter accessing labelFunction.

Some other piece of code gets the labelField from the model and uses it to help determine the label of the renderer.  I don't remember where that is and don't have time to look.  A labelFunction-enabled model would extend the current models, add a labelFunction property, and extensions of the code that used labelField would then also use labelFunction.

Of course, I could be wrong...

**Comment by nihavend** [comment]
> I can't spend time on this now sorry, but (as at least a temporary solution) did you try changing the order of :
> labelField="@title" labelFunction="treeLabel"
> 
> to :
> labelFunction="treeLabel" labelField="@title"
> 
> in the mxml? (I'm not sure if that will work, but it might be worth a try)

Replacing the order of the attributes worked for now @greg-dove in terms of function call order. But after the comments of @aharui I am not sure how to go next. What is your suggestion ?

While debugging I realised this workaround is not enough. Label function checks some XML nodes via names and get actions. This workaround does not let the code to handle the logic properly with the XML data.

XML data and the labelFunciton may be checked in the sample code.

The parameter item should expected to be the whole XML data at least compared to flex version but only "@title" is passed.

![image](https://user-images.githubusercontent.com/5983818/69490738-8a86d280-0e9c-11ea-9285-492579f5ee9e.png)

Call of royale : 

![image](https://user-images.githubusercontent.com/5983818/69490741-9e323900-0e9c-11ea-983d-bd89fcf71744.png)

Flex debugging views :

```
override protected function makeListData(data:Object, uid:String, 
	rowNum:int):BaseListData
{
    var treeListData:TreeListData = new TreeListData(itemToLabel(data), uid, this, rowNum);
    initListData(data, treeListData);
    return treeListData;
}
```

![image](https://user-images.githubusercontent.com/5983818/69490733-7511a880-0e9c-11ea-9d02-4515076fbd2d.png)

![image](https://user-images.githubusercontent.com/5983818/69490811-c79f9480-0e9d-11ea-9a8a-cab98511ff8b.png)

![image](https://user-images.githubusercontent.com/5983818/69490816-d1c19300-0e9d-11ea-92c7-53cb4cab72e5.png)

I guess it is better to wait for more experienced one to take the issue.
