### ISSUE TITLE
Common Issues in all entry Programs. designed as clickable ,blink screen,Alternative item color

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#566]
Buttons are not designed as clickable buttons like in flex system.
System blinks on each saving and deletion of entries.
There is  blank left grid  when there is no entry system should show rows with or without data. (Alternative item color is required on rows even there is no data )
![7-8-9](https://user-images.githubusercontent.com/36731338/69140694-e2c26c80-0a77-11ea-8852-2eec591fbe5d.gif)

**Comment by aharui** [comment]
You can make the buttons look almost like anything you want by changing the CSS
