### ISSUE TITLE
> required instead of ?

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#567]
In menu and sorting of adg column > is required instead of ?
In menu ![image](https://user-images.githubusercontent.com/36731338/69141219-1e116b00-0a79-11ea-8520-48431c17efb7.png) is required on right corner as in flex.

There was dropdown arrow for submenu instead of question mark.
There was dropdown icon for sorting in flex, required in royale

![13-14](https://user-images.githubusercontent.com/36731338/69140982-8c096280-0a78-11ea-9feb-81fd2296668a.gif)

**Comment by aharui** [comment]
I noticed that the VDI did not have the environment variable

`JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8`

Royale uses Unicode characters for some graphics and on Windows you have to dictate that the output is UTF8 instead of Windows Code Page.

**Comment by pashminakazi** [comment]
@aharui Thank u so much
