### ISSUE TITLE
Tab should shift cursor to next writable field.

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#573]
difference between flex and royale
![20](https://user-images.githubusercontent.com/36731338/69142640-1606fa80-0a7c-11ea-8897-6b6d1f0d6aba.gif)

**Comment by pashminakazi** [comment]
s:TextInput tabIndex is not implemented in SDK

**Comment by aharui** [comment]
tabIndex should be implemented in the base class UIComponent.  I can't tell from the image what isn't working, but tabbing worked in a simple test case I tried.
