### ISSUE TITLE
maxChars and restrict is not functional in Spark TextInput

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#577]
maxChars and restrict function stubs are not implemented for s:TextInput

**Comment by aharui** [comment]
You should be able to implement these yourself.  maxChars would set element.maxLength and restrict would set element.pattern.  You might need to change the restrict pattern to match the pattern used by HTMLInputElement.

**Comment by alinakazi** [comment]
@aharui  Thanks alot its working

**Comment by pashminakazi** [comment]
@aharui maxChars is working now but please implement restrict stub we tried but it's not working

**Comment by aharui** [comment]
should be fixed in 8dee4cdd8f9a50cd4d7909ff4217c1ca61b1a3c2
