### ISSUE TITLE
Selection of DateField is not working in Contractor Setup

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#578]
reference issue :
https://github.com/apache/royale-asjs/issues/559

**Comment by aharui** [comment]
The DateField seems to be working properly now, except that the MaskedTextInput in the MaskedDateField is throwing a null exception because bAdvance=true but embedTextField is null.  So you will have to figure out whether why your code is not accepting the change from DateField

**Comment by pashminakazi** [comment]
On selection of date the value displayed in textInput is "/ /"  
![datefield select null value](https://user-images.githubusercontent.com/42200979/70034746-814fe100-15d3-11ea-924b-6b97ada85595.gif)

**Comment by pashminakazi** [comment]
Go to Inventory from Setup in Menu
Go to Setups Carriage/Freight - > contractor

file : dbzCarriageContractorSetup at path D:\DBIZSOL\Main\Royale\src\com\dbz\modules\INV
file : MaskedDateField at path D:\DBIZLib\src\com\dbz\controls

**Comment by aharui** [comment]
Have you resolved the exceptions that were being thrown by MaskedTextInput?

**Comment by pashminakazi** [comment]
MaskedTextInput is not throwing any exception in Contractor Setup.
Please have a look at this issue Tomorrow when you have time.
Thanks

**Comment by aharui** [comment]
On the VDI, MaskedTextInput is still throwing an exception.

**Comment by pashminakazi** [comment]
With 2 days Old SDK dbzCarriageContractorSetup was like
![image](https://user-images.githubusercontent.com/42200979/70115314-18bf3d80-1681-11ea-8fb8-e87d6acf82b4.png)

With 2 days Yesterday SDK dbzCarriageContractorSetup is like
![image](https://user-images.githubusercontent.com/42200979/70115248-ef9ead00-1680-11ea-93fb-e87ea0932354.png)

Why Month is Turned into "Undefined Undefined"
and Dates into "Nan"

**Comment by pashminakazi** [comment]
@aharui 
MaskedTextInput is throwing this exception on VDI
exception : "uncaught TypeError: cannot read property 'text' of null"
embedTextField is UITextField and embedTextField .text is throwing this exception
![image](https://user-images.githubusercontent.com/42200979/70120058-76f21d80-168d-11ea-8d5e-4110311040a2.png)

**Comment by aharui** [comment]
Last time I looked, there was code in MaskedTextInput.updateDisplayList that nulls the embedTextField.  There is code above it that was “if (false)” which is strange.  Maybe someone on your team disabled an “if” statement and caused MaskedTextInput to always null embedTextField.  But that’s why you get an exception when the DateField date changes.

Make sure the VDI has the latest sources.

**Comment by pashminakazi** [comment]
if (false) changes had been reverted and VDI has the latest Source and Latest SDK

**Comment by aharui** [comment]
Have you debugged into the version of MaskedTextInput on the VDI and determined if it still goes down the code path that nulls embedTextField?

**Comment by pashminakazi** [comment]
MaskedTextInput.as in Flex File : https://paste.apache.org/ntulc
MaskedTextInput.as in Royale File : https://paste.apache.org/ngc12

Please Check the difference of Both files

**Comment by aharui** [comment]
The MaskedTextInput.as from Royale you linked to is not the one on the VDI.  It still has if (false).  It is very difficult and inefficient for me to help you if there are these kinds of inconsistencies between your system and the one I am being asked to use.

I will go modify MaskedTextInput and see if I can then reproduce the problem you are reporting.

**Comment by aharui** [comment]
It appears that the logic in MaskedDateField and MaskedTextInput is corrupting the selected date.  I don't think it is an efficient use of my time to try to understand your logic.  If you put breakpoints on MaskedTextInput's updateDisplayList, you should be able to follow the corruption.  A correct selectedDate is formatted and passed into the MaskedTextInput's text setter.  That calls bindable__set__text which calls updateDisplayList.    handle_input is called and that starts the corruption of the date and eventually a new corrupted string is passed to the text setter.

**Comment by aharui** [comment]
OK, I decided to investigate further.  There were some SDK behaviors the Masked components were depending on that I am implementing emulations for.

**Comment by pashminakazi** [comment]
@aharui Thank u so much
