### ISSUE TITLE
AdvancedDataGrid should show only one row selected at a time

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#581]
![image](https://user-images.githubusercontent.com/36731338/69420798-4ba62080-0cd4-11ea-9611-ba5cf441c5e8.png)

Setups->Product->Conditions

**Comment by alinakazi** [comment]
two records are highlighted as selected on the same time

**Comment by aharui** [comment]
Needs more detailed steps to reproduce.  I went to this screen and clicked on a few items and could not get the problem to appear

**Comment by alinakazi** [comment]
It was produced on random click and I was in debug mode on chrome. I am closing this issue
