### ISSUE TITLE
For DropDown Look and feel 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#587]
Type/Active dropdown is required same as in flex. (remove scrolling, extra gape in options and 
 properly aligned)
![point26](https://user-images.githubusercontent.com/36731338/69499823-fff99f80-0eaa-11ea-8c09-fd4b98340942.gif)

**Comment by aharui** [comment]
I do not understand the problem.  If you look at the changes I made you might be able to modify it a bit and get what you want.

**Comment by pashminakazi** [comment]
Thanks Alex
