### ISSUE TITLE
Exceptions in SkinnableTextBase.js

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#588]
Go to Accounts Payable Module
Go to Setups -> **ATM Rental Income**

click new and give input to fields as
![image](https://user-images.githubusercontent.com/36731338/69525748-9cf52080-0f1d-11ea-80fb-932ebbbba0d5.png)

click save.

Following exceptions on console in debug mode.

![image](https://user-images.githubusercontent.com/36731338/69525699-864ec980-0f1d-11ea-84be-5dc80cca8302.png)

Uncaught TypeError: Cannot set property 'maxLength' of null
dbzATMRentalReceipt.js:2285 Uncaught TypeError: Cannot set property 'selected' of undefined
Uncaught TypeError: Cannot read property 'text' of undefined

**Comment by aharui** [comment]
The changes to add maxChars were not correct.  Some SkinnableTextBase subclasses like TextArea do not use an HTMLInputElement as the element.  The maxChars code should probably be moved to TextInput, or TextArea will need to override maxChars and do something else.  The latter is probably the best answer but will take more time to implement.

**Comment by aharui** [comment]
I will move to TextInput as it is blocking other work

**Comment by alinakazi** [comment]
@aharui thank you so much

**Comment by aharui** [comment]
Fixed in 383f819ce032299060041a439bdc66f94b9ea18f
