### ISSUE TITLE
Additional Blank div overlapped the screen

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#589]
Go to Inventory Module

Go to Setups ->Inventory Recalculate Email Setup

 file name : dbzInventoryRecalculateEmailingMaster

Additional Blank div overlapped the screen . see screenshot below

![image](https://user-images.githubusercontent.com/36731338/69526489-1e997e00-0f1f-11ea-92d2-d4225fd0b258.png)

**Comment by aharui** [comment]
dbzInventoryRecalEmailDetail is using ClassAliasBead.  Because it is not a module or application, it causes an exception that prevents the popup from finishing its initialization.  Try removing ClassAliasBead and see if that fixes the problem.
