### ISSUE TITLE
AdvancedDataGrid, groupedColumns does not work

### ISSUE THREAD

**Issue by T-San001** [apache/royale-asjs#593]
Hi,

It seems groupedColumns does not work.  With the attached test case, the output contains a frame but no contents.

Would you please check?

Thanks.
[ADGColumnGroup.zip](https://github.com/apache/royale-asjs/files/3896749/ADGColumnGroup.zip)

**Comment by yishayw** [comment]
Looks like we need to find a way for nested columns to be added to the main column list and to create a new item renderer for DataGridButtonBar which lays out the group headers and the column headers.

**Comment by aharui** [comment]
FWIW, if I were doing the work, I would try to re-use as much Flex code as possible.  The ADG HeaderRenderer seems to already know about grouping.  I don't see to many flash dependencies, most we have already emulated.

**Comment by yishayw** [comment]
Thanks for the pointer, I'll take a look at that.

**Comment by yishayw** [comment]
> FWIW, if I were doing the work, I would try to re-use as much Flex code as possible.  The ADG HeaderRenderer seems to already know about grouping.  I don't see to many flash dependencies, most we have already emulated.

I made an initial attempt to do that in f5cfbf4 but listData isn't getting populated which is causing a runtime error. @aharui , if you have time for this feel free to pick it up from the adg_grouped branch or to start afresh. I'll likely only be able to work on it next week.

**Comment by aharui** [comment]
@yishayw if you still have time to work on this, then I will let you drive it.  I am dealing with Alina/Pashmina's issues first, then some issues by Serkan as they are somewhat related.  If I have time left over I will look at the ADG branch.  If you are blocked by a particular issue like listData then if you can describe it in more detail so I can quickly look that increases the chance that I can help by investigating that specific issue.  I will not make major changes to try to finish the GroupedColumn support until you run out of time.

**Comment by aharui** [comment]
GroupedColumns appear to be working now.

**Comment by T-San001** [comment]
Alex, great thanks.  

I've confirmed the fix with the latest build.
It is fine with the js-debug but in case of js-release no text appears.  Could you check?  My console log is as attached.  Is my environment setting something bad?

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/ADGColumnGroup.js:111: WARNING - Parse error. extra visibility tag
  * @private
    ^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/mx/collections/HierarchicalCollectionViewCursor.js:774: WARNING - unreachable code
  return null;
  ^^^^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/mx/controls/advancedDataGridClasses/DataItemRendererFactoryForICollectionViewAdvancedDataGridData.js:132: WARNING - Variable referenced before declaration: dataGroup
  ir = org.apache.royale.utils.Language.as(this.itemRendererFactory.createItemRenderer(dataGroup), org.apache.royale.core.ISelectableItemRenderer);      
                                                                                       ^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/mx/core/UIComponent.js:3202: WARNING - Suspicious code. This code lacks side-effects. Is there a bug? 
  } else if ((this.mx_core_UIComponent__toolTip == null || this.mx_core_UIComponent__toolTip == "") && this.mx_core_UIComponent__toolTipBead != null) {  
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/mx/utils/ObjectUtil.js:638: WARNING - unreachable code
  return "(unknown)";
  ^^^^^^^^^^^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/org/apache/royale/events/ItemClickedEvent.js:74: WARNING - Parse error. extra @export tag
 * @export
   ^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ c:/Workspace/Test/Test Royale/bin/js-debug/org/apache/royale/html/beads/VirtualDataItemRendererFactoryForArrayData.js:178: WARNING - Variable referenced before declaration: dataGroup
  ir = org.apache.royale.utils.Language.as(this.itemRendererFactory.createItemRenderer(dataGroup), org.apache.royale.core.ISelectableItemRenderer);      
                                                                                       ^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ externs/dialogPolyfill.js:19: WARNING - accessing name dialogPolyfill in externs has no effect. Perhaps you forgot to add a var keyword?
dialogPolyfill = function() {
^^^^^^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ externs/dialogPolyfill.js:19: WARNING - variable dialogPolyfill is undeclared
dialogPolyfill = function() {
^^^^^^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager println
隴ｦ蜻・ externs/dialogPolyfill.js:27: WARNING - name dialogPolyfill is not defined in the externs.
dialogPolyfill.registerDialog = function(dialog) {
^^^^^^^^^^^^^^

12譛・30, 2019 8:46:35 蜊亥ｾ・com.google.javascript.jscomp.LoggerErrorManager printSummary
隴ｦ蜻・ 0 error(s), 10 warning(s), 98.0% typed
The project 'ADGColumnGroup' has been successfully compiled and optimized.
23.236618 seconds

**Comment by aharui** [comment]
I didn't have time to test js-release.  I will look into it later unless someone else beats me to it.

**Comment by aharui** [comment]
OK, the reason it isn't running for you is that you have to use the `-js-dynamic-access-unknown-members` compiler option because you are using plain objects in the example and the minifier will rename the field names without that option.  Here's the compiler command-line that worked for me:

`js/bin/mxmlc +configname=flex -js-dynamic-access-unknown-members src/ADGColumnGroup.mxml`

Adding that option will make your code larger.  Some people have different opinions, but in my opinion the best practice in Royale is to not use plain objects and create data classes instead.  Then you won't need that compiler option.  Adding data classes will also make your code bigger, but it I think it can also make it smaller depending on how many accesses there are to the object's properties.  But with data classes you will also get compiler checking that you didn't mis-type a property name and various data-binding warnings will go away, which should improve your productivity.

**Comment by T-San001** [comment]
Alex, thanks a lot.  I've added this option in VS Code's asconfig.json.  I've also understood the used of data class.

yishayw an Alex, thanks for all of your work.
I will close this issue.
