### ISSUE TITLE
MaskedTextInput is not Taking Input

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#594]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml

Code field is not taking input
Code field is : 
<cc:MaskedTextInput id="setupCode" width="120" tabIndex="1" x="177" y="156" maxChars="4" restrict="A-Z/a-z/0-9" height="20"
									inputMask="####" focusOut="dbzUtil.balanceCode(setupCode);"/>

If have revert those changes in MaskedTextInput
remove if(false) and uncomment  if(fontUpdated),if(dateField)
But still its not Working

![MaskedTextInput Code doesn't accept data](https://user-images.githubusercontent.com/42200979/69787153-b75d2180-11dd-11ea-9599-4951dea8c430.gif)

**Comment by aharui** [comment]
Remove the "restrict" and see if that helps.  I don't think it is currently coded to handle slashes.  You might want to tweak the way the restrict RegEx is built.  Maybe Flash ignores the slashes so you can just remove them from the restrict.

**Comment by pashminakazi** [comment]
I have removed restrict="A-Z/a-z/0-9" from MaskedTextInput but still its not taking input

**Comment by aharui** [comment]
Comment out the keypress handler from the restrict commit and see if that is making a difference.

**Comment by aharui** [comment]
But also note that what Josh was trying to fix was ensuring proper suffixes on property names.  Someone is using the VDI right now, but I think applications.mxml has a top tag with the prefix "shm" so inner property tags of "mx" are no longer allowed.

IOW, if you use mx:Application, you use mx:beads, but if you are using "shm:ShmApplication" you would use "shm:beads".  Although the Flex compiler should have also complained about that.

-Alex

**Comment by pashminakazi** [comment]
Still not working I have update SDK on VDI and Compile Lib and Project
Please check on VDI
Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml

**Comment by aharui** [comment]
A problem was found in user code and they have been notified.
