### ISSUE TITLE
After Downloading New SDK Today Error on <mx:beads> "This tag is unexpected. It will be ignored."

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#595]
We are using  
<mx:beads>
        <js:ClassAliasBead />
</mx:beads>
in our Main Application file and in all module files but after downloading new Sdk today 
Error occured : 
![image](https://user-images.githubusercontent.com/42200979/69793307-fd1fe700-11e9-11ea-9d77-f7c2067a7a4f.png)

**Comment by carlosrovira** [comment]
@pashminakazi recently @joshtynjala solved this bug in compiler (https://github.com/apache/royale-compiler/commit/ea3b7d904adbf25177ed9f1d5a7cfc1da249f6a8)
Then you need to fix your code so your child nodes has the right prefix. I think similar yesterday with TourDeJewel.

**Comment by aharui** [comment]
What Josh was trying to fix was ensuring proper suffixes on property names. Someone is using the VDI right now, but I think applications.mxml has a top tag with the prefix "shm" so inner property tags of "mx" are no longer allowed.

IOW, if you use mx:Application, you use mx:beads, but if you are using "shm:ShmApplication" you would use "shm:beads". Although the Flex compiler should have also complained about that.

-Alex
