### ISSUE TITLE
RadioButton is not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#596]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Companies from Setups in Menu
File : com/dbz/modules/Common/dbzCompanySetup.mxml

No exception on console 
![RadioButton](https://user-images.githubusercontent.com/42200979/69863124-ddf28980-12bd-11ea-823d-f2d1ca1bf15f.gif)

**Comment by aharui** [comment]
which file actually has the radio buttons in it?

**Comment by pashminakazi** [comment]
PickList_Simple.This file is in DBizlib

**Comment by aharui** [comment]
Hmm.  The radio button's mxmlDocument is not set to the PickList.  These problems often take a while to debug.

**Comment by pashminakazi** [comment]
@aharui Thanks alot

**Comment by pashminakazi** [comment]
@aharui Thank u so much
