### ISSUE TITLE
Missing semicolon causes compiler error !

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#600]
Missing semicolon causes compiler error, should inform with descriptive message for developer, like missing semicolone.

I forgot to put semicolon at the end of the first line by mistake and got the compiler error :

The code :

![image](https://user-images.githubusercontent.com/5983818/69906943-9adb0800-13dc-11ea-84b3-9549c1a440b2.png)

Compiler error :

![image](https://user-images.githubusercontent.com/5983818/69906944-a2021600-13dc-11ea-93a1-cd4fe30dbb4b.png)

**Comment by carlosrovira** [comment]
Hi @nihavend this seems a compiler error, maybe better log in the compiler issues instead here

**Comment by nihavend** [comment]
It has been fixed already @carlosrovira and was created long time ago at 1 Dec 2019. I will consider for the new ones.
