### ISSUE TITLE
Code field becomes empty after search something in ADG

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#601]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml
dbzAuthorizedPerson is using a lib file dbzSetupList.mxml

![Code field becomes empty](https://user-images.githubusercontent.com/42200979/69949813-04a9fd80-1514-11ea-9965-26f5493a8e5d.gif)
![image](https://user-images.githubusercontent.com/42200979/69949828-0a074800-1514-11ea-8a25-f7eaab96296d.png)

**Comment by aharui** [comment]
In dbzFixedAssetModule.initModule, I am getting "TypeError: this.parentMXMLDocument.validateSession is not a function" which makes sense.  It looks like initModule should call parentMXMLDocument.parentMXMLDocument.validateSession instead.

I don't know if that exception is the root cause

**Comment by aharui** [comment]
I cannot get Authorized Person in the menu probably due to above exception so I cannot debug further.

**Comment by pashminakazi** [comment]
@aharui Check now on VDI

**Comment by pashminakazi** [comment]
@aharui Thank u so much
