### ISSUE TITLE
Screen blink on New,Save,Undo and Delete Record

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#604]
Screen Blink on New,Save,Undo and Delete Record
showBusyCursor="true" is not working in mx:RemoteObject
Screen should not blink on any Action.
Instead of Blinking showBusyCursor should work (Busy or Wait Cursor)
![Blink Screen](https://user-images.githubusercontent.com/42200979/69954024-4179f280-151c-11ea-9842-80a6c0f5dfc4.gif)

In Some Cases like in this Video 
(selectedItem of ADG is different and the description displayed on Screen is of different row)
Please help

**Comment by aharui** [comment]
Unable to get to Sales module and the Location setup.  The Sales module returns a null pointer error from the server, so I cannot investigate further.

**Comment by pashminakazi** [comment]
@aharui Check now on VDI

**Comment by aharui** [comment]
Duplicate of #566

**Comment by pashminakazi** [comment]
@aharui Thank u so much
