### ISSUE TITLE
EventDispatcher.js:73 Uncaught TypeError: Cannot read property 'royale_wrapper' of undefined

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#607]
![image](https://user-images.githubusercontent.com/42200979/70123326-3ea20d80-1694-11ea-85b3-2a856337fd08.png)

**Comment by aharui** [comment]
Need more information.  What screen, how many items in the ADG?  Are you sure you picked up the latest changes like this one 10d06fe0506249b880d04b0599da1c3ceacf9144?

**Comment by pashminakazi** [comment]
Yes, I have downloaded Latest SDK with all changes.
This scenario was randomly occured.
Please have a look at issue : https://github.com/apache/royale-asjs/issues/608

**Comment by pashminakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Bill Of Material Types from Setups in Menu
File : com/dbz/modules/INV/dbzBillOfMaterialTypeSetup.mxml

This exception is thrown when we delete a record and then delete another record.
![Royale_wrapper issue](https://user-images.githubusercontent.com/42200979/70128295-68603200-169e-11ea-96b9-21a3fd0ae98a.gif)

**Comment by pashminakazi** [comment]
@aharui Thank u so much
