### ISSUE TITLE
SVG Overflow is visible In PickList

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#608]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Purchase from Select in Menu
Go to Store Room -> Store from Setups in Menu
File : com/dbz/modules/Common/dbzStoreSetup.mxml

Open Carriage Contractor PickList (Last PickList) and Select 4th Row from PickList.
![image](https://user-images.githubusercontent.com/42200979/70123457-8a54b700-1694-11ea-964e-16ad9be276e6.png)
![image](https://user-images.githubusercontent.com/42200979/70123614-d273d980-1694-11ea-9e2e-5a1e6cb7c637.png)

Because of this Overlapped svg Class,At a time two rows are selected and we can not select some records from PickList

**Comment by pashminakazi** [comment]
This overflow issue is also in Company Setup
Go to Purchase from Select in Menu
Go to Companies from Setups in Menu
Open 2nd PickList (Profit/Loss A/c) and Select any from first three rows from PickList.
File : com/dbz/modules/Common/dbzCompanySetup.mxml
![image](https://user-images.githubusercontent.com/42200979/70124762-4ca55d80-1697-11ea-93ab-b0fc30612841.png)

**Comment by aharui** [comment]
The SVG Overflow has pointer-events:none so it shouldn't be a factor.  I tried the Store setup and could not reproduce the problem.  I tried the Companies setup and could not reproduce a problem.  I can select from the first 3 rows although some rows seem to cause the Picklist to go away.  I don't know if that is intentional or not.  Or is that what you mean by "cannot select"?

**Comment by pashminakazi** [comment]
"cannot select" Means : It is selected and highlighted but on selecting first 3 rows Popup doesn't close : 
Please have a look at that Video of Companies PickList
![PickList not selected](https://user-images.githubusercontent.com/42200979/70207217-e9c1ce00-174b-11ea-981a-f77eea076caf.gif)

**Comment by pashminakazi** [comment]
I have identified the problem.
There is 3 radio button in PickList **All,Active,InActive**
By Default Active is selected.System should show Only Active rows in Picklist.
Those rows which can't be selected are InActive rows but they are shown with Active rows.
If i click on **InActive** or **All** and then **Active** then Picklist shows Only **Active** Record.But by Default if Active is Selected.System is showing **Active** and **InActive** records in Picklist.
Please have a look at screenshots and Video.

when Opening Picklist **Active** is selected but it is showing some **InActive** records as well (means it is showing rows same as it is showing for **All** radioButton)
![image](https://user-images.githubusercontent.com/42200979/70232086-69b45c00-177d-11ea-9aac-40678232cde0.png)


All RadioButton
![image](https://user-images.githubusercontent.com/42200979/70232215-bd26aa00-177d-11ea-9068-1b690c2d5ef0.png)


Active RadioButton
![image](https://user-images.githubusercontent.com/42200979/70232216-bd26aa00-177d-11ea-9d6b-06967485502d.png)
these Active records are changed than those records which were shown on PickList open these were also Active records

InActive RadioButton
![image](https://user-images.githubusercontent.com/42200979/70232350-11318e80-177e-11ea-84b1-d906f6ac83ee.png)


Video :
![Picklist active,inactive records](https://user-images.githubusercontent.com/42200979/70232492-5f469200-177e-11ea-88fc-b4f77d26f78c.gif)

**Comment by aharui** [comment]
PickList_Simple.mxml has an rbSelectedHandler with a comment that says it is run when the module is loaded that should filter the DG.  When it is run, the ArrayCollection is empty so I suspect this code is running too soon.

However, the rbSelectedHandler is coded to act on a "selectedChange" event which does not exist in Flex RadioButton.  So it seems like this code has been changed for Royale.

It is also possible that the Flex code relied on timing of creationComplete vs the server response.  That is generally an unsafe thing to rely on.  When the server responds that is when the filter should be applied, but on line 105 of handleResult, the filtering is commented out.

Without knowing what the original Flex code did, i don't know if there are issues in the Royale SDK that need to be addressed or not.  If you can identify incorrect SDK behavior (other than timing between creationComplete and server response then describe that in detail and I can investigate that.

**Comment by pashminakazi** [comment]
I have uncommented arrDGDataProvider.filterFunction = filterDG; from handleResult.
Issue resolved,Thank u so much.
