### ISSUE TITLE
Image missing load handler event?

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#61]
It was suggested in #60 to use a load event listener to check when an image was loaded. However I can't see any load handler in the js:Image control. It has rollover, click, double click etc  etc handlers but doesn't seem to have any load handler. Is there a bead to add this?

**Comment by Harbs** [comment]
There's no need for a special load event. See [my comment](https://github.com/apache/royale-asjs/issues/60#issuecomment-340518737).

**Comment by justinmclean** [comment]
You said "You can probably set visibility to false and use a load event listener to make it show again." I'm assuming this was in error and is not currently supported. Can you confirm?

**Comment by Harbs** [comment]
Yes. My comment was poorly worded. `layoutNeeded` is dispatched when an image is loaded, not `load`.

**Comment by justinmclean** [comment]
JFYI (and anyone reading this) layoutNeeded is not support as an event hander in MXML.
