### ISSUE TITLE
Mx and Spark TextInput editable property is not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#610]
Mx and Spark TextInput editable property is not working
File : https://paste.apache.org/eennn
![TextInput Editable Property](https://user-images.githubusercontent.com/42200979/70133169-6e0e4580-16a7-11ea-91ce-fec8b4e5d572.gif)

**Comment by aharui** [comment]
You should be able to implement this just like you did for maxChars.  There is a "readOnly" attribute on HTMLInputElement.  Remember to only change Spark TextInput and not SkinnableTextBase.

**Comment by pashminakazi** [comment]
Yesterday I have implemented editable property of Textinput using readOnly attribute of HTMLInputElement.But it doesn't work.
Have a Look
File : https://paste.apache.org/t4qnq
Changes in Spark TextInput.as
https://paste.apache.org/g5g2w
Video : 
![Editable Property in Spark Textinput](https://user-images.githubusercontent.com/42200979/70210350-3d381a00-1754-11ea-9280-0a3fe1e5ff79.gif)

**Comment by aharui** [comment]
It is hard to tell from the video, but it looks like the readOnly attribute is not set on the element.  I suggest that you step over the line that sets readOnly and examine the element and see if that line of code actually set the attribute.   If it did, then some other code removed it.  If it didn't get set, I would try setting the string "true" instead of the boolean.

**Comment by pashminakazi** [comment]
I have debugged into editable property in TextInput it is setting readOnly = false.
![textInput editable debug](https://user-images.githubusercontent.com/42200979/70230671-a0d53e00-177a-11ea-8667-085d938c3b13.gif)

**Comment by aharui** [comment]
it should be setting readOnly = true

readOnly === !editable

**Comment by pashminakazi** [comment]
https://github.com/apache/royale-asjs/commit/f9638f2ff1d0b3b7eaecc45b06ba5acb5d641e65
