### ISSUE TITLE
ADG behavior on selection of record

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#615]
In some cases ADG selected record is changed than the values are displayed on screen.
Values displayed on screen should be of selected record of ADG

![Showing changed record data](https://user-images.githubusercontent.com/42200979/70527593-191e7380-1b6e-11ea-8948-d491cdc5aef4.gif)
![image](https://user-images.githubusercontent.com/42200979/70527740-68fd3a80-1b6e-11ea-93d6-1ee331b46e07.png)

**Comment by aharui** [comment]
I am unable to reproduce on the VDI.  I am disconnecting from the VDI.  If you can reproduce it there, try leaving the browser at that screen so I can try it when I start work tomorrow.

**Comment by pashminakazi** [comment]
No one is using VDI,why are you disconnecting from the VDI.
I have one urgent Issue Please solve this issue today :
https://github.com/apache/royale-asjs/issues/616

**Comment by aharui** [comment]
It is the end of my workday.  I need you or someone on your team to
1) restore the Git repos on the VDI
2) reproduce this problem AFTER making the recommended changes for #613.

It is not always possible for me to respond to your urgent issues this late in my workday.

**Comment by pashminakazi** [comment]
We do not have Internet access on VDI.
So I download SDK on my local machine then copy it to VDI.

**Comment by aharui** [comment]
Git was working on the VDI.  You can double-check with Alina if you want.

**Comment by pashminakazi** [comment]
SDK is cloned on VDI
![image](https://user-images.githubusercontent.com/42200979/70704822-996ee100-1cf4-11ea-854f-9f53461a35b1.png)
I have just changed 
frameworks/projects/Core/src/main/royale/org/apache/royale/utils/css/addDynamicSeparator.as
Because in constructor of addDynamicSeparator
sheet.insertRule(selectorString); is causing build failed with Error : insertRule expected arguments 2
then i replace sheet.insertRule(selectorString); with sheet.insertRule(selectorString,0);
because insertRule is method of CSSStyleSheet which has two arguments 1: String and 2: int.

There is no other change in SDK so please now work on VDI.

**Comment by aharui** [comment]
I still cannot reproduce this problem on the VDI
