### ISSUE TITLE
Issues in top,bottom,left,right,height,width On HIGH PRIORITY

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#616]
Issues in Every File

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Misc-> Cities from Setups in Menu
File : com/dbz/modules/Common/dbzCitySetup.mxml

Before Adding css to dbzCitySetup.mxml
![image](https://user-images.githubusercontent.com/42200979/70599750-cac1b100-1c0f-11ea-96b2-cfb1f59ac2a1.png)

After adding this css to dbzCitySetup.mxml
Css : https://paste.apache.org/2zuht
![image](https://user-images.githubusercontent.com/42200979/70599144-4b7fad80-1c0e-11ea-8555-757103dc3894.png)

Go to Inventory from Select in Menu
Go to Documents-> Configure from Setups in Menu
File : com/dbz/modules/Common/dbzDocumentSetup.mxml

Before Adding css to dbzDocumentSetup.mxml
![image](https://user-images.githubusercontent.com/42200979/70599755-cf866500-1c0f-11ea-81b4-6f965d905e1d.png)

After adding this css to dbzDocumentSetup.mxml
Css : https://paste.apache.org/t9ywu
![image](https://user-images.githubusercontent.com/42200979/70599284-9699c080-1c0e-11ea-94cc-1fa33fc04fab.png)

Go to Inventory from Select in Menu
Go to Freight Rate from Setups in Menu
File : com/dbz/modules/Common/dbzFreightRateSetup.mxml
dbzFreightRateSetup.mxml
![alignment properties](https://user-images.githubusercontent.com/42200979/70599567-3eaf8980-1c0f-11ea-906f-571fda686ff7.gif)

**Comment by aharui** [comment]
Why are you adding such CSS to your app like width: auto?  It should not be necessary.  The SDK code should take care of proper sizing and positioning.  I'm sure there are still bugs in some of the SDK layout code.  I am willing to fix SDK layout code, but not the SDK code should not have to manage CSS like width: auto.

I will not be able to help you with this issue as written.  If you are trying to get these screens to look more like the Flex version, then open a separate issue for that without any custom CSS.

**Comment by pashminakazi** [comment]
I do not want to add css  like width: auto.I was adding this css to only
show you that the setups are looking like flex if we add css.
But i can not add css in all setups so please fix bugs in some of SDK
layout.I am not using css in my application.
I have added css for just giving you layout demo.
Thanks

**Comment by pashminakazi** [comment]
I want setups to look like flex without adding any css

**Comment by aharui** [comment]
I noticed that the rowHeight on ADG was not correct, so I fixed that, but otherwise the screens look the same to me.  You will have to be more specific about what differences you are seeing.  Royale may not be able to be pixel-for-pixel identical to Flex, but should be pretty close, especially because your code uses lots of absolute sizes and positions.

**Comment by pashminakazi** [comment]
@aharui Thanks
