### ISSUE TITLE
Some Space Required after column Separator in ADG

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#620]
File : https://paste.apache.org/72e6m
Output : 
![image](https://user-images.githubusercontent.com/42200979/70704640-3bda9480-1cf4-11ea-937a-9df7d2d230f7.png)

There should be some space after column separator like Flex :
![separator](https://user-images.githubusercontent.com/42200979/70705513-ffa83380-1cf5-11ea-9f5d-38fc8f06ac39.png)

**Comment by aharui** [comment]
I made some adjustments in bf84288.  You can tweak it if you want to.

**Comment by pashminakazi** [comment]
@aharui Thanks
