### ISSUE TITLE
ADG rows color should be bold on those rows which shouldn't be selected

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#624]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Misc-> Departments from Setups in Menu
File : com/dbz/modules/Common/dbzDepartmentSetup.mxml
using PickList_Simple which is in DBizLib

Some ADG rows can't be selected.but there color should be bold so the user can understand that these rows are not for selection. like,
In Flex:
![Radiobutton vdi](https://user-images.githubusercontent.com/42200979/70897418-61c5a900-2014-11ea-8111-64491bcaa9ac.gif)

In Royale:
There is no difference between rows color so the user is having problem.
![Radiobutton local](https://user-images.githubusercontent.com/42200979/70897650-def11e00-2014-11ea-97f7-80d3a45141b7.gif)

**Comment by aharui** [comment]
What technique is the code using to make some lines bold?  What files contain that code?  I've spent several minutes looking for it and cannot find any code that should turn the renderer bold.

**Comment by pashminakazi** [comment]
Please Implement function setStyle in mx.controls.advancedDataGridClasses.AdvancedDataGridItemRenderer
we are using 
setStyle('fontWeight', value.type == '1' ? 'bold' : 'normal');
setStyle('textSelectedColor', value.Active == '0' ? '#ACA899' : '#000000');
setStyle('textRollOverColor', value.Active == '0' ? '#ACA899' : '#000000');
in our library files GridActiveItemRenderer and GridCustomItemRenderer

**Comment by pashminakazi** [comment]
Please Check
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to GL from Select in Menu
Go to Chart of Accounts-> Maintain from Setups in Menu
File : com/dbz/modules/GL/dbzChartOfAccountsSetup.mxml

we are using itemRenderer="com.dbz.controls.GridCustomItemRenderer" in AdvancedDataGrid
GridCustomItemRenderer is our Library file in DbizLib

if itemRenderer property of AdvancedDataGrid is not working then please implement itemRenderer and
**setStyle** function in mx.controls.advancedDataGridClasses.**AdvancedDataGridItemRenderer**

if itemRenderer property of AdvancedDataGrid is working then
Please Implement function **setStyle** function in mx.controls.advancedDataGridClasses.**AdvancedDataGridItemRenderer**
we are using 
setStyle('fontWeight', value.type == '1' ? 'bold' : 'normal');
setStyle('textSelectedColor', value.Active == '0' ? '#ACA899' : '#000000');
setStyle('textRollOverColor', value.Active == '0' ? '#ACA899' : '#000000');
in our library files **GridActiveItemRenderer** and **GridCustomItemRenderer**

Thanks.
Please help

**Comment by pashminakazi** [comment]
Thank u so much Alex.

I have a request please look at issue #626 today
