### ISSUE TITLE
MaskedTextInput field is behaving incorrect

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#628]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml
Code Field is MaskedTextInput which is in DbizLib

MaskedTextInput field is not allowing to input.then i replace super.text = _working.join(""); with super.text;
Now it is allowing input but if we enter 4 digit code like '1111' and then we want to remove it then only last '1' will be removed and if we enter any other digit instead of '1' then it will enter only '1'
Please help me i can't understand what maskedTextInput is doing.
I am sending you Flex and Royale files for comparison
Flex MaskedTextInput : https://paste.apache.org/alo92
royale MaskedTextInput : https://paste.apache.org/eo1yx
![Code in authorized](https://user-images.githubusercontent.com/42200979/71065295-d0c90c00-2192-11ea-9870-aa053e60a88e.gif)

**Comment by pashminakazi** [comment]
@aharui Please have a look at this issue

**Comment by pashminakazi** [comment]
Test case  :  
MaskedTextInput.as : https://paste.apache.org/fp9wi
HelloWorld.mxml : https://paste.apache.org/g40de

@aharui  please check this issue on high priority. I am stuck for past two days in this issue.

I have checked, debugged. I couldn't find the reason.

We have different work hours. Please check whenever you are available and email me right after you check so i can see before your end of work day.

**Comment by aharui** [comment]
The HelloWorld test case is not functioning the same as the app.  In the app when you tab out of a blank Code field it gets replaced with "0000".  I compiled the test case in Flex and it also did not replace the code with "0000".

I guess I will try to make my own test case, but this is not an efficient use of my time.

**Comment by aharui** [comment]
I will commit some changes to TextInput shortly, but MaskedTextInput also needs to change to call event.preventDefault after handleDeletions because the update of the working array and setting of text happens immediately in the browser (instead of a deferred updateDisplayList in Flex) so the runtime handles the delete key on the text that was already processed by MaskedTextInput.

```            // Delete one character before the insertion point 
            // and moves the insertion point to one position back.
            if( event.keyCode == Keyboard.BACKSPACE ) {
                _position = selectionBeginIndex;
                handleDeletions(true);
                event.preventDefault();
            }
                // Delete one character at the insertion point 
            else if( event.keyCode == Keyboard.DELETE ) {
                handleDeletions();
                event.preventDefault();
            }
```

**Comment by aharui** [comment]
The other changes are to support selectionBeginIndex/selectionEndIndex in TextInput, and to retain selection when text is set (the browser sets selection to the end) and to emulate KeyboardEvent.keyCode

**Comment by aharui** [comment]
Should be fixed by 
f9b9c7c

**Comment by pashminakazi** [comment]
This issue is different from https://github.com/apache/royale-asjs/issues/626
In this issue there is no auto generated code '0000 'HelloWorld test case is functioning the same as the app.you can check this setup for the scenario
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml

After your commit and changes to MaskedTextInput still problem is same 
![Still maskedtextinput issue2](https://user-images.githubusercontent.com/42200979/71147541-e994f880-224a-11ea-958b-10eb177ad580.gif)

Please test HelloWorld Example after your changes.if helloworld Example works then our app setups will work.

MaskedTextInput.as : https://paste.apache.org/fnzmm
HelloWorld.mxml : https://paste.apache.org/g40de

Thanks
