### ISSUE TITLE
ADG properties selectionMode,allowMultipleSelection,doubleClickEnabled,itemDoubleClick required

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#630]
selectionMode="multipleRows" allowMultipleSelection="true" doubleClickEnabled="true" 
 itemDoubleClick="f_ManageSelection('I')" is not working in AdvancedDataGrid.
Please implement these properties
Test Case : https://paste.apache.org/uy57r

**Comment by aharui** [comment]
initial implementations were committed in:
7cd5e348a47a7739f0f4385f53db90cdf1ad90db
and
4236a95d2a1203e3f16794cef5ccf0db6fce9815
