### ISSUE TITLE
Uncaught TypeError: mx.containers.beads.DividedBoxLayout is not a constructor

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#632]
This issue is occured randomly.sometime when i open any setup the screen of setup is blank and this exception is thrown.
![image](https://user-images.githubusercontent.com/42200979/71098128-02fa5e00-21d3-11ea-9565-a76adcc3f265.png)

![image](https://user-images.githubusercontent.com/42200979/71098272-3dfc9180-21d3-11ea-8013-3b7b1f31bcee.png)
![dividedboxlayout](https://user-images.githubusercontent.com/42200979/71098493-9af84780-21d3-11ea-8ea2-2f888386b7bf.gif)

![Royale wrapper exception](https://user-images.githubusercontent.com/42200979/71098913-41dce380-21d4-11ea-83d7-129e898557fa.gif)
![Royale wrapper exception2](https://user-images.githubusercontent.com/42200979/71099216-be6fc200-21d4-11ea-8875-d145b75eda30.gif)

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to product-> Product Loc Wise S.TaxR from Setups in Menu
File : com/dbz/modules/Common/dbzLocWiseSTaxWHTR.mxml
but perhaps this issue doesn't reproduce on VDI..So Please Solve this issue without depending on setups

**Comment by aharui** [comment]
I was able to produce on the VDI using product-> Product Loc Wise S.TaxR from Setups in Menu.
The Setup that was loaded appears to be:
com/dbz/modules/Common/dbzProductLocWiseSTaxRMaster.mxml
The output for that module is dated 11/22/2019, so it hasn't been compiled in a while and its list of dependencies may be out of date.

I am closing this issue.  You can reopen it if you can reproduce this on a freshly compiled module.
