### ISSUE TITLE
Generated JavaScript file has errors (semi-colon expected etc)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#633]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Documents -> Configure from Setups in Menu
File : com/dbz/modules/Common/dbzDocumentTabSetup.mxml

dbzDocumentTabSetup has two tabs **General** and **Types**
1st tab is **General** where a module is loaded called **dbzDocumentSetup**
File : com/dbz/modules/Common/dbzDocumentSetup.mxml 
It is working fine

In 2nd tab **Types** where a module is loaded called **dbzDocumentDetailSetup**
File : com/dbz/modules/Common/dbzDocumentDetailSetup.mxml 
it is not loaded because 
dbzDocumentDetailSetup.js :
 ![image](https://user-images.githubusercontent.com/42200979/71150796-2f09f380-2254-11ea-9aef-6cbf9d6e2b4e.png)

dbzDocumentDetailSetup.js is even not loaded in index.html you can see dbzDocumentDetailSetup.js in Eclipse IDE
Path : Click on SHMA-> Web -> com->dbz->modules->Common->dbzDocumentDetailSetup.js

**Comment by aharui** [comment]
There is a text property in com/dbz/modules/Common/dbzDocumentSetup.mxml that spans multiple lines.  I think you can workaround the problem by defining the string in the Script block and binding to it or assigning it on creationComplete event.

**Comment by pashminakazi** [comment]
In dbzDocumentSetup or In dbzDocumentDetailSetup?
problem is in dbzDocumentDetailSetup

**Comment by pashminakazi** [comment]
Can you mention the line that cause the issue

**Comment by aharui** [comment]
line 1152

**Comment by pashminakazi** [comment]
Thanks

**Comment by pashminakazi** [comment]
@aharui Thank u so much Issue resolved :)
