### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#634]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Sites from Setups in Menu
File : com/dbz/modules/Common/dbzSitesSetup.mxml

![SitesSetup id issue](https://user-images.githubusercontent.com/42200979/71152809-3c75ac80-2259-11ea-8956-18759f502226.gif)

Exception on Line : si_Type.selectedItem.id
si_Type is DropdownList
![image](https://user-images.githubusercontent.com/42200979/71152871-6e870e80-2259-11ea-94cf-17dfbf22fac4.png)

**Comment by aharui** [comment]
In dbzSitesSetup.mxml line 206:
```arrSiteTypeDP = arrSiteTypeResult[0][0] as ArrayCollection```

I think we agreed that a different pattern has to be used for nested array collections.  You might want to grep your code for this pattern.
