### ISSUE TITLE
Invalid string comparison in new date code

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#64]
This code is incorrect and fails to work:

```
        public function getIndexForSelectedDate():Number
        {
            if (!_selectedDate) return -1;

            var str:String = _selectedDate.toDateString();

            for(var i:int=0; i < _days.length; i++) {
                var test:Date = _days[i] as Date;
				
				if (test && test.toDateString() == str)
					return i;

            }
            return -1;
		}
```

As it is doing comparisons on dates stings like so:

str: "Thu Nov 09 2017"
test: "Thu Nov 09 2017 00:00:00 GMT+1100 (AEDT)"

The strings will never match.

(Tested on OSX Chrome other browsers may or may not have the same issue)

**Comment by Harbs** [comment]
Something does not seem right.
Your second string is what you get when calling toString() -- not toDateString().

Please attach a test case and steps to reproduce.

**Comment by justinmclean** [comment]
Timezones and daylight savings is also likely to cause issues. Suggest we go back to checking numeric month and year.

**Comment by justinmclean** [comment]
To reproduce select a month and step forward a month and backwards a month. See also #62 and pull request with that.

**Comment by Harbs** [comment]
That was a bug which existed prior to the change you are referring to. I just committed a fix for that bug.

Unless you can give me a way to reproduce your problem, I'm going to close this issue.

Timezones and dls will not effect things.
