### ISSUE TITLE
ADG focus should be on last saved record

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#652]
In many Setups there is no focus on any record.
Focus should be on last saved record.

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Asset from Select in Menu
Go to Reporting Levels ->  Region from Setups in Menu
File : com/dbz/modules/FA/dbzRptLvl1Setup.mxml

![Rptlevel focus issue](https://user-images.githubusercontent.com/42200979/71711296-1daf1280-2e22-11ea-9566-158de912bd5a.gif)

**Comment by aharui** [comment]
Focus or selection?

**Comment by pashminakazi** [comment]
@aharui Both Focus and Selection

**Comment by pashminakazi** [comment]
@aharui if you have time please look at these three setups today
https://github.com/apache/royale-asjs/issues/652
https://github.com/apache/royale-asjs/issues/651
https://github.com/apache/royale-asjs/issues/647

Thanks

**Comment by aharui** [comment]
Are other setups having this problem or only a few?  If only a few, compare how they set the selectedIndex.

"Focus" means what control will accept keyboard input.  What component do you expect should have focus?  What code is setting focus there?  And what is being typed on the keyboard?

**Comment by pashminakazi** [comment]
i didn't see any difference between setups for setting the selectedIndex= last saved record.

Many setups which is using dbzSetuplist is having this problem that there selectedIndex is not last saved record.
some setups without dbzsetupList have this problem as well.
you can See 
Go to Import from Select in Menu
**Go to Import -> Port from Setups in Menu**
File : com/dbz/modules/IMP/dbzPortSetup.mxml
**This setup is not using setuplist but it has this issue.**

Go to Import from Select in Menu
Go to Foreign Currency -> Types from Setups in Menu
File : com/dbz/modules/Common/dbzFCRateType.mxml
This setup is also not using setuplist but it has no issue then why Port Setup has this issue.
Please resolve this problem on priority

**Comment by aharui** [comment]
In dbzPortSetup, I do not see any logic that would set selRecID to the last element which then would set selectedIndex properly.  Of course I could have missed it, so if I did, please point out the lines of code that should do that.

**Comment by aharui** [comment]
Fixed Assets does not seem to be available on the VDI, so I cannot investigate further.
I recommend setting a breakpoint in the selectedIndex setter and see who calls it with what values.

**Comment by pashminakazi** [comment]
Fixed Assets is available on vdi when you first select sales or any other module 1st then fixed assets will be shown in module list

**Comment by pashminakazi** [comment]
dbzPortSetup is not in FixedAssets
It is in Import Module.
and i debug dbzPortSetup in flex and Royale at same time,both have same execution steps in flex DbzportSetup is selecting the last saved index.
In Royale dbzPortSetup has loses selection of  last saved index at the end but there is no difference between flex and royale code.
I didn't understand what is going on.
Please have a look at dbzPortSetup.it is setting last added element to selectedindex many times

**Comment by pashminakazi** [comment]
Line no **62**,line no **79**,line no **91**,line no **336**
they all are **dg.selectedIndex = selRecID;**

**Comment by pashminakazi** [comment]
First portion of Video is of Royale and 2nd portion is of Flex.
Code is same,but selection is different
![selection in portsetup](https://user-images.githubusercontent.com/42200979/71801416-acb76700-307c-11ea-906e-4690b214c21b.gif)

**Comment by aharui** [comment]
in dbzSetupList, for a new record it sets the selIndex = arrPageData.length, which is out of bounds.  I added a check to ADG to force the value into bounds.  But you might want to clean up code like that elsewhere.

**Comment by aharui** [comment]
In dbzPortSetup, what is selRecID?  Is it a valid value?

**Comment by pashminakazi** [comment]
Yes it has a valid value..this is used in our all setups.
Thanks.

**Comment by pashminakazi** [comment]
Still not working in PortSetup
Before this change it was selecting last selected index then during execution it loses its selection.
but after this change there is no selection not even one time

**Comment by pashminakazi** [comment]
![selection in portsetup after change](https://user-images.githubusercontent.com/42200979/71803674-3f5b0480-3083-11ea-93dc-4272c7695c82.gif)

**Comment by aharui** [comment]
PortSetup now works after change 2f3ba9888b7460c221a988c798acba22203644b3

**Comment by pashminakazi** [comment]
@aharui  Issue resolved Thanks

**Comment by pashminakazi** [comment]
Selection is of 2 records
https://mail.google.com/mail/u/0/#sent/QgrcJHrnvDdmKTHTZmzThSrmSSKWtDKXtzB?projector=1

**Comment by pashminakazi** [comment]
@aharui Thank u so much Issue Resolved
