### ISSUE TITLE
Maven doesn't produce binary executables (jar)

### ISSUE THREAD

**Issue by heitara** [apache/royale-asjs#657]
If you build successfully with Maven you can't use the Apache Royal from Terminal (CLI). There is a discussion already about that - http://apache-royale-users.20374.n8.nabble.com/missing-mxmlc-jar-td2474.html. Proper work around is to pass the correct parameters or to build with ant. 
Preffered solution is to have a flag that can be passed to maven to generate those. This flag should be added to the documentation.

**Comment by carlosrovira** [comment]
Hi @heitara,

thanks for report this issue. Currently Maven build need to fix distribution target, so we can build a valid SDK for IDEs with Maven. We currently do this final step with ANT. I have this in my TODO list to work with @chrisdutz at some time (hopefully soon). Is this the problem you're reporting?

Thanks!

**Comment by aharui** [comment]
When we say "distribution" that means setting up the folder structure expected by most IDEs, but I think it could be much easier to allow a simple compilation from the command line.  Although some might argue that if you are using Maven you should be setting up Maven projects for everything and not just use the command-line.  I think that's why we have the archetype project:  to make it easier to setup a Maven project.

It would be interesting to see if a volunteer could make a copy of the js/bin/mxmlc and modify it to work with a Maven build.  The two things that first come to mind would be overriding class paths to point at the jars in the local repo, and coming up with a default set of compiler options.  The Ant builds use frameworks/royale-config.xml and similar configs.  There might be other issues.

**Comment by heitara** [comment]
I would expect one of the following solutions:
- run a command (shell/batch file) that will create a distributional binary (a folder all the things, which someone gets when using npm) that can be used with any IDE or from CLI (simiral to what we have with current AIR [32.0.* at the moment]  version)
- run an ant script with the same result
- run maven with special argument(s) with the same result as above
As far as I can understand - if I build with ant (haven't tried that bit yet) then I'll get the missing jars and everything will be fine to be able to used Apache Royal from the CLI. 
I believe customizing the mxmlc is not good option. Maybe we can create a new version like mxmlc_mvn or similar.

**Comment by heitara** [comment]
@carlosrovira could you share your ANT workaround, so I can try to extend the Maven script? Please use my email.

**Comment by carlosrovira** [comment]
Hi @heitara, I use this sh on Mac. Depending on you OS, you can transform accordingly:

https://gist.github.com/carlosrovira/200753108de263fa43e80d3228213509

**Comment by carlosrovira** [comment]
about maven build: You normally use `mvn install` in a folder where you have a pom.xml. That pom.xml is the project object model that describes your project.

You can try that for example with Tour de Jewe here: https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel

From terminal command window just make `mvn install`. That will create the compilation in `target` folder.

If you want to create a project in just a command with maven use this: 

https://github.com/apache/royale-asjs/wiki/Create-Royale-project-with-Maven

**Comment by carlosrovira** [comment]
I think the problem here is that you expect to use `mxmlc` directly. ANT build is just to use with IDEs like VSCode or Moonshine, so the tool use it to give you code intelligence. But for your own builds, you must switch from trying to use mxmlc to use mvn install based on a pom.xml

**Comment by piotrzarzycki21** [comment]
> I think the problem here is that you expect to use `mxmlc` directly. ANT build is just to use with IDEs like VSCode or Moonshine, so the tool use it to give you code intelligence. But for your own builds, you must switch from trying to use mxmlc to use mvn install based on a pom.xml

As a user of Royale SDK which I have downloaded from website or Nightly build from our Jenkins I have following options:
1) Build my application using Moonshine IDE or VSCode using downloaded SDK
2) Build my application by Apache Ant using build.xml script file prepared for application using downloaded SDK
3) Build my application using Apache Maven, where I don't need downloaded SDK cause all required dependencies will be downloaded from central repository based on my pom.xml file .

As a Royale SDK developer which wanted to build whole framework, cause I would like to add new feature to it etc. I have following options:
1) I can build framework using Apache Maven - all pom.xml files are in place and instruction is in our documentation how to do that
2) I can build framework using Apache Ant - all build.xml files are in place as well

Additionally as a user currently I can produce distribution version of SDK. As other mention Maven unfortunately do not produce fully good version. Last time when I was checking what was produced (about 1 year ago) - I was able to use produced SDK in IDE - and intellisence worked, but I was not able to build my application using produced SDK.

**Comment by aharui** [comment]
Hopefully someday the newer IDEs will support Maven projects directly.

**Comment by piotrzarzycki21** [comment]
> Hopefully someday the newer IDEs will support Maven projects directly.

Moonshine supports Maven, you can run command form IDE and predefined some commands.

**Comment by heitara** [comment]
@piotrzarzycki21 I had problems building royal successfully with maven from the .zip downloaded straight from apache royal site (`apache-royale-0.9.6-src.zip`) (https://royale.apache.org/source-code/) The problem is that the themes can't be build because of missing dependency (airglobal:swc:20 or something similar) . I had made a minor tweak to the root `pom.xml` in `royale-asjs` which fixes this issue.
`<repository>
      <id>apache-maven-release</id>
      <url>http://repository.jspresso.org/maven2/</url>
      <name> MVN repo</name>
    </repository>`
Another thing that I faced - Maven runs out of memory (maybe I have to configure JVM).

I've been using MacOS Catalina with Java 1.8 and Apache Maven 3.6.3 

About maven and IDE-s supporting it - Then probably IntelliJ would be a good match, because it supports maven. I'm using IntelliJ to build AIR/Flash/Flex projects and it would be nice to be able to stick with it when using Royal.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 I had problems building royal successfully with maven from the .zip downloaded straight from apache royal site (`apache-royale-0.9.6-src.zip`) (https://royale.apache.org/source-code/) The problem is that the themes can't be build because of missing dependency (airglobal:swc:20 or something similar) . I had made a minor tweak to the root `pom.xml` in `royale-asjs` which fixes this issue.
> `<repository> <id>apache-maven-release</id> <url>http://repository.jspresso.org/maven2/</url> <name> MVN repo</name> </repository>`
> Another thing that I faced - Maven runs out of memory (maybe I have to configure JVM).
> 
> I've been using MacOS Catalina with Java 1.8 and Apache Maven 3.6.3
> 
> About maven and IDE-s supporting it - Then probably IntelliJ would be a good match, because it supports maven. I'm using IntelliJ to build AIR/Flash/Flex projects and it would be nice to be able to stick with it when using Royal.

If you wanted to build SDK itself I recommend you to checkout all repositories and do [build](https://github.com/apache/royale-asjs/wiki/Build-Apache-Royale-with-Maven). Could shed some light and tell us what are you trying to achieve in general?

**Comment by carlosrovira** [comment]
IntelliJ supports Maven too. Eclipse and VSCode through plugins...
Maven is widely supported with IDEs in general

**Comment by carlosrovira** [comment]
Hi @heitara you should be able to build from maven directly from the 3 repositories. You need to follow this:

https://github.com/apache/royale-asjs/wiki/Build-Apache-Royale-with-Maven

we worked recently to simplify it greatly

**Comment by heitara** [comment]
I'm trying to build a Flex project with Apache Royal. But the project is quite huge and has many library dependencies. At the moment we are building it using NANT (something similar to ant) on a CI server. I need to have access to the CLI version of the tools like mxmlc and compc to be able to adjust the NANT scripts, once we convert the AS3/Flex code to one that can be compiled with Royal.

My idea is to have a local copy of the SDK, so we can do adjustments if needed. Once I build the SDK I should able to distribute it to our CI servers and use the NANT scripts.

A good idea is to update the Apache Royal page to let the users, that building with Maven won't result in having working binaries and you have to use ANT to get the binaries. 

I'll try to build everything from source (from github). I'll post the result here.
I don't mind using maven when working with new Royal projects, but converting all the scripts in my case is not an option, because the Flex project is just a part of the whole product. Everything else is build with NANT.

**Comment by piotrzarzycki21** [comment]
> I'm trying to build a Flex project with Apache Royal. But the project is quite huge and has many library dependencies. At the moment we are building it using NANT (something similar to ant) on a CI server. I need to have access to the CLI version of the tools like mxmlc and compc to be able to adjust the NANT scripts, once we convert the AS3/Flex code to one that can be compiled with Royal.
> 
> My idea is to have a local copy of the SDK, so we can do adjustments if needed. Once I build the SDK I should able to distribute it to our CI servers and use the NANT scripts.
> 
> A good idea is to update the Apache Royal page to let the users, that building with Maven won't result in having working binaries and you have to use ANT to get the binaries.
> 
> I'll try to build everything from source (from github). I'll post the result here.
> I don't mind using maven when working with new Royal projects, but converting all the scripts in my case is not an option, because the Flex project is just a part of the whole product. Everything else is build with NANT.

Thanks for explanation, so now everything has perfect sense to me and there is no reason pushing you into Maven, cause obviously converting your project to Maven would take unnecessary time and energy. Let us know how goes with building project using Ant. Good Luck!

**Comment by carlosrovira** [comment]
hi @heitara, I just fixed maven distribution sdk. So you can use the IDE to build with it standard IDE ways, a part from the normal maven way (mvn install). So you don't need to use ANT anymore if you don't want. I updated wiki here: https://github.com/apache/royale-asjs/wiki/build-scripts

I'll close this ticket, reopen if you find some issue
