### ISSUE TITLE
DataGrid/DataGridColumn problems in Scroller/Group/Panel

### ISSUE THREAD

**Issue by T-San001** [apache/royale-asjs#658]
There are several problems:

1. Horizontal (may be vertical) scroll bar does not function.

2. All fields are displayed in the fixed Panel width, consequently, the width of each field is ignored.

3. Compared with the Flash output, rows are not drawn gray color by every two rows.

4. textAlign attribute does not function.

5. headerStykeName attribute does not function.

Would you please check the attachment?  Thanks.

[DGC2.txt](https://github.com/apache/royale-asjs/files/4028701/DGC2.txt)

[DGC2.xlsx](https://github.com/apache/royale-asjs/files/4028696/DGC2.xlsx)

**Comment by aharui** [comment]
I switched your example to AdvancedDataGrid (instead of DataGrid) and I think it works ok.  If you don't want to use ADG, you can try moving some of the functionality down into DataGrid classes.

**Comment by T-San001** [comment]
Alex, thanks.  I checked with the latest build but no output.  I used VS Code with the latest ActionScript/MXML extension.  I will recheck tomorrow.

**Comment by aharui** [comment]
It might have required some changes I had pending.  I've pushed the latest changes, so try again and if still no output, check the console for errors.

**Comment by T-San001** [comment]
Alex, still no output.  No contents in release console.  But the following contents in debug console.

`2Language.js:242 invalidateParentSizeAndDisplayList not implemented
Language.js:242 invalidateProperties not implemented
Language.js:242 mouseEnabled not implemented
2Language.js:242 invalidateParentSizeAndDisplayList not implemented
Language.js:242 mouseEnabled not implemented
8Language.js:242 updateDisplayList not implemented
Language.js:242 invalidateParentSizeAndDisplayList not implemented
Language.js:242 verticalAlign not implemented
6Language.js:242 updateDisplayList not implemented
4Language.js:242 invalidateParentSizeAndDisplayList not implemented
18Language.js:242 updateDisplayList not implemented
9Language.js:242 invalidateParentSizeAndDisplayList not implemented
7Language.js:242 updateDisplayList not implemented
Language.js:242 invalidateParentSizeAndDisplayList not implemented
3Language.js:242 updateDisplayList not implemented
7Language.js:242 invalidateParentSizeAndDisplayList not implemented
Language.js:242 verticalAlign not implemented
51Language.js:242 invalidateParentSizeAndDisplayList not implemented`

Could you show the options you used?  My VS code options may have problems.

**Comment by aharui** [comment]
Try giving the Application tag a width and height.  In Flex, the SWFs had a default width/height.  We haven't implemented that for JS yet partly because I'm not sure whether that is worth emulating.  I assumed that most folks do set some sort of width/height (often just 100%) but maybe not.

**Comment by T-San001** [comment]
Alex, 

mx:DataGrudColumn does not support height attribute.  Would you please check it?

**Comment by aharui** [comment]
I don't see a height attribute for mx:DataGridColumn in the Flex documentation.  Where is it documented and/or what is it supposed to do?

**Comment by T-San001** [comment]
Alex, I’ve just tried your suggestion of specifying height.  So far, I do not know how to fix the no output. With your first fix, there was output.

**Comment by aharui** [comment]
This is what worked for me:

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
			   xmlns:mx="library://ns.apache.org/royale/mx"
			   xmlns:s="library://ns.apache.org/royale/spark" width="1400" height="400">
	<fx:Script>
		<![CDATA[

			import mx.collections.ArrayCollection;

			[Bindable]
			private var myCp:ArrayCollection = new ArrayCollection([
				{
					no: "1",
					contactPointId: "00000001",
					contactPoint: "No-Paper",
					zipCode: "123-4567",
					prefecture: "Kagawa",
					city: "Takamatsu",
					address: "",
					phoneNumber: "",
					faxNumber: "123456789",
					templateId1: "ABCD0001",
					templateId2: "ABCD0002",
					templateId3: "ABCD0003",
					templateId4: "ABCD0004",
					templateId5: "ABCD0005",
					multiFormFlagLabel: "Multi-form (AB, CD, both AB and CD)",
					kanjiFlagLabel: "Not Required",
					furiganaFlagLabel: "Not Required",
					loanAmountFlagLabel: "Not required",
					insuranceAmountSumFlagLabel: "Not Required",
					insurancePlanId: "00112233",
					partnerIdLabel: "Partner A",
					userName: "",
					updatedDate: "",
					deleteFlagLabel: ""
				}
			]);
		]]>

	</fx:Script>

	<s:Scroller width="100%" height="100%">
		<s:Group>
			<s:Panel x="19" y="235" width="1324" height="394" title="Search Result">
				<mx:AdvancedDataGrid id="workTable" tabFocusEnabled="false" x="-1" y="0" width="1324" height="100%" 
							 horizontalScrollPolicy="on" dataProvider="{myCp}">
					<mx:columns>
						<mx:AdvancedDataGridColumn width="65" dataField="no" headerText="No." />
						<mx:AdvancedDataGridColumn dataField="contactPointId" headerText="お客さま連絡先ID" width="300" />
						<mx:AdvancedDataGridColumn dataField="contactPoint" headerText="お客さま連絡先（宛名）" width="350"/>
						<mx:AdvancedDataGridColumn dataField="zipCode" headerText="郵便番号" width="200"/>
						<mx:AdvancedDataGridColumn dataField="prefecture" headerText="住所（都道府県）" width="300"/>
						<mx:AdvancedDataGridColumn dataField="city" headerText="住所（区市町村）" width="300"/>
						<mx:AdvancedDataGridColumn dataField="address" headerText="住所（残り）" width="200"/>
						<mx:AdvancedDataGridColumn dataField="phoneNumber" headerText="電話番号" width="200"/>
						<mx:AdvancedDataGridColumn dataField="faxNumber" headerText="FAX番号" width="200"/>
						<mx:AdvancedDataGridColumn dataField="templateId1" headerText="連絡票テンプレート（漢字）ID" width="300"/>
						<mx:AdvancedDataGridColumn dataField="templateId2" headerText="連絡票テンプレート（ひらがな）ID" width="300"/>
						<mx:AdvancedDataGridColumn dataField="templateId3" headerText="連絡票テンプレート（カタカナ）ID" width="300"/>
						<mx:AdvancedDataGridColumn dataField="templateId4" headerText="連絡票テンプレート（英語）ID" width="300"/>
						<mx:AdvancedDataGridColumn dataField="templateId5" headerText="連絡票テンプレート（混合）ID" width="300"/>
						<mx:AdvancedDataGridColumn dataField="multiFormFlagLabel" headerText="複票フラグ" width="200"/>
						<mx:AdvancedDataGridColumn dataField="kanjiFlagLabel" headerText="連絡要漢字フラグ" width="200"/>
						<mx:AdvancedDataGridColumn dataField="furiganaFlagLabel" headerText="連絡要フリガナフラグ" width="200"/>
						<mx:AdvancedDataGridColumn dataField="loanAmountFlagLabel" headerText="要ローン金額フラグ（連絡票）" width="300"/>
						<mx:AdvancedDataGridColumn dataField="insuranceAmountSumFlagLabel" headerText="要合計保険金額フラグ（連絡票）" width="300"/>
						<mx:AdvancedDataGridColumn dataField="insurancePlanId" headerText="プランID" width="200"/>
						<mx:AdvancedDataGridColumn dataField="partnerIdLabel" headerText="パートナー" width="200"/>
						<mx:AdvancedDataGridColumn dataField="userName" headerText="更新ユーザー" width="200"/>
						<mx:AdvancedDataGridColumn dataField="updatedDate" headerText="更新日時" width="200"/>
						<mx:AdvancedDataGridColumn dataField="deleteFlagLabel" headerText="削除" width="100" />
					</mx:columns>
				</mx:AdvancedDataGrid>
			</s:Panel>
			<s:Label y="93" width="1900" height="45" fontSize="30" textAlign = "center" text="Contact Master" verticalAlign="top"/>
		</s:Group>
	</s:Scroller>
</s:Application>
```

**Comment by T-San001** [comment]
Alex, thanks.  I've confirmed the fix.  I will check why my mxml does not work.
