### ISSUE TITLE
Invalid Date in Setup

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#659]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Carriage/Freight -> Customer Approved Depot from Setups in Menu
File : com/dbz/modules/Common/dbzApprovedDepotSetup.mxml

Selection of Date is invalid
![Invalid Date](https://user-images.githubusercontent.com/42200979/71874876-d6d45c00-3144-11ea-8e17-14f711b2f184.gif)

**Comment by pashminakazi** [comment]
Date is undefined "NaN",Date button is also missing

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Purchase from Select in Menu
Go to Products -> Rates - Date Wise from Setups in Menu
File : com/dbz/modules/PUR/dbzDateWisePrdRateSetup.mxml

In Royale
![image](https://user-images.githubusercontent.com/42200979/71883339-0fc9fc00-3158-11ea-9105-5dd362849384.png)

In Flex
![image](https://user-images.githubusercontent.com/42200979/71883485-5ddeff80-3158-11ea-84c1-e0d5892d2d31.png)
![image](https://user-images.githubusercontent.com/42200979/71883541-73ecc000-3158-11ea-8824-bf817cbe4e77.png)

**Comment by aharui** [comment]
In MaskedTextInput's handleInput, the call to updateDisplayList should probably be outside the for loop.  There may be other issues besides that, but that calling updateDisplayList inside the loop is certainly causing problems.

**Comment by pashminakazi** [comment]
@aharui Thank u so much Issue Resolved
