### ISSUE TITLE
ColorPicker is not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#661]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Purchase from Select in Menu
Go to Purchase -> Requisition Types from Setups in Menu
File : com/dbz/modules/PUR/dbzPurchaseRequSetup.mxml

In Royale
![image](https://user-images.githubusercontent.com/42200979/71957662-321f5080-3210-11ea-8c71-4749a767386d.png)

In Royale
![image](https://user-images.githubusercontent.com/42200979/71957678-3a778b80-3210-11ea-8a22-a99ec486e766.png)

**Comment by yishayw** [comment]
We have a Basic ColorPicker in examples.

**Comment by pashminakazi** [comment]
ColorPickerExample is not working
File : https://paste.apache.org/8m7va
![image](https://user-images.githubusercontent.com/42200979/71958852-19646a00-3213-11ea-8b2f-82323f783043.png)

**Comment by aharui** [comment]
ColorPicker will need to be emulated just like DropDownList and ComboBox.  You should be able to re-use the beads in Basic or subclass them.  You can try implementing ColorPicker by looking at how DropDownList and ComboBox are emulated.

**Comment by pashminakazi** [comment]
Alex you are right but I do not have time to work on SDK..I am only working on Royale now a days,I have to send 98 more complex setups to our QA team till 15-January-2020.Its my deadline date of setups

**Comment by pashminakazi** [comment]
@aharui Thank u so much ColorPicker is working now.
I have another issue 
File Code :
https://paste.apache.org/b2a5j
When we select color from ColorPicker,spark textinput's color should be change.
Spark textInput color and contentBackgroundColor property is not working.Please implement these properties.I will be very Thankful to You.

Flex/Royale Comparison Video:
![Color of Spark TextInput](https://user-images.githubusercontent.com/42200979/72041848-753ff900-32ce-11ea-8318-ae7dfb0d2d33.gif)

**Comment by aharui** [comment]
"color" seemed to already work in my local testing.  I got contentBackgroundColor to work in this commit: 49512caedb8e6cc64bdf804913745b78a00ec42e

**Comment by pashminakazi** [comment]
When we open dbzPurchaseRequSetup **in Flex.**
<s:TextInput color="{valueObj == null ? 0 : valueObj.purchaseRequColor}" contentBackgroundColor="{valueObj == null ? 0 : valueObj.purchaseRequColor}" id="purchaseRequColor"  width="100" tabIndex="3" maxChars="30"  x="187" y="223" height="19"/>

the Color of s:TextInput  is same as the color of ColorPicker.
then when we open ColorPicker and select any Color,the Change method of ColorPicker called
<mx:ColorPicker id="purchaseColor" change="changeEvt(event);" x="296" y="223" height="19" width="108"/>

public function changeEvt(event:ColorPickerEvent):void 
			{
				purchaseRequColor.text= event.currentTarget.selectedItem;
			}

This changeEvt is setting the color of textinput same as ColorPicker's color.

**In Royale** 
There's default selection of Color in ColorPicker,but textinput is not setting that Color,textinput is white,
then when i change Color from ColorPicker **ChangeEvt** function Called but purchaseRequColor.text is null because there's no value in **event.currentTarget.selectedItem;**
then i change 
purchaseRequColor.text= event.currentTarget.selectedItem; to
purchaseRequColor.text= event.currentTarget.selectedColor;
then the number of color is setted on textInput,But not the Color.
Video: 
![SelectedColor of colorpicker](https://user-images.githubusercontent.com/42200979/72131741-f23aa380-339e-11ea-96eb-c376d54c3931.gif)

**Comment by aharui** [comment]
Without the VDI, I cannot see your code, so I can only guess at how you set it up.  Since you are using bindings, the color setter in UIComponent and contentBackgroundColor setter in SkinnableTextBase need to be implemented to call setStyle like the backgroundColor setter in UIComponent.  You should be able to make and test those changes.  It is the end of my workday.

**Comment by pashminakazi** [comment]
Hi Alex,
VDI is working now Please connect VDI with Computer namevdi.sidathyder.com.pk:6105 instead of
vdi.sidathyder.com.pk:6022
Other credentials are same

**Comment by aharui** [comment]
I can connect to the VDI, but cannot log into the app, so I cannot do any more work.

**Comment by pashminakazi** [comment]
SelectedItem is working now,But there is no color in TextInput

**Comment by aharui** [comment]
In dbzPurchaseRequSetup, there is a "valueObj".  The colors of the TextInput is bound to valueObj.purchaseRequColor, but I do not see any code that sets it when the ColorPicker is changed.  What code is supposed to change valueObj.purchaseRequColor?

**Comment by pashminakazi** [comment]
make this Example working
https://paste.apache.org/4l1pz
if we change the color from ColorPicker that color should be applied on s:TextInput

**Comment by aharui** [comment]
In that example, I do not see any code that will change the color or contentBackgroundColor of the s:TextInput.

**Comment by pashminakazi** [comment]
i dont know what code will change color or contentBackgroundColor of s:TextInput.
If i know then i will check this example myself and then check my setup according to this example

**Comment by pashminakazi** [comment]
In this Example https://paste.apache.org/4l1pz
please add a code to change color of textInput whenever ColorPicker color is changed

**Comment by aharui** [comment]
A simple way is:

```            public function changeEvt(event:ColorPickerEvent):void 
            {
                purchaseRequColor.text = event.currentTarget.selectedItem;
                //purchaseRequColor.setStyle("color", purchaseColor.selectedColor);
                purchaseRequColor.setStyle("contentBackgroundColor", purchaseColor.selectedColor);                
            }
```

I commented out setting the color otherwise the font would match the background and you wouldn't see anything

**Comment by pashminakazi** [comment]
Ok thank u so much Alex

**Comment by aharui** [comment]
I think I fixed the problem in the royale-compiler change: 4efb7de5b1b00e62af8198b6ac5ee909ded92d42

**Comment by pashminakazi** [comment]
@aharui Thank u so much its working now
