### ISSUE TITLE
Restrict Property is working but we can Copy/paste the restricted text in textfield

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#662]
In dbzClearingAgentSetup Phone field is restricted to number so we can not type alphabets in phone number.But we are able to copy and paste alphabets in phone field which is incorrect.

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Import from Select in Menu
Go to Import -> Clearing Agent from Setups in Menu
File : com/dbz/modules/IMP/dbzClearingAgentSetup

Video attachment : first part is of Flex,2nd part is of Royale.
Check difference
![Restrict property copy paste](https://user-images.githubusercontent.com/42200979/71968903-897ceb00-3227-11ea-9a26-bf2ab1548688.gif)
.mxml

**Comment by pashminakazi** [comment]
@aharui thanks but still not working 
![Restrict Property issue still exist](https://user-images.githubusercontent.com/42200979/72041931-b6380d80-32ce-11ea-9e04-6ea066326c88.gif)

**Comment by aharui** [comment]
Please verify that the RestrictTextInputBead.js you see in the debugger is the latest one.  It will have both a validateKeypress and a validateInput method.

There has been too many occurrences of not getting the latest code.  I don't want to spend time on that just to find out the code has not been properly updated.  Plus, the VDI is still inaccessible to me.

**Comment by pashminakazi** [comment]
RestrictTextInputBead.js : https://paste.apache.org/myukk

**Comment by pashminakazi** [comment]
@aharui Thank u so much Its working now
