### ISSUE TITLE
Saved Record code shouldn't be editable

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#663]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Document Type Category Setup from Setups in Menu
File : com/dbz/modules/SAL/dbzDocTypeCategorySetup.mxml

When i open dbzDocTypeCategorySetup the cursor is on code field of saved record and i can edit it,when i edit code field of saved record and press save button then exception is thrown in DbzUtil which is in lib
dbzUtil has a function balanceCode which is called on Code field.
focusOut="dbzUtil.balanceCode(setupCode);"

Royale vs Flex Video
![saved record shouldn't be able to edit](https://user-images.githubusercontent.com/42200979/71971056-9e5b7d80-322b-11ea-8296-e902a4c8f523.gif)

**Comment by aharui** [comment]
Will need the VDI to investigate further.

**Comment by pashminakazi** [comment]
Hi Alex,
VDI is working now Please connect VDI with Computer namevdi.sidathyder.com.pk:6105 instead of
vdi.sidathyder.com.pk:6022
Other credentials are same

**Comment by pashminakazi** [comment]
Still issue not resolved
![Code resaved](https://user-images.githubusercontent.com/42200979/72217483-31f4bd00-3550-11ea-9e1d-5f512d0529e2.gif)

**Comment by pashminakazi** [comment]
Edit code field
![saved record](https://user-images.githubusercontent.com/42200979/72321328-66d65080-36c5-11ea-9293-f131d331bbfe.gif)
