### ISSUE TITLE
While Scrolling Dropdownlist blank area will be shown in Dropdown

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#664]
Please Remove white area which is shown in Dropdownlist,only dropdown values should be shown in dropdownlist.

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Price -> Titles from Setups in Menu
File : com/dbz/modules/SAL/dbzPriceTitleSetup.mxml

![dropdown values will be hidden](https://user-images.githubusercontent.com/42200979/71972949-8b4aac80-322f-11ea-9d5a-0e802e989598.gif)

**Comment by pashminakazi** [comment]
@aharui Please reply on this issue

**Comment by aharui** [comment]
I am unable to reproduce excess blank area in my local tests.  Will need the VDI to work or you will have to debug it yourself.

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved
