### ISSUE TITLE
Vertical Scrollbar should be visible when we resize ADG columns

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#666]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Store Room -> Store City Distance from Setups in Menu
File : com/dbz/modules/SAL/dbzStoreCityDistanceSetup.mxml
![Scroller](https://user-images.githubusercontent.com/42200979/72046863-146aed80-32db-11ea-874a-0005bf1009a6.gif)

**Comment by aharui** [comment]
Vertical or Horizontal scrollbar?  Seems like it should be horizontal.

**Comment by pashminakazi** [comment]
yes Horizontal scrollbar

**Comment by aharui** [comment]
The VDI is still not available so I can't investigate in detail.  In the test cases I looked, when you resize a column, the other columns also adjust their size so there is no excess width to require a horizontal scrollbar.  I will need the VDI to understand why this particular ADG lets its columns grow beyond the width of the ADG unless you can provide a simple test case.

As a workaround, I think you could try adding a CSS selector like 

.AdvancedDataGridListArea
{
    overflow-x: auto;
}

**Comment by pashminakazi** [comment]
Thanks Alex.
There's no change after adding css
![image](https://user-images.githubusercontent.com/42200979/72131139-3a58c680-339d-11ea-9564-cdb0732fb2ef.png)

Hopefully VDI will be available today,then when you have time please check this issue on VDI

**Comment by aharui** [comment]
If you look at the debugger, you can see that dg has a width of 418px.  If you add up the column widths (I can only see DataGridColumn0 is 83.2px wide) does it add up to more than 418?  If not, then the column is clipping the renderers, the column does not extend beyond the right side.

Without the VDI, I cannot see how the DG was setup.  What does the ADG MXML tag look like?  Maybe there is some property that is being used that allows the columns to extend beyond the right side.

**Comment by pashminakazi** [comment]
Hi Alex,
VDI is working now Please connect VDI with Computer namevdi.sidathyder.com.pk:6105 instead of
vdi.sidathyder.com.pk:6022
Other credentials are same

**Comment by pashminakazi** [comment]
after these changes i am unable to resize ADG columns and there's an extra column in ADG after this change.
![ADG scroller](https://user-images.githubusercontent.com/42200979/72217507-ae879b80-3550-11ea-8871-66ad81fc771e.gif)

**Comment by aharui** [comment]
More fixes in 98f3a67dc5abf51877baec8f3716619d6106e3cf

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved
