### ISSUE TITLE
if TextArea is multiRow then Horizontal Scroll should be visible

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#667]
![Horizontal Scroller](https://user-images.githubusercontent.com/42200979/72047176-c1de0100-32db-11ea-91ec-71088cc956cd.gif)

**Comment by aharui** [comment]
Spark or MX TextArea?

**Comment by pashminakazi** [comment]
Spark TextArea

**Comment by aharui** [comment]
This seems to be working for me with mx:TextArea.
