### ISSUE TITLE
Spark TextArea is not taking Input

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#668]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Payment Sections from Setups in Menu
File : com/dbz/modules/PUR/dbzPaymentSectionSetup.mxml

Flex/Royale Video
![TextArea not taking input](https://user-images.githubusercontent.com/42200979/72051589-64e74880-32e5-11ea-929a-a50799b5485b.gif)

**Comment by aharui** [comment]
Is there some feature of Spark TextArea that you require instead of MX TextArea?  Otherwise, it might be easier to map Spark's TextArea to MX TextArea for now.

**Comment by pashminakazi** [comment]
I have changed Spark's TextArea to MX TextArea and now it is taking input.
But Please resolve https://github.com/apache/royale-asjs/issues/667 with mx or spark textarea
