### ISSUE TITLE
NavigatorContent inside a TabNavigator

### ISSUE THREAD

**Issue by T-San001** [apache/royale-asjs#669]
This markup does not work.

Would you please check?

The following is an example code.

`<?xml version="1.0" encoding="utf-8"?>	
<s:Application xmlns:fx = "http://ns.adobe.com/mxml/2009"
			   xmlns:mx="library://ns.apache.org/royale/mx"
			   xmlns:s="library://ns.apache.org/royale/spark">	

	<s:Scroller width="100%" height="100%">
		<s:Group>
			<mx:TabNavigator x="96" y="9" width="763" height="1078" tabFocusEnabled="false">
				<s:NavigatorContent id="navigator1" width="100%" height="100%" label="PHOTO-1">
					<s:Scroller id="scroler1" x="0" y="0" width="763" height="1057">
						<s:Group>
							<s:TextArea text="This is the first pane" />
						</s:Group>
					</s:Scroller>
				</s:NavigatorContent>
				<s:NavigatorContent id="navigator2" width="100%" height="100%" label="PHOTO-2">
					<s:Scroller id="scroler2" x="0" y="0" width="763" height="1057">
						<s:Group>
							<s:TextArea text="This is the second pane" />
						</s:Group>
					</s:Scroller>
				</s:NavigatorContent>
			</mx:TabNavigator>
		</s:Group>
	</s:Scroller>		
</s:Application>`

**Comment by aharui** [comment]
This example is working better now
