### ISSUE TITLE
mx:NumberValidator is validating NumericStepper source incorrectly

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#675]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Bank Reconciliation from Setups in Menu
File : com/dbz/modules/GL/dbzBankReconSetup.mxml

When i am entering **9999** into NumericStepper it turns into **100** and validation of numericStepper using mx:NumberValidator is incorrect

Flex Vs Royale Video :
![NumericStepper](https://user-images.githubusercontent.com/42200979/72250089-a5fc9700-361c-11ea-94bf-c59335b6aac1.gif)

**Comment by pashminakazi** [comment]
Range is working now but NumericStepper is validation is not working
![NumericStepper validation](https://user-images.githubusercontent.com/42200979/72319986-7bfdb000-36c2-11ea-9a52-ca017da4266c.gif)

**Comment by aharui** [comment]
What value is not validating?

**Comment by pashminakazi** [comment]
In dbzBankReconSetup
<mx:NumberValidator id="vldrc_ACCOUNT_START" enabled="{rc_ACCOUNT_START.enabled}" source="{**rc_ACCOUNT_START**}" property="value" required="true" minValue="1" maxValue="9999999" allowNegative="false"/>

source="{**rc_ACCOUNT_START**}"  is **NumericStepper**

<s:NumericStepper id="**rc_ACCOUNT_START**" x="153" y="35" width="100" height="22" maximum="9999999" maxChars="7" tabIndex="3" change="isModified=true"/>

On save button fn_ValidateForm is called which is validating NumericStepper values.
if(vldrc_ACCOUNT_START.enabled && vldrc_ACCOUNT_START.validate().type == ValidationResultEvent.INVALID) {
return;
}

It should not return from here because i am giving right value for NumberValidator **vldrc_ACCOUNT_START** so why it is returning ?
it is not returning in Flex. i am giving same values in Royale

it means the validation is not correct
Flex vs Royale Video
![NumericStepper validation flex royale](https://user-images.githubusercontent.com/42200979/72321109-de57b000-36c4-11ea-91a1-87cb2489c45e.gif)

**Comment by aharui** [comment]
I cannot understand the problem from watching these videos.  What values are not validating and when?  Your description above described the code, but not the values that are causing a problem.  From watching the video, it looks like the validator is correctly saying that "0" is invalid since the minValue is set to 1 in the code you showed.

Instead of making more videos, try making a simple test case.

**Comment by pashminakazi** [comment]
I can't understand the problem in a simple test case
https://paste.apache.org/fflx8
when i give a value of numericStepper 1 and click save button it doesn't return and execute else part that  Alert.show("Validation is working");
if(vldrc_ACCOUNT_START.enabled && vldrc_ACCOUNT_START.validate().type == ValidationResultEvent.INVALID) {
return;
}
Alert.show("Validation is working");
means validation is correct.
In my dbzBankReconSetup everything is same then why it returns?

**Comment by aharui** [comment]
I compiled and ran the test case and the Alert showed up.

**Comment by aharui** [comment]
If the validate() method is returning INVALID, you will have to debug into it and understand why.

**Comment by pashminakazi** [comment]
In Example i have selected "1" from numericStepper
value in validate function is "1"
![image](https://user-images.githubusercontent.com/42200979/72718471-d356c100-3b97-11ea-818a-af4b53f72dc0.png)

In my Setup, I am selecting any number from numericStepper it is returning 0
value in validate function is "0"
![image](https://user-images.githubusercontent.com/42200979/72718792-6bed4100-3b98-11ea-9920-c74e7302f0f4.png)

**Comment by pashminakazi** [comment]
I have identified the same problem in Example :
https://paste.apache.org/to6wh

If i have numericStepper with enabled=false then numericStepper is disabled and the default value of numericStepper is "0" so the debugger returns from it and i can not save the record.

in flex if there is a numericStepper enabled=false ,debugger doesn't returns from it and continues its execution
