### ISSUE TITLE
CheckBox is not shown as ADG Column 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#676]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to General Ledger from Select in Menu
Go to Voucher Type from Setups in Menu
File : com/dbz/modules/GL/dbzVoucherTypeSetup.mxml

I tried to change mx:CheckBox to s:Checkbox then **data** property is undefined in s:Checkbox,then i add data property but still it is not showing in ADG.
Then i revert s:Checkbox to mx:CheckBox

![CheckBox in adg](https://user-images.githubusercontent.com/42200979/72253413-4e155e80-3623-11ea-9740-e5284dd970e6.gif)

**Comment by aharui** [comment]
In theory, you should not be changing your MXML.  The MXML that worked in Flex should work in Royale.  Which checkbox were you using in Flex?

**Comment by pashminakazi** [comment]
In Flex i was using mx:Checkbox and same in Royale

**Comment by aharui** [comment]
OK, I will get MX Checkbox to work

**Comment by aharui** [comment]
Other people are also using custom item renderers based on emulation components, so the current emulation needs some refactoring.

As a temporary workaround, you can use the default item renderer and use a custom labelFunction that returns a checked box.  This worked in my tests:

```
            private function oddsEvens(value:Object):String
            {
                var checked:Boolean = <some logic based on value's properties>;
                return (checked) ? "☑" : "☐";
            }
```

**Comment by pashminakazi** [comment]
Please send me your test Example.
from where this function is called?

**Comment by aharui** [comment]
Custom labelFunctions go in the column.  In my simple test case, something like:

```
                <mx:AdvancedDataGridColumn dataField="colB" headerText="B" width="100"  visible ="true"
                                           labelFunction="oddsEvens"/>
```

**Comment by pashminakazi** [comment]
not working
![image](https://user-images.githubusercontent.com/42200979/72597910-90df7b00-3930-11ea-8df8-4fd990b5e93b.png)
` private function oddsEvens(value:Object):String
            {
                var checked:Boolean = data.vtu_Selected == '0' ? false : true;
                return (checked) ? "☑" : "☐";
            }

<mx:AdvancedDataGrid id="dgAuthorities" sortExpertMode="true" styleName="advancedDataGrid" 
													 rowHeight="20" verticalAlign="middle" resizableColumns="true"
													 change="fn_PFWithAuthItem();" dataProvider="{vtuData}" textAlign="left" 
													 tabEnabled="false" tabFocusEnabled="false" left="2" right="2" bottom="10"
													 top="95">
<mx:columns>
<mx:AdvancedDataGridColumn dataField="vtu_Selected" headerText="Selected" width="70" labelFunction="oddsEvens"/>
</mx:columns>
</mx:AdvancedDataGrid>
<s:CheckBox x="27" y="6" label="Selected" id="vtu_Selected" height="20"/>`

**Comment by aharui** [comment]
Any exceptions in the console?  You might need to check if data is null.  The label function is working fine for me.

**Comment by aharui** [comment]
The labelFunction is incorrect, it should be

```
private function oddsEvens(value:Object):String { 
var checked:Boolean = value.vtu_Selected == '0' ? false : true; 
return (checked) ? "☑" : "☐"; 
}
```
