### ISSUE TITLE
mvn  compile in royale-asjs repo is currently failing

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#68]
"mvn clean compile" on the develop branch is currently failing with this error:
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.2.1:wget (get-createjs) on project Fonts: IO Error: Error while expanding /Users/justinmclean/royale-asjs/frameworks/fontsrc/target/downloads/flat-ui-2.2.2.zip: Negative seek offset -> [Help 1]

Removing the cached file (to force it to downloaded a new file) fails to solve the issue:
rm /Users/justinmclean/.m2/repository/.cache/maven-download-plugin/flat-ui-2.2.2.zip

This is the URL it is downloading from:
[INFO] --- download-maven-plugin:1.2.1:wget (get-createjs) @ Fonts ---
Downloading: https://github.com/designmodo/Flat-UI/archive/2.2.2.zip
3213K downloaded

Which looks correct.

Changing to 2.3.0 (listed in releases) [1] also fails to resolve the issue.

1. https://github.com/designmodo/Flat-UI/releases

**Comment by justinmclean** [comment]
Looks like the zip on GitHub is possibly corrupted as I'm getting "Decompression failed" when trying to download directly in a browser from the above URL.

**Comment by piotrzarzycki21** [comment]
Just tried build framework on Windows 10, but before that I have removed everything from .m2 folder. Build went perfectly fine. Something specific to Mac OSX ? I will try on Mac once I will find the time to setup Maven there.

**Comment by justinmclean** [comment]
Is https://github.com/designmodo/Flat-UI/archive/2.2.2.zip a valid zip file for you?

**Comment by justinmclean** [comment]
wget https://github.com/designmodo/Flat-UI/archive/2.2.2.zip
--2017-11-06 17:40:42--  https://github.com/designmodo/Flat-UI/archive/2.2.2.zip
Resolving github.com... 192.30.255.112, 192.30.255.113
Connecting to github.com|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/designmodo/Flat-UI/zip/2.2.2 [following]
--2017-11-06 17:40:44--  https://codeload.github.com/designmodo/Flat-UI/zip/2.2.2
Resolving codeload.github.com... 192.30.255.120, 192.30.255.121
Connecting to codeload.github.com|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: '2.2.2.zip'

    [                                        <=>] 3,290,162    404KB/s   in 9.0s   

2017-11-06 17:41:02 (355 KB/s) - '2.2.2.zip' saved [3290162]

MacBook-Pro:~ justinmclean$ unzip 2.2.2.zip
Archive:  2.2.2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by piotrzarzycki21** [comment]
Yes! I can unpack it without any problem. Just checked also on my Mac it's working also, so this is something on your machine.

![image](https://user-images.githubusercontent.com/24554795/32428532-7541e168-c2c6-11e7-9617-3719c8671aaa.png)

**Comment by justinmclean** [comment]
You mind doing:
 wget https://github.com/designmodo/Flat-UI/archive/2.2.2.zip

and then:
md5 2.2.2.zip

and see if you get this result:
MD5 (2.2.2.zip) = 62403497f7316fbab9416cf8083e38b3

**Comment by piotrzarzycki21** [comment]
Result of MD5 check:
Piotrs-Mac-mini:Downloads piotr$ md5 Flat-UI-2.2.2.zip
MD5 (Flat-UI-2.2.2.zip) = b1fdedcaa46fce23145e234f00c5371c

**Comment by justinmclean** [comment]
The file downloaded is "2.2.2.zip" so not sure where you got "Flat-UI-2.2.2.zip" from

**Comment by piotrzarzycki21** [comment]
When I'm downloading file from your link it's change the name to: Flat-UI-2.2.2.zip. I don't use wget.

**Comment by piotrzarzycki21** [comment]
This is problem on your machine ?

**Comment by Harbs** [comment]
It's valid for me too.
It redirects to:
https://codeload.github.com/designmodo/Flat-UI/zip/2.2.2

Maybe your machine is not following the redirect for some reason?

**Comment by Harbs** [comment]
(and for me as well it downloads as Flat-UI-2.2.2.zip)

**Comment by justinmclean** [comment]
Looks like GitHub download is now fixed - note that the length is now specified in the HTTP request.

 wget https://github.com/designmodo/Flat-UI/archive/2.2.2.zip
--2017-11-07 09:00:23--  https://github.com/designmodo/Flat-UI/archive/2.2.2.zip
Resolving github.com... 192.30.255.113, 192.30.255.112
Connecting to github.com|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/designmodo/Flat-UI/zip/2.2.2 [following]
--2017-11-07 09:00:24--  https://codeload.github.com/designmodo/Flat-UI/zip/2.2.2
Resolving codeload.github.com... 192.30.255.120, 192.30.255.121
Connecting to codeload.github.com|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3290162 (3.1M) [application/zip]
Saving to: '2.2.2.zip'

100%[==========================================>] 3,290,162    448KB/s   in 8.7s   

2017-11-07 09:00:34 (370 KB/s) - '2.2.2.zip' saved [3290162/3290162]

MacBook-Pro:royale-asjs justinmclean$ md5 2.2.2.zip
MD5 (2.2.2.zip) = b1fdedcaa46fce23145e234f00c5371c
MacBook-Pro:royale-asjs justinmclean$ unzip 2.2.2.zip
Archive:  2.2.2.zip
11175cd57f44519bf967608e69a9b4bc37a4d470
   creating: Flat-UI-2.2.2/
...

**Comment by piotrzarzycki21** [comment]
Have you changed something on your sight to get it working?

**Comment by justinmclean** [comment]
Nothing changed at my end to get it working.
