### ISSUE TITLE
<s:Panel>'s skinClass attribute does not work with PanelSkin.mxml

### ISSUE THREAD

**Issue by T-San001** [apache/royale-asjs#680]
With skinClass = "PanelSkin" attribute specified for <s:Panel>, the build fails with the following exception.
PSolv1A.mxml line 11 column 98 : java.lang.IllegalArgumentException: No handler specified for nodes of type 'MXMLClass'

[PSolve1A.xlsx](https://github.com/apache/royale-asjs/files/4063049/PSolve1A.xlsx)

Without skinClass = "PanelSkin" attribute, the build is successful, but the output has several problems:

1. <s:Label>'s color attribute does not work.

2. <s:Label>'s text is split at the space position (in case of double byte, the text is split at each character).
   ==> There is a work around to bypass this problem, which is to use width attribute.

**Comment by aharui** [comment]
Should be working now with royale-compiler change b08f10de2729221a85602624838bc785a9b6fea9
and royale-asjs change
ccb2eb9aa5cfd7e5382eeb1857991e98e2647492
