### ISSUE TITLE
Combination of AdvancedDataGrid/fx components does generate mess

### ISSUE THREAD

**Issue by T-San001** [apache/royale-asjs#681]
mxml element structure is,

 <s:Scroll>
   <s:Panel>
     <s:Group>
       <mx:AdvancedDatagrid>
         <mx:groupedColumns>
           <mx:AdvancedDataGridColumn>
           <mx:AdvancedDataGridColumn>
           <mx:AdvancedDataGridColumnGroup>
             <mx:AdvancedDataGridColumn>
               <fx:Component>
                 <mx:Label>
                   <fx:Script>

The output is mess.

[PSolve1B.xlsx](https://github.com/apache/royale-asjs/files/4063275/PSolve1B.xlsx)

**Comment by T-San001** [comment]
This is the mxml with extension renamed to txt.

[PSolv1B.txt](https://github.com/apache/royale-asjs/files/4147948/PSolv1B.txt)

**Comment by aharui** [comment]
This should be fixed by the "has" branch changes
