### ISSUE TITLE
After scrolling Dropdown up down 40 to 50 time

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#684]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Misc -> Employees from Setups in Menu
File : com/dbz/modules/Common/dbzEmployeeSetup.mxml

After Scrolling Department Dropdown many times.the dropdown is behaving like :
![dropdownlist issue](https://user-images.githubusercontent.com/42200979/72430528-72547500-37b4-11ea-9e2b-5d985825d321.gif)

**Comment by aharui** [comment]
Please!  No more videos!  Please describe in words what is expected vs actual and provide detail.

**Comment by pashminakazi** [comment]
I have sended this Setup to our QA team.
they were testing this setup,while testing they scroll dropdown scroller up and down many times to see that any issue occurs or not.after 1 min of scrolling dropdown is out of control,you can see the video,we don't understand what was happening

**Comment by aharui** [comment]
If it takes 1 minute to break the scrolling, then I am going to assume this is lower priority.  The way to test and debug is to create a test harness.  I already added a bunch of trace output that can be uncommented to help catch issues.

But first, I need a description in words.  I can't tell what is going on from the video.  I can't tell if the mouse is still interacting with the scroller or whether the screen eventually stabilizes.
