### ISSUE TITLE
TabNavigator.SelectedChild.Label is throwing exception

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#685]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Security -> Group Privileges from Setups in Menu
File : com/dbz/modules/Common/dbzGroupPrivileges.mxml

In our application we were using mx:ViewStack and s:TabNavigatorContent with TabBar
its not working in Royale so I commented **TabBar**,
and replace **mx:ViewStack** with **mx:TabNavigator** and 
 **s:TabNavigatorContent** with **mx:VBox** which is working fine
but now in dbzGroupPrivileges setups there's a check 
if (VS.selectedChild.label=="COA")
VS is id of ViewStack in Flex and In Royale VS is id of TabNavigator
in ViewStack selectedChild is implemented but using TabNavigator it is giving exception

![image](https://user-images.githubusercontent.com/42200979/72594391-165f2d00-3929-11ea-9121-6e0dd0db71a8.png)

![image](https://user-images.githubusercontent.com/42200979/72594376-0ba49800-3929-11ea-9e95-d9548047e91a.png)

**Comment by aharui** [comment]
Debug into the selectedChild getter.  Let us know what you discover.

**Comment by pashminakazi** [comment]
In ViewStack.as selectedChild  getter the selectedChild = -1 so it returns null,why it is setting selectedChild = -1

**Comment by aharui** [comment]
I assume you meant `selectedIndex == -1`

Does your code set selectedIndex to 0 or some other valid number on the TabNavigator?

**Comment by pashminakazi** [comment]
on Second tab it is setting selectedIndex == 1
on First tab it is setting selectedIndex == -1

**Comment by aharui** [comment]
If you set selectedIndex to -1, then selectedChild should be null.  Why would your code set selectedIndex to -1?
