### ISSUE TITLE
Datefield is setting Everydate to today's date

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#689]
setupColumnDate and setupColumnDate1 are MaskedDateField
We are setting dates like
var startDate:Date = DateField.stringToDate(setupColumnDate.text, "DD/MM/YYYY");
var endDate:Date = DateField.stringToDate(setupColumnDate1.text, "DD/MM/YYYY");

In Flex it is setting correct date to startDate and endDate but in Royale it is setting today's date on startDate and endDate 

In Flex:
![image](https://user-images.githubusercontent.com/42200979/72709808-7f43e080-3b87-11ea-8d14-5711456e8928.png)
![image](https://user-images.githubusercontent.com/42200979/72709821-836ffe00-3b87-11ea-9a04-d219914b2cf0.png)

In Royale :
![image](https://user-images.githubusercontent.com/42200979/72709838-8d91fc80-3b87-11ea-9928-f86b68e0e07d.png)
![image](https://user-images.githubusercontent.com/42200979/72709849-9256b080-3b87-11ea-960a-84a528ce5030.png)

**Comment by aharui** [comment]
DateField.stringToDate needs to be implemented.  Try uncommenting the code and replace the ResourceManager monthNames with a hard coded array for now.

**Comment by pashminakazi** [comment]
Please make this Example Functional
https://paste.apache.org/a0wcj

**Comment by aharui** [comment]
Example seems to be working after commit
e5a236330ceaa2090f2332661b41603a319d1fb8
