### ISSUE TITLE
ListBase.js:157 Uncaught TypeError: Cannot read property 'contentView' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#690]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Import from Select in Menu
Go to Import -> Import Charges from Setups in Menu
File : com/dbz/modules/IMP/dbzImportChargesSetup.mxml

on Clicking Formula ImageButton
File : com/dbz/modules/IMP/dbzImportChargesFormulaPopup.mxml will be opened
and this exception is thrown

![image](https://user-images.githubusercontent.com/42200979/72783222-b2e63f80-3c47-11ea-92f8-ede311854b98.png)
![image](https://user-images.githubusercontent.com/42200979/72783231-b974b700-3c47-11ea-9e7b-c05b76dc22ba.png)

**Comment by aharui** [comment]
What are the values of `this` and `this.view`?

**Comment by pashminakazi** [comment]
**this** is spark.components.List
**this.view** is spark.components.beads.SparkContainerView

**Comment by aharui** [comment]
In spark.components.supportClasses.ListBase.as, try changing all uses of SkinnableContainerView to SparkContainerView.

**Comment by pashminakazi** [comment]
There' some issue in New SDK.Every setup is throwing Exception Please resolve https://github.com/apache/royale-asjs/issues/706
After replacing SkinnableContainerView  to SparkContainerView with New SDK
This Exception occurs : 
![image](https://user-images.githubusercontent.com/42200979/74220534-b19db500-4cd1-11ea-9ef7-e8957fbeeda0.png)
![image](https://user-images.githubusercontent.com/42200979/74220761-43a5bd80-4cd2-11ea-9603-68ceb8a8668f.png)

After replacing SkinnableContainerView  to SparkContainerView with Old SDK everything works fine
![image](https://user-images.githubusercontent.com/42200979/74220786-515b4300-4cd2-11ea-8dbd-22a35f593aa2.png)
