### ISSUE TITLE
White space is visible if resize all records of ADG at one side

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#691]
White space is visible if resize all records of ADG at one side
In Flex if we are resizing all records at one side the last record can't be resized so the white space is not visible.

In Royale : 
![image](https://user-images.githubusercontent.com/42200979/72795585-bbe30b00-3c5f-11ea-9a1b-0a7b8cefcae9.png)

In Flex : 
![image](https://user-images.githubusercontent.com/42200979/72795585-bbe30b00-3c5f-11ea-9a1b-0a7b8cefcae9.png)

**Comment by aharui** [comment]
I don't understand what steps you took to reproduce it.  I could not reproduce it in my simple test case.  Where did you click and drag and in what order?

**Comment by pashminakazi** [comment]
Video :  simple test case vs my Setup
![ADG resize issue](https://user-images.githubusercontent.com/42200979/72867565-2f892480-3d01-11ea-9852-eb9fe3da6ce2.gif)

**Comment by pashminakazi** [comment]
I know you hate video's but for your better understanding i created video
In this video there is no issue in simple test case ADG when we resize it
but in my setup when i resize columns the area after last column is white instead of alternative row color

**Comment by aharui** [comment]
Are you sure there aren't any exceptions in the console?

**Comment by aharui** [comment]
There is custom CSS for #dgProducts that is forcing the ADG to a width that is overriding the calculations of the Royale code.  Royale does not support such custom CSS
