### ISSUE TITLE
Jewel: Tooltip - removing controls with tooltips while tooltip text is visible

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#697]
Hi,
I have a custom ListItemRender, I added a tooltip to each item:

```
<j:ListItemRenderer xmlns:fx="http://ns.adobe.com/mxml/2009" 
    xmlns:j="library://ns.apache.org/royale/jewel" 
    xmlns:js="library://ns.apache.org/royale/basic" 
    xmlns="http://www.w3.org/1999/xhtml" xmlns:mx="library://ns.apache.org/royale/mx"
    xmlns:html="library://ns.apache.org/royale/html">

    <fx:Script>
        <![CDATA[
            
            [Bindable]
            public function get label():String
            {                   
                return data.label.toString();
            }
            
            [Bindable]
            public function get image():String
            {
                return data.icon.toString();
            }
		]]>
    </fx:Script>
    <j:beads>
        <js:ItemRendererDataBinding />
        <j:ToolTip toolTip="{label}"/>
    </j:beads>

    <j:HGroup itemsHorizontalAlign="itemsCenter" width="100%" >
        <j:Image src="{image}" visible="{true}"/>
    </j:HGroup>
</j:ListItemRenderer>

```
Our list:
```
   <j:List id="testList" itemRenderer="ImageListItemRenderer"  
   dataProvider="{data}" labelField="label" change="testListChangeHandler(event)">
      <j:beads>
         <j:HorizontalLayout itemsExpand="false" itemsHorizontalAlign="itemsLeft" />
      </j:beads>
   </j:List>

```

Our event:

```
   private function testListChangeHandler(event:Event):void
   {
      data.removeItemAt(event.target.selectedIndex);
   }
```

Issue:
When deleting an item from the dataProvider while the tooltip is visible. The bead does not disappear and remains visible.

**Comment by carlosrovira** [comment]
Hi Jose,

just added a commit that will be needed to solve this issue.

The removal of the tooltip must be handled in the item renderer. You can solve using the following code in your renderer:

```as3
/**
 * listen to "itemRemoved" event dispatched from the List
 */
override public function addedToParent():void
{
    super.addedToParent();

    var view:ListView = this.itemRendererParent as ListView;
    host = view.host as List;
    IEventDispatcher(host).addEventListener("itemRemoved", handleItemRemoved);
}

/**
 * check if the renderer (item) is the current and in that case ensure remove listener and tip.
 */
protected function handleItemRemoved(event:ItemRemovedEvent):void
{
    if(event.item == this)
    {
        IEventDispatcher(host).removeEventListener("itemRemoved", handleItemRemoved);
        tt.removeTip();
    }
}
```

I'll consider to make this a bead to have this practice accesible.

**Comment by carlosrovira** [comment]
forgot to mention that `tt` is the toolTip add `localId="tt"` (or the name you prefer for the ToolTip bead in the renderer.

**Comment by javeiga-iest** [comment]
thanks for the quickness!
i will implement it to my code

> Hi Jose,
> 
> just added a commit that will be needed to solve this issue.
> 
> The removal of the tooltip must be handled in the item renderer. You can solve using the following code in your renderer:
> 
> ```actionscript-3
> /**
>  * listen to "itemRemoved" event dispatched from the List
>  */
> override public function addedToParent():void
> {
>     super.addedToParent();
> 
>     var view:ListView = this.itemRendererParent as ListView;
>     host = view.host as List;
>     IEventDispatcher(host).addEventListener("itemRemoved", handleItemRemoved);
> }
> 
> /**
>  * check if the renderer (item) is the current and in that case ensure remove listener and tip.
>  */
> protected function handleItemRemoved(event:ItemRemovedEvent):void
> {
>     if(event.item == this)
>     {
>         IEventDispatcher(host).removeEventListener("itemRemoved", handleItemRemoved);
>         tt.removeTip();
>     }
> }
> ```
> 
> I'll consider to make this a bead to have this practice accesible.

**Comment by yishayw** [comment]
> > I'll consider to make this a bead to have this practice accesible.

Definitely.

**Comment by carlosrovira** [comment]
@javeiga-iest , @yishayw, you better use the new bead `ToolTipRemovalWhenItemRemoved` instead of the custom code exposed before.
