### ISSUE TITLE
Datefield popup not closed if I again select already selected date

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#700]
In this screenshot already 21-Jan-2020 is selected when i re-select 21-Jan-2020 from calender Popup isn't closed,It should be closed

![image](https://user-images.githubusercontent.com/42200979/73341304-346c4c00-429e-11ea-804b-143b557429a8.png)

**Comment by aharui** [comment]
Is this the unmodified MX DateField or your MaskedDateField?  In my tests, the MX DateField does close.

**Comment by pashminakazi** [comment]
No, In simple test case MX Datefield doesn;t close
File: https://paste.apache.org/yf4rq
![Datefield doesn't close](https://user-images.githubusercontent.com/42200979/73425121-7fe03200-4352-11ea-9838-4fb9d3ebdd22.gif)
