### ISSUE TITLE
Our Custom File dbzResizableTitleWindow extends Spark TitleWindow is not resizable

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#701]
dbzResizableTitleWindow.as : https://paste.apache.org/xorru
dbzResizableTitleWindow is in DBIZLib
In many Setups we are using PickList_Simple which is also in DBIZLib
PickList_Simple's opening and closing tag is <controls:dbzResizableTitleWindow>
So the PickList_Simple Should be resizable.

**Comment by aharui** [comment]
What is a Setup that uses this, so I don't have to waste time guessing?

**Comment by pashminakazi** [comment]
TaxRate setup's picklist should be resizeable

**Comment by pashminakazi** [comment]
Connect VDI now

**Comment by aharui** [comment]
Where/how is the skinClass specified?

If the skinClass is specified in CSS, the following is needed in Royale (at least for now)
	IViewport: ClassReference("spark.components.beads.SparkSkinScrollingViewport");

Then we'll see if other bugs happen for TitleWindow.  Custom skins are working for Form/FormItem.

I will investigate further tomorrow.

**Comment by aharui** [comment]
I made several changes culminating in commit d8aeacf5d43f366b6646f87edfbc5937ea7be220.
Spark Panel now uses the PanelSkin so hopefully your custom skin will now work better.
