### ISSUE TITLE
RadioButton Selection depends on Spark TextInput's value

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#702]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Import from Select in Menu
Go to Import -> LC Charges from Setups in Menu
File : com/dbz/modules/IMP/dbzLCChargesSetup.mxml

there's a check for radiobutton
<s:RadioButton id="rbNone" label="None" groupName="ChargesType" selected="{(lcc_Chg_Percnttag.text == '0' ? true : false)}"  click="fn_SetChargesType();" tabIndex="16"/>

 **selected="{(lcc_Chg_Percnttag.text == '0' ? true : false)}"**  lcc_Chg_Percnttag is a spark TextInput and its value is 0 but while debugging it shows its value 1 which is wrong so the radiobutton can't be selected

**Comment by aharui** [comment]
In the LCCharges running on the VDI, the dg.selectItem has percnttag = "1".  This would normally set the radio button, but it appears the version was compiled against an old Spark TextInput so the binding isn't set up correctly.  In my local tests, the binding is set up correctly.

**Comment by aharui** [comment]
After recompiling LCCharges on the VDI, I can see that LCCharges.js has the right binding information.  I am afraid to update the test server as my past attempts have resulted in not being able to log in again.  Make sure that LCCharges is being compiled against the latest version of Spark TextInput.
