### ISSUE TITLE
dataGrid jewel issue sdk 0.9.7

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#703]
Hi,
I'm not sure if it't a bug or not :
https://stackoverflow.com/questions/59972776/apache-royale-issue-with-datagrid-jewel-on-sdk-0-9-7

Could I have some help on this ?
Regards

**Comment by carlosrovira** [comment]
Hi Fred ,solved in SOF :)

**Comment by cristallium** [comment]
Hi Carlos,
Many thanks for your quick reply  (... and sorry for this idiot mistake I made ...)
I can now try your great work !
Regards
