### ISSUE TITLE
Panel Overlapped after downloading new SDK

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#706]
I have downloaded SDK on 28-Jan-2020 Everything was working fine
![image](https://user-images.githubusercontent.com/42200979/73648023-7df1d800-469e-11ea-811a-cac5fccf2eea.png)

Today i downloaded new SDK and layout is overlapped
BorderContainer is overlapped on Panel.
Panel is hidden as BorderContainer overlapped it.

**Comment by aharui** [comment]
My investigation showed that the Setup shown above was not re-compiled and was therefore using a mix of old and new code.  I recompiled the setup and the output .js file looks correct, but on the VDI I am now not able to login and do further testing.

This was essentially not a good use of my time.  Please verify that the code you use is all the latest before filing bugs.

**Comment by pashminakazi** [comment]
All setups are compiled with new SDK

**Comment by aharui** [comment]
On the VDI, they weren't compiled with the latest setup since CompanySetup was commented out of the build script, and thus the CompanySetup did not work correctly as a result.

I went and uncommented CompanySetup and re-compiled it and it appeared to have the right output, but then I could not log into the application on the VDI.

If you can get CompanySetup to show up on the VDI and it looks wrong, verify that the dbzCompanySetup.js file's data for spark.components.Panel specifies a skinClass.  I think you can search for 'skinClass' in dbzCompanySetup.js.

**Comment by pashminakazi** [comment]
I am working locally because VDI is having issue.
CompanySetup is compiled with new SDK and dbzCompanySetup.js includes
this["skinClass"] = spark.skins.spark.PanelSkin},
dbzCompanySetup.js : https://paste.apache.org/s7wlw
But still issue in Panel.
![image](https://user-images.githubusercontent.com/42200979/73717589-15f1cf00-473c-11ea-842c-87c2bded2f4e.png)

**Comment by aharui** [comment]
In the debugger, verify that the dbzCompanySetup.js actually loaded by the browser contains the `this["skinClass"] = spark.skins.spark.PanelSkin` code.

Then if so, from the debugger console, see what
`document.getElementsByClassName("Panel")[0].royale_wrapper.skin` evaluates to and post a screenshot of the DOM under the Panel.

On the VDI, the skin was null because it was running old code

**Comment by pashminakazi** [comment]
I have compiled CompanySetup on my local machine
Exception in CompanySetup after compiling it with new SDK
TypeError: Cannot read property 'dispatchEvent' of null                       (Panel.js)
![image](https://user-images.githubusercontent.com/42200979/74148521-734bbb80-4c27-11ea-95a6-807180c13965.png)
![image](https://user-images.githubusercontent.com/42200979/74148522-747ce880-4c27-11ea-9db0-915c5c52a32a.png)


after executing document.getElementsByClassName("Panel")[0].royale_wrapper.skin in Console
![image](https://user-images.githubusercontent.com/42200979/74148644-c1f95580-4c27-11ea-9cdf-02044e3a31f7.png)

**Comment by aharui** [comment]
Something is still out-of-date on your system.  PanelView is no longer the view for Panel.

**Comment by pashminakazi** [comment]
There' some issue in New SDK.Every setup is throwing Exception Please resolve this issue.
Everything is up to date on VDI and Everything is compiled with new SDK.

After replacing SkinnableContainerView  to SparkContainerView with New SDK
This Exception occurs : 
![image](https://user-images.githubusercontent.com/42200979/74220534-b19db500-4cd1-11ea-9ef7-e8957fbeeda0.png)
![image](https://user-images.githubusercontent.com/42200979/74220761-43a5bd80-4cd2-11ea-9603-68ceb8a8668f.png)

After replacing SkinnableContainerView  to SparkContainerView with Old SDK everything works fine
![image](https://user-images.githubusercontent.com/42200979/74220786-515b4300-4cd2-11ea-8dbd-22a35f593aa2.png)

**Comment by aharui** [comment]
PanelView should not be used if you are set up correctly

**Comment by pashminakazi** [comment]
Please check on VDI when you have time

**Comment by pashminakazi** [comment]
I think the issue is because of this commit : support custom skins in Spark Containers
After this commit it downloaded new sdk and issue occurs.please have a look at issues on VDI

**Comment by aharui** [comment]
Well, yes, that change should have cause PanelView to not be used anymore.  For some reason it is still being used which would cause a problem.  The most likely reason is that some code is not updated.  The VDI no longer has a valid Git repo so I cannot verify the source code.

I tried to use the VDI.  Company Setup looked like it worked.  Then I think somebody else started using the VDI.  I will stop using it.

**Comment by pashminakazi** [comment]
Please connect the VDI,I have connected VDI for just a while.VDI is free now

**Comment by aharui** [comment]
TitleWindowSkin needs to replace TitleWindowView.  Apparently the recent issues are not reported against Company Setup but against a TitleWindow-based popup.  These are important details that should be reported instead of having to search the source code and interpret screenshots.

**Comment by pashminakazi** [comment]
In which file TitleWindowSkin needs to replace with TitleWindowView?

**Comment by aharui** [comment]
That's a note to myself.  I put notes from my investigations on the VDI in these issues before working on them in case the VDI stops working.  There are other changes that need to be made as well.  You can make changes for DateBase and look at NumberFormatter precision issues.

**Comment by pashminakazi** [comment]
What to change in NumberFormatter Precision Function? 
 public function set precision(value:Object):void
        {
            //precisionOverride = value;

            _precision = value != null ?
                         int(value) : int(value)
                        /* resourceManager.getInt(
                             "formatters", "numberFormatterPrecision") */ ;
        }

**Comment by pashminakazi** [comment]
![image](https://user-images.githubusercontent.com/42200979/74514831-346f7b80-4f2f-11ea-990f-037fc87b96af.png)
![image](https://user-images.githubusercontent.com/42200979/74514869-451ff180-4f2f-11ea-8bde-98eb43f54387.png)
These exception on Every Setup and PanelTitleBar is hidden in Every Setup

**Comment by aharui** [comment]
I will need the VDI to work properly to investigate.

**Comment by pashminakazi** [comment]
latest SDK is available on VDI using git clone and all library's and setups related to issues are compiled with new SDK,you can use VDI now

**Comment by aharui** [comment]
When I logged into the VDI, the Company Setup was visible and looked fine.  Will need more explicit steps to reproduce any issues.

**Comment by aharui** [comment]
Panels in Retail Inspection/Particulars Setup, and PickList_Discrete appear correct.  Will need explicit steps to reproduce any issues.
