### ISSUE TITLE
Issue in Populating ADG data for first time in Detail Grid

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#709]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to ATM Rental Income from Setups in Menu
File : com/dbz/modules/AR/dbzATMRentalReceipt.mxml

When i open this setup exception is thrown
![image](https://user-images.githubusercontent.com/42200979/74137639-fd892500-4c11-11ea-81ad-c9bb918dcf31.png)

in this setup all 3 records of ADG has also records in Detail Grid but when i open this setup 1st record of ADG is selected nothing in Detail grid is shown
![image](https://user-images.githubusercontent.com/42200979/74137668-0843ba00-4c12-11ea-93fd-164dbc5a1778.png)

after that i click on 2nd record and then click on 1st record of ADG now detail grid records are shown
![image](https://user-images.githubusercontent.com/42200979/74137922-7b4d3080-4c12-11ea-86a5-35ea544d44b1.png)

**Comment by aharui** [comment]
Variables in DateBase.as need to have an initial value.  You should be able to do this yourself.

Look for variables such as:
private static var _dayNamesShort:Array;

The ASDoc should tell you the initial value where it says @default.

Variables with "override" in the name do not need to have an initial value.

**Comment by pashminakazi** [comment]
I have added default values for _monthNamesShort and _dayNamesShort 
DateBase.js :
mx.formatters.DateBase._monthNamesShort = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

Still same exception is thrown

**Comment by aharui** [comment]
Debug into it to verify that the browser loaded the code with these changes.

**Comment by pashminakazi** [comment]
Yes,Browser loaded the code with these changes : 
![image](https://user-images.githubusercontent.com/42200979/74259091-2516e500-4d19-11ea-9747-3898de36f3f7.png)
Still same exception.Please check on VDI and resolve this issue

**Comment by aharui** [comment]
Someone seemed to be using the VDI and logged me out.  So I will not take the time to investigate your issues until you can tell me that people are done using the VDI. 

 If you verified the new code and debugged into the new code, why did you get the same exception?  Why is the value null?

**Comment by pashminakazi** [comment]
I was logged into VDI to send you screenshot of latest code.i do not logged into VDI now.

**Comment by pashminakazi** [comment]
I dnt know why i am getting the same exception.

**Comment by aharui** [comment]
The app on the VDI cannot login.  So I cannot investigate further.  

When you debugged into the latest code, what did you see?  Was the variable initialized?  If so, why couldn't it be read?

**Comment by aharui** [comment]
I didn't see earlier that there is a static initializer function in DateBase, so instead of initializing
monthNamesShort, try initializing monthNamesShortOverride, and similar for the other variables.

**Comment by pashminakazi** [comment]
@aharui Thanks issue resolved
