### ISSUE TITLE
TypeError : Cannot read property 'positioner' of null (UIBase.js)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#710]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to General Ledger from Select in Menu
Go to Voucher Type from Setups in Menu
File : com/dbz/modules/GL/dbzVoucherTypeSetup.mxml

![image](https://user-images.githubusercontent.com/42200979/74141455-c10cf780-4c18-11ea-8b71-68ddaf385757.png)

**Comment by aharui** [comment]
Same as #681

**Comment by aharui** [comment]
This should work now with the "has" branch changes.
