### ISSUE TITLE
RadioButton Behaviour is not same as flex

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#711]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Import from Select in Menu
Go to Import -> LC Charges from Setups in Menu
File : com/dbz/modules/IMP/dbzLCChargesSetup.mxml

There's 3 radioButton in dbzLCChargesSetup
Percentage
Amount
None
On selection of any RadioButton function is called fn_SetChargesType.
In this function there is a check for all radioButtons.
By default None is selected.when i select Percentage or Amount RadioButton,then if part of None radiobutton is executed which is wrong,then i have to again select Percentage  or Amount RadioButton then the right part is executed.
Please help

**Comment by pashminakazi** [comment]
for 1st time it works but for 2nd time it doesn't work
when I open the setup by default None radiobutton is selected both textfield should be disabled and it is working fine
![image](https://user-images.githubusercontent.com/42200979/74216975-de4ccf00-4cc7-11ea-9f45-537c37125f81.png)
when I Select Amount radiobutton,Amount textfield should be enabled and percentage textfield should be disabled and it is working fine
![image](https://user-images.githubusercontent.com/42200979/74217021-0e946d80-4cc8-11ea-9952-3071b3c5f28d.png)
when I Select Percentage radiobutton,Percentage textfield should be enabled and Amount textfield should be disabled and it is working fine
![image](https://user-images.githubusercontent.com/42200979/74217032-1b18c600-4cc8-11ea-82a3-6c4fdd60ec7d.png)

but now if i select any of them None,Percentage or Amount Everytime system is assuming that Percentage radioButton is Selected.
![image](https://user-images.githubusercontent.com/42200979/74217086-50251880-4cc8-11ea-85f6-b5bde26583bd.png)

**Comment by pashminakazi** [comment]
Still same issue

**Comment by aharui** [comment]
Did you verify that the browser is running the latest code?

**Comment by pashminakazi** [comment]
Yes,browser is running the latest code
RadioButton.js : ![image](https://user-images.githubusercontent.com/42200979/74259425-ad958580-4d19-11ea-8362-1cd35c6fb181.png)

Still issue in radiobutton

**Comment by aharui** [comment]
Each RadioButton seems to be getting a separate Group.

**Comment by pashminakazi** [comment]
@aharui Thanks issue resolved
