### ISSUE TITLE
PickList is having same record on both sides

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#712]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Retail Inspection from Select in Menu
Go to Particulars Setup from Setups in Menu
File : com/dbz/modules/RI/dbzParticularsSetup.mxml

When i open Conditions PickList,Active radioButton is selected but there is no record in Picklist
![image](https://user-images.githubusercontent.com/42200979/74215012-6f6c7780-4cc1-11ea-90bf-8a642b15ac1d.png)
then i have to select All radio button and then Active so the records are shown in Picklist.
![image](https://user-images.githubusercontent.com/42200979/74215013-6f6c7780-4cc1-11ea-9739-dc01d3d67a1f.png)

Other issue is that
if i double click on 00003 code from left side and it is removed from left side and added into right side and then my Cursor is on 00004 Code now then i double Click on 00004 but the Code added on right side is 00003 not 00004 and 00004 is not removed from right side.There should be only one occurrence of Every Code on left or right side
For better understanding i am sending a video
![List of picklist](https://user-images.githubusercontent.com/42200979/74215304-73e56000-4cc2-11ea-85e8-fefc046b3c65.gif)

**Comment by aharui** [comment]
Verify RadioButtonGroup.selectedValue is properly set on init.

**Comment by aharui** [comment]
Verify selectedIndex/Item after remove item

**Comment by aharui** [comment]
RBG selectedValue was not responding to programmatically setting RB.selected=true.  This is fixed in commit 44a084f4439d353179c88f537a1cd59d13275476

**Comment by pashminakazi** [comment]
Still issue RadioButtonGroup.selectedValue is null when by default Active radioButton is selected.

**Comment by pashminakazi** [comment]
ADG.selectedIndex is same
Example : double click on 3rd row of ADG it will be removed from left side grid and added to the right side grid,On left side grid its selectedIndex was 2,after removal of that element from left side grid another element will take place on 2nd index,but it should change the selectedItem.
it is not changing the selectedItem.

**Comment by aharui** [comment]
I didn't fix ADG.selectedIndex earlier.  This really should have been filed as two separate issues.

ADG.selectedIndex should be fixed in 7ad6a08caf5c678ac0580531c1bb360e31608c5b
I found out the radio button issue is about MX RadioButton and that should now be fixed in 6cc82c4fac3ba353ce14c8f12373ba05f121c639

**Comment by pashminakazi** [comment]
@aharui Thanks now RadioButton issue is resolved but ADG.selectedItem is not changing,

**Comment by pashminakazi** [comment]
And after change in RadioButtonGroup every Picklist with radiobutton is overlapped like :
![image](https://user-images.githubusercontent.com/42200979/74594201-3d5a6d00-5055-11ea-8a8c-960a88bacd71.png)

**Comment by aharui** [comment]
On the VDI, the Retail Inspection is not in the Select menu so I cannot investigate further.

Did you verify that there were no exceptions thrown?

**Comment by pashminakazi** [comment]
When some module is not shown in menu please select sales or inventory
module then all modules will be shown in menu

**Comment by aharui** [comment]
The VDI is not working again.  I can't log in.  I tried Sales earlier and it did not add Retail Inspection.  I will try Inventory when the VDI is working again.  I probably won't have time to work tomorrow until about 4pm US west coast.

**Comment by pashminakazi** [comment]
VDI is working Now

**Comment by aharui** [comment]
Your code is relying on ADG.selectedItems, not selectedItem.

**Comment by aharui** [comment]
Flex seems to set selectedIndex to -1 when the selectedItem is removed, so I have emulated that. The ADG should then show nothing selected

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved
