### ISSUE TITLE
Conversion of Numbers to Decimal is not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#713]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Import from Select in Menu
Go to Product -> Unit Rates from Setups in Menu
File : com/dbz/modules/Common/dbzUnitRateSetup.mxml

In Flex :
![image](https://user-images.githubusercontent.com/42200979/74217932-ae52fb00-4cca-11ea-850d-264379f3ac30.png)
In Royale
![image](https://user-images.githubusercontent.com/42200979/74217940-b14deb80-4cca-11ea-9ff9-1b6ffb7e02fb.png)

**Comment by aharui** [comment]
Which Flex/Royale components are involved?

**Comment by pashminakazi** [comment]
On Clicking Convert Button fn_TestConversion function called
```
protected function fn_TestConversion(event:MouseEvent):void
			{
				if( txtFrom.text=="")
				{
					Alert.show("You have specified an invalid 'From Unit' in Test Conversion.");
					return;
				}
				var responder9:Responder = new Responder(fn_roListRH,fn_HandleFault);
 			 var token9:AsyncToken =roConvert.fn_EvaluteExpression(ur_functionname.text, txtFrom.text,ur_defaultvalue.text, Number(ur_roundfactor.text) );
			 token9.addResponder(responder9);
 			 trace(token9); 

				
			}
			
```
This function is calling a java function
```
public static String fn_EvaluteExpression(String Expression, String Value, String DValue, int RoundTo)
	{
		String lsReturn = DValue;
		try{

			ScriptEngineManager mgr = new ScriptEngineManager();
			ScriptEngine engine = mgr.getEngineByName("JavaScript");
			Expression = Expression.replaceAll("X", Value);
			Expression = Expression.replaceAll("x", Value);
			String foo = Expression;
			double ldVal = fn_RoundDecimal(Double.parseDouble((engine.eval(foo).toString())), RoundTo);
			lsReturn = String.valueOf(ldVal);
		}
		catch (Exception e) {}
		return lsReturn;
	}
	
ResultHandler : ```
private function fn_roListRH(e:ResultEvent):void {
				
				var Value:String = e.result as String;
				txtToUnit.text = Value;
			}
```

Java Function :

```

**Comment by pashminakazi** [comment]
txtFrom is TextInput which is one of the parameter passing to Java function
while passing it is sending only 3 instead of 3.000 to java function.
<s:TextInput x="129" y="18.5" width="94" height="22" valueCommit="txtFrom_valueCommitHandler(event)" enabled="true" id="txtFrom" tabIndex="6" restrict="0-9."/>

valueCommit :
```
protected function txtFrom_valueCommitHandler(event:FlexEvent):void
			{
				txtFrom.text = fmtNumber1.format(txtFrom.text);
			}
```
<mx:NumberFormatter id="fmtNumber1" decimalSeparatorFrom="." decimalSeparatorTo="." precision="3"
							rounding="nearest" thousandsSeparatorFrom="," thousandsSeparatorTo="," 	useNegativeSign="true"
							useThousandsSeparator="true"/>

**Comment by pashminakazi** [comment]
mx:NumberFormatter is involved in Flex/Royale

**Comment by pashminakazi** [comment]
mx:NumberFormatter precision is not working correctly

**Comment by pashminakazi** [comment]
What to change in NumberFormatter Precision Function?

public function set precision(value:Object):void
       {
           //precisionOverride = value;

           _precision = value != null ?
                        int(value) : int(value)
                       /* resourceManager.getInt(
                            "formatters", "numberFormatterPrecision") */ ;
       }
