### ISSUE TITLE
RangeError: null         (ArrayList.js)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#714]
![image](https://user-images.githubusercontent.com/42200979/74323789-e11ef100-4da7-11ea-8c2a-1be0433beacf.png)

**Comment by aharui** [comment]
If you want my help, you have to help me help you.  If I have to spend time trying to figure out how to reproduce a problem in your application, then I won't be able to help as quickly.

I just spent several minutes trying to figure out how to get to this screen and cannot figure it out, and thus you will have to wait another work day for any further investigation from me.

**Comment by pashminakazi** [comment]
Sorry,
Check another issue for now,i will send details of this issue later

**Comment by pashminakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to General Ledger from Select in Menu
Go to Reccuring Voucher from GL in Menu
File : com/dbz/modules/GL/dbzRecurringSetup.mxml

I am sending you video of issue for better understanding
![RangeError](https://user-images.githubusercontent.com/42200979/74416724-5ef60180-4e67-11ea-8b1f-51d8f773c100.gif)

**Comment by aharui** [comment]
Please, no more videos.  There is a known issue with custom item renderers.  If these scenarios involve custom item renderers you do not need to file separate issues for them.

**Comment by aharui** [comment]
Should be fixed with "has" branch changes
