### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined   (base.js)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#715]
![image](https://user-images.githubusercontent.com/42200979/74325339-3d831000-4daa-11ea-837b-ad352ada90f5.png)
![image](https://user-images.githubusercontent.com/42200979/74325346-407e0080-4daa-11ea-9009-32380afb79f8.png)

**Comment by aharui** [comment]
Not enough information.  It is your responsibility to provide enough information for me to reproduce this problem.  It is not a good use of my time to search your source code to try to figure out how to get to this screen.

**Comment by pashminakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to PSSM -> Facility from Setups in Menu
File : com/dbz/modules/Common/dbzFacilityMaster.mxml

when i open this setup,Exception occurs and setup doesn't open
![image](https://user-images.githubusercontent.com/42200979/74821168-015d2b80-5325-11ea-9754-943649d226ca.png)
![image](https://user-images.githubusercontent.com/42200979/74821218-15a12880-5325-11ea-8617-c34eb7a0d4fe.png)

**Comment by aharui** [comment]
The compiler is not generating the right code for labelFunction="SetupList.fn_SomeFunction".  I've opened royale-compiler#119 to track it.

As a workaround, create a local function that calls SetupList.fn_SomeFunction.

**Comment by pashminakazi** [comment]
<mx:AdvancedDataGridColumn dataField="setupDetailColumn3" headerText="Product Code" width="165" labelFunction="CallingSetupFunction"/>

```
public function CallingSetupFunction():void {
	SetupList.fn_FormatProductGrid();
}
```
Error: Incorrect number of arguments.  Expected 2

```
public function fn_FormatProductGrid( item:Object, column:AdvancedDataGridColumn):String {
				if (item[column.dataField] == null)
					return item[column.dataField];
				else
					return dbzUtil.formatInputVal(item[column.dataField], arrProductFormat[1], arrProductFormat[0], arrProductFormat[2]); 
			}
```
What arguments should be passed to fn_FormatProductGrid?

**Comment by aharui** [comment]
Both arguments.  CallingSetupFunction should have the same parameters as fn_FormatProductGrid and pass those parameters to fn_FormatProductGrid

**Comment by pashminakazi** [comment]
i have created a local function :
```
public function CallingSetupFunction(item:Object, column:AdvancedDataGridColumn):void {
			    SetupList.fn_FormatProductGrid(item,column);
			}
```
<mx:AdvancedDataGridColumn dataField="setupDetailColumn3" headerText="Product Code" width="165" labelFunction="CallingSetupFunction"/>
labelFunction="SetupList.fn_FormatProductGrid" is replaced with  labelFunction="CallingSetupFunction" 
setuplist.fn_FormatProductGrid is called from local function but it doesn't work as it should work as a labelfunction

and if i call SetupList.fn_FormatProductGrid directly from labelfunction then this exception occurs
![image](https://user-images.githubusercontent.com/42200979/80962614-c4cea580-8e26-11ea-9228-d4a13e85e09b.png)

![image](https://user-images.githubusercontent.com/42200979/80962625-cac48680-8e26-11ea-8b64-fbcf8af7a6d9.png)

![image](https://user-images.githubusercontent.com/42200979/80962634-d021d100-8e26-11ea-9c80-8957c5eb940e.png)


Why this.Setuplist is undefined when i am calling this.SetupList.fn_FormatProductGrid as labelfunction ?

**Comment by pashminakazi** [comment]
<mx:AdvancedDataGridColumn dataField="setupDetailColumn3" headerText="Product Code" width="165" labelFunction="CallingSetupFunction"/>
labelFunction="SetupList.fn_FormatProductGrid" is replaced with labelFunction="CallingSetupFunction"
setuplist.fn_FormatProductGrid is called from local function but it doesn't work as it should work as a labelfunction

**Comment by aharui** [comment]
Is CallingSetupFunction called with the correct parameters?  Set a breakpoint and debug into it.  Make sure it returns the value from SetupList.fn_FormatProductGrid.

If you want, post the code for CallingSetupFunction.

**Comment by pashminakazi** [comment]
In **dbzSetupList**
```
public function fn_FormatProductGrid( item:Object, column:AdvancedDataGridColumn):String {
    if (item[column.dataField] == null)
	return item[column.dataField];
    else
        return dbzUtil.formatInputVal(item[column.dataField], arrProductFormat[1], arrProductFormat[0],arrProductFormat[2]); 
}
```
In `dbzFacilityMaster`
```
public function CallingSetupFunction(item:Object, column:AdvancedDataGridColumn):void {
	 SetupList.fn_FormatProductGrid(item,column);
}
```
`<mx:AdvancedDataGridColumn dataField="setupDetailColumn3" headerText="Product Code" width="165" labelFunction="CallingSetupFunction"/>  `
 
labelFunction="SetupList.fn_FormatProductGrid" replaced with labelFunction="CallingSetupFunction" as a royale workaround

CallingSetupFunction Called
![image](https://user-images.githubusercontent.com/42200979/84744698-04171700-afcd-11ea-81ab-9a16b8360abb.png)
![image](https://user-images.githubusercontent.com/42200979/84744745-12653300-afcd-11ea-91dc-e43c4b1caf1a.png)

CallingSetupFunction Called SetupList.fn_FormatProductGrid
![image](https://user-images.githubusercontent.com/42200979/84744811-24df6c80-afcd-11ea-864c-8e0824dacf5c.png)
![image](https://user-images.githubusercontent.com/42200979/84744928-4f312a00-afcd-11ea-84ca-82667d66748d.png)

SetupList.fn_FormatProductGrid Called dbzUtil.formatInputVal

 dbzUtil.formatInputVal returns
![image](https://user-images.githubusercontent.com/42200979/84745056-74be3380-afcd-11ea-88d7-0dc27d0604ac.png)


Product Code
![image](https://user-images.githubusercontent.com/42200979/84745264-c5359100-afcd-11ea-875b-ae037aa99de6.png)

**Comment by aharui** [comment]
CallingSetupFunction is a LabelFunction so it must return a String.  It can't be a `void`

**Comment by pashminakazi** [comment]
@aharui Thank u so much,Issue has been resolved by replacing **void** return type **String**
