### ISSUE TITLE
If any File is compiled with new SDK which is using ViewStack

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#717]
Internal error: java.lang.IllegalArgumentException: Multiple entries with same value: VS=VS and get__borderRightPriority=VS com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)com.google.common.collect.JdkBackedImmutableBiMap.create(JdkBackedImmutableBiMap.java:45)com.google.common.collect.RegularImmutableBiMap.fromEntryArray(RegularImmutableBiMap.java:92)com.google.common.collect.RegularImmutableBiMap.fromEntries(RegularImmutableBiMap.java:58)com.google.common.collect.ImmutableBiMap.copyOf(ImmutableBiMap.java:368)com.google.common.collect.ImmutableBiMap.copyOf(ImmutableBiMap.java:340)com.google.javascript.jscomp.VariableMap.<init>(VariableMap.java:49)com.google.javascript.jscomp.VariableMap.fromMap(VariableMap.java:205)org.apache.royale.compiler.utils.JSClosureCompilerWrapper.compile(JSClosureCompilerWrapper.java:187)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:574)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:446)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:267)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:224)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:371)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:306)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:264)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:246)

**Comment by aharui** [comment]
rename the "VS" id to something longer
