### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispatchEvent' of null (Panel.js:56)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#718]
After downloading new SDK today on my local machine every setup is having no data because of this exception
![image](https://user-images.githubusercontent.com/42200979/74636575-1b163b80-518a-11ea-97c5-9d1972b8ca93.png)
![image](https://user-images.githubusercontent.com/42200979/74636659-4436cc00-518a-11ea-8fef-bdb5db47e3ce.png)

Picklist is having no data because of this exception
![image](https://user-images.githubusercontent.com/42200979/74636583-1f425900-518a-11ea-8720-d037cd8d6e95.png)

![image](https://user-images.githubusercontent.com/42200979/74636594-26696700-518a-11ea-96d6-60ccf38d940f.png)

Picklist is having no data because of this exception

![image](https://user-images.githubusercontent.com/42200979/74636762-7b0ce200-518a-11ea-8730-ab5dfabc5e5c.png)

**Comment by pashminakazi** [comment]
![image](https://user-images.githubusercontent.com/42200979/74928000-78182880-53fa-11ea-9087-e5c9399fdb26.png)
![image](https://user-images.githubusercontent.com/42200979/74928014-7ea6a000-53fa-11ea-9473-0f2a0cb974dd.png)
![image](https://user-images.githubusercontent.com/42200979/74928024-8403ea80-53fa-11ea-97ee-0e6ed592ecfb.png)

**Comment by aharui** [comment]
I see Panels in Retail Inspection and PickList_Discrete are working.  If there is some other scenario were Panels are not working, provide explicit steps to reproduce.

**Comment by pashminakazi** [comment]
This issue still occurs with new SDK on my local machine
![image](https://user-images.githubusercontent.com/42200979/75011060-7d2fb300-54a0-11ea-9c33-2a4521f407f5.png)
On my local machine sdk is git repo and build doesn't failed.
On VDI whenever i git repo SDK and compile the royale-compiler build failed because it can't download 
E:\apache-royale-0.9.3-bin-js-swf\royale-compiler\compiler-externc\target\downloads\es5.js
E:\apache-royale-0.9.3-bin-js-swf\royale-compiler\compiler-externc\target\downloads\es6_collections.js
E:\apache-royale-0.9.3-bin-js-swf\royale-compiler\compiler-externc\target\downloads\browser\html5.js and 2 3 more dependencies
So i have to copied these from old sdk and paste into latest sdk
and then compiler compiled successfully

**Comment by pashminakazi** [comment]
now i will check this issue on VDI by copying this SDK on VDI and compile library and setups,and then if this issue occurs on VDI as well.then its a issue of SDK
