### ISSUE TITLE
TextInput should be disabled or enabled on Dropdown selection

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#720]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Purchase from Select in Menu
Go to Products -> Rates - Date Wise from Setups in Menu
File : com/dbz/modules/PUR/dbzDateWisePrdRateSetup.mxml

When we select General from dropdownlist,5 textfield should be disabled which is on the top of dropdownlist.
Its working fine if i select general from dropdownlist again,but General is selected by default so it is not working for the first time 

First time when opened this setup :
![image](https://user-images.githubusercontent.com/42200979/74647952-7520fc00-519e-11ea-88c1-c0d7a0fb834a.png)

After selecting General from dropdownlist again : 
![image](https://user-images.githubusercontent.com/42200979/74647981-8538db80-519e-11ea-85bd-572c3d8d9a6c.png)

**Comment by aharui** [comment]
This scenario also appears to be relying on the valueCommit event.  Try using creationComplete instead for the initial setup.  There appears to be a "change" handler for when the value actually changes.
