### ISSUE TITLE
MaskedTextInput inputMask is working after pressing any key on TextField

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#721]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Misc -> Oracle Integration from Setups in Menu
File : com/dbz/modules/Common/dbzOraIntConfigSetup.mxml

In the second tab "Account Code" there are 13 fields in this tab.All fields are MaskedTextInput like 
`<cc:MaskedTextInput id="setupColumn8" width="360" tabIndex="10" x="194" y="97" maxChars="80" inputMask="###-###-###-###-####-######-#######-###-#####-##-####" />`
these all fields are having input mask and these fields should be look like :
![image](https://user-images.githubusercontent.com/42200979/74813892-e7691c00-5317-11ea-8435-2597676c8bf5.png)

but Royale is showing all fields blank
![image](https://user-images.githubusercontent.com/42200979/74813917-f780fb80-5317-11ea-98b6-35a1a5531e55.png)

so when i save a record,An exception thrown on java side and record doesn't saved.
When i click on any field and press **any key from keyboard** then it will look like flex MaskedTextInput,but it should look like flex by default,not on Clicking field and pressing any key

After clicking on 2 fields and press any button from keyboard,it looks like flex
![image](https://user-images.githubusercontent.com/42200979/74814259-b0473a80-5318-11ea-85c9-f1a26f667973.png)

**Comment by aharui** [comment]
I went to that screen and it had the dashes in the correct places.

**Comment by pashminakazi** [comment]
Check now,record was saved,now i delete the record from this setup now every field is blank and Account Code tab fields should have - - - - - - instead of blank

**Comment by aharui** [comment]
I am not clear on how to reproduce the problem.  What record are you referencing?  That sounds different from the original problem which was about initialization.

Please provide a better explanation of the steps involved.  I will try it some other day.

**Comment by pashminakazi** [comment]
You do not have to do something..
only open this setup on VDi and see the problem.

**Comment by aharui** [comment]
I will connect to the VDI, but seeing the problem isn't always helpful.  I usually need to know what code ran that resulted in the problem in order to determine what code is not working properly.

**Comment by aharui** [comment]
The VDI is not at this screen.  It is the Voucher screen.  I am disconnecting and will try again tomorrow if you can provide a set of steps to reproduce the problem.

**Comment by pashminakazi** [comment]
In this setup there is only one record can be saved because there's no new
and delete button in this setup.
In VDI when you open this setup record was already saved so the field were
- - - - - - - - - -
now i delete this record from database and now everything is blank,so now
you can test this issue.
In Flex, If there is no record in this setup but still "Account Code" tab
fields have - - - - by default
In Royale,there is blank field so when i save record with these blank field
record couldn't be saved and then i have to click on these field and press
any key from keyboard to produce - - - - - - - in these records and then
record saved

**Comment by aharui** [comment]
Most of the MaskedTextInputs have their updateDisplayList called because the init code sets text.  No text seems to be set on these MaskedTextInputs.  You could try calling updateDisplayList instead of invalidateDisplayList in the inputMask setter, or maybe override addedToParent() and call it there.

**Comment by pashminakazi** [comment]
I have tried adding
```
override public function addedToParent():void
{
    super.addedToParent();
    updateDisplayList(width,height);
}
``` 
at the same time calling invalidateDisplayList() from set inputMask and also without invalidateDisplayList()

OR

```
override public function addedToParent():void
{
    updateDisplayList(width,height);
}

```
at the same time calling invalidateDisplayList() from set inputMask and also without invalidateDisplayList()

But it doesn't work

**Comment by aharui** [comment]
Calling updateDisplayList from "set inputMask" clearly caused a problem, so I would not do that.

You must call the super.addedToParent or else lots of things will not work.

I can't tell if you tried that combination or not.  It is best to only change one thing at a time.
