### ISSUE TITLE
mx:List valueCommit function is not being triggered

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#722]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Incentive Scheme from Setups in Menu
File : com/dbz/modules/SAL/dbzIncentiveSchemeSetup.mxml

In Incentive scheme setup there's a **mx:List** right after **Exclude Customer Label**
When you click on it and select any record from picklist and click ok nothing will be shown in mx:List because valueCommit of mx:list isn't triggered.
```
<mx:List id="inc_Cust_DescList"  x="209" y="408"  showDataTips="true" rowCount="10" width="386" 
					 rowHeight="15" enabled="true" editable="false" visible="false" valueCommit="fn_SetDesc();" height="81"/> 
```
```
private function fn_SetDesc():void{
				inc_Cust_Desc.text="";
				for(var j:int = 0; j < inc_Cust_DescList.dataProvider.length; j++){
					inc_Cust_Desc.text+=inc_Cust_DescList.dataProvider[j]+ "\r" ;
					
				}
			}
```
I am posting a small video here for better understanding that you can see the steps and the function call,valueCommit function is not called in royale :
![list valuecommit](https://user-images.githubusercontent.com/42200979/74822447-f4d9d280-5326-11ea-9269-dae54a5f2e6c.gif)

**Comment by aharui** [comment]
valueCommit is not a public event.  Use "change" event instead

**Comment by pashminakazi** [comment]
In Flex,valueCommit is working for mx:List

**Comment by aharui** [comment]
Of course it worked in Flex, but we are not going to emulate 100% of Flex.  Internal, undocumented events and APIs are a low priority for emulation, especially if there is an alternative.
