### ISSUE TITLE
System should scroll automatically to the last added record in ADG

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#723]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Debit/Credit Note Type from Setups in Menu
File : com/dbz/modules/PUR/dbzDebitCrdtSetup.mxml

System should scroll automatically to the last added record in ADG,
Example : I have added latest record with 56 Code now Scroller is on the top and this record is on bottom.So i have scroll down to see this record.
![image](https://user-images.githubusercontent.com/42200979/74823170-1d160100-5328-11ea-8c90-24165e33b3ae.png)

Scroller should scroll down automatically to this record like : 
![image](https://user-images.githubusercontent.com/42200979/74823219-3028d100-5328-11ea-92f2-570c4b25065e.png)

**Comment by aharui** [comment]
Flex ADG does not appear to scroll to a new item.  I didn't see anything in your code that would either, but I did find that ADG didn't support scrollToIndex which is used in other Setups, so I implemented that.

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved
