### ISSUE TITLE
Uncaught TypeError: Cannot read property 'measuringElement' of null  (UITextFormat.js:271)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#728]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Misc -> Oracle Integration from Setups in Menu
File : com/dbz/modules/Common/dbzOraIntConfigSetup.mxml

![image](https://user-images.githubusercontent.com/42200979/75111350-a6943e80-565a-11ea-9e31-3f375d120d49.png)
![image](https://user-images.githubusercontent.com/42200979/75111358-af851000-565a-11ea-81f6-d0ecd53cda6a.png)

I compiled this setup with new sdk on my local machine and this exception occurs and setup is looking like  :
![image](https://user-images.githubusercontent.com/42200979/75111386-e9eead00-565a-11ea-97a3-5f3d2fdb033f.png)

**Comment by pashminakazi** [comment]
after adding updateDisplayList(width,height); instead of invalidateDisplayList(); in MaskedTextInput's inputmask setter this exception occurs,when i revert MaskedTextInput and compile this setup again it looks fine but still same issue - - - -  is not visible in Account Code fields
![image](https://user-images.githubusercontent.com/42200979/75111567-40f58180-565d-11ea-85d1-550ef971c02a.png)

**Comment by pashminakazi** [comment]
I am sending you runtime changes in MaskedTextInput.js file :
when using invalidateDisplayList() in InputMask Setter : 

CompanySetup : 
![image](https://user-images.githubusercontent.com/42200979/75111651-2f60a980-565e-11ea-8622-11180315db4a.png)

Oracle Integration Setup : 
![image](https://user-images.githubusercontent.com/42200979/75111638-1ce67000-565e-11ea-9437-29f0cbb00d71.png)
![image](https://user-images.githubusercontent.com/42200979/75111643-1f48ca00-565e-11ea-908b-1913f44f67d5.png)



after removing invalidateDisplayList() from InputMask Setter and adding updateDisplayList(width,height);

updateDisplayList(width,height) is working fine on CompanySetup,those fields which should have - - - - - in Company setup is working after this change but Oracle Integration and many other setups is throwing this exception after this change in MaskedTextInput 
CompanySetup : 
![image](https://user-images.githubusercontent.com/42200979/75111614-ec9ed180-565d-11ea-8fc7-e8eb2cf67c2b.png)

Oracle Integration Setup : 
![image](https://user-images.githubusercontent.com/42200979/75111623-faeced80-565d-11ea-9c3a-ab8859fe8ff7.png)
![image](https://user-images.githubusercontent.com/42200979/75111629-06401900-565e-11ea-9729-645cc9516cf3.png)

**Comment by aharui** [comment]
Try using an override of addedToParent instead, as I suggested in #721
