### ISSUE TITLE
Jewel DataGrid: column label bindings

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#729]
DataGrid:
- DataGridColumn label binding: The label property of DataGridColumn is not updated.

**Comment by carlosrovira** [comment]
Hi @javeiga-iest, please make one issue per problem so we can manage it.
I'll need some sample code (minimal) to reproduce problems 2 and 3. I can manage 1 (column label bindings), and we can use this issue just for that one.
Thanks
