### ISSUE TITLE
mx:NumberValidator required property is not making fields RED

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#732]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Bank Reconciliation from Setups in Menu
File : com/dbz/modules/GL/dbzBankReconSetup.mxml

In flex:
![image](https://user-images.githubusercontent.com/42200979/75155182-48865a80-5731-11ea-8c5d-fddd24a60e38.png)

In Royale :
![image](https://user-images.githubusercontent.com/42200979/75155210-5805a380-5731-11ea-8710-9bfa9d43cc7a.png)

**Comment by aharui** [comment]
required shouldn't be a factor because NS has a value of 0.
