### ISSUE TITLE
CheckBox Selection doesn't effect on ADG Checkbox Column 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#740]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Documents -> Verification Plans from Setups in Menu
File : com/dbz/modules/Common/dbzVerificationPlanSetup.mxml

When Include in Plan or Print Footer Checkbox is checked then ADG Checkbox related to Include in Plan or Print Footer should be checked like in Flex,but they are not checked in Royale
In Flex : 
![image](https://user-images.githubusercontent.com/42200979/75445008-5f71ba80-5986-11ea-82f8-fcff9295b696.png)

In Royale : 
![image](https://user-images.githubusercontent.com/42200979/75445121-9ea00b80-5986-11ea-88ae-bb2b17dbfbe0.png)

**Comment by aharui** [comment]
Try with latest changes

**Comment by pashminakazi** [comment]
I have downloaded new sdk today after your this commit https://github.com/apache/royale-asjs/commit/36cbf6ae96d642ad7839b564f003c2445562a320
And this is still not working

**Comment by aharui** [comment]
I looked at your code and tried to re-create the same CheckBox item renderer using Flex.  In Flex the checkbox is not clickable if enabled="false" on the CheckBox as it is in your code.  I deleted the enabled="false" and then I could check the Checkbox, but it did not save that information in the data array probably because the ADG is not set to editable=true, and the column is set to editable=false and rendererisEditor is not set.

I recommend that you debug your Flex version and determine how the Checkbox could work in such a scenario or if something got changed when migrating to Royale.

**Comment by pashminakazi** [comment]
In our Flex Application,ADG is set to editable=false and checkbox is set to enabled=false but on the selection of **Include in Plan** or **Print Footer**  selected="{data.inclde == '0' ? false : true}" and its setting the Checkbox selection and a function Called on the change Event of **Include in Plan** or **Print Footer** checkbox
```
protected function selectAll(event:Event):void
			{
				// TODO Auto-generated method stub
				for(var i:int = 0; i<edgDP.length ; i++){
					edgDP[i].inclde = chkAll.selected? "1": "0";	
				}
				edgDP.refresh();
				edgEntry.validateNow();
			}

```

**Comment by pashminakazi** [comment]
there's an exception on Royale side 
![image](https://user-images.githubusercontent.com/42200979/75654132-dce84400-5c80-11ea-9e68-786c48a36bd9.png)
![image](https://user-images.githubusercontent.com/42200979/75654147-e40f5200-5c80-11ea-8510-553bf2c3f847.png)
inclde is id of AdvancedDataGridColumn **Include in Plan**
Exception is thrown on selectedField="{data.inclde}" selected="{data.inclde == '0' ? false : true}"
	```
<mx:AdvancedDataGridColumn headerText="Include in Plan" width="50" editable="false" id="inclde" dataField="inclde" >
							<mx:itemRenderer>
								<fx:Component>
									<mx:CheckBox enabled="false" textAlign="center" horizontalCenter="0" width="100%"
												 selectedField="{data.inclde}" selected="{data.inclde == '0' ? false : true}"/>
								</fx:Component>
							</mx:itemRenderer>
						</mx:AdvancedDataGridColumn>
```

**Comment by pashminakazi** [comment]
Now its working Fine Thanks
