### ISSUE TITLE
Jewel VirtualComboBox - ComboBoxTextPrompt

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#742]
I'm working with VirtualComboboxes. ComboBox has ComboBoxTextPrompt bead, that allow us to show a message inside the field when none item is selected.
There's a way to use ComboBoxTextPrompt in VirtualCombobox?

**Comment by carlosrovira** [comment]
Hi Javier,
just tried with the TDJ example and is working right:

```
<j:VirtualComboBox localId="virtualIconCmb"
			className="cmbSimpleiIconListItemRenderer" labelField="label"
			dataProvider="{listModel.bigIconListVOData}" rowCount="4" rowHeight="52">
	<j:beads>
		<j:ComboBoxTextPrompt prompt="Some text here..."/>
	</j:beads>
</j:VirtualComboBox>
```
