### ISSUE TITLE
Detail Setup doesn't Picked Up by Parent Setup

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#743]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to ATM Rental Payment from Setups in Menu
File : com/dbz/modules/AR/dbzATMRentalPayment.mxml
I dont know why this setup doesn't pick its Detail **dbzATMRentalPaymentDetail**
Everything is same like ATM Rental Income.
![image](https://user-images.githubusercontent.com/42200979/75659026-1faf1980-5c8b-11ea-9c76-c9604589df10.png)

**Comment by aharui** [comment]
There was an exception being thrown in dbzATMRentalPaymentDetail that should have been reported.
