### ISSUE TITLE
TypeError: Cannot read property 'dataField' of undefined

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#744]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Lease Rental from Setups in Menu
File : com/dbz/modules/AR/dbzLeaseRental.mxml

Click On + button then Detail window will be opened then again Click on + button a row will be added to Detail window then Click On Second Column Site Name,This Exception will be occured
![image](https://user-images.githubusercontent.com/42200979/75659886-96004b80-5c8c-11ea-99a5-d3aeba4010a2.png)

![image](https://user-images.githubusercontent.com/42200979/75660023-d95aba00-5c8c-11ea-8873-1a1439e7984b.png)

**Comment by aharui** [comment]
You will need to provide more details and determine which Royale APIs are not working as expected.

**Comment by aharui** [comment]
I tried to investigate, but the Lease Rental setup throws exceptions when initializing.  The MaskedDateField may not be parenting the MaskedTextInput.  There is suspicious code in MaskedDateField that could skip the addChild call in createChildren.

Maybe getChildIndex is not working correctly

**Comment by aharui** [comment]
columnIndex is not set in event forwarded by AdvancedDataGridSingleSelectionMouseController

**Comment by pashminakazi** [comment]
Thanks but till exist,
![image](https://user-images.githubusercontent.com/42200979/75950797-13fe6580-5ecc-11ea-821b-cc9b91d9e965.png)
Click On + button then Detail window will be opened then again Click on + button a row will be added to Detail window then Click On Second Column **Site Name** and then on 5th column **Description**.this Exception will be occured

**Comment by aharui** [comment]
Technically, this is a different scenario (itemDoubleClick instead of itemClick).  Should be fixed in 8f4acc30eb7792079cd61d47fcf79b68efb0f920
