### ISSUE TITLE
TypeError: Cannot read property 'setFocus' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#745]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Sales Commission Scheme Setup from Setups in Menu
File : com/dbz/modules/AP/dbzSaleCommissionSchemeSetup.mxml

Click On + button then Detail window will be opened then again Click on + button a row will be added to Detail window then Click On Second Column Qty From (Group 1),This Exception will be occured
![image](https://user-images.githubusercontent.com/42200979/75664116-c1d2ff80-5c93-11ea-99f4-f757b6da8b60.png)
![image](https://user-images.githubusercontent.com/42200979/75664127-c7c8e080-5c93-11ea-87b4-fbfecf9ac79a.png)

Click on any other Column : TypeError: Cannot read property 'toString' of undefined
![image](https://user-images.githubusercontent.com/42200979/75664225-f21a9e00-5c93-11ea-85bb-ddb40e12a448.png)
![image](https://user-images.githubusercontent.com/42200979/75664263-0199e700-5c94-11ea-9360-6a9cf645ff91.png)

**Comment by aharui** [comment]
Need to establish FM in popups
