### ISSUE TITLE
TypeError: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#746]
This Exception is thrown,when i select date,date can't be selected in every setup
![image](https://user-images.githubusercontent.com/42200979/75664652-9f8db180-5c94-11ea-8ba2-59b049f72ce7.png)

**Comment by aharui** [comment]
Not sure what changed, but in the MaskedTextInput's text setter the call to updateDisplayList can  access the embedTextField which hasn't been created yet.  You can try checking if the component is has a parent
```
if (parent)
   updateDisplayList(0,0);
```

Or call updateDisplayList in an override of addedToParent() as I've suggested on some other issues.

**Comment by aharui** [comment]
After more investigation, the dateField flag is set in MaskedTextInput in the DateField, but the embedTextField is null.
