### ISSUE TITLE
PopUpManager.removePopUp is throwing Exception

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#750]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Price -> Price Entry from Setups in Menu
File : com/dbz/modules/SAL/dbzPriceEntryTabs.mxml which is loading a module
com/dbz/modules/SAL/dbzPriceEntryAPL.mxml

Click Copy Button then + plus Detail window will be opened then click Cancel to close Popup this exception will occur

![image](https://user-images.githubusercontent.com/42200979/76060197-8e011e00-5fa2-11ea-981c-7f18160351a7.png)
![image](https://user-images.githubusercontent.com/42200979/76060211-92c5d200-5fa2-11ea-98e0-9e9c7b298d8d.png)

**Comment by aharui** [comment]
See if 8a9a07d222e39c2d25b814786ed2a1f803c98994 helps.  It could be that the popup is being removed more than once.

**Comment by pashminakazi** [comment]
@aharui Thank u so much its working fine now
