### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of null     dbzVoucherFormatSetup.js:1766 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#754]
roject Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to General Ledger from Select in Menu
Go to VoucherType from Setups in Menu
File : com/dbz/modules/GL/dbzVoucherTypeSetup.mxml

Click on **NEW** button and then Click on **Voucher Printing** LinkButton

![image](https://user-images.githubusercontent.com/42200979/76405498-08b6a880-63aa-11ea-8a4d-c825254e1f77.png)

**Comment by aharui** [comment]
This Setup is also running into #811.  Reopen if still a problem after fix for #811.
