### ISSUE TITLE
<j:TabBar> seems broken when set in <j:Group> SDK 0.9.7 royale-asjs_jsonly #1053

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#759]
Hi,
I come back to work on my website using Apache Royale. It seem since last build (3 or 5 months over) that TabBar doesn't fill it's childs if insered into a group.

Here is the code :

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic" 
                xmlns:j="library://ns.apache.org/royale/jewel" 
                >
    <j:initialView>
        <j:View>
        <j:Label text="HELLO"/>

        <j:Group width="100%" height="100%">
            <j:TabBar width="100%" rowHeight="60">
                <j:beads>
                    <js:ConstantBinding sourcePropertyName="tabBarDataSample" destinationPropertyName="dataProvider"/>
                    <j:AssignTabContent selectedContentProperty="content">
                        <j:content>
                            <j:TabBarContent width="100%" height="600">
                                <j:SectionContent name="informations" >
                                    <j:Label text="Informations"/>
                                </j:SectionContent>
                                    <j:SectionContent name="commandes" >
                                    <j:Label text="Commandes"/>
                                </j:SectionContent>
                            </j:TabBarContent>
                        </j:content>
                    </j:AssignTabContent>
                </j:beads>
            </j:TabBar>
        </j:Group>

        </j:View>
    </j:initialView>   


    <fx:Script>
        <![CDATA[
            import org.apache.royale.collections.ArrayList;

			private var _tabBarDataSample:ArrayList = new ArrayList([
				{label:"Informations", content:"informations"},
				{label:"Commandes", content:"commandes"}
			]);
			
			[Bindable]
			public function get tabBarDataSample():ArrayList
			{
				return _tabBarDataSample;
			}
        ]]>
    </fx:Script>
</j:Application>
```

To make this code working I must remove `<j:Group width="100%" height="100%">`

There is no error in console

Maybe I made a mistake ?

Regards

**Comment by carlosrovira** [comment]
Hi, 
quick fix is you need 
`<j:View width="100%" height="100%">`

explanation: recently I added code to make containers smarter, so we can nest them using % sizes, but that requires that although before you can left a continer does not have width or height declared, now it is a must.

View is the one that is not allowing to view the rest, since now Group has "overflow: hidden". That seems the most natural and close to how Flex do this kind of things

HTH

Carlos

**Comment by cristallium** [comment]
Hi Carlos,

Many thanks for you quick reply as alway !

In fact I always have the issue because I give you a simplified test case. 

In reality I use a `group `with states, parent is a `ScrollableSectionContent `parent with `ApplicationMainContent `parent with `ApplicationResponsiveView `parent with `initialView `parent with `Application`. (I used code from tour de Jewel)

Setting 100% on each parent make issues. So I will try to do another smallest test case and open a new issue if I can't make it working.

Thanks again !

**Comment by carlosrovira** [comment]
Hi, since the change is recent latest 24-48h, maybe can still have issues with different content not already tested. You can as well compare you actual code with actual TDJ code, so maybe something is different to.

**Comment by cristallium** [comment]
Hi Carlos,

Many thanks for you quick reply as alway !

In fact I always have the issue because I give you a simplified test case. 

In reality I use a `group `with states, parent is a `ScrollableSectionContent `parent with `ApplicationMainContent `parent with `ApplicationResponsiveView `parent with `initialView `parent with `Application`. (I used code from tour de Jewel)

Setting 100% on each parent make issues. So I will try to do another smallest test case and open a new issue if I can't make it working.

Thanks again !

Hi,
Worked fine when clean et rebuild all project !

**Comment by cristallium** [comment]
Hi,
Worked fine when clean et rebuild all project !
Thanks

**Comment by carlosrovira** [comment]
Hi Fred,
just let you know that I make group work as before (not clipping content), since is the same as Flex worked. Instead Container is the one that composes Viewport and clip content. So I added VContainer and Container and now Card extends VContainer instead of VGroup. This should be now more coherent.

**Comment by cristallium** [comment]
Hi Carlos,
Thanks for this usefull information. I agree with you, this is more coherent.
I will try today
