### ISSUE TITLE
using "gap" property in <j:HGroup> is ignored or throw error (SDK0.9.7 royale-asjs_jsonly #1053)

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#762]
Hi (...Carlos ?),

Here is the test case :

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:j="library://ns.apache.org/royale/jewel" 
	xmlns:js="library://ns.apache.org/royale/basic" 
	xmlns:local="*" >


	<j:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</j:valuesImpl>

	<j:initialView>
		<j:View width="100%" height="100%">
			<j:HGroup gap="40">
				<j:Button text="BT1"/>
				<j:Button text="BT2"/>
			</j:HGroup>
		</j:View>
	</j:initialView>
</j:Application>
```

Found issue when using gap property :
if set to 20, then it seem have no effet
if set to 40, then throw following error

![image](https://user-images.githubusercontent.com/6851433/77074084-915bc700-69f0-11ea-908d-7b1533e18e2a.png)

Regards

**Comment by carlosrovira** [comment]
Hi Fred,

thanks I found a bug since the limit value to pass is "10" but I was showing other one.
I committed now the fix.

Thanks

Carlos
