### ISSUE TITLE
itemsHorizontalAlign property on j:VContainer seem not working SDK0.9.7#1070

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#767]
Hi again Carlos,

If I'm using correctly VContainer, it seems there is a issue with itemsHorizontalAlign .
Here is test case :

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:j="library://ns.apache.org/royale/jewel" 
	xmlns:js="library://ns.apache.org/royale/basic" 
	xmlns:local="*" >


	<j:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</j:valuesImpl>

	<j:initialView>
		<j:View width="100%" height="100%">

			<j:VContainer width="100%" itemsHorizontalAlign="itemsCenter">
				<j:Label text="I want to be on center"/>
			</j:VContainer>

		</j:View>
	</j:initialView>

</j:Application>
```

and the result 

![image](https://user-images.githubusercontent.com/6851433/77175417-ebc55800-6ac2-11ea-9b52-da1e0249ebb9.png)

**Comment by carlosrovira** [comment]
Hi Fred, 
you're right, thanks for reporting this. I reworked the layouts to make work the different configurations. it's curious I didn't catch this before...

**Comment by cristallium** [comment]
Many thanks Carlos !
Since Iast 6 months I realise that there are plenty of good features. Before I used a lot of css to align items, now it's a real pleasure to use Apache Royale only for styling (I have some small issues using it and add questions on it to SOF). Moreover Jewel is now a complete set of components to build applications. Congratulation to you and all Apache Royale staff and contribuers. I wish all my encouragement for the future

**Comment by carlosrovira** [comment]
Hi Fred, glad to hear the effort is working for you! That encourages us to continue improving.
Thanks! :)
