### ISSUE TITLE
j:Card in a Group with j:VerticalCenteredLayout result in j:Card 'height' property not working SDK0.9.7#1070

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#768]
Hi again ;-)

When using a j:VerticalCenteredLayout then Card height is the size of starting navigator window

Take this test case (height of j:Card is 80)

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:j="library://ns.apache.org/royale/jewel" 
	xmlns:js="library://ns.apache.org/royale/basic" 
	xmlns:local="*" >


	<j:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</j:valuesImpl>

	<j:initialView>
		<j:View width="100%" height="100%">

			<j:Group  width="100%" height="100%">
				<j:beads>
					<j:VerticalCenteredLayout />
				</j:beads>

				<j:Card width="50%" height="80">
					<j:Label text="HELLO"/>
				</j:Card>
			</j:Group>

		</j:View>
	</j:initialView>

</j:Application>
```
![image](https://user-images.githubusercontent.com/6851433/77179228-76f51c80-6ac8-11ea-9a4a-6c9ee2e64be3.png)
If I remove j:VerticalCenteredLayout then it's working right

**Comment by carlosrovira** [comment]
Thanks for reporting, just fixed in layouts. I think centered layouts must override other behaviours. Introduced as well this test in TDJ at the end of layouts. Thanks
