### ISSUE TITLE
j:Group itemsHorizontalAlign property issue. SDK#0.9.7 #1086

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#783]
Hi Carlos,
I'm not sure if `itemsHorizontalAlign `property must exist or not for` j:Group`.
For now, you can use it, the compiler don't complain. 
But if you use it there is an error on runtime :

![image](https://user-images.githubusercontent.com/6851433/77404478-17418e80-6db2-11ea-9746-b13505bc3a08.png)

Here is test case:

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:j="library://ns.apache.org/royale/jewel" 
	xmlns:js="library://ns.apache.org/royale/basic" 
	xmlns:local="*" >


	<j:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</j:valuesImpl>

	<j:initialView>
		<j:View width="100%" height="100%">

			<j:Group  width="100%" height="100%" itemsHorizontalAlign="itemsCenter">
					<j:Card width="80%" height="10"/>
					<j:Label text="HELLO"/>
			</j:Group>

		</j:View>
	</j:initialView>

</j:Application>
```

**Comment by cristallium** [comment]
same issue for itemsVerticalAlign

**Comment by carlosrovira** [comment]
Hi Fred,

this methods are to use with the subclasses VGroup and HGroup and not for Group. It's clear that does not have sense to have in the Group class, so maybe the solution is replicate in subclasses. Will see what to do in that case. Thanks

**Comment by cristallium** [comment]
Hi Carlos,

Thanks for you message.

I use a lot of  code completion in VSC (visual studio code) to know what are usable property . (I was doubting myself that `itemsHorizontalAlign ` what not for `Group` )

I'm afraid that a new dev guy makes like me (auto completion code),  using `itemsHorizontalAlign   ` in `Group ` and think SDK is buggy.

Other than that it's not really annoying

**Comment by carlosrovira** [comment]
Hi Fred,

just do the refactor to remove APIs from the Group and Container level in this commit: 59aa6238704586f4f40222fbec760b50318575a8
