### ISSUE TITLE
j:HGroup/j:HContainer itemsVerticalAlign property issue SDK0.9.7#1086

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#784]
Hi Carlos,

I'm playing a little with `itemsVerticalAlign  `and `itemsHorizontalAlign `for H/V Group and Container.

when using a `VGroup `or `VContainer `then `itemsHorizontalAlign="itemsCenter"` works fine.
1) In this case (VGroup or VContainer), is `itemsVerticalAlign `must be usable ? (if yes it seems not working)

Now the opposite: when using `HGroup `or `HContainer `then `itemsVerticalAlign  `doesn't work.

2) Same question as previous,  in this case (HGroup or HContainer) is `itemsHorizontalAlign`must be usable ? (if yes it seems not working)

Here is test case for the issue with `HGroup `:
```

<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:j="library://ns.apache.org/royale/jewel" 
	xmlns:js="library://ns.apache.org/royale/basic" 
	xmlns:local="*" width="100%" height="100%">


	<j:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</j:valuesImpl>

	<j:initialView >
		<j:View width="100%" height="100%">

			<j:HGroup width="100%" height="100%" itemsVerticalAlign="itemsCenter" >
					<j:Card width="80%" height="10"/>
					<j:Label text="HELLO"/>
			</j:HGroup>

		</j:View>
	</j:initialView>

</j:Application>
```

and the result :
![image](https://user-images.githubusercontent.com/6851433/77406318-c1221a80-6db4-11ea-8705-9d2836059d09.png)

**Comment by carlosrovira** [comment]
In that case is itemsVerticalAlign="itemsCentered" not itemCenter. That can't be the same in that case.

**Comment by carlosrovira** [comment]
mmm, I'm thinking that to avoid confusion, I maybe could make the same for both, but in the vertical case then add in the method the suffix...I'll try as I have little time to do it

**Comment by cristallium** [comment]
Ho yes, I didn't realise that was not the same name...
Sorry for this wrong issue

**Comment by piotrzarzycki21** [comment]
@carlosrovira yesterday I have spend a lot of time adjust application to use above, so are you going to change anything more in that matter ?

**Comment by carlosrovira** [comment]
Hi Piotr, I'll try to make both literals the same if I can. In that case I think it will make all our life easier to not having to know if is "itemCenter" or "itemCentered". If that's the case you will just need to search for "itemCentered" and replace all for "itemCenter".

**Comment by carlosrovira** [comment]
just fixed and tested in my 2 latest commits now

**Comment by piotrzarzycki21** [comment]
> Hi Piotr, I'll try to make both literals the same if I can. In that case I think it will make all our life easier to not having to know if is "itemCenter" or "itemCentered". If that's the case you will just need to search for "itemCentered" and replace all for "itemCenter".

One thing is change and replace, the second thing is test whole application whether everything is really working fine. I hope it is the final change. Thanks!

**Comment by carlosrovira** [comment]
Hi Piotr, we're before 1.0 to ensure APIs are right. I think is one of the important things at this time since at later time if users grow will more hard to do this kind of changes.
