### ISSUE TITLE
404 On https://royale.apache.org/tourdejewel/#!datagrid_panel

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#785]
Hi,

There is a death link on 
https://royale.apache.org/tourdejewel/#!datagrid_panel
When clic on source code for datagrid then the link is
`
https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/DataGridPlayGround.mxml`

it should be

`https://github.com/apache/royale-asjs/blob/develop/examples/jewel/TourDeJewel/src/main/royale/DataGridPlayGround.mxml`

Path in source code seems relative, perhaps it will be good on next update of TDJ ?

**Comment by carlosrovira** [comment]
ops!, thanks for caching that. I need to change that path so all source code links goes to the right url. Fixed in my last commit. Thanks!
