### ISSUE TITLE
j:DataGrid change event is called as many times as there are columns SDK0.9.7#1086

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#788]
Hi,

I think I found an weird issue. The `change `event in a` j:DataGrid` is called one time if there is 1 column, twice if there are 2 columns, 5 times if there are 5 columns, etc...

Here is test case with 3 columns :

```
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:j="library://ns.apache.org/royale/jewel" 
	xmlns:js="library://ns.apache.org/royale/basic" 
	xmlns:local="*" width="100%" height="100%" applicationComplete="ev_appComplete()">


	<j:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</j:valuesImpl>

	<j:initialView >
		<j:View width="100%" height="100%">
			<j:VContainer width="100%" height="100%">
				
				<j:DataGrid id="dg" width="100%" height="100" change="ev_change(event)">
					<j:columns>
						<j:DataGridColumn label="Label" dataField="label"/>
						<j:DataGridColumn label="Label2" dataField="label2"/>
						<j:DataGridColumn label="Label3" dataField="label3"/>
					</j:columns>
				</j:DataGrid>
				<j:Label id="lbl" multiline="true"/>
			</j:VContainer>
		</j:View>
	</j:initialView>

<fx:Script>
	<![CDATA[
		import org.apache.royale.collections.ArrayList;
		import org.apache.royale.events.Event;

		private function ev_appComplete():void{
			dg.dataProvider = new ArrayList([{label:'One item to clic',label2:'Just for test2',label3:'Just for test3'}]);
		}

		private function ev_change(e:Event):void{
			lbl.text += "\n" + e.toLocaleString();
		}
	]]>
</fx:Script>
</j:Application>
```

![image](https://user-images.githubusercontent.com/6851433/77434138-b67d7a80-6de0-11ea-9e9a-cfbad1aa8e27.png)

**Comment by piotrzarzycki21** [comment]
Hi @cristallium, 
Is there any reason why are you not writing those question on users mailing list ? Some of them are may not be an issues, but could be a valid questions. Later when someone need some answer it is hard to find anything on GitHub once issue is closed.

**Comment by cristallium** [comment]
Hi Piotr,
I don't really understand how it is working, and what is the best practice.
Do you ask specificaly for this question or all last reports ?
When I think it's a using question I use SOF (see for exemple https://stackoverflow.com/questions/60762467/apache-royale-how-to-set-formitem-text-label-width or https://stackoverflow.com/questions/60760550/apache-royale-equivalent-of-enabled-property-on-jbutton) but when I think it's a bug I use issue report on git.

Maybe I'm wrong ? Could you tell me what is the best way and the more profitable for Apache Royale ?
Please tell me and I will change the way to report

**Comment by carlosrovira** [comment]
Hi Fred, 
thanks for reporting this. 
In this case is good to make an issue, since it was a bug. At least I can work better with GitHub issues.

**Comment by cristallium** [comment]
Hi Carlos,
Thanks for your reply, so I will continue this way. I also prefer use GitHub issues because it's very friendly , and I can quick and easily copy/paste screenshoot to add more informations about issue
