### ISSUE TITLE
Uncaught TypeError: child.getExplicitOrMeasuredWidth is not a function  (UIComponent.js:2958)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#789]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to General Ledger from Select in Menu
Go to Voucher Type from Setups in Menu
File : com/dbz/modules/GL/dbzVoucherTypeSetup.mxml

![image](https://user-images.githubusercontent.com/42200979/77639053-eb710500-6f79-11ea-8b25-683f96a10310.png)

![image](https://user-images.githubusercontent.com/42200979/77639270-4d316f00-6f7a-11ea-9b36-8980a82afd39.png)

**Comment by pashminakazi** [comment]
@aharui Press new button and see this issue

**Comment by aharui** [comment]
I can't reproduce the problem.  But if you are using s:TextArea, probably better to switch to mx:TextArea

**Comment by pashminakazi** [comment]
@aharui after replacing s:TextArea with mx:TextArea,this exception occurs on clicking new button
![image](https://user-images.githubusercontent.com/42200979/79322795-c04d5600-7f26-11ea-8bed-a99773e8a54f.png)

**Comment by pashminakazi** [comment]
@aharui Please resolve this issue on high priority.this issue happens in many setups

**Comment by aharui** [comment]
This appears unrelated to TextArea.  In the debugger, find out which component is the problem.  Check the 'this' pointers in the call stack or the '_strand' of the beads like VirtualListView.
