### ISSUE TITLE
Centre image incorrectly positions image and fails to take account of it's height and width

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#79]
Example code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">
    
    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View width="100%" height="100%">
            <js:Container width="600" height="300">
                <js:style>
                    <js:SimpleCSSStyles backgroundColor="#FF0000" />
                </js:style>
                <js:Image src="http://apache.org/img/asf_logo.png">
                    <js:beads>
                        <js:CenterElement />
                    </js:beads>
                </js:Image>
            </js:Container>
        </js:View>
    </js:initialView>

</js:Application>
```

Doesn't centre the image:
![2017-11-13_15-17-44](https://user-images.githubusercontent.com/144504/32709647-14bb32c0-c886-11e7-996e-20bf1ed56f25.png)

Inspecting the image you can see it's style been set to:
position: absolute; left: 300px; top: 150px;

**Comment by Harbs** [comment]
You did not specify a size for the image. The following works:

````
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">
    
    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View width="100%" height="100%">
            <js:Container width="600" height="300">
                <js:style>
                    <js:SimpleCSSStyles backgroundColor="#FF0000" />
                </js:style>
                <js:Image src="http://apache.org/img/asf_logo.png" width="429" height="175">
                    <js:beads>
                        <js:CenterElement />
                    </js:beads>
                </js:Image>
            </js:Container>
        </js:View>
    </js:initialView>
</js:Application>
````
If you need the image to be centered after it's loaded and the size calculated, you will need to trigger a new layout event once that happens.

**Comment by justinmclean** [comment]
Please don't close issues early. I raised this issue as in the application I'm building the size of the image is not know at run time and multiple images are dynamically in the same place holder. The example I gave  illustrates this.

**Comment by Harbs** [comment]
What is not clear?

Like I said: For dynamically loaded images, you need to trigger a new layout on the container. You can do that by dispatching "layoutNeeded". This is by design.

If you want this to happen automatically, you can create a new bead which listens to the image and updates as needed.

One way to do that would be to listen for layoutNeeded on the image.

**Comment by justinmclean** [comment]
Dispatching layoutNeeded as suggested don't work

Neither this:
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

    <fx:Script><![CDATA[        
        public function changeImage():void {
            image.src = "http://apache.org/img/flex.jpg";
            holder.dispatchEvent(new Event("layoutNeeded"));
        }
        ]]></fx:Script>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View width="100%" height="100%">
            <js:beads>
                <js:VerticalLayout />
            </js:beads>
            <js:Label text="Here's the ASF logo" />
            <js:Container id="holder" width="520" height="300">
                <js:style>
                    <js:SimpleCSSStyles backgroundColor="#333333" />
                </js:style>
                <js:Image id="image" src="http://apache.org/img/asf_logo.png" width="429" height="175">
                    <js:beads>
                        <js:CenterElement />
                    </js:beads>
                </js:Image>
            </js:Container>
            <js:TextButton text="Change Image" click-="changeImage()" />
        </js:View>
    </js:initialView>

</js:Application>

**Comment by Harbs** [comment]
Obviously. You are calling layoutNeeded before the image is loaded.

**Comment by justinmclean** [comment]
So I assume what you meant is that you need to listen for layoutNeeded on the image and when that is received then dispatch layoutNeeded on the container that holds the image.. If so that only sort of works as you get a very ugly jump of the image in the wrong position jumping to the correct position.

Rather than closing issues when you may not of tested the solution you suggested it's probably better to ask me to test your suggestion first and then only close it if it works.

Example code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic"
                applicationComplete="init()">

    <fx:Script><![CDATA[        
        public function init():void {
            image.addEventListener("layoutNeeded", resetImage);
        }

        public function changeImage():void {
            image.src = "http://apache.org/img/flex.jpg";
        }

        public function resetImage():void {
            holder.dispatchEvent(new Event("layoutNeeded"));
        }
        ]]></fx:Script>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <js:initialView>
        <js:View width="100%" height="100%">
            <js:beads>
                <js:VerticalLayout />
            </js:beads>
            <js:Label text="Here's the ASF logo" />
            <js:Container id="holder" width="520" height="300">
                <js:style>
                    <js:SimpleCSSStyles backgroundColor="#333333" />
                </js:style>
                <js:Image id="image" src="http://apache.org/img/asf_logo.png">
                    <js:beads>
                        <js:CenterElement />
                    </js:beads>
                </js:Image>
            </js:Container>
            <js:TextButton text="Change Image" click-="changeImage()" />
        </js:View>
    </js:initialView>

</js:Application>
```

Trying to work around this by setting image.visible = false / true also doesn't seem to work.
