### ISSUE TITLE
java.lang.NumberFormatException : For input string: "111111111111"

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#794]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Carriage/Freight -> Tank Lorry Seals Setup from Setups in Menu
File : com/dbz/modules/SAL/dbzSealsSetup.mxml

Click on any record on which Add button is enabled and then click Add button,add 111111111 to **To seal** and 2222222222 in **From Seal** and click save button,this exception will be occured
![image](https://user-images.githubusercontent.com/42200979/78034762-95d59780-7381-11ea-8f9b-f0aebcc73c51.png)

**Comment by aharui** [comment]
What did the Flex app send to the server and what is Royale sending to the server?  And why?
