### ISSUE TITLE
Strange behavior of form item due to label retrieved from resource

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#797]
While using resource from locale, form layout behaves strange.
Here is the example, for the source : 

```
     <mx:FormItem id="id_userName" label="Kullanici Adi">
         <s:TextInput id="userName"/>
     </mx:FormItem>
```
![image](https://user-images.githubusercontent.com/5983818/78425071-bac85400-767a-11ea-902b-7ec9d392c079.png)

when change to :

```
    <mx:FormItem id="id_userName" label="{resourceManager.getString('messages', 'userName')}">
          <s:TextInput id="userName"/>
    </mx:FormItem>
```

![image](https://user-images.githubusercontent.com/5983818/78425078-cddb2400-767a-11ea-948e-da020e8e9f74.png)

**Comment by nihavend** [comment]
This is better than before @aharui but I guess still have issues.

![image](https://user-images.githubusercontent.com/5983818/79377809-f3163f00-7f64-11ea-9b31-f9e5f1f3c18b.png)

**Comment by nihavend** [comment]
@aharui

I debugged the code at the bottom an here are the results :

this function calculates the width
```
mx.containers.FormItem.prototype.commitProperties = function() {
  mx.containers.FormItem.superClass_.commitProperties.apply(this);
  if (this.mx_containers_FormItem_labelChanged) {
    this.mx_containers_FormItem_labelObj.text = this.label;
    this.mx_containers_FormItem_labelObj.validateSize();
    this.mx_containers_FormItem_labelChanged = false;
  }
};
```

This method is visited 7 times

1. for userName1 label, labelChange is false
2. for userName1 label, labelChange is false
3. for password1 label, label changed is true, label = "Şifre"
4. for password1 label, label changed is false
5. for div.Container.FormItem, label changed is false
6. for div.Container.FormItem, label changed is false
7. for userName1 label, labelChange is true, label = "Kullanıcı Adı"

I guess the when the method mx.containers.FormItem.prototype.commitProperties is called, the first label is not initialized yet because it is getting text from resources and as the calculation is done in the first pass the width is wrongly - mean the for the second label, "password1" is set at that time - calculated due to empty first label.

This is some kind of sequence of timing issue. I could not investigate the root cause.

Here is the source :

```

<?xml version="1.0" encoding="latin5" ?>

<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
			   xmlns:s="library://ns.apache.org/royale/spark"
			   xmlns:mx="library://ns.apache.org/royale/mx"
			   height="600" width="800"
			   >
	<fx:Metadata>
		[ResourceBundle("messages")]
	</fx:Metadata>
	
	<s:Group width="288" height="179">
		
		<s:layout>
			<s:VerticalLayout gap="10" paddingRight="10" paddingLeft="10" paddingTop="10" paddingBottom="20" />
		</s:layout>
		
		<s:Panel
			horizontalCenter="0"
			verticalCenter="0"
			id="loginPanel1" 
			width="288" 
			height="179" 
			chromeColor="#E2E5E7"
			title="{resourceManager.getString('messages', 'loginTitle')}" 
			>
			
			<mx:Form id="main_form1" width="100%" height="100%" top="10" left="5"><!-- defaultButton="{button}" -->
				
				<mx:FormItem id="id_userName1" label="{resourceManager.getString('messages', 'userName')}"> 
					<s:TextInput id="userName1"/>
				</mx:FormItem>
				
				<mx:FormItem id="id_password1" label="Sifre">
					<s:TextInput id="password1" displayAsPassword="true"/>
				</mx:FormItem>
				
				<<mx:FormItem>
					<s:Button id="button1" width="64" label="{resourceManager.getString('messages', 'login')}"/>
				</mx:FormItem>
			</mx:Form>		
			
		</s:Panel>
		
	</s:Group>
	
</s:Application>


```

**Comment by aharui** [comment]
Re-opening per Serkan's email.  Did the last change not fix your case?  I seemed to work for me.

**Comment by nihavend** [comment]
@aharui 
firtst point, I really did not know that you pushed a fix three days ago. I did not get any notification. How can we fix this ?

After updating and compiling with your fix I can say that the calculation sequence is fixed. But for now, I am facing another issue.

When the size of the labels extends via locale change, the text field behind is shifted.

For this problem;
1. For the real application when change the local it show horizontal scroll bar : 
for the locale us :

![image](https://user-images.githubusercontent.com/5983818/80196406-0fca0b00-8626-11ea-8b4b-1510cd642e9e.png)

when change the local via flag button to turkish :
![image](https://user-images.githubusercontent.com/5983818/80196469-21131780-8626-11ea-96e2-6554608fee4b.png)

2. I prepared the test case but it does not behave sames as the real application. It does not show the scrollbar but still shifts (Note : also the styling is different I am not sure why)
for the locale us : 

![image](https://user-images.githubusercontent.com/5983818/80196745-74856580-8626-11ea-80f8-763d12c4472f.png)

when change the local via flag button to turkish 👍 
![image](https://user-images.githubusercontent.com/5983818/80196817-8830cc00-8626-11ea-8748-5242aadb6396.png)

**Comment by yishayw** [comment]
> @aharui
> firtst point, I really did not know that you pushed a fix three days ago. I did not get any notification. How can we fix this ?

@nihavend , Are you subscribed to commits@royale.apache.org ?

**Comment by nihavend** [comment]
> > @aharui
> > firtst point, I really did not know that you pushed a fix three days ago. I did not get any notification. How can we fix this ?
> 
> @nihavend , Are you subscribed to [commits@royale.apache.org](mailto:commits@royale.apache.org) ?

I guess no @yishayw until now. Thanks !

**Comment by nihavend** [comment]
decreasing the spacing between the label and boxes may solve the issue. is it css thing ?
