### ISSUE TITLE
multiple radiobutton should not be selected at a time

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#804]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Inventory Scheduled Setup from Setups in Menu
File : com/dbz/modules/INV/dbzInventorySchedulingSetup.mxml

In this setup when we select AM RadioButton then PM RadioButton should not be selected at same time 
![image](https://user-images.githubusercontent.com/42200979/79064984-b3cac280-7cc6-11ea-9679-bd047a7fc66c.png)

**Comment by aharui** [comment]
The code is binding group="{ampm}" where the RadioButtonGroup has id="ampm".  Try setting groupName="ampm" instead.

**Comment by pashminakazi** [comment]
@aharui Thanks issue has been resolved
