### ISSUE TITLE
MXRoyale Application 'preinitialize' fires a second time after 'initialize'

### ISSUE THREAD

**Issue by greg-dove** [apache/royale-asjs#805]
Repro in HelloWorld:

> onStartupEvent:preinitialize
> onStartupEvent:initialize
> onStartupEvent:creationComplete 
> onStartupEvent:preinitialize
> onStartupEvent:applicationComplete

```
<mx:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                   xmlns:mx="library://ns.apache.org/royale/mx"
				   preinitialize="onStartupEvent(event)"
				   initialize="onStartupEvent(event)"
				   applicationComplete="onStartupEvent(event)"
				   creationComplete="onStartupEvent(event)"
                   width="600" height="400" >
	<!-- to do: layout="absolute" minWidth="955" minHeight="600" -->
	<fx:Style>
		@namespace mx "library://ns.apache.org/royale/mx";
		
		/* set position:absolute to make the (x,y) properties work */
		mx|Label {
			position: absolute;
		}
		
	</fx:Style>

	<fx:Script><![CDATA[
		import org.apache.royale.events.Event;
		public function onStartupEvent(event:Event):void{
			trace('onStartupEvent:'+event.type);
		}
		]]>
	</fx:Script>

	<mx:Label text="Hello World" x="20" y="20" />
        
</mx:Application>
```

**Comment by greg-dove** [comment]
By comparison, a mx:Application in Flex, has the following sequence:

> [trace] onStartupEvent:preinitialize
> [trace] onStartupEvent:creationComplete
> [trace] onStartupEvent:applicationComplete
> [trace] onStartupEvent:initialize

**Comment by aharui** [comment]
Wow!  In Flex, "initialize" is supposed to go before creationComplete.  It should for other components.  I wonder when that broke.

In MXRoyale, no serious attempt has been made to emulate the order of events because the lifecycle underneath is different, so patches are welcome.

**Comment by greg-dove** [comment]
Actually I will double check this - just in case. I was using client copy of the flex sdk. I will check with normal sdk in case they changed something.,

**Comment by greg-dove** [comment]
Sorry, that seems like it might be somethiing that was messed with in the 'custom' sdk I was using
I tested with an old 3.6 SDK and also with Spark in recent Apache release and the order is as expected. Thanks for prompting me to check!

> [trace] onStartupEvent:preinitialize
> [trace] onStartupEvent:initialize
> [trace] onStartupEvent:creationComplete
> [trace] onStartupEvent:applicationComplete

So it seems the original issue is just the double preinitialize event

**Comment by aharui** [comment]
That's the order I would expect.  Note that Flex also did not put the Application on the display list until late which is not the case in Royale (and not something I would want us to emulate).  And also that Flex had deferred instantiation and the LayoutManager and validateNow() and hopefully we wouldn't have to emulate all of that.  It is also possible that validateNow() could change the timing of events in Flex.

**Comment by greg-dove** [comment]
that is probably the reason in that case. the original code had a validateNow() in the preinitialize handler... thanks

**Comment by greg-dove** [comment]
@aharui I made changes that avoid the extra dispatch of preinitialize. But I don't really understand why the extra preinitialize dispatches were for in mx.core.Application, so I did not remove them. 
I can't see a problem with what I did, but because I also don't understand why the original code is as it is, you might want to take a glance at it: https://github.com/apache/royale-asjs/commit/d45d47636fec97c2da79309a74ba7e0bef86b8af

**Comment by greg-dove** [comment]
@aharui I hope you don't mind but I will assign this to you. You can simply dismiss/close it if you don't have time to check what I did (I don't expect there would be any side effects, just wanted a sanity check).
