### ISSUE TITLE
Unable to add text in Amount field

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#807]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Feasibility from Select in Menu
Go to Pipeline Gain/Loss Monthwise from Setups in Menu
File : com/dbz/modules/FS/dbzGainLossPipelineMonthlySetup.mxml

I am unable to Add text in **Amount** field
```
<s:Label text="Amount (+/-)" x="10" y="212" height="20" width="105" textAlign="right" verticalAlign="middle"/>			
<s:TextInput id="setupColumn5" width="145" tabIndex="2" restrict="-[0-9]" x="122" y="212" maxChars="10" height="20" valueCommit="fn_FormatValue(setupColumn5)"/>

private function fn_FormatValue(item:TextInput):void {
 item.text = SetupList.fmtAmount.format(item.text==""?"0":item.text);
}
```

**Comment by aharui** [comment]
Are you sure this is the correct "restrict" property?  It looks like it would prevent typing in numbers.  What are you trying to type?

**Comment by pashminakazi** [comment]
@aharui Thanks.
restrict="-[0-9]" is replaced with restrict="-0-9" now its working
