### ISSUE TITLE
Uncaught invalid setValue parameters   (VariableDefinition.js:131)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#809]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to PSSM -> Concession from Setups in Menu
File : com/dbz/modules/Common/dbzConcessionMaster.mxml

Fill all fields and then click save button
![image](https://user-images.githubusercontent.com/42200979/79557371-e22c1180-80bb-11ea-907c-fe1bb871bfb1.png)
![image](https://user-images.githubusercontent.com/42200979/79557399-ece6a680-80bb-11ea-8069-2f09c629abac.png)

**Comment by aharui** [comment]
This is a side-effect of #811

**Comment by pashminakazi** [comment]
@aharui Thank u so much Issue has been resolved
