### ISSUE TITLE
Field is blank by default

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#810]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Retail Inspection from Select in Menu
Go to Meter(Nozzel) Setup from Setups in Menu
File : com/dbz/modules/RI/dbzMeterNozzleSetup.mxml

the input for description is disabled in Flex and Royale as well for this Setup but in Flex it shows something already written in description field but in Royale description field is blank

In Royale: 
![image](https://user-images.githubusercontent.com/42200979/79561068-1e627080-80c2-11ea-995a-4c4659cd7284.png)

In Flex:
![image](https://user-images.githubusercontent.com/42200979/79561081-26221500-80c2-11ea-8e0d-e80437d3532e.png)

**Comment by aharui** [comment]
s:TextInput editable=false

**Comment by aharui** [comment]
This issue is also affected by #811.  Reopen if still an issue after fix for #811

**Comment by pashminakazi** [comment]
@aharui Still description field is blank after clicking NEW button

**Comment by aharui** [comment]
If something isn't working, one of the things you should do is check for exceptions being thrown.  There is an s:TextArea throwing an exception when you hit the New button.  I recommend replacing all s:TextArea with mx:TextArea.
