### ISSUE TITLE
TypeError: Cannot read property 'index' of null      (VirtualListView.js:91)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#811]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Retail Inspection from Select in Menu
Go to Meter(Nozzel) Setup from Setups in Menu
File : com/dbz/modules/RI/dbzMeterNozzleSetup.mxml

Wait to load this setup and then this exception occurs
![image](https://user-images.githubusercontent.com/42200979/79561352-ab0d2e80-80c2-11ea-88d7-1c5791b958dd.png)

![image](https://user-images.githubusercontent.com/42200979/79561493-e0b21780-80c2-11ea-8db9-60a4cb3be7ae.png)

**Comment by aharui** [comment]
Which component?  How many items?  What is the size of the component?

**Comment by aharui** [comment]
This is the same fix as the last fix for #789

**Comment by pashminakazi** [comment]
@aharui Still issue exist

**Comment by pashminakazi** [comment]
@aharui Thank u so much.Issue has been resolved
