### ISSUE TITLE
Application hangs on Screen when deleting detail record

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#812]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Carriage/Freight -> Driver Setup from Setups in Menu
File : com/dbz/modules/Common/dbzDriverMasterSetup.mxml

when delete record from detail grid application hangs on that screen.

**Comment by aharui** [comment]
This setup is affected by #811.  Reopen if still a problem after fix for #811.

**Comment by pashminakazi** [comment]
@aharui Still Application hangs on Screen when deleting record from detail grid

**Comment by aharui** [comment]
I hit delete button on right side and it seemed to work.  I could select another record.

**Comment by pashminakazi** [comment]
@aharui Thanks Alex.
Issue doesn't occur when deleting record from main grid,application hangs when deleting record from detail grid click on **Cross button** near detail grid
![image](https://user-images.githubusercontent.com/42200979/81662214-aedc6880-9456-11ea-8ac9-3e36b8bfe774.png)

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved
