### ISSUE TITLE
Uncaught TypeError: cls is not a constructor      (MXMLDataInterpreter.js:126)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#813]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to PSSM -> Facility from Setups in Menu
File : com/dbz/modules/Common/dbzFacilityMaster.mxml

when open this setup exception occurs
![image](https://user-images.githubusercontent.com/42200979/80073856-d29c4500-8561-11ea-9d98-f654a19eb4ca.png)

**Comment by aharui** [comment]
Examine the data array at the point of failure to determine which component should have been created there.

**Comment by pashminakazi** [comment]
I dont know how to do this

**Comment by aharui** [comment]
data is one of the parameters and other variables are accessing the array so you can tell how far into the array the code is looking.  Then see what is in the array (probably a null) but the rest of the array before and after should give you clues as to what component it was looking for.  There will be "id" properties that help.

**Comment by aharui** [comment]
```com.dbz.modules.components.ImageButton extends mx.controls.Image``` and is in a SWC.
It is referenced from MXML via ```xmlns:components="com.dbz.modules.components.*"```
But no goog.requires for it in the MXML output so it isn't loaded.

**Comment by aharui** [comment]
It is successfully compiled into many other modules.  I can't reproduce it in a simple test case.  Try adding a hidden ImageButton to dbzFacilityMaster as a workaround.

**Comment by pashminakazi** [comment]
@Embed source should be removed
