### ISSUE TITLE
Menu construction with xml data

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#815]
Here is the expected view when click on the button : 

![image](https://user-images.githubusercontent.com/5983818/80528545-c7e91200-899e-11ea-9948-0292aaee8fda.png)

live test [click](http://www.tlos.com.tr/royale_bugs/815/js-debug/)

Here is the test case : 
```

<?xml version="1.0" encoding="latin5" ?>

<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
			   xmlns:s="library://ns.apache.org/royale/spark"
			   xmlns:mx="library://ns.apache.org/royale/mx"
			   height="288" width="179"
			   >

	<fx:Script>
		<![CDATA[
			import mx.events.MenuEvent;
			import mx.controls.Menu;
			
			private function createAndShow():void {
				var myMenu:Menu = Menu.createMenu(null, filterMenuData, false);
				myMenu.id = "filterMenu"
				myMenu.labelField="@label";
				myMenu.addEventListener(MenuEvent.ITEM_CLICK, filterMenu_itemClickHandler);
				myMenu.show(statuFilterButton.localToGlobal(new Point(0,0)).x + 50, statuFilterButton.localToGlobal(new Point(0,0)).y + 25);
			}

			protected function filterMenu_itemClickHandler(event:MenuEvent):void {
				// to be implemented
				trace("Label of the menu item : " + event.label);
			}
				
		]]>
	</fx:Script>
	
	<fx:Declarations>
		<fx:XML format="e4x" id="filterMenuData">
			<menuitem label="Status Filter" id="statusFilter">
				<menuitem label="List All"/>			
				<menuitem label="Ready"/>
				<menuitem label="Waiting"/>
				<menuitem label="Working"/>
				<menuitem label="Successful"/>
				<menuitem label="Failed"/>
				<menuitem label="Time-out"/>
				<menuitem label="Skipped"/>
				<menuitem label="Stopped}"/>
				<menuitem label="Paused"/>
				<menuitem label="Disabled"/>
			</menuitem>
		</fx:XML>
	</fx:Declarations>

	<mx:Button id="statuFilterButton" label="Select Filter" click="createAndShow();"/>
	
</s:Application>

```

**Comment by aharui** [comment]
The Menu.show call will have an additional first parameter.

```myMenu.show(null, statuFilterButton.localToGlobal(new Point(0,0)).x + 50, statuFilterButton.localToGlobal(new Point(0,0)).y + 25);```

**Comment by nihavend** [comment]
I confirm that menu is displayed @aharui 

But with two problems (needs to be reopened)
1. menu displayed but but not as expected 
2. onClick handler is not functioning

live test [click](http://www.tlos.com.tr/royale_bugs/815/js-debug/)

![image](https://user-images.githubusercontent.com/5983818/81787873-56ff3980-950a-11ea-9cb2-ec6c4033c25b.png)

Displays the root element of the xml as menu and the rest as submenus which is not I needed. You can see the one in flex above.

**Comment by yishayw** [comment]
> The Menu.show call will have an additional first parameter.
> 
> `myMenu.show(null, statuFilterButton.localToGlobal(new Point(0,0)).x + 50, statuFilterButton.localToGlobal(new Point(0,0)).y + 25);`

@aharui , I know it's been a while, but can you explain why the extra param is necessary. There is code that only runs when parent is null without which the menu does not display properly in our app.
