### ISSUE TITLE
DropdownList width is smaller than its element's width

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#820]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Documents ->Setup Verification Plans from Setups in Menu
File : com/dbz/modules/Common/dbzSetUpVerificationPlan.mxml

Dropdownlist width should automatically set there width as the element in it
in some setup the width of dropdown is less than the width of its elements so the text is cutted of and text is overlapped on dropdown button

Text overlapping dropdown button :
![image](https://user-images.githubusercontent.com/42200979/80954522-f93a6580-8e16-11ea-928e-bbd5ac4c52ba.png)

width of element is greater than the dropdown width and it is cutted off its text

This should be **verfication plan for procurement** but it is only showing **verfication plan for** 
![image](https://user-images.githubusercontent.com/42200979/80954803-854c8d00-8e17-11ea-8fd6-a1baef80e8c7.png)
![image](https://user-images.githubusercontent.com/42200979/80954873-a90fd300-8e17-11ea-857c-28cfdd8e6958.png)

**Comment by aharui** [comment]
I added clipping in 9cc8965d1ebfa2dea300521dfb32f78c184257ae

Maybe your long labels are breaking to another line.  In your CSS you can try adding

.ListItemRenderer {
    white-space: nowrap;
}

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved
