### ISSUE TITLE
s:List change event is not being triggered

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#830]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Import from Select in Menu
Go to Import -> Import Chargesfrom Setups in Menu
File : com/dbz/modules/IMP/dbzImportChargesSetup.mxml

Click on this button :
https://user-images.githubusercontent.com/42200979/77047368-6ec4b080-69e6-11ea-9fda-6f316d7c0ddc.png
New window will be opened which is : com/dbz/modules/IMP/dbzimportChargerFormulaPopup

**In Flex** 
when we double click any element from s:List with ID **lstSysVariable** named system Columns a change event is triggered **fn_addSysColumns**
```
private function fn_addSysColumns(e:Event):void {
				selectedListItem = List(e.currentTarget).selectedItem;
				impchg_Formula_Disp.text = impchg_Formula_Disp.text + " " + selectedListItem.label;
				impchg_Formula.text = impchg_Formula.text + " " + selectedListItem.id;
				
			}
```
and that element will be added in Formula Editor which is mx:TextArea
		`<mx:TextArea id="impchg_Formula_Disp" maxChars="400" width="593" tabIndex="1" x="1" y="2" height="146" valueCommit="bValidate=false;"/>`

![image](https://user-images.githubusercontent.com/42200979/81812152-2be30d00-953f-11ea-9dca-cf4c3629e326.png)

**In Royale** 
when i double click on any element from system column nothing is added in Formula Editor TextArea because change event is not being triggered
![image](https://user-images.githubusercontent.com/42200979/81812417-854b3c00-953f-11ea-8876-69ae0e0e4fd7.png)

**Comment by aharui** [comment]
On the first click of the double-click, does the list selection change?  If you make a simple test case with s:List, does the list selection change?

**Comment by pashminakazi** [comment]
@aharui Thanks now change event is being triggered..
but there's an exception in function which is called on change event. 
![image](https://user-images.githubusercontent.com/42200979/82033841-bef28300-96b6-11ea-86a6-24d6a21c0ecf.png)
Change function : 
```
private function fn_addSysColumns(e:Event):void {
				selectedListItem = List(e.currentTarget).selectedItem;
				impchg_Formula_Disp.text = impchg_Formula_Disp.text + " " + selectedListItem.label;
				impchg_Formula.text = impchg_Formula.text + " " + selectedListItem.id;
				
			}

```
selectedListItem is null that's why selectedListItem .label is null
why selectedListItem is setted null?
selectedListItem is object variable

**Comment by pashminakazi** [comment]
@aharui Thank u so much.
On a single click value is added in formula editor 2 times
![image](https://user-images.githubusercontent.com/42200979/82193382-c14f1a00-990e-11ea-8437-8c1bee3195c2.png)
