### ISSUE TITLE
MX - Computed Font Size Different on Chrome and IE

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#835]
In Chrome it's 12px, in IE it looks like 16px. As a result, layout breaks in IE. 

In theory, these lines in defaults.css should fix this, but they don't.

* {
	font-family:	Arial;
	font-size:		12px;

}

**Comment by yishayw** [comment]
The problem manifests only in nested elements, so it could be that the global selector is working but there's a different problem.

**Comment by aharui** [comment]
When you say "computed" is that using getComputedStyles() or some other technique?  IIRC, browser and user stylesheets can win over the * selector, or some default padding/margin/border will be added to the effective size of the component.

**Comment by yishayw** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<mx:Application xmlns:mx="library://ns.apache.org/royale/mx" xmlns:fx="http://ns.adobe.com/mxml/2009">
	<fx:Script>
		<![CDATA[
			private function init():void
			{
				COMPILE::JS
				{
					trace('computed font size: ' + getComputedStyle(document.getElementsByClassName("Label")[0]).fontSize);
				}
			}
		]]>
	</fx:Script>
	<mx:Label text="Hello from main" creationComplete="init()"/>
</mx:Application>
```

Yes, for IE the result is 16px, for Chrome it's 12px.

Not a nested problem as I'd thought.

**Comment by aharui** [comment]
Someone with vision impairment can ask for a bigger font.  If our components do not respond to that we should consider doing that.  But if you want to force 12 like Flex pretty much did, I think you have to use CSS Type Selectors.  IIRC, the browsers specify Type Selectors for many HTMLElements which I think are evaluated before *.

-Alex

**Comment by yishayw** [comment]
I think for emulation we should probably go with 12 like Flex. At least the app I'm porting would expect that.

Interesting that the below code works for IE, i.e. global selector is effective. I'll see if I can figure out the difference with the Royale code I posted above.

```
<!DOCTYPE html>
<html>
<head>
<style>
	* {
		font-size: 18px;
		font-family: Arial;
	}
</style>
</head>
<body>
	<span>Hello</span>
</body>
</html>

```

**Comment by yishayw** [comment]
I was ignoring messages like

SEC7113: CSS was ignored due to mime type mismatch

Which go away when serving from a localhost instead of just opening a file in the browser. Problem gone away.
