### ISSUE TITLE
2 Rows highlighted at a time 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#851]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Feasibility from Select in Menu
Go to Gain/Loss from Setups in Menu
File : com/dbz/modules/FS/dbzGainLossMasterSetup.mxml

Delete any detail record then 2 rows will be highlighted,Only one row (first row) should be highlighted
![image](https://user-images.githubusercontent.com/42200979/84013025-d1986900-a991-11ea-9a80-8686bff6a1b1.png)

**Comment by aharui** [comment]
I was unable to connect to the VDI.  Does this happen in other lists or only this one?  I could not reproduce it in a small test case.  Can you reproduce it in a smaller test case?  If not, what are some differences that could affect selection?

**Comment by pashminakazi** [comment]
@aharui This is happening in many other setup,i dnt know why.when i delete detail record then two records will be selected at a time.you can check this in driver setup and Gain/Loss setup
Module Sales -> carriage/Freight -> Driver Setup 
File Path : com/dbz/modules/Common/dbzDriverMasterSetup

Module Feasibility -> Gain/Loss  
File Path : com/dbz/modules/FS/dbzGainLossMasterSetup

**Comment by aharui** [comment]
The source does not match the JS output, so I am not going to investigate this issue as it may be using old code.  I did find that programmatic setting of selectedIndex was not working in my latest ADG so I pushed a change that should fix that.

**Comment by pashminakazi** [comment]
@aharui This issue is occuring in all setups,at a time 2 records are selected even after your commit
![image](https://user-images.githubusercontent.com/42200979/84360433-7eb5f000-abe3-11ea-9f9c-6c17ed1aa165.png)

**Comment by greg-dove** [comment]
@aharui I can't recall exactly, but I have seen this at one point when I was working on datagrids. I think it might be either after dataProvider changes or sort changes with prior selection, but tbh I can't remember for sure. I will try to check tomorrow to see if I can repro if you did not establish the repro yet.

**Comment by aharui** [comment]
I pushed a change yesterday where programmatic selection change wasn't selecting anything instead of selecting two things in ADG so make sure you have latest code before doing any testing.  ADG handles multiple selection so sometimes stale selectedIndices affect what is selected.  That said, it occurred to me this morning that the app uses a validateNow() after delete and I think that's probably the problem here.

**Comment by pashminakazi** [comment]
@aharui Thanks issue resolved
