### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined    (AdvancedDataGridLayout.js:40)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#852]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Specific Gravity @60-60degF from Setups in Menu
File : com/dbz/modules/PUR/dbzSpecificGravitySetup.mxml

![image](https://user-images.githubusercontent.com/42200979/84184992-c5063480-aaa7-11ea-9361-4657fa15ae63.png)

![image](https://user-images.githubusercontent.com/42200979/84185009-ccc5d900-aaa7-11ea-9b0d-8f2709ca7200.png)

**Comment by pashminakazi** [comment]
@aharui Still doesn't work after your commit
![image](https://user-images.githubusercontent.com/42200979/84360825-26cbb900-abe4-11ea-83a1-a64628056c4e.png)
![image](https://user-images.githubusercontent.com/42200979/84360880-3e0aa680-abe4-11ea-8646-95b6cc6b282e.png)

**Comment by pashminakazi** [comment]
![image](https://user-images.githubusercontent.com/42200979/84362688-0fda9600-abe7-11ea-9953-ea303ef8af61.png)

**Comment by aharui** [comment]
That's a different error condition.

**Comment by aharui** [comment]
If columns == null, return without doing anything.

**Comment by pashminakazi** [comment]
When i have added 
```
if (columns == null) {
return;
} 
```
in DataGridLinesBeadForICollectionView then this same exception occurs in DataGridColumnResizeBead then i added 
```
if (columns == null) {
return;
} 
```
 in DataGridColumnResizeBead  and then again this exception occurs in DataGridLinesBeadForICollectionView but on other line then i added this again there and exception gone.
Thanks
