### ISSUE TITLE
DropdownList selected Value is empty in Setup

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#856]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Carriage/Freight -> Tank Lorry Seals Setup from Setups in Menu
File : com/dbz/modules/SAL/dbzSealsSetup.mxml

Click on New Button Select Site and click Save and then click Add button popup will be opened,
Seals type dropdown has no selectedIndex,why?
SelectedIndex=0 and labelField="label" but no selected value is shown on dropdown

![image](https://user-images.githubusercontent.com/42200979/84271028-fe40b200-ab44-11ea-97fe-9cee15040d81.png)
![image](https://user-images.githubusercontent.com/42200979/84271041-03056600-ab45-11ea-94eb-43b814b93956.png)

**Comment by pashminakazi** [comment]
@aharui Problem doesn't occur in Simple test Case,then why in this setup dropdown selection is showing empty? there's no change in simple test case dropdown and this dropdown

**Comment by aharui** [comment]
I don't see a "New" button when I run on the VDI (I do see it in the screenshots).

**Comment by pashminakazi** [comment]
@aharui There should be a screen resolution Problem thats why New button didn't shown on your screen

**Comment by aharui** [comment]
If I can't access the "New" button then I cannot help you.  Maybe adjust your code so that it can fit on the display on the VDI.  There is a lot of space to the left of the New button.

It may also help if you post the code for that DropDownList.

**Comment by pashminakazi** [comment]
Now all buttons will be visible to you

Click on New button then give value in Site Picklist and click save then click Add button.
In com/dbz/modules/SAL/dbzSealsSetupDetail.mxml
Check the Seal Type Dropdown
```
[Bindable] private var arrNatureDataProvider:ArrayCollection =
				new ArrayCollection([{label:"Button",id:0},{label:"Click", id:1}]);
<s:DropDownList id="sd_Seal_Type" tabIndex="12" x="97" y="136" width="110" height="20" 
			dataProvider="{arrNatureDataProvider}" selectedIndex="0" />
```
I also added labelField="label" but still selection is empty for dropdown

**Comment by pashminakazi** [comment]
![image](https://user-images.githubusercontent.com/42200979/85379642-6f289680-b555-11ea-9dc5-1137c181ff28.png)
![image](https://user-images.githubusercontent.com/42200979/85379714-81a2d000-b555-11ea-9d20-d3fbfa823d8e.png)
![image](https://user-images.githubusercontent.com/42200979/85379797-98492700-b555-11ea-8db2-4afb70bea0f4.png)
![image](https://user-images.githubusercontent.com/42200979/85379862-adbe5100-b555-11ea-9225-bdb55f62164f.png)

**Comment by aharui** [comment]
I don't understand what the images are meant to show or what the differences are between them.

If it means that the prompt is being displayed, there may be a timing issue where selectedIndex=0 should override the prompt.  Try it in a simple test case.

**Comment by pashminakazi** [comment]
In simple test case it is working fine,but in many setups dropdown is empty.
I compared other dropdown with this dropdown but nothing is changed between
both dropdowns

**Comment by aharui** [comment]
The correct text is in the display but is hidden for some reason, maybe the clipPath

**Comment by pashminakazi** [comment]
@aharui Thank u so much,Issue resolved
