### ISSUE TITLE
Column Editor goes on 1st column instead of any Column

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#863]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Recieveable from Select in Menu
Go to Sales Commission Scheme Setup from Setups in Menu
File : com/dbz/modules/AR/dbzSalesCommissionScheme.mxml

Click on New Button then Plus(+) and then again + button on New window
if i want to add the value in 2nd,3rd,4th or any column and i double click on that column,the editor goes on 1st column and take input in 1st column for Every column

In this Image I click on 3rd column and system is taking input in 1st column,when i input in 1st column it will be saved in 3rd column,but it should take input in 3rd column if i double click on 3rd column
![image](https://user-images.githubusercontent.com/42200979/84495608-de37fc80-acc4-11ea-9133-7d12faf52ab3.png)

**Comment by aharui** [comment]
What happens if you single-click?  Maybe a double-click handler is affecting the editor.  In my test cases, editing works as expected.  Does the grid have any edit event handlers?

**Comment by pashminakazi** [comment]
Same thing happens for single and double click

**Comment by pashminakazi** [comment]
@aharui Thank u so much Issue has been resolved
