### ISSUE TITLE
mx:RichTextEditor is just a textbox,no designing properties shown in Royale

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#873]
mx:RichTextEditor's bold,italic,underline.font size,font style,and color picker,bullets,align left,right,center is not visible in Royale.
Please implement

In Flex:
![image](https://user-images.githubusercontent.com/42200979/85559144-df611600-b642-11ea-8d5c-ae8ddbed2fce.png)

In Royale:
![image](https://user-images.githubusercontent.com/42200979/85559199-f0118c00-b642-11ea-9e1e-715fdc8d6575.png)

**Comment by aharui** [comment]
What happens with the output?  Do you want some sort of format for the text like HTML? RTF?  Something else?

**Comment by pashminakazi** [comment]
I want these all functionalities In mx:RichTextEditor
![properties](https://user-images.githubusercontent.com/42200979/85838137-8e702f80-b7b2-11ea-9025-0580ad30ee74.png)

**Comment by aharui** [comment]
Sure but what happens to the text after the user edits it?  Is it converted to HTML, RTF, something else?

**Comment by aharui** [comment]
I added an mx:TinyEditor you can try as a replacement for mx:RichTextEditor.

To use it you must get the latest compiler.

Also, you will need to run in some folder
`npm init`
`npm install tiny-editor  --save`

Then after building your Royale app, copy the node_modules folder to appropriate bin/js-debug folder so it ends up as bin/js-debug/node_modules.

It may not work on IE11.

**Comment by pashminakazi** [comment]
I git clone new sdk
1) Compile royale-compiler
2) Compile royale-asjs
3) run npm init and npm install tiny-editor --save in royale-asjs
4) then compile my first library dbzLib
5) then replace mx:RichTextEditor with mx:TinyEditor in D:/DBIZCOMLIB/src/com/dbz/modules/Common/dbzProductProfileSpecsPopup.mxml
6) then run npm init and npm install tiny-editor --save in DBIZCOMLIB
7) compile DBIZCOMLIB 
8) then run npm init and npm install tiny-editor --save in D:\DBIZSOL\Main\Royale

After doing this all when i compile my Royale app this error occurs :
![image](https://user-images.githubusercontent.com/42200979/86010684-2a10d280-ba35-11ea-8df9-59850cb4eb38.png)

**Comment by pashminakazi** [comment]
console : https://paste.apache.org/eulk1

**Comment by aharui** [comment]
That error means that you are not using the latest compiler.  Run `ant wipe-all` in royale-compiler to make sure everything rebuilds.

**Comment by pashminakazi** [comment]
I have compiled latest sdk with ant wipe-all.
But there's some problem in compiler
When i compile royale-compiler on my vdi there's some dependencies which
can't be downloaded from internet.
All dependencies downloaded except 5 or 6 dependencies
In royale-compiler/compiler-externs/target/ there are es3.js,
es5.js,
es6.js,
es6_collections.js

System downloads es3 and es6
And can't download
es5,es6_collections

And In royale-compiler/compiler-externs/target/downloads
html5.js
Gecko_css
css_dom2 or something like that
These 5 or 6 dependencies can't be downloaded at the time of compilation
So the build failed whenever i compiled new compiler
So i have to place these dependencies from old compiler so then it will be
compiled successfully.otherwise all other things in compiler is git clone
and new and compiled today

**Comment by aharui** [comment]
If you can manually get those files, that should be ok.  Or you can comment out the <antcall target="tests" /> in compiler-externc/build.xml.  The main goal is to get royale-compiler to build, then build the royale-asjs again, then your app.

**Comment by pashminakazi** [comment]
I have compile latest royale-compiler and then royale-asjs and then my app
but this issue occurs

**Comment by pashminakazi** [comment]
@aharui Thank u so much TinyEditor is working now

**Comment by aharui** [comment]
Your company should donate money to TinyEditor developer.

**Comment by pashminakazi** [comment]
Ok Alex

**Comment by pashminakazi** [comment]
I will discuss with my company to donate money to TinyEditor developer.
