### ISSUE TITLE
mx:Image uploading is not working

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#878]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Security -> Users from Setups in Menu
File : com/dbz/modules/SEC/dbzUsersTabSetup.mxml

dbzUsersTabSetup is loading dbzUserSetup_Financials.mxml
Path for dbzUserSetup_Financials : com/dbz/modules/SEC/dbzUserSetup_Financials.mxml

mx:Image is used in dbzUserSetup_Financials
when i click upload button and upload any .png,.jpg image nothing happens in Royale with any exception.
Image doesn't uploaded

When i click Upload button this function called
```
private function btnUploadClick_EH(event:MouseEvent):void {
	var imagesFilter:FileFilter = new FileFilter("Images", "*.jpg;*.jpeg;*.JPG;*.JPEG;*.gif;*.png");
	strFileRef = new FileReference();
	strFileRef.addEventListener(Event.SELECT, fn_FileSelect_EH);			
	strFileRef.browse([imagesFilter]);
	picRemoved =false;
}

private function fn_FileSelect_EH(event:Event):void {
	if(event.target.size > maxImageSize)
	{
	   Alert.show ("Image size should be less than 300KB");
	}
	else
	{
	   strFileRef.addEventListener(Event.COMPLETE, fn_FileUpload_EH);
	   strFileRef.load();
	}
}
private var mobj_ImgBytes:ByteArray= null;
private function fn_FileUpload_EH(event:Event):void {
	strFileRef.load();
	mobj_ImgBytes = strFileRef.data;
	bPicChange = true;
	profilePic.source = mobj_ImgBytes;
}
```

These all functions executed
![image](https://user-images.githubusercontent.com/42200979/86162183-d7641300-bb27-11ea-8c85-ed717a83014e.png)

In Flex Image uploaded : 
![image](https://user-images.githubusercontent.com/42200979/86162540-61ac7700-bb28-11ea-8544-c23894be48d5.png)

**Comment by aharui** [comment]
Loading images from loaded data is trickier in Royale because the browser can't handle image data like Flash does.  Your code will have to detect the file type and encode the data.

```
		import mx.utils.ByteArray;
		import org.apache.royale.utils.Base64;

        var encodedData:String = Base64.encode(strFileRef.data as ByteArray);
	profilePic.source = "data:image/png;base64," + encodedData;
```

I think you have to swap out `image/png` for `image/jpeg` and other formats depending on what got loaded.

**Comment by pashminakazi** [comment]
@aharui Thank u so much,Issue resolved
