### ISSUE TITLE
Jewel and ClipBead

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#883]
Hi guys, 
**Some context**
I am trying to implement the CSS clip-path property in my application images ...
https://developer.mozilla.org/es/docs/Web/CSS/clip-path

My intention is to use the Circle () function without arguments to give the images an Avatar look.
```
.avatar{
    -webkit-clip-path: circle();
    clip-path: circle();
}
```

**The problem**
When trying to compile the project, the SDK cannot solve it if we introduce it to the CSS of the application.

**My approach**
I am currently using Jewel controls and have seen the ClipBead bead
https://royale.apache.org/asdoc/index.html#!org.apache.royale.svg/ClipBead

I haven't found much information about the bead in the API, nor have I found any usage examples in the TourDeJewel project or in any other SDK sample projects.

Is this bead compatible with Jewel controls? How should I use it?

I've been looking at the definition of the bead, and I've seen that it allows passing a path as an argument that will be applied to the Sprite.

Is there any chance of being able to directly pass the Circle () function the same way we do in CSS?

**Comment by yishayw** [comment]
Sorry for the late answer. We're using it with org.apache.royale.svg.Image. If you can use it with that, you can do something like:

<svg:Image src="...">
  <svg:beads>
     <svg:ClipBead id="myClipBead"/>
  </svg:beads>
</svg:Image>

And then:
var myPath:PathBuilder= new PathBuilder();
myPath.draw...
myClipBead.path  = myPath.

I'm not sure this is what you are looking for - specifically I'm not sure if we have a simple way to create a circle with PathBuilder. It might be better to try to create your own bead.
