### ISSUE TITLE
FileBrowser.as always dispatches cancel event.

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#886]
**Some Context**
Depending on the browser, a focus, key or mouse handler is triggered ... when the file selection form is closed.
Then maybeCancel function is called with a timeout of 100ms:

![image](https://user-images.githubusercontent.com/55754204/87284780-0d759f80-c4f7-11ea-9732-86b17dda9a4f.png)

The maybeCancel function, analyzes if there are selected files, if there are no files, interprets it as that there has been a cancellation (since we cannot get the cancel event directly):
![image](https://user-images.githubusercontent.com/55754204/87285071-5decfd00-c4f7-11ea-83dd-22a206e300bb.png)

**Issue**
When calling maybeCancel function, the length of the file list is always 0, so cancel event is always dispatched.

**Our solution**
Increasing the response time of the maybeCancel function to 150ms solves the problem.
![image](https://user-images.githubusercontent.com/55754204/87286366-12d3e980-c4f9-11ea-8c2b-7deba1897c5f.png)

**Comment by carlosrovira** [comment]
Hi Javier, 
if others don't propose any other solution I think we can increment that timeout. Will wait some hours, to see if others propose  a better solution if not will increment the timeout.

**Comment by aharui** [comment]
Probably the timeout should be in a public static variable so it can be tweaked for different circumstances.

**Comment by carlosrovira** [comment]
ok Alex, will do that way

**Comment by javeiga-iest** [comment]
> Probably the timeout should be in a public static variable so it can be tweaked for different circumstances.

good approach
