### ISSUE TITLE
Label text strings are "trimmed"

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#89]
Any space in the text property of a label are "trimmed". In some cases this can give odd results.

A contrived example:
(obviously the label could be replaced by a single label in this case but this is just to illustrate the point / issue.)

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

   <js:valuesImpl>
       <js:SimpleCSSValuesImpl/>
   </js:valuesImpl>

    <js:beads>
         <js:ApplicationDataBinding />
    </js:beads>


    <fx:Script><![CDATA[
        [Bindable] public var name:String = "John";
        ]]></fx:Script>

   <js:initialView>
       <js:View>
           <js:Container>
               <js:beads>
                   <js:HorizontalLayout />
               </js:beads>
               <js:Label text="Hi "/>
               <js:Label text="{name}"/>
               <js:Label text=" and welcome"/>
           </js:Container>
       </js:View>
   </js:initialView>
</js:Application>
```

Produces this output:
![2017-11-15_15-14-24](https://user-images.githubusercontent.com/144504/32818571-298174d8-ca18-11e7-9cba-68a470892a51.png)

HTML keeps spaces for instance the spaces are not trimmed in these HTML examples:
```
<span>Hi </span><span>John</span><span> and welcome</span>
<span>value: </span><input type="text" />
```

Also the same in Flex:
```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
			   xmlns:s="library://ns.adobe.com/flex/spark" 
			   xmlns:mx="library://ns.adobe.com/flex/mx">
	
	<s:HGroup>
		<s:Label text="value " />
		<s:TextInput />
	</s:HGroup>
	
</s:Application>
```

**Comment by justinmclean** [comment]
Note the space are not actually trimmed this is caused by the display: inline-block; style.

**Comment by bigosmallm** [comment]
This is as per HTML specs.  By default the `white-space` CSS property is `normal`, i.e sequence of whitespaces are collapsed.  
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by justinmclean** [comment]
Right don't you think this may surprise users?

**Comment by justinmclean** [comment]
Actually you are incorrect  in that a starting or training space is removed with white-space normal. White-space normal only collapses more than one white space.

In fact the example I give above illustrates exactly this:
<span>Hi </span><span>John</span><span> and welcome</span>

Do you still think this is invalid?

**Comment by Harbs** [comment]
If you want regular span elements, you can use <js:Span/> instead of <js:Label/>

**Comment by justinmclean** [comment]
So do you agree that your comment that this is as per HTML specs and because of white-space normal it's incorrect and not relevant to this issue? And that's the reason you closed this issue and marked it "invalid" is also incorrect? White-spaxce normal does not remove white space at the start or end, sure it may collapse it if it exists but will not remove it altogether.

**Comment by justinmclean** [comment]
I didn't want to use spans in this particular case but even if you do as suggested above it also trims the starting and ending whitespaces. I tried a few variations of the code below.

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

   <js:valuesImpl>
       <js:SimpleCSSValuesImpl/>
   </js:valuesImpl>

    <js:beads>
         <js:ApplicationDataBinding />
    </js:beads>


    <fx:Script><![CDATA[
        [Bindable] public var name:String = "John";
        ]]></fx:Script>

   <js:initialView>
       <js:View>
           <js:Container width="400" height="100">
               <js:beads>
                   <js:HorizontalLayout />
               </js:beads>
               <js:Span text="Hi "/>
               <js:Span text="{name}"/>
               <js:Span text=" and welcome"/>
           </js:Container>
       </js:View>
   </js:initialView>
</js:Application>
```

It would be a good idea IMO to leave issues open until suggestion have been tested or if feedback is given let the person who raised the issue close it or wait until discussion has finished before closing it.

This is not the first time that issues have been closed prematurely.

**Comment by Harbs** [comment]
Please do your research instead of raising issues.

There is no trimming going on. It's standard HTML behavior. Labels use `white-space: nowrap; display: inline-block;` to get consistent display of single-line labels. That's behaving as designed.

`<js:Span/>` maps to a one-to-one output of `<span>` elements. There is no CSS applied to that, but it will pick up whatever CSS is applied to the parent elements.

You likely need to nest it in a `<js:Div>` element or `<js:Group>`. If you are using `<js:Container>` you will get `white-space: nowrap;` from that.

Your browser has developer tools. Use them to understand what's going on.
