### ISSUE TITLE
Uncaught TypeError: GF.UIDBuffer is undefined when compiling in release SDK 0.9.8 build#2020-07-31

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#898]
Hi,
I done a small website with Royale.
Works fine in debug mode but when compiling it in release I have this issue when using AsyncToken

```
Uncaught TypeError: GF.UIDBuffer is undefined
    createUID UIDUtil.js:73
    createUID UIDUtil.js:44
```

![image](https://user-images.githubusercontent.com/6851433/90423803-68ce1b00-e0bd-11ea-9faa-00f8b248e5f5.png)

Here is my asconfig.json : 
```
 {
    "config": "royale",
    "compilerOptions": {
        "debug": false,
        "targets": ["JSRoyale"],
        "source-path": [
            "src/main/resources"
        ],
        "source-map": true,
        "html-template": "src/main/resources/jewel-example-index-template.html",
		"theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css",
		"js-library-path": ["${royalelib}/js/libs/MXRoyaleJS.swc"]
    },
    "copySourcePathAssets": true,
    "additionalOptions": "-js-dynamic-access-unknown-members=true",
    "files":
    [
        "src/main/royale/App.mxml"
    ]
}
```

Do I miss something ? I don't know where to dig.
Thanks for your help...

**Comment by cristallium** [comment]
I would like to add that issue is not on compile time, but when the application is using AsyncToken

**Comment by joshtynjala** [comment]
> 2020-07-31

Have you tried a newer build? I think that this issue is fixed.

**Comment by cristallium** [comment]
many thanks Josh, tried with today build, and worked fine !
Next time I will try last build before asking ...
