### ISSUE TITLE
Spans don't layout horizontally as expected

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#90]
This code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/royale/basic">

   <js:valuesImpl>
       <js:SimpleCSSValuesImpl/>
   </js:valuesImpl>

    <js:beads>
         <js:ApplicationDataBinding />
    </js:beads>


    <fx:Script><![CDATA[
        [Bindable] public var name:String = "John";
        ]]></fx:Script>

   <js:initialView>
       <js:View>
           <js:Container width="400" height="100">
               <js:Span text="Hi "/>
               <js:Span text="{name}"/>
               <js:Span text=" and welcome"/>
           </js:Container>
       </js:View>
   </js:initialView>
</js:Application>
```

or this:
```
           <js:Container width="400" height="100">
               <js:Span text="Hi "/><js:Span text="{name}"/><js:Span text=" and welcome"/>
           </js:Container>
```

Displays like this which is probably unexpected:
![2017-11-15_19-11-17](https://user-images.githubusercontent.com/144504/32825357-ca22aa0e-ca38-11e7-9041-a68b4a764b77.png)

When this:
```
<span>Hi </span><span>John</span><span> and welcome</span>
```

Displays as this:
<span>Hi </span><span>John</span><span> and welcome</span>

**Comment by Harbs** [comment]
Please stop raising new issues instead of doing research.

**Comment by justinmclean** [comment]
Can you please give a reason for close and marking stuff as invalid before doing so.

**Comment by Harbs** [comment]
I explained it here:
https://github.com/apache/royale-asjs/issues/89#issuecomment-344519105

**Comment by justinmclean** [comment]
Which explains nothing. Please point to documentation or an example or something that actually solves the issue raised. It's would also be polite to wait until the person who raised the issue respond before closing it.

**Comment by Harbs** [comment]
I thought you could find this on your own:
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
