### ISSUE TITLE
Sorting arrays with Array.NUMERIC not working correctly

### ISSUE THREAD

**Issue by jleistner** [apache/royale-asjs#900]
In Flash it was possible to sort arrays numerically by passing the option `Array.NUMERIC` to the sort function ([reference](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Array.html#sort())) even if the array didn't contain numbers. This option also exists in Apache Royale but is not working correctly.

Code to reproduce:
```
trace("---- TEST START");
var a: Array = ["1", "10", "2", "20", "100"];
a.sort(Array.NUMERIC);
trace(a);
trace("---- TEST END");
```
Result in Flex/Flashplayer:
```
[trace] ---- TEST START
[trace] 1,2,10,20,100
[trace] ---- TEST END
```

Result in Apache Royale:
```
---- TEST START
Array(5) [ "1", "10", "100", "2", "20" ]
---- TEST END
```

Apache Royale ignores the option `Array.NUMERIC` and just sorts lexicographically.

**Comment by Harbs** [comment]
This is almost certainly due to the array being strings instead of numbers. I believe the fix is simple, but I don't have time to test.

Language.as has the following function:
````
        private static function compareAsNumber(a:Object, b:Object):int
        {
            if (a > b)
            {
                return muler;
            } else if (a < b)
            {
                return -muler;
            }
            return 0;
        }
````

Making the following change should fix this issue:
````
        private static function compareAsNumber(a:Object, b:Object):int
        {
            a = +a;
            b = +b;
            if (a > b)
            {
                return muler;
            } else if (a < b)
            {
                return -muler;
            }
            return 0;
        }
````
Can you test and create a PR if it fixes it?

Thanks!
Harbs

**Comment by jleistner** [comment]
Hi Harbs,

I did some testing and
```
a = +a;
b = +b;
```
is not working for me (`Implicit coercion of a value with static type Object to a possibly unrelated type Number.`) but
```
a = Number(a);
b = Number(b);
```
is. If casting the values like this is acceptable I would open a PR.

On a side note:
To be able to build Apache Royale on Linux (not sure if this is OS dependent) I had to rename [royale-asjs/frameworks/js/projects/JQueryJS ](https://github.com/apache/royale-asjs/tree/develop/frameworks/js/projects/JQueryJS) to jQueryJS (lower case 'j') because the project name in [royale-asjs/frameworks/projects/JQuery/build.xml:22](https://github.com/apache/royale-asjs/blob/develop/frameworks/js/projects/JQueryJS/build.xml#L22) uses a lower case 'j' as well. Should I address this in the PR as well and if so, would it be better to rename the folder or to change the project name?

Thanks
Jonathan

**Comment by Harbs** [comment]
Sure `Number()` is good.

**Comment by carlosrovira** [comment]
Hi @jleistner the jquery issue better in a separate PR. Thanks!
