### ISSUE TITLE
Error with Jewel DataGrid after upgrade to last nightly build

### ISSUE THREAD

**Issue by SolidSoft-Lda** [apache/royale-asjs#904]
After I upgrade to the last nightly build, I started to have the following error with a simple Jewel DataGrid use case.

Isolated simple use case with a Jewel DataGrid:

    <j:DataGrid>
        <j:columns>
            <j:DataGridColumn label="Test"/>
        </j:columns>
    </j:DataGrid>

Error in console:

null: Uncaught TypeError: Cannot read property 'rowHeight' of null
: org.apache.royale.jewel.beads.views.DataGridView.createLists @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/beads/views/DataGridView.js:176:93
org.apache.royale.jewel.beads.views.DataGridView.createChildren @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/beads/views/DataGridView.js:103:10
org.apache.royale.jewel.beads.views.DataGridView.set__strand @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/beads/views/DataGridView.js:402:8
org.apache.royale.core.ElementWrapper.addBead @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/core/ElementWrapper.js:115:15
org.apache.royale.core.HTMLElementWrapper.addBead @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/core/HTMLElementWrapper.js:43:65
org.apache.royale.core.UIBase.addBead @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/core/UIBase.js:372:53
org.apache.royale.utils.loadBeadFromValuesManager @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/utils/loadBeadFromValuesManager.js:41:16
org.apache.royale.core.UIBase.addedToParent @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/core/UIBase.js:554:27
org.apache.royale.jewel.supportClasses.group.GroupBase.addedToParent @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/supportClasses/group/GroupBase.js:58:84
org.apache.royale.jewel.Group.addedToParent @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/Group.js:67:59
org.apache.royale.core.UIBase.addElement @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/core/UIBase.js:398:5
org.apache.royale.jewel.supportClasses.group.GroupBase.addElement @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/supportClasses/group/GroupBase.js:154:81
org.apache.royale.utils.MXMLDataInterpreter.initializeStrandBasedObject @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:235:12
org.apache.royale.utils.MXMLDataInterpreter.generateMXMLArray @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:121:53
org.apache.royale.utils.MXMLDataInterpreter.generateMXMLInstances @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:265:49
org.apache.royale.jewel.View.addedToParent @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/View.js:63:49
org.apache.royale.jewel.Application.addElement @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/Application.js:136:5
org.apache.royale.jewel.Application.initialize @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/Application.js:282:10
org.apache.royale.jewel.Application.start @ /Users/hugo/Desktop/GC/bin/js-debug/org/apache/royale/jewel/Application.js:251:10
<anonymous> @ /Users/hugo/Desktop/GC/bin/js-debug/index.html:903:13

**Comment by greg-dove** [comment]
I looked into this quickly today, but I could not repro the issue yet.
My test was simply to paste your code into a new GridCell in Tour De Jewel DataGridPlayGround.mxml, like so:
```
<j:GridCell desktopNumerator="1" desktopDenominator="2" tabletNumerator="1" tabletDenominator="2" phoneNumerator="1" phoneDenominator="1">
	<j:Card>
		<j:CardPrimaryContent>
			<j:DataGrid>
				<j:columns>
					<j:DataGridColumn label="Test"/>
				</j:columns>
			</j:DataGrid>
		</j:CardPrimaryContent>
	</j:Card>
</j:GridCell>
```

I tested the above in debug build of Tour de Jewel, and did not see the problem yet. I will come back to it tomorrow or the following day and investigate more. I am not using nightly build, I am using my local Royale build, so I will try to see if there is any difference there too.

**Comment by carlosrovira** [comment]
Hi, I tried the same and worked right in my local.
Maybe could be a problem in the nightly build? please download the new one from this night and let us know if it continue failing. If that's the case we'll take a look. In the meantime you'll need to build from sources (if that's the case)
Thanks for reporting

**Comment by carlosrovira** [comment]
Hi Hugo,
I can almost ensure you're not running latest code since DataGridView line reported is empty in the actual version, so I think something is wrong with your development Royale SDK.

**Comment by SolidSoft-Lda** [comment]
I was my fault.
Very sorry for that.
I saw your post today and I tried now to do a clean before build and that action put everything to working again and also the original bug fixed with the nighlty build (DataGrid don't allow the propor use of TextInput) are all fixed.
