### ISSUE TITLE
Unable to access Array items by index 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#905]
TypeError: cannot read property '1' of undefined at arrTempObjContainer[1] 
arrTempObjContainer an Array

Code : 
![image](https://user-images.githubusercontent.com/42200979/92476539-90199300-f1f8-11ea-9a13-f0e01886623e.png)

![image](https://user-images.githubusercontent.com/42200979/92476798-f30b2a00-f1f8-11ea-820f-5cc22943e81b.png)

![image](https://user-images.githubusercontent.com/42200979/92477164-8a707d00-f1f9-11ea-8899-308a649c1ecf.png)

![image](https://user-images.githubusercontent.com/42200979/92476505-7d9f5980-f1f8-11ea-897e-2f7be487615a.png)
![image](https://user-images.githubusercontent.com/42200979/92476519-842dd100-f1f8-11ea-83a8-e04b9631dbbb.png)

**Comment by aharui** [comment]
In the second screenshot, the breakpoint needs to be after the call (line 296) otherwise you are examining the variable before the call, when it is the Array assigned earlier.

It isn't clear how the value then gets passed to fn_roReportUtilRH.  Understanding that may help you understand why you are getting a different value there.

**Comment by pashminakazi** [comment]
If you have time please check on VDI
Click on PDF button from screen to trigger the breakpoints

**Comment by aharui** [comment]
It is important for you to learn the application and framework code.  It is not efficient for me to debug an asynchronous event in your code.  Where is fn_roReportUtilRH referenced in your application code?  How does this current view get to those places in your code?

**Comment by pashminakazi** [comment]
fn_roReportUtilRH is in our main Application file, applications.mxml

**Comment by aharui** [comment]
Yes, I can see that from the screenshots, but what isn't clear is how that code gets called after the other code in the screenshots that seem to indicate that a valid response was returned.  I see in the source screenshot that some references to fn_roReportUtilRH are commented out.

It might also help if you can show the full stack trace at the exception.  Right now most of it is cutoff
