### ISSUE TITLE
TabBar horizontal layout fails when combined with ResponsiveVisibility bead

### ISSUE THREAD

**Issue by brianraymes** [apache/royale-asjs#907]
A TabBar cannot layout horizontally when a ResponsiveVisibility bead is used.

**Steps to Reproduce**

1. _Create a TabBar with a ResponsiveVisibility bead_

```
<j:TabBar width="100%"
    itemRenderer="renderers.TabBarHorizontalIconItemRenderer"
    dataProvider="{someDataProvider}">

    <j:beads>
        <j:ResponsiveVisibility phoneVisible="false"
            tabletVisible="true"
            desktopVisible="true"
            wideScreenVisible="true" />
    </j:beads>

</j:TabBar>
```

**Expected Results**

The TabBar displays horizontally and is hidden in phone sizes.

**Actual Results**

The TabBar displays vertically in tablet, desktop, and widescreen sizes.

**Workaround**

A suitable workaround would be to add the ResponsiveVisibility bead to another container surrounding the TabBar.

**Comment by carlosrovira** [comment]
I can't remember why I set the display to `block` instead to `flex` maybe there was some issue at the time I stated Jewel but I don't see a problem now, so this should work always.
