### ISSUE TITLE
ScrollToIndex does not work in all cases

### ISSUE THREAD

**Issue by mjesteve** [apache/royale-asjs#916]
Working with a Jewel List control, I have noticed that when a selectedIndex is assigned outside the visible area of the control, the scroll is not positioned correctly.
Leaving the assignment of the selectedIndex aside and focusing on the scrollToIndex function we can observe an error in the option "variableRowHeight = false", specifically in line 204, in ListView.as:

![ListView as_NoVariableRowHeight](https://user-images.githubusercontent.com/55754195/95019954-a0daee80-0668-11eb-9f82-c41eebb510d6.png)

It is compared with "pm.rowHeight" but "rowHeight" is assigned (variable that is not given a value and is always 0)

I have changed the line, changing "rowHeight" to "pm.rowHeight" and it has been fixed.
Could this be the final solution?

On the other hand, when we configure variableRowHeight = true it does not work well either, in this case the scroll gets desynchronized "much more" and although I have solved it I think it is better to go step by step.

PR?

Thx
Hiedra

**Comment by carlosrovira** [comment]
Thanks! This seems to be a side effect of the recent refactor to remove PM's proxy members from TLCs.
