### ISSUE TITLE
Jewel ComboBox freeze with SearchFilter

### ISSUE THREAD

**Issue by SolidSoft-Lda** [apache/royale-asjs#917]
Hi,

I found a bug with Jewel ComboBox and SearchFilter bead.
This can be easy reproduced with several itens with similar options however it can be simulated on Tour de Jewel.

Steps to reproduce:
1. Locate ComboBox on Tour de Jewel components;
2. Go to Local Search Filter sample;
3. Select any item with mouse;
4. Select all text and type "i";
5. The only option will be "Iron Man" and at this point you can't select the option or close the list and the application will freeze.

**Comment by SolidSoft-Lda** [comment]
After I bring the SearchFilter bead to my project, I found a fix or workaround to this bug.

On SearchFilter.as, I added this on my side:
        public override function set list(value:List):void
        {
            super.list = value;
            COMPILE::JS
            {
            list.addEventListener(MouseEvent.CLICK, onListClick);
            }
        }

        private function onListClick(event:MouseEvent):void
        {
            comboView.popUpVisible = false;
        }

If is OK, I can commit it.
I started a discussion on mailing list.

**Comment by carlosrovira** [comment]
Hi Hugo,

I'm reopening since the bug is still there. It's better to close when it's solved really on the repo. Also, if a commit solves it it can be close directly by using "fixed #<issue-number>" on the description.

As I commented I get a RTE with this solution in TDJ, so I think something is not completely right. I couldn't still check the issue and the solution myself. Just tried your snippet.

Thanks

**Comment by SolidSoft-Lda** [comment]
Hi Carlos,

Instead of monkey patch, I refreshed my fork, applied the fix, compile with ant and tested directly on TDJ.
Then, I just commit and create a pull request: https://github.com/apache/royale-asjs/pull/922

Thanks.

**Comment by carlosrovira** [comment]
Thanks Hugo! going to review :)

**Comment by carlosrovira** [comment]
just recently committed your fix fro PR 922
