### ISSUE TITLE
labelField always expected to exist in spark dropdown

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#918]
This 

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
               xmlns:s="library://ns.apache.org/royale/spark">
	       <s:DropDownList
	       focusEnabled="false"
	       selectedIndex="0"
	       width="60"
		       >
		       <s:dataProvider>
		       <s:ArrayList>
		       <fx:String>200</fx:String>
		       </s:ArrayList>
		       </s:dataProvider>
		       </s:DropDownList> 
</s:Application>
```

Will result in

TypeError: Cannot read property 'toString' of undefined

spark.components.beads.DropDownListView.spark_components_beads_DropDownListView_selectionChangeHandler (DropDownListView.js:58)
org.apache.royale.events.EventDispatcher.fireListeners (EventDispatcher.js:97)
goog.events.EventTarget.dispatchEventInternal_ (eventtarget.js:382)
org.apache.royale.events.EventDispatcher.dispatchEvent (EventDispatcher.js:72)
mx.controls.beads.models.SingleSelectionIListModel.set__dataProvider (SingleSelectionIListModel.js:103)
spark.components.supportClasses.DropDownListBase.set__dataProvider (DropDownListBase.js:54)
org.apache.royale.utils.MXMLDataInterpreter.initializeStrandBasedObject (MXMLDataInterpreter.js:193)
org.apache.royale.utils.MXMLDataInterpreter.generateMXMLArray (MXMLDataInterpreter.js:121)
org.apache.royale.utils.MXMLDataInterpreter.generateMXMLInstances (MXMLDataInterpreter.js:265)
mx.core.UIComponent.createChildren (UIComponent.js:955)
spark.components.SkinnableContainer.createChildren (SkinnableContainer.js:147)
spark.components.Application.createChildren (Application.js:90)
mx.core.UIComponent.initialize (UIComponent.js:901)
mx.core.UIComponent.addedToParent (UIComponent.js:442)
spark.components.SkinnableContainer.addedToParent (SkinnableContainer.js:133)
org.apache.royale.core.UIBase.addElement (UIBase.js:395)
mx.managers.SystemManager.addChild (SystemManager.js:109)
mx.managers.SystemManager.mx_managers_SystemManager_initializeTopLevelWindow (SystemManager.js:244)
mx.managers.SystemManager.start (SystemManager.js:227)
(anonymous) (index.html:393)

**Comment by yishayw** [comment]
@aharui, can u have a look?

**Comment by aharui** [comment]
I might have time this week, but if you want to try something, bring in LabelUtil and call it after checking for the prompt.
