### ISSUE TITLE
Jewel ArrayListSelectionModel, selectedItem

### ISSUE THREAD

**Issue by mjesteve** [apache/royale-asjs#921]
Hi,
I think I have encountered an error in the selectedItem setter in Jewel ArrayListSelectionModel.
Before the re-selection of an element, same item, "selectionChanged" is always thrown because it is understood that the existing selectedIndex is different from the current one, even though it is not because there is a copy-paste error in the setter:

![image](https://user-images.githubusercontent.com/55754195/96197032-2efc8200-0f51-11eb-8281-45e49e68dcab.png)

¿Podría ser?

![image](https://user-images.githubusercontent.com/55754195/96197162-8a2e7480-0f51-11eb-8207-9f660cf74c45.png)

Thx.
Hiedra.

**Comment by carlosrovira** [comment]
Hi @mjesteve, I think you're right.
@greg-dove I'm going to make this change, but if that's not a typo and have a motivation behind that we're not seeing please revert it.
Thanks both! :)

**Comment by carlosrovira** [comment]
Hi @greg-dove 

since you responded:

> Sorry I don't think that's a typo. Maybe it's not the most readable code
but i think the event should only happen if selected Index changed. Will
verify when I officially wake up (because I am supposed to be asleep right
now)

I reverted the commit and left this issue open awaiting for your thoughts

Thanks

**Comment by carlosrovira** [comment]
Since Greg already check this and seems to be ok I'll close this issue

(comments from greg here: https://github.com/apache/royale-asjs/commit/edc132ccf214c381703c816fa90f23e179c993c4)
