### ISSUE TITLE
Create Royale project with Maven

### ISSUE THREAD

**Issue by frettarenan** [apache/royale-asjs#928]
Good afternoon,

I tried to configure the project in maven but it presented some errors.

Can you help me? Is this documentation correct?

https://github.com/apache/royale-asjs/wiki/Create-Royale-project-with-Maven

![2020-10-29_14h33_43](https://user-images.githubusercontent.com/7624856/97610518-bfc46a80-19f3-11eb-93b6-4d371dee787e.png)

**Comment by frettarenan** [comment]
`<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.apache.royale.examples</groupId>
  <artifactId>ASimpleRoyaleTestApp</artifactId>
  <version>1.0</version>
  <packaging>swf</packaging>

  <properties>
    <compiler.debug>true</compiler.debug>
  </properties>

  <build>
    <sourceDirectory>src/main/royale</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.royale.compiler</groupId>
        <artifactId>royale-maven-plugin</artifactId>
        <version>0.9.7</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass>App.mxml</mainClass>
          <targets>JSRoyale</targets>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.royale.compiler</groupId>
            <artifactId>compiler-jx</artifactId>
            <version>0.9.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Core</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>

    
    <dependency>
      <groupId>com.adobe.flash.framework</groupId>
      <artifactId>playerglobal</artifactId>
      <version>20.0</version>
      <type>swc</type>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>HTML</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Language</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
      <classifier>js</classifier>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>apache-release</id>
      <properties>
        <compiler.debug>false</compiler.debug>
      </properties>
    </profile>
  </profiles>

</project>
`

**Comment by frettarenan** [comment]
`
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.apache.royale.examples</groupId>
  <artifactId>ASimpleRoyaleTestApp</artifactId>
  <version>1.0</version>
  <packaging>swf</packaging>

  <properties>
    <compiler.debug>true</compiler.debug>
  </properties>

  <build>
    <sourceDirectory>src/main/royale</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.royale.compiler</groupId>
        <artifactId>royale-maven-plugin</artifactId>
        <version>0.9.7</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass>App.mxml</mainClass>
          <targets>JSRoyale</targets>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.royale.compiler</groupId>
            <artifactId>compiler-jx</artifactId>
            <version>0.9.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Core</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>

    
    <dependency>
      <groupId>com.adobe.flash.framework</groupId>
      <artifactId>playerglobal</artifactId>
      <version>20.0</version>
      <type>swc</type>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>HTML</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Language</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
      <classifier>js</classifier>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>apache-release</id>
      <properties>
        <compiler.debug>false</compiler.debug>
      </properties>
    </profile>
  </profiles>

</project>
`

**Comment by frettarenan** [comment]
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.apache.royale.examples</groupId>
  <artifactId>ASimpleRoyaleTestApp</artifactId>
  <version>1.0</version>
  <packaging>swf</packaging>

  <properties>
    <compiler.debug>true</compiler.debug>
  </properties>

  <build>
    <sourceDirectory>src/main/royale</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.royale.compiler</groupId>
        <artifactId>royale-maven-plugin</artifactId>
        <version>0.9.7</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass>App.mxml</mainClass>
          <targets>JSRoyale</targets>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.royale.compiler</groupId>
            <artifactId>compiler-jx</artifactId>
            <version>0.9.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Core</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>

    
    <dependency>
      <groupId>com.adobe.flash.framework</groupId>
      <artifactId>playerglobal</artifactId>
      <version>20.0</version>
      <type>swc</type>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>HTML</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Language</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
      <classifier>js</classifier>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>apache-release</id>
      <properties>
        <compiler.debug>false</compiler.debug>
      </properties>
    </profile>
  </profiles>

</project>
`

**Comment by frettarenan** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.apache.royale.examples</groupId>
  <artifactId>ASimpleRoyaleTestApp</artifactId>
  <version>1.0</version>
  <packaging>swf</packaging>

  <properties>
    <compiler.debug>true</compiler.debug>
  </properties>

  <build>
    <sourceDirectory>src/main/royale</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.royale.compiler</groupId>
        <artifactId>royale-maven-plugin</artifactId>
        <version>0.9.7</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass>App.mxml</mainClass>
          <targets>JSRoyale</targets>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.royale.compiler</groupId>
            <artifactId>compiler-jx</artifactId>
            <version>0.9.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Core</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>

    
    <dependency>
      <groupId>com.adobe.flash.framework</groupId>
      <artifactId>playerglobal</artifactId>
      <version>20.0</version>
      <type>swc</type>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>HTML</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Language</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
      <classifier>js</classifier>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>apache-release</id>
      <properties>
        <compiler.debug>false</compiler.debug>
      </properties>
    </profile>
  </profiles>

</project>

**Comment by frettarenan** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.apache.royale.examples</groupId>
  <artifactId>ASimpleRoyaleTestApp</artifactId>
  <version>1.0</version>
  <packaging>swf</packaging>

  <properties>
    <compiler.debug>true</compiler.debug>
  </properties>

  <build>
    <sourceDirectory>src/main/royale</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.royale.compiler</groupId>
        <artifactId>royale-maven-plugin</artifactId>
        <version>0.9.7</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass>App.mxml</mainClass>
          <targets>JSRoyale</targets>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.royale.compiler</groupId>
            <artifactId>compiler-jx</artifactId>
            <version>0.9.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Core</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>

    
    <dependency>
      <groupId>com.adobe.flash.framework</groupId>
      <artifactId>playerglobal</artifactId>
      <version>20.0</version>
      <type>swc</type>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>HTML</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Language</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
      <classifier>js</classifier>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>apache-release</id>
      <properties>
        <compiler.debug>false</compiler.debug>
      </properties>
    </profile>
  </profiles>

</project>

**Comment by frettarenan** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.apache.royale.examples</groupId>
  <artifactId>ASimpleRoyaleTestApp</artifactId>
  <version>1.0</version>
  <packaging>swf</packaging>

  <properties>
    <compiler.debug>true</compiler.debug>
  </properties>

  <build>
    <sourceDirectory>src/main/royale</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.royale.compiler</groupId>
        <artifactId>royale-maven-plugin</artifactId>
        <version>0.9.7</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass>App.mxml</mainClass>
          <targets>JSRoyale</targets>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.royale.compiler</groupId>
            <artifactId>compiler-jx</artifactId>
            <version>0.9.7</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Core</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>

    
    <dependency>
      <groupId>com.adobe.flash.framework</groupId>
      <artifactId>playerglobal</artifactId>
      <version>20.0</version>
      <type>swc</type>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>HTML</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
    </dependency>
    <dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>Language</artifactId>
      <version>0.9.7</version>
      <type>swc</type>
      <classifier>js</classifier>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>apache-release</id>
      <properties>
        <compiler.debug>false</compiler.debug>
      </properties>
    </profile>
  </profiles>

</project>

**Comment by frettarenan** [comment]
Segue pom.xml

**Comment by frettarenan** [comment]
![2020-10-29_14h48_42](https://user-images.githubusercontent.com/7624856/97612182-d79cee00-19f5-11eb-85e4-7b37ae6d362e.png)
![2020-10-29_14h48_51](https://user-images.githubusercontent.com/7624856/97612191-dd92cf00-19f5-11eb-94c1-51c65c196dd8.png)

**Comment by carlosrovira** [comment]
Hi, probably that page is a bit out of date. 
I created recently a new archetype for Jewel and Crux showcased here (https://apache.github.io/royale-docs/presentations/StartingFromABlankFile-ApacheCon2020.pdf) in slide 3. It configure a project with Jewel UI Set.

`mvn archetype:generate -DarchetypeGroupId=org.apache.royale.framework -DarchetypeArtifactId=royale-jewel-application-archetype -DarchetypeVersion=0.9.8-SNAPSHOT`

Use this for inlcluding Crux too: `-DincludeCrux=true`

HTH

**Comment by carlosrovira** [comment]
I can see from your code that is out of date since playerglobal should go in a profile (in case you want SWF output).
The other archetype I put in my other response should work ok for you

**Comment by frettarenan** [comment]
Thanks very much,

I tried to set the parameter "-DincludeCrux = true", still keeps giving error.
it seems that this version does not exist, as the project on the official website is in version "0.9.7" "-DarchetypeVersion = 0.9.8-SNAPSHOT"

![2020-10-29_18h50_48](https://user-images.githubusercontent.com/7624856/97636371-ca90f680-1a17-11eb-93a8-fba7211ae3b5.png)

**Comment by carlosrovira** [comment]
ops, yes you're right, that code is not released yet, so you need to use a nightly build at the end of this page: https://royale.apache.org/get-involved/

sorry for the inconvenience.

**Comment by frettarenan** [comment]
thanks, but I couldn't create the project using maven because the dependencies don't exist in the central maven. Do you need to configure them manually? How do I run the hello world presented in the "Apache CON 2020" presentation?

**Comment by carlosrovira** [comment]
Hi,

sorry, 0.9.8 is still not released. Hope we get that soon! :)
You need to build the project locally. But is not as simple as that since there's 3 repos. Here's the recipe [1] also the script I use in macos that you can refactor to windows [2]

[1] https://github.com/apache/royale-asjs/wiki/Build-Apache-Royale-with-Maven
[2] https://gist.github.com/carlosrovira/200753108de263fa43e80d3228213509

**Comment by frettarenan** [comment]
I understand.

I started to perform the procedures you gave me in the documentation, but I have a simple problem:

the "royale-typedefs" project requires version 0.9.8 of the compiler, which is already in version 0.9.9.

What do I have to do to get the right versions?

**Comment by frettarenan** [comment]
I managed to change the required compiler version to 0.9.9.
Thank you very much, I managed to create the project with MAVEN: mvn archetype: generate -DarchetypeGroupId = org.apache.royale.framework -DarchetypeArtifactId = royale-jewel-application-archetype -DarchetypeVersion = 0.9.8-SNAPSHOT-DincludeCrux = true

**Comment by carlosrovira** [comment]
Hi, there's an undergoing process to create 0.9.8 release probably something is not reverted after the last try. Can't say right now since I don't have the repos at hand. Sorry for the invoncenience, great you finally was able to work over it :)
