### ISSUE TITLE
TinyEditor Properties

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#929]
,I was using mx:RichTextEditor in my application then i replace it with mx:TinyEditor there's a problem that i am using TinyEditor in both Master and Detail,when i add any record in detail and came back to master page then TinyEditor's styling bar will be twice then thrice and more and more

![image](https://user-images.githubusercontent.com/42200979/98220231-d0cf2780-1f6f-11eb-8667-5da217a775af.png)

and there's many properties I am using but they aren't available in TinyEditor. I don't know how to add them in TinyEditor because RichTextEditor is a .mxml file and TinyEditor is a .AS file

Please check : https://paste.apache.org/ex340

**Comment by pashminakazi** [comment]
@aharui Thanks Alex,but issue still exist 
![image](https://user-images.githubusercontent.com/42200979/98519334-73e6b080-2292-11eb-8dea-1474b2f5a6de.png)

and please make this example working,many properties are not working
https://paste.apache.org/424hn

**Comment by aharui** [comment]
I am not getting double toolbars in my test cases.  Make sure the new code is being used and set breakpoints or verify that the attribute does get removed from the editor.

**Comment by pashminakazi** [comment]
@aharui Thank u so much
