### ISSUE TITLE
Recent fix for issue #811 breaks VirtualDataContainerView.removeAllItemRenderers in SparkRoyale

### ISSUE THREAD

**Issue by estanglerbm** [apache/royale-asjs#941]
Recent fix for issue #811 (change was to exclude some elements in UIComponent.numElements) causes problems for VirtualDataContainerView.removeAllItemRenderers() [called via VirtualListView, as IBeadView of DataGroup in SparkRoyale].

Specifically, removeAllItemRenderers() doesn't remove all of them, since it relies on numElements and expects the total count.

**Comment by yishayw** [comment]
Nice catch, @estanglerbm, looks like you are halfway to a fix. Maybe DataGroup needs a different view bead that overrides removeAllItemRenderers() ? Pull requests are more than welcome.

**Comment by estanglerbm** [comment]
Well, I can certainly patch removeAllItemRenderers().  But I'm really trying to point out that the relatively-recent change by @aharui to UIComponent.numElements (checking the royale_wrapper) may break more things.

Should numElements really return less than the number of elements, as expected by other code?  If so, that's fine;  can patch functions as needed.  Just want to confirm.  [Both sets of code are doing something unusual:  removeAllItemRenderers() is deleting all-but-two, and numElements is returning less than the number of elements.  So not sure who should win.]

**Comment by yishayw** [comment]
With emulation components the test is to see if Flex behavior is replicated.

**Comment by Harbs** [comment]
`elements` in Royale usually has the expectation of being Royale elements. When that assumption is not true, the non-royale elements need to be filtered out (or be explicitly dealt with). So yeah, checking `royale_wrapper` makes sense. I'm guessing `VirtualListView` also has non-Royale elements?

**Comment by aharui** [comment]
Each component set (Basic, Jewel, MXRoyale) can have different infrastructure.  MXRoyale expects UIComponents and numElements tries to ignore other HTMLElements that are used to implement virtual lists.  In many cases, MXRoyale can re-use beads from Basic, but often that isn't the case, and many Basic beads are customized or subclassed for MXRoyale.  You can compare the beads in the defaults.css for Basic and MXRoyale and see many custom beads for MXRoyale.

IMO, that should be the case here.  A solution would not patch `org.apache.royale.html.beads.VirtualDataContainerView`, as I think it works correctly for Basic.  Instead, create a subclass of `org.apache.royale.html.beads.VirtualDataContainerView` and override `removeAllItemRenderers`.

**Comment by estanglerbm** [comment]
Note that though numElements() adjusts based on royale_wrapper, getElementAt() doesn't.  (So to find the first element past the top div, have to do getElementAt(1).)

**Comment by Harbs** [comment]
I wonder if a better fix might be to override `internalChildren()` instead of `numElements`. @aharui Thoughts?

**Comment by aharui** [comment]
Maybe, but IMO, internalChildren really shouldn't be filtered.  Higher-level APIs like numElements can be.

IOW, in a multi-target implementation, some API should abstract getting all children, so if you decide to filter internalChildren, you may someday need another API to get unfiltered children.
