### ISSUE TITLE
Spark DropDown Button Sizing is Off

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#952]
This app

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application 
	xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.apache.org/royale/spark"
	creationComplete="init()"
	>
	<fx:Script>
		<![CDATA[
			import mx.collections.ArrayCollection;

			private function init():void
			{
				var coll:ArrayCollection = new ArrayCollection();
				coll.addItem({"name": "NAME 1", "processedName": "name 1"});
				pageListCombo.dataProvider = coll;
			}
		]]>
	</fx:Script>		
	<s:DropDownList id="pageListCombo" labelField="processedName"/>
</s:Application>
```
Shows this

![image](https://user-images.githubusercontent.com/2101885/100143412-33d81e00-2e8d-11eb-8ee4-5de663e2579c.png)

**Comment by yishayw** [comment]
Workaround is to replace

	<s:DropDownList id="pageListCombo" labelField="processedName"/>
with

	<s:DropDownList id="pageListCombo" labelField="processedName" height="20"/>

**Comment by yishayw** [comment]
There's a cycle where the drop down button is measured for height and each time its height is set to "" its offesetHeight increases by 10px. Not sure why this happens (svg arrowdown?).

I think I saw a similar thing happen in issue #949 for measured width.

**Comment by estanglerbm** [comment]
I've been getting this problem, too.

**Comment by yishayw** [comment]
Svg path calculation based on size seems to be off. My last commit helps but still doesn't look 100% right.

**Comment by yishayw** [comment]
Although the test case was solved I'm still seeing it in my app

**Comment by estanglerbm** [comment]
The fix works really well, except for the attached test case (mx:Tree + s:DropDownList).  (If you comment out DropDownList, the spacing problem is gone.)
[TestTreeDropdown.mxml.txt](https://github.com/apache/royale-asjs/files/5614557/TestTreeDropdown.mxml.txt)

**Comment by yishayw** [comment]
@estanglerbm , I have seen all sorts of problems with objects being declared like that in mxml. Try creating the data provider from a script and maybe it will fix ur issue.

**Comment by estanglerbm** [comment]
That was a simple version of the test case;  the real versions (in a real application) use non-inline dataProviders and still have the issue.  It works fine in Flex.

**Comment by estanglerbm** [comment]
Even if you put mx:Tree in an s:NavigatorContent of an mx:ViewStack, it affects every s:DropDownList in every tab of that mx:ViewStack.  It's a potent control!
