### ISSUE TITLE
ViewStack Laying Its Children Out Vertically

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#962]
In this app, clicking to select the second child, shows an offset from the top.

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application 
	xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.apache.org/royale/spark"
	xmlns:mx="library://ns.apache.org/royale/mx"
	>
	<fx:Script>
		<![CDATA[
			private function onClick():void
			{
				myViewStack.invalidateSize();
				myViewStack.selectedChild = myVbox2;
			}

		]]>
	</fx:Script>
	<mx:ViewStack resizeToContent="true" width="100%" id="myViewStack">
		<mx:VBox width="100%" id="myVbox1">
			<s:Group id="myGroup1" width="100%" height="20" style="background-color: blue"/>
		</mx:VBox>
		<mx:VBox width="100%" id="myVbox2">
			<s:Group id="myGroup2" width="100%" height="20" style="background-color: red"/>
		</mx:VBox>
	</mx:ViewStack>
	<s:Button click="onClick()" label="Click" bottom="0"/>
</s:Application>

```

**Comment by yishayw** [comment]
I am not sure why ViewStack is using Box layout

**Comment by yishayw** [comment]
Reverting bafb72696a39657f3373e820c86239b30bae7890 seems to fix it, but need to understand this better

**Comment by estanglerbm** [comment]
I also saw this, with <mx:ViewStack> of <s:NavigatorContent>.  The offset from the top got larger and larger, the more items (i.e. tabs) I added to ViewStack, making it unusable.  Setting width / height or x / y on NavigatorContent didn't help.

**Comment by yishayw** [comment]
A quick workaround is to add

<mx:beads>
	<mx:BasicLayout/>
</mx:beads>

to the viewstack, but that might have a bad effect on the sizing of children. I'll see if I can fix this with some help from @aharui .

**Comment by estanglerbm** [comment]
Fix works great!

**Comment by estanglerbm** [comment]
@yishayw Commit f8693c868163e509f474f7ed340dc830e8b25e5b fixed it perfectly.  Awesome!
