### ISSUE TITLE
fx:Declarations doesn't initialize fx:Number or fx:Boolean

### ISSUE THREAD

**Issue by estanglerbm** [apache/royale-asjs#999]
In attached test case, fx:Number and fx:Boolean are undefined.

[TestDeclarations.mxml.txt](https://github.com/apache/royale-asjs/files/5675232/TestDeclarations.mxml.txt)

Flash Debug Player shows error:

```
VerifyError: Error #1030: Stack depth is unbalanced. 3 != 0.

	at org.apache.royale.core::Application/initialize()[/org/apache/royale/0.9.8/org/apache/royale/core/Application.as:0]
	at org.apache.royale.core::Application/initHandler()[/org/apache/royale/0.9.8/org/apache/royale/core/Application.as:161]
```

Where to begin looking for the place to fix it?

**Comment by yishayw** [comment]
@estanglerbm , this is a compiler issue. We've run into it too. It probably won't make it into this release as everyone is in over their heads with end of year ports and such. The workaround is to just declare vars in scripts with [Bindable].

If you do want to explore compiler code this might be a good place to start

https://github.com/apache/royale-compiler/wiki/developer-guide

**Comment by estanglerbm** [comment]
@aharui Appears fixed.  Thanks!
